"""Lot 6 : currys japonais et indiens, dals (lentilles sèches), boulettes, bowls."""

PATCHES = {
    "curry_japonais_1caddf": [
        ("add", "white_rice_short_grain_seed_dried", 300, "g", "carbohydrate"),
        ("qty", "onion_raw", 150),
        ("qty", "sesame_oil_plant", 30),
        ("del", "table_salt_unenriched"),  # roux et bouillon déjà salés (Na 1239 mg)
        ("txt", "ajoutez 45 ml d'huile de sésame", "ajoutez 30 ml d'huile de sésame"),
        ("txt", ", préparé avec des légumes végétariens,", ""),
        ("txt", ", préparé avec de la farine de riz et des épices végétariennes", ""),
        ("txt", " ou de lait", ""),
        ("txt", "Servez le curry japonais sur du riz cuit, préparé avec du riz et de l'eau, et garnissez de persil plat et de carottes râpées, si désiré.",
         "Pendant la cuisson, rincez 300 g de riz japonais et cuisez-le à couvert dans 360 ml d'eau 12 minutes. Servez le curry sur le riz."),
    ],
    "curry_katsu_vegan_f2e6a3": [
        ("qty", "rice_flour", 60),
        ("qty", "onion_raw", 150),
        ("qty", "sesame_oil_plant", 40),
        ("txt", "Faites chauffer une quantité généreuse d'huile de sésame", "Faites chauffer 30 ml d'huile de sésame"),
        ("txt", "Ajoutez le curry en poudre aux oignons", "Ajoutez le curry en poudre et 20 g de farine de riz aux oignons"),
        ("txt", " Ajoutez un peu de crème de coco pour donner une texture crémeuse.", ""),
    ],
    "curry_palak_paneer_b4ca11": [
        ("qty", "table_salt_unenriched", 4),
        ("txt", "6 g de sel de table", "4 g de sel de table"),
        ("txt", "250 g de fromage végétal râpé en cubes si souhaité", "250 g de paneer en cubes"),
        ("txt", "la richesse du fromage végétal", "la richesse du paneer"),
        ("txt", "30 ml de crème de coco", "30 ml de lait de coco"),
        ("txt", " et de noix de coco râpée si désiré", ""),
        ("txt", " Présenter dans des bols préchauffés pour conserver la chaleur.", ""),
        ("step-", "Pour une présentation visuelle attrayante"),
    ],
    "curry_paneer_butter_masala_9e638c": [
        ("qty", "table_salt_unenriched", 4),
        ("txt", "20 ml de canola_oil", "20 ml d'huile de colza"),
        ("txt", "250 g de fromage râpé en cubes de 2 cm", "250 g de paneer en cubes de 2 cm"),
        ("txt", "Assaisonner avec 6 g de sel et 4 g de garam masala.", "Assaisonner avec 4 g de sel."),
        ("step-", "Présenter dans des bols préchauffés"),
    ],
    "curry_split_pea_k2f9x1": [
        ("add", "water", 900, "ml", "liquid"),
        ("add", "yellow_mustard_spice_seed", 3, "g", "spice"),
        ("add", "curry_leaf", 3, "g", "herb"),
        ("txt", "dans 35 ml d'huile de tournesol", "dans 30 ml d'huile de tournesol"),
        ("txt", "900 ml d'eau de coco", "900 ml d'eau"),
        ("txt", "Assaisonner avec de la levure nutritionnelle et servir sans attendre.", "Saler, parsemer de coriandre fraîche et servir."),
    ],
    "curry_sri_lankan_jackfruit_1cff43": [
        ("ing", "lime_raw", "lime_juice_fresh", 40, "ml"),
        ("qty", "onion_raw", 150),
        ("qty", "coconut_oil_plant", 30),
        ("txt", "300g d'oignons jaunes", "150g d'oignons jaunes"),
        ("txt", "45ml d'huile de coco", "30ml d'huile de coco"),
        ("txt", "de jus de 140g de citron vert", "de 40 ml de jus de citron vert"),
        ("step-", "Servir aussitôt dans des bols préchauffés."),
        ("step-", "Démouler et servir chaud."),
    ],
    "curry_sri_lankan_pumpkin_7f1edb": [
        ("qty", "onion_raw", 150),
        ("txt", "300g d'oignons émincés", "150g d'oignons émincés"),
        ("txt", "tendres et fragrances", "tendres et parfumés"),
        ("txt", "faites-les blanchir pendant 5 minutes à feu moyen-vif, en remuant régulièrement, jusqu'à ce qu'elles soient tendres et légèrement caramélisées",
         "faites-les revenir pendant 5 minutes à feu moyen-vif, en remuant régulièrement, jusqu'à ce qu'elles soient légèrement colorées"),
        ("txt", "accompagné de riz ou de naan cuit à feu moyen-vif pendant 8 minutes, jusqu'à ce qu'il soit doré et croustillant.",
         "accompagné de riz ou de naan."),
    ],
    "dal_afghan_sabzi_chalaw_18f6a5": [
        ("title", "Sabzi afghan aux épinards et lentilles"),
        ("add", "water", 700, "ml", "liquid"),
        ("qty", "sunflower_oil_plant", 45),
        ("step-", "Ajouter 20ml d'huile de tournesol pour enrober"),
        ("txt", "accompagné de riz végan au safran", "accompagné de riz basmati (chalaw)"),
        ("time", 21, 0, 40),
    ],
    "dal_ajapsandali_8ebefc": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("qty", "garlic_raw", 10),
        ("txt", "Ajouter 2 g d'ail émincé", "Ajouter 10 g d'ail émincé"),
        ("step-", "levure nutritionnelle"),
        ("step-", "Servir dans des bols préchauffés"),
    ],
    "dal_armenian_lentil_soup_0f1067": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 200),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "l'oignon émincé (300g)", "l'oignon émincé (150g)"),
        ("txt", "Incorporez les lentilles vertes (300g)", "Incorporez les lentilles vertes rincées (200g)"),
        ("txt", "Couvrez-les de 800 ml", "Couvrez-les de 750 ml"),
        ("txt", "laissez mijoter pendant 20 minutes", "laissez mijoter pendant 30 minutes"),
        ("txt", "le jus de citron (100g) et assaisonnez avec du sel (5g)", "le jus de citron (40 ml) et assaisonnez avec du sel (2g)"),
    ],
    "dal_boulettes_suedoises_2ac55d": [
        ("qty", "onion_raw", 100),
        ("qty", "egg_raw", 110),
        ("qty", "nutmeg_spice", 1),
        ("steps", [
            "Écraser 400g de pois chiches cuits avec 100g d'oignon finement haché et 60g de chapelure jusqu'à obtenir une pâte homogène.",
            "Ajouter 110g d'œufs battus (2 œufs), 1g de muscade moulue, 5g de sel et 2g de poivre, puis mélanger.",
            "Former des boulettes de 3 cm de diamètre en les roulant entre les mains humides.",
            "Faire dorer les boulettes dans 45ml d'huile à feu moyen pendant 8 à 10 minutes, en les retournant régulièrement.",
            "Servir chaud avec une purée de pommes de terre, de la confiture d'airelles ou des légumes sautés.",
        ]),
    ],
    "dal_boulettes_suedoises_vegan_fea9f6": [
        ("add", "flaxseed_linseed_ground", 7, "g", "binder"),
        ("add", "water", 45, "ml", "liquid"),
        ("add", "coconut_milk_plant", 150, "ml", "sauce"),
        ("qty", "onion_raw", 100),
        ("qty", "nutmeg_spice", 1),
        ("txt", "300g d'oignon jaune haché", "100g d'oignon jaune haché"),
        ("txt", "5g de noix de muscade", "1g de noix de muscade"),
        ("txt", "Vous pouvez utiliser une crème de coco mélangée avec un peu de lait de coco et des herbes fraîches pour cela, en remuant pendant environ 2 minutes.",
         "Chauffer 150 ml de lait de coco avec un peu de sel, de poivre et de muscade pendant 2 minutes, jusqu'à léger épaississement."),
    ],
    "dal_buddha_bowl_4ffca3": [
        ("qty", "quinoa_raw_dried", 200),
        ("qty", "avocado_raw", 200),
        ("qty", "olive_oil_plant", 20),
        ("qty", "garlic_raw", 5),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("steps", [
            "Rincer 200g de quinoa et le cuire dans deux fois son volume d'eau salée pendant environ 15 minutes, jusqu'à absorption complète. Laisser tiédir.",
            "Préchauffer le four à 200°C. Égoutter et sécher 400g de pois chiches, les mélanger avec 20ml d'huile d'olive, du sel et du poivre, puis les rôtir 25 minutes jusqu'à ce qu'ils soient croustillants.",
            "Préparer la sauce tahini : mélanger 45ml de tahini, 40ml de jus de citron, 5g d'ail râpé et 45ml d'eau jusqu'à obtenir une sauce lisse.",
            "Couper 200g d'avocat en tranches, 350g de concombre en rondelles et 200g de carotte en rubans.",
            "Répartir le quinoa dans les bols, puis disposer par sections les pois chiches rôtis, l'avocat, le concombre et la carotte.",
            "Arroser de sauce tahini, parsemer de 15g de graines de sésame et de 10g de coriandre fraîche, puis servir.",
        ]),
    ],
    "dal_chana_classic_k1d1p4": [
        ("txt", "cuisez dans 900ml d'eau à 180°C pendant 25 minutes", "cuisez dans 900ml d'eau frémissante pendant 25 minutes"),
        ("txt", "ainsi que 5g de cumin, 3,8g de curcuma", "ainsi que 3,8g de curcuma"),
        ("txt", " Vous pouvez également ajouter un peu de levure nutritionnelle pour un goût umami supplémentaire.", ""),
        ('qty', 'chilli_pepper_raw', 10),
        ('txt', "Ajoutez 25g d'ail et 10g de gingembre,", "Ajoutez 25g d'ail, 10g de gingembre et 10 g de piment vert haché,"),
        ('step-', 'Laissez reposer pendant quelques minutes avant de servir'),
    ],
    "dal_chole_bhature_dbcac0": [
        ("add", "wheat_all_purpose_flour_unenriched_unbleached", 200, "g", "carbohydrate"),
        ("add", "water", 310, "ml", "liquid"),
        ("add", "sunflower_oil_plant", 40, "ml", "fat_frying"),
        ("add", "ginger_raw_root_fresh", 10, "g", "aromatic"),
        ("qty", "yellow_onion_raw", 150),
        ("flag", "gluten_free", False),
        ("txt", "dans 35 ml d'huile de coco à 170°C", "dans 35 ml d'huile de coco à feu moyen"),
        ("txt", "mijoter 20 minutes à 150°C", "mijoter 20 minutes à feu doux"),
        ("txt", "Préparer la pâte pour les bhature en mélangeant la farine de blé, l'huile de coco et l'eau.",
         "Préparer la pâte des bhature en mélangeant 200g de farine de blé, une pincée de sel, 10 ml d'huile de coco et 110 ml d'eau."),
        ("txt", "Frire les bhature dans l'huile de coco à 175°C", "Frire les bhature dans un bain d'huile de tournesol à 175°C"),
        ("txt", "comme le cilantro ou la coriandre", "comme la coriandre"),
        ("step-", "Démouler les bhature"),
    ],
    "dal_chole_curry_de_pois_chiches_851fca": [
        ("time", 15, 720, 100),
    ],
    "dal_coconut_classic_k1d1p5": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("txt", "Verser 400ml de lait de coco", "Verser 425ml de lait de coco"),
    ],
    "dal_dal_makhani_c9ce94": [
        ("time", 21, 480, 90),
    ],
    "dal_dal_tadka_4c3536": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("txt", "Garnir d'oignons frits croustillants et de 10 g", "Garnir de 10 g"),
        ("txt", "Servir sans attendre, dans des bols préchauffés.", "Servir sans attendre."),
    ],
    "dal_de_lentilles_corail_vegan_8cc6a7": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "pendant 18 à 20 minutes à 90°C", "pendant 18 à 20 minutes"),
        ("txt", "avec 5 g de sel si nécessaire", "avec 2 g de sel si nécessaire"),
    ],
    "dal_ethiopian_atkilt_wat_afd168": [
        ("add", "water", 150, "ml", "liquid"),
    ],
    "dal_ethiopian_misir_wot_4203c8": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("flag", "kid_friendly", False),
    ],
    "dal_falafel_traditionnels_214e07": [
        ("txt", "Faire frire les falafel dans 45 ml d'huile d'olive préchauffée à 175°C pendant 3 à 4 minutes par côté",
         "Faire dorer les falafel à la poêle dans 45 ml d'huile d'olive chaude pendant 3 à 4 minutes par côté"),
        ("step-", "Déguster et ajuster la quantité de sel"),
        ("step-", "Présenter les falafel de manière créative"),
        ("step-", "Servir et profiter de ce plat levantin"),
    ],
    "dal_galettes_de_pois_chiches_db4c7a": [
        ("add", "table_salt_unenriched", 5, "g", "seasoning"),
        ("qty", "onion_raw", 100),
        ("qty", "chickpea_flour", 60),
        ("txt", "avec 300g d'oignon, 9g d'ail, 3g de cumin et 3g de coriandre", "avec 100g d'oignon, 9g d'ail, 3g de cumin, 3g de coriandre et 5g de sel"),
        ("txt", "150g de farine de pois chiche", "60g de farine de pois chiche"),
    ],
    "dal_grain_bowl_mediterraneen_2d5531": [
        ("qty", "quinoa_raw_dried", 200),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("txt", "250g de quinoa cru dans 500ml", "200g de quinoa cru dans 400ml"),
        ("txt", "avec le jus de 100g de citron", "avec 40ml de jus de citron"),
        ("txt", ", de graines de sésame et d'un filet", " et d'un filet"),
        ("step-", "levure nutritionnelle"),
        ("step-", "Démouler, napper de sauce tahini"),
    ],
}
