"""Lot 7 : harira, houmous, kadhi, khichdi, koshari, soupes de lentilles, shepherd's pies, dosa, köfte."""

PATCHES = {
    "dal_harira_822880": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 150),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "300 g d'oignon jaune", "150 g d'oignon jaune"),
        ("txt", "300 g de lentilles vertes", "150 g de lentilles vertes rincées"),
        ("txt", "laisser mijoter 20 minutes", "laisser mijoter 35 minutes"),
        ("txt", "Assaisonner avec 5 g de sel", "Assaisonner avec 2 g de sel"),
    ],
    "dal_hummus_traditionnel_7f6ccc": [
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("add", "water", 60, "ml", "liquid"),
        ("add", "parsley_fresh_herb", 5, "g", "herb"),
        ("txt", "Faire tremper les pois chiches secs pendant 12 heures, puis les cuire 1 heure avec une pincée de bicarbonate de soude.",
         "Faire tremper 160 g de pois chiches secs pendant 12 heures, puis les cuire 1 heure avec une pincée de bicarbonate de soude (environ 400 g de pois chiches cuits)."),
        ("txt", "pendant 4 minutes à feu moyen-vif", "pendant 4 minutes"),
        ("txt", "continuer à mixer 1 minute à feu doux", "continuer à mixer 1 minute"),
        ("txt", "persil plat, servir chaud", "persil plat, servir à température ambiante"),
        ("dish", "starter"),
    ],
    "dal_italian_pasta_e_ceci_3fbb85": [
        ("qty", "onion_raw", 150),
        ("txt", "Faire revenir 300g d'oignon", "Faire revenir 150g d'oignon"),
        ("txt", "en saupoudrant de fromage râpé", "en saupoudrant de parmesan râpé"),
    ],
    "dal_kadhi_pakora_078de2": [
        ("ing", "olive_oil_plant", "sunflower_oil_plant"),
        ("add", "water", 520, "ml", "liquid"),
        ("txt", "Chauffer 45 ml d'huile d'olive dans une casserole profonde à 170-180 °C", "Chauffer un bain d'huile de tournesol dans une casserole profonde à 170-180 °C"),
    ],
    "dal_kadhi_pakora_vegan_5cb5d4": [
        ("ing", "olive_oil_plant", "sunflower_oil_plant", 45),
        ("add", "water", 530, "ml", "liquid"),
        ("txt", "Chauffez 46ml d'huile d'olive dans une casserole profonde", "Chauffez un bain d'huile de tournesol dans une casserole profonde"),
    ],
    "dal_khichdi_23f932": [
        ("ing", "green_lentil_boiled", "red_lentil_dried", 150),
        ("qty", "white_rice_raw_seed_unenriched", 200),
        ("add", "water", 1000, "ml", "liquid"),
        ("txt", "Rincer 300g de riz basmati et 300g de lentilles vertes", "Rincer 200g de riz basmati et 150g de lentilles corail"),
        ("txt", "les lentilles vertes", "les lentilles corail"),
        ("txt", "Verser 600ml d'eau bouillante", "Verser 1 litre d'eau bouillante"),
        ("txt", "cuire à feu doux pendant 15 minutes", "cuire à feu doux pendant 20 minutes"),
    ],
    # lentilles et riz « cuits dans l'huile » : recette refaite
    "dal_koshari_15670d": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 150),
        ("qty", "white_rice_raw_seed_unenriched", 200),
        ("qty", "rice_vermicelli_raw_dried", 50),
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("steps", [
            "Rincer 150 g de lentilles vertes et les cuire 25 minutes dans de l'eau bouillante salée, jusqu'à ce qu'elles soient tendres. Égoutter.",
            "Émincer finement 300 g d'oignon et le faire frire dans 30 ml d'huile d'olive à feu moyen 15 à 20 minutes, jusqu'à ce qu'il soit brun et croustillant. Égoutter sur du papier absorbant.",
            "Dans la même casserole, avec le reste d'huile, faire dorer 50 g de vermicelles de riz brisés pendant 2 minutes. Ajouter 200 g de riz rincé, 450 ml d'eau et une pincée de sel, couvrir et cuire 15 minutes à feu doux.",
            "Préparer la sauce : faire revenir 9 g d'ail haché et 3 g de cumin pendant 1 minute, ajouter 240 g de tomates en dés et 400 g de sauce tomate, puis laisser mijoter 10 minutes. Hors du feu, ajouter 30 ml de vinaigre blanc.",
            "Mélanger le riz et les lentilles, répartir dans les bols, napper de sauce tomate et parsemer d'oignons croustillants.",
        ]),
        ("time", 17, 0, 45),
    ],
    "dal_koshari_egyptien_73828c": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 150),
        ("qty", "white_rice_raw_seed_unenriched", 150),
        ("qty", "pasta_raw_dried", 150),
        ("qty", "table_salt_unenriched", 2),
        ("steps", [
            "Cuire séparément 150 g de lentilles vertes rincées 25 minutes dans de l'eau bouillante salée, 150 g de riz long grain 12 minutes dans de l'eau salée et 150 g de petites pâtes 8 minutes, al dente. Égoutter.",
            "Émincer 300 g d'oignons jaunes en rondelles très fines et les faire frire dans 30 ml d'huile d'olive à feu moyen-vif pendant 20 minutes, jusqu'à ce qu'ils soient bruns et croustillants. Égoutter sur du papier absorbant.",
            "Préparer la sauce tomate épicée : faire revenir 9 g d'ail haché dans 15 ml d'huile d'olive, ajouter 240 g de tomates concassées, 400 g de sauce tomate, 3 g de cumin en poudre et 2 g de sel. Cuire 15 minutes, puis ajouter 30 ml de vinaigre blanc.",
            "Dans chaque bol, superposer le riz, les lentilles et les pâtes, napper de sauce tomate et couvrir d'oignons croustillants. Servir chaud.",
        ]),
    ],
    "dal_lebanese_lentil_soup_eae561": [
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "300g d'oignon jaune", "150g d'oignon jaune"),
        ("txt", "Assaisonner de 5g de sel et ajouter 100g de jus de citron frais", "Assaisonner de 2g de sel et ajouter 40 ml de jus de citron frais"),
        ("step-", "Cette soupe est idéale pour un repas réconfortant"),
    ],
    "dal_lentil_corail_classic_k1d1p1": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("add", "water", 700, "ml", "liquid"),
        ("add", "lime_juice_fresh", 15, "ml", "acid"),
        ("step-", "levure nutritionnelle"),
    ],
    "dal_lentil_shepherd_pie_vegan_926ebd": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 200),
        ("add", "olive_oil_plant", 15, "ml", "fat"),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "300 g d'oignons en dés dans un peu d'huile", "150 g d'oignons en dés dans 15 ml d'huile d'olive"),
        ("txt", "300 g de lentilles vertes et 750 ml de bouillon végétal, et faites cuire pendant 20 minutes",
         "200 g de lentilles vertes rincées et 750 ml de bouillon végétal, et faites cuire pendant 25 minutes"),
        ("txt", "5 g de sel de mer", "2 g de sel"),
        ("txt", "Servez chaud, en préchauffant des bols et en ajoutant un filet d'huile d'olive.", "Servez chaud."),
    ],
    "dal_lentil_shepherd_s_pie_477c76": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 200),
        ("add", "vegetable_stock_dried", 9.4, "g", "ingredient"),
        ("add", "water", 750, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("txt", "Faire cuire 300g de lentilles vertes dans un bouillon végétal", "Faire cuire 200g de lentilles vertes dans 750 ml de bouillon végétal"),
        ("txt", "300g d'oignon jaune", "150g d'oignon jaune"),
        ("txt", "un plat à gratin beurré d'huile d'olive", "un plat à gratin beurré"),
    ],
    "dal_lentil_shepherds_pie_vega_27455d": [
        ("qty", "green_lentil_dried", 200),
        ("add", "vegetable_stock_dried", 9.4, "g", "ingredient"),
        ("add", "water", 750, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("txt", "Faites cuire 300 g de lentilles vertes dans un bouillon végétal", "Faites cuire 200 g de lentilles vertes dans 750 ml de bouillon végétal"),
        ("txt", "Faites revenir 300 g d'oignons", "Faites revenir 150 g d'oignons"),
        ("txt", "Servez chaud, dans des bols préchauffés, en accompagnant", "Servez chaud, en accompagnant"),
    ],
    "dal_lentilles_aux_epinards_be2017": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 150),
        ("qty", "garlic_raw", 10),
        ("txt", "2 g d'ail haché", "10 g d'ail haché"),
        ("txt", "Ajouter 200 g de lentilles vertes", "Ajouter 150 g de lentilles vertes rincées"),
        ("step-", "en ajoutant un peu de crème de coco"),
        ("step-", "levure nutritionnelle"),
    ],
    "dal_lentilles_corail_au_lait_de_co_19d485": [
        ("qty", "garlic_raw", 10),
        ("txt", "Ajouter 2g d'ail émincé", "Ajouter 10g d'ail émincé"),
        ("txt", " et de noix de coco râpée", ""),
    ],
    "dal_makhani_vegan_259219": [
        ("del", "olive_oil_plant"),
        ("txt", "Cuire dans l'eau bouillante à 100°C pendant 1 heure, jusqu'à tendreté complète. La texture doit être al dente.",
         "Cuire dans l'eau bouillante pendant 1 heure, jusqu'à tendreté complète."),
        ("txt", "pendant au moins 30 minutes à 80°C", "pendant au moins 30 minutes"),
        ("txt", "Ajouter 50 ml d'huile d'olive et 15 ml d'huile de coco", "Ajouter 15 ml d'huile de coco"),
        ("txt", "typique de la cuisine indienne végétarien", "typique de la cuisine indienne"),
        ("txt", "comme du cilantro ou du basilic", "comme de la coriandre"),
        ("time", 21, 720, 110),
    ],
    "dal_masala_dosa_7d4088": [
        ("del", "mustard"),
        ("add", "curry_leaf", 3, "g", "herb"),
        ("add", "water", 250, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("steps", [
            "La veille, faire tremper 150 g d'urad dal pendant 4 heures, l'égoutter et le mixer finement avec un peu d'eau. Mélanger avec 150 g de farine de riz, 3 g de sel et environ 250 ml d'eau pour obtenir une pâte fluide. Couvrir et laisser fermenter 8 à 12 heures dans un endroit tiède.",
            "Préparer la farce : cuire 600 g de pommes de terre à l'eau 15 à 20 minutes jusqu'à ce qu'elles soient tendres, puis les écraser grossièrement.",
            "Chauffer 15 ml d'huile dans une poêle, faire crépiter 3 g de graines de moutarde 30 secondes, puis ajouter les feuilles de curry, le piment vert et 150 g d'oignon émincé. Cuire 6 à 8 minutes jusqu'à ce que l'oignon soit doré.",
            "Ajouter 3 g de curcuma, 3 g de coriandre moulue, le gingembre râpé, les pommes de terre écrasées et 2 g de sel. Mélanger et rectifier l'assaisonnement.",
            "Chauffer une poêle antiadhésive à feu moyen-vif et l'huiler légèrement. Verser une louche de pâte et l'étaler en spirale en un cercle fin.",
            "Cuire 2 à 3 minutes jusqu'à ce que les bords soient dorés et la surface mate. Déposer un peu de farce sur un côté, plier le dosa et servir aussitôt avec un chutney.",
        ]),
        ("time", 30, 720, 40),
    ],
    # köfte turcs : non cuits au four, boulgour gonflé dans les lentilles
    "dal_mercimek_koftesi_34f72d": [
        ("add", "water", 600, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("sugg-", "cream"),
        ("flag", "vegan", True),
        ("flag", "lactose_free", True),
        ("steps", [
            "Rincer 250 g de lentilles corail et les cuire dans 600 ml d'eau à feu doux pendant 15 minutes, jusqu'à absorption presque complète.",
            "Hors du feu, incorporer 250 g de boulgour fin, couvrir et laisser gonfler 15 minutes.",
            "Pendant ce temps, faire revenir 150 g d'oignon émincé dans 45 ml d'huile d'olive pendant 5 minutes jusqu'à ce qu'il soit translucide, puis ajouter 20 g de concentré de tomate, 3 g de cumin et 3 g de paprika. Cuire 1 minute.",
            "Mélanger les lentilles et le boulgour avec la préparation à l'oignon, 5 g de sel et 30 g de persil ciselé. Pétrir quelques minutes jusqu'à obtenir une pâte homogène qui se tient.",
            "Façonner des boulettes allongées en les pressant dans la paume de la main.",
            "Servir à température ambiante sur des feuilles de laitue, avec les tomates coupées en quartiers.",
        ]),
        ("time", 25, 15, 20),
    ],
    "dal_mujadara_2f5904": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 250),
        ("qty", "white_rice_raw_seed_unenriched", 200),
        ("add", "water", 1000, "ml", "liquid"),
        ("txt", "Ajouter 300g de lentilles vertes rincées", "Ajouter 250g de lentilles vertes rincées"),
        ("txt", "Incorporer 300g de riz long grain rincé", "Incorporer 200g de riz long grain rincé"),
        ("step-", "Apprécier les saveurs complexes"),
        ("step-", "Notez que la qualité des lentilles"),
        ("step-", "levure nutritionnelle"),
        ("time", 11, 10, 70),
    ],
    "dal_nepali_chickpea_curry_020035": [
        ("add", "water", 150, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("txt", "avec 150 ml d'eau, ainsi que les épices (garam masala, cumin, coriandre moulue et curcuma),", "avec 150 ml d'eau,"),
    ],
    "dal_nepali_dal_bhat_7860b1": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("add", "white_rice_raw_seed_unenriched", 300, "g", "carbohydrate"),
        ("qty", "garlic_raw", 10),
        ("txt", "Ajouter 2g d'ail", "Ajouter 10g d'ail"),
        ("step-", "Vérifier que les lentilles sont fondues"),
        ("step-", "Ajouter un filet d'huile de coco sur le dal"),
        ("step-", "Présenter le plat de manière appétissante"),
    ],
    "dal_pakora_b418ab": [
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("add", "water", 120, "ml", "liquid"),
        ("serv", 4),
        ("txt", "Chauffez 45 ml d'huile de tournesol dans un wok profond à 170°C", "Chauffez un bain d'huile de tournesol dans un wok profond à 170°C"),
        ("step-", "Servez les pakoras dans des bols en papier"),
    ],
    "dal_persian_lentil_soup_71e221": [
        ("ing", "lemon_raw", "lemon_juice", 30, "ml"),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "300g d'oignon cru", "150g d'oignon"),
        ("txt", "Mixer partiellement pour une texture épaisse et crémeuse, vérifier que ajuster si nécessaire.", "Mixer partiellement pour obtenir une texture épaisse et crémeuse."),
        ("txt", "Ajouter 5g de sel de table", "Ajouter 2g de sel de table"),
        ("txt", "jus de citron cru", "jus de citron"),
        ("txt", "Servir aussitôt dans des bols préchauffés, en garnissant de coriandre fraîche ciselée et d'un filet d'huile d'olive vierge extra, accompagné d'un pain pita tiède ou de riz basmati.",
         "Servir aussitôt, accompagné de pain ou de riz basmati."),
    ],
    "dal_pois_chiches_rotis_ff8cc6": [
        ("step-", "levure nutritionnelle pour un parfum fromagé"),
        ("step-", "les faire frire dans de l'huile d'olive après les avoir rôtis"),
        ("txt", " Servez-les dans un bol en terre cuite, garnis de quelques feuilles de persil frais et d'un filet d'huile d'olive.", ""),
    ],
    "dal_ragout_de_pois_chiches_moulus_f64412": [
        ("add", "vegetable_stock_dried", 9.4, "g", "ingredient"),
        ("add", "water", 750, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", ", jusqu'à ce qu'elle devienne liquide et brillante", " à feu moyen"),
        ("txt", "Ajoutez 300 g d'oignon émincé", "Ajoutez 150 g d'oignon émincé"),
        ("txt", "20 g de sauce berbere", "20 g de berbéré"),
        ("txt", "Versez le liquide de cuisson (bouillon végétal)", "Versez 750 ml de bouillon végétal"),
        ("txt", "avec 5 g de sel", "avec 2 g de sel"),
    ],
}
