"""Lot 8 : fin des dals et soupes de légumineuses, dashi, premiers desserts."""

PATCHES = {
    "dal_revithia_922f79": [
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("txt", "Arroser généreusement d'45 ml d'huile d'olive", "Arroser de 45 ml d'huile d'olive"),
        ("txt", "du jus de citron (environ 100g)", "40 ml de jus de citron"),
        ("txt", ", évoquant la fraîcheur de la mer Méditerranée", ""),
        ("txt", ", qui transporte les sens dans les paysages ensoleillés de la Grèce antique", ""),
        ("time", 13, 720, 195),
    ],
    "dal_sabzi_sabz_592004": [
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("add", "water", 150, "ml", "liquid"),
        ("qty", "yellow_onion_raw", 150),
        ("txt", "Presser le jus de 100g de citron", "Ajouter 40 ml de jus de citron"),
        ("txt", " et que les tiges sont croustillantes", ""),
        ("step-", "Ajouter un filet d'huile de tournesol pour donner"),
        ("step-", "Rectifier l'assaisonnement une dernière fois"),
    ],
    "dal_salade_de_lentilles_ethiopienn_5a9dd6": [
        ("qty", "water", 600),
        ("qty", "garlic_raw", 5),
        ("add", "lemon_juice", 20, "ml", "acid"),
        ("txt", "à frémissement doux, à 160°C,", "à frémissement doux,"),
        ("txt", "20 ml de crème de coco", "20 ml de lait de coco"),
        ("txt", "puis chauffer pendant 3 minutes à feu doux jusqu'à ce que le plat soit légèrement réchauffé et les saveurs bien mélangées",
         "puis laisser tiédir quelques minutes pour que les saveurs se mélangent"),
    ],
    "dal_salade_de_pois_chiches_2e32de": [
        ("qty", "chickpea_raw_dried", 250),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("txt", "Faire tremper 400g de pois chiches", "Faire tremper 250g de pois chiches secs"),
        ("txt", "le jus de 100g de citron", "40 ml de jus de citron"),
    ],
    "dal_sambar_581de8": [
        ("add", "water", 700, "ml", "liquid"),
        ("qty", "yellow_onion_raw", 150),
        ("qty", "coconut_oil_plant", 30),
        ("txt", "250 g de lentilles jaunes moelleuses", "250 g de lentilles corail"),
        ("txt", "chauffer 45 ml d'huile de coco et faire revenir 300 g d'oignon jaune", "chauffer 30 ml d'huile de coco et faire revenir 150 g d'oignon jaune"),
        ("txt", "20 g de poudre de sambar végétal", "20 g de poudre de sambar"),
        ("txt", "garni de feuilles de curry fraîches et de coriandre moulue pour ajouter une touche de fraîcheur et de couleur, accompagné de riz basmati cuit à la perfection ou des naans frais",
         "accompagné de riz basmati ou d'idlis"),
    ],
    "dal_sambar_indien_fcf6d8": [
        ("add", "yellow_mustard_spice_seed", 3, "g", "spice"),
        ("add", "curry_leaf", 5, "g", "herb"),
        ("add", "water", 700, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("qty", "coconut_oil_plant", 30),
        ("txt", "chauffer 45 ml d'huile de coco et faire revenir 300 g d'oignon", "chauffer 30 ml d'huile de coco et faire revenir 150 g d'oignon"),
        ("txt", "ajouter des légumes de saison (haricots verts, aubergine, tomate)", "ajouter les carottes"),
        ("txt", " et de noix de coco râpée si désiré", ""),
        ("step-", "Pour une présentation plus élégante, disposer les idlis"),
    ],
    "dal_shorbat_adas_d4f98a": [
        ("add", "paprika_powder", 3, "g", "spice"),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("qty", "onion_raw", 150),
        ("qty", "olive_oil_extra_virgin_plant", 30),
        ("qty", "table_salt_unenriched", 2),
        ("steps", [
            "Rincer 250 g de lentilles corail et les égoutter.",
            "Faire revenir 150 g d'oignon émincé et 200 g de carotte en dés dans 30 ml d'huile d'olive à feu moyen pendant 6 minutes, jusqu'à ce que l'oignon soit doré.",
            "Ajouter 9 g d'ail émincé, 3 g de cumin et 3 g de curcuma, puis cuire 1 minute en remuant.",
            "Verser les lentilles et 750 ml de bouillon de légumes, porter à ébullition puis cuire à feu doux 20 minutes, jusqu'à ce que les lentilles soient fondantes.",
            "Mixer la soupe pour obtenir une texture crémeuse, puis ajouter 40 ml de jus de citron et 2 g de sel.",
            "Préparer le tadka : chauffer 20 ml d'huile de coco, faire grésiller 3 g de paprika 20 secondes, puis le verser sur la soupe.",
            "Servir chaud avec du pain croustillant.",
        ]),
    ],
    "dal_soupe_de_lentilles_621239": [
        ("ing", "green_lentil_boiled", "green_lentil_dried", 150),
        ("qty", "garlic_raw", 10),
        ("txt", "Ajouter les 200g de lentilles vertes", "Ajouter 150g de lentilles vertes rincées"),
        ("txt", "accompagné de riz basmati ou de pain naan", "accompagné de pain"),
        ("step-", "levure nutritionnelle"),
    ],
    # lablabi : une soupe sans liquide dans la composition
    "dal_soupe_de_pois_chiches_tunisien_86e4b0": [
        ("add", "vegetable_stock_dried", 9.4, "g", "ingredient"),
        ("add", "water", 1000, "ml", "liquid"),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("qty", "table_salt_unenriched", 2),
        ("steps", [
            "Faire chauffer 30 ml d'huile d'olive à feu moyen, ajouter 9 g d'ail haché et 3 g de cumin, puis cuire 1 minute en remuant.",
            "Ajouter 400 g de pois chiches cuits, 1 litre d'eau et le bouillon en poudre. Porter à ébullition puis laisser mijoter 20 minutes.",
            "Mixer un tiers de la soupe pour lier le bouillon, puis ajouter 40 ml de jus de citron, 2 g de sel et 2 g de poivre.",
            "Répartir 150 g de pain rassis en morceaux dans les bols et verser la soupe bouillante par-dessus.",
            "Arroser des 15 ml d'huile d'olive restants, parsemer de coriandre fraîche et servir aussitôt.",
        ]),
        ("time", 15, 0, 25),
    ],
    "dal_soupe_lentilles_turque_e797cb": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("qty", "garlic_raw", 10),
        ("txt", "l'ail (2g)", "l'ail (10g)"),
        ("txt", ", en sentant son parfum subtil et en vérifiant que la température atteint 180°C", ""),
        ("txt", ", en sentant la vapeur chaude qui s'échappe et en vérifiant que la température atteint 95°C", ""),
        ("txt", "fondantes mais non écrasées, en vérifiant régulièrement que la lame ressort sèche et en sentant la texture qui se développe", "complètement fondantes"),
        ("step-", "levure nutritionnelle"),
    ],
    "dal_sri_lankan_dhal_curry_fae1be": [
        ("add", "vegetable_stock_dried", 7.5, "g", "ingredient"),
        ("add", "water", 600, "ml", "liquid"),
        ("ing", "lime_raw", "lime_juice_fresh", 40, "ml"),
        ("qty", "onion_raw", 150),
        ("qty", "sunflower_oil_plant", 30),
        ("txt", "dans un bouillon de légumes végétal", "dans 600 ml de bouillon de légumes"),
        ("txt", "Faites revenir 300g d'oignon et 9g d'ail dans 45ml", "Faites revenir 150g d'oignon et 9g d'ail dans 30ml"),
        ("txt", "puis laissez mijoter pendant 10 minutes à feu doux, jusqu'à ce que les légumes soient tendres", "puis laissez mijoter pendant 20 minutes à feu doux, jusqu'à ce que les légumes soient tendres"),
        ("txt", "le jus de 140g de citron vert", "40 ml de jus de citron vert"),
        ("step-", "Vous pouvez également ajouter d'autres légumes"),
        ("step-", "n'oubliez pas de partager ce délicieux curry"),
    ],
    "dal_tajine_pois_chiches_citron_047521": [
        ("add", "water", 100, "ml", "liquid"),
        ("qty", "onion_raw", 150),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "Ajouter 300 g d'oignon émincé", "Ajouter 150 g d'oignon émincé"),
        ("txt", "avec 5 g de sel", "avec 2 g de sel"),
    ],
    "dal_turkish_mercimek_soup_a7afcf": [
        ("ing", "red_lentil_boiled", "red_lentil_dried"),
        ("ing", "mint_fresh_herb", "dried_mint_herb", 3),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("qty", "onion_raw", 150),
        ("txt", "Faire chauffer l'beurre dans une casserole à feu moyen, puis ajouter l'oignon jaune et la carotte cuite en petits dés.",
         "Faire fondre 20g de beurre dans une casserole à feu moyen, puis ajouter l'oignon et la carotte en petits dés."),
        ("txt", "faire fondre les 40g de beurre, puis ajouter les 20g de menthe séchée et les 100g de jus de citron frais",
         "faire fondre les 20g de beurre restants et ajouter 3g de menthe séchée"),
        ("txt", "Servir la soupe chaude, en garnissant de la préparation à base de menthe et de citron. Décorer avec des feuilles de menthe fraîche pour un effet visuel appétissant.",
         "Ajouter 40 ml de jus de citron à la soupe et la servir chaude, arrosée du beurre à la menthe."),
    ],
    "base_dashi_broth_a3a517": [
        ("ing", "button_mushroom_raw", "shiitake_mushroom_dried"),
        ("txt", "15g de champignons de Paris séchés", "15g de champignons shiitake séchés"),
        ("txt", "du kombu et des champignons de Paris", "du kombu et des shiitakes"),
        ("txt", "2g de sel de mer végan", "2g de sel"),
        ("step-", "Vous pouvez également ajouter d'autres ingrédients végans"),
    ],
    "dessert_baklava_aux_pistaches_06e5ed": [
        ("txt", "Broyer les pistaches et les noix avec le sucre", "Broyer les pistaches et les noix avec 50 g de sucre"),
        ("txt", "Huiler un plat rectangulaire avec du beurre", "Beurrer un plat rectangulaire"),
        ("txt", "faire bouillir l'eau, le sucre, le sirop de dattes et l'eau de fleur d'oranger", "faire bouillir 150 ml d'eau, 150 g de sucre, le miel et l'eau de fleur d'oranger"),
        ("step-", "Goûter et rectifier l'assaisonnement, en ajoutant un peu de cannelle"),
        ("txt", "des pistaches concassées et un peu de sirop de dattes", "des pistaches concassées"),
        ("time", 30, 240, 45),
    ],
    "dessert_brownie_vegan_d4c6bd": [
        ("del", "white_sugar"),
        ("txt", "60ml de lait de coco", "60ml de lait d'amande"),
        ("txt", "Servir chaud, avec une texture fondante", "Servir tiède, avec une texture fondante"),
    ],
    "dessert_cannele_bordelais_c55eca": [
        ("steps", [
            "La veille, chauffer 500 ml de lait avec la vanille et 50 g de beurre jusqu'à ce que le beurre fonde. Laisser tiédir.",
            "Mélanger 100 g de farine et 250 g de sucre, puis ajouter 110 g d'œufs et 36 g de jaunes. Verser le lait tiède progressivement en fouettant, puis ajouter 50 ml de rhum.",
            "Couvrir et réfrigérer au moins 24 heures.",
            "Préchauffer le four à 250°C. Beurrer généreusement les moules en cuivre ou en silicone.",
            "Remuer la pâte, remplir les moules aux 3/4 et cuire 15 minutes à 250°C, puis 45 à 50 minutes à 190°C, jusqu'à ce que les cannelés soient bien bruns.",
            "Démouler aussitôt et laisser refroidir au moins 30 minutes sur une grille : la croûte doit être caramélisée et croustillante, l'intérieur fondant.",
        ]),
    ],
    "dessert_charlotte_aux_fraises_e3f32c": [
        ("qty", "ladyfinger", 190),
        ("ing", "lemon", "lemon_juice", 30, "ml"),
        ("qty", "white_sugar", 110),
        ("add", "water", 100, "ml", "liquid"),
        ("txt", "dans un sirop léger à base de sucre et d'eau", "dans un sirop léger (30 g de sucre dissous dans 100 ml d'eau)"),
        ("txt", "en émulsionnant 200ml de crème fraîche, 250g de fromage râpé, 80g de sucre", "en fouettant 200ml de crème fraîche, 250g de mascarpone, 80g de sucre"),
        ("txt", " Rectifier l'assaisonnement si nécessaire.", ""),
        ("txt", " La sauce doit être chaude et les fraises doivent être bien réparties.", ""),
    ],
    # base « biscuits digestifs » absente de la composition : pâte sablée maison
    "dessert_cheesecake_fruits_rouges_3460f6": [
        ("add", "wheat_all_purpose_flour_unenriched_unbleached", 120, "g", "base"),
        ("qty", "white_sugar", 190),
        ("flag", "gluten_free", False),
        ("serv", 10),
        ("txt", "Préparez la base en mixant 200 g de biscuits digestifs en poudre avec 80 g de beurre fondu.",
         "Préparez la base en sablant 120 g de farine avec 40 g de sucre et 80 g de beurre fondu, puis précuisez-la 10 minutes à 170°C."),
        ("txt", "battez 600 g de fromage avec", "battez 600 g de fromage frais avec"),
        ("txt", "ou jusqu'à ce que la lame d'un couteau ressorte sèche. Cela indique que le cheesecake est cuit et prêt à être dégusté.",
         "jusqu'à ce que le centre soit pris mais encore légèrement tremblotant."),
        ("txt", "nappez le cheesecake de coulis de fruits rouges et décorez-le avec des fruits frais", "décorez le cheesecake avec des fruits rouges frais"),
        ("step-", "Présentez le cheesecake avec fierté"),
        ("step-", "est un choix idéal pour toute occasion spéciale"),
        ("time", 30, 300, 65),
    ],
    "dessert_chia_pudding_coco_mangue_d61cff": [
        ("step-", "Servez sans attendre, car la chaleur et la fraîcheur"),
    ],
    "dessert_clafoutis_cerises_0731cf": [
        ("txt", "Servir chaud, dans des assiettes préchauffées, avec", "Servir tiède, avec"),
    ],
    "dessert_compote_de_pommes_maison_cdbdd0": [
        ("add", "water", 30, "ml", "liquid"),
    ],
    "dessert_cookie_chocolat_vegan_b9c6cc": [
        ("serv", 18),
        ("txt", "150 g d'huile fondue", "145 g de beurre végétal fondu"),
        ("txt", "pépites de chocolat noir à plus de 70% de cacao", "pépites de chocolat noir (au moins 40 % de cacao)"),
        ("step-", "Vérifier que les cookies sont croustillants sur les bords"),
        ("step-", "Servir sans attendre."),
    ],
    "dessert_creme_brulee_a19dfa": [
        ("qty", "white_sugar", 150),
        ("txt", ", en vous assurant qu'il est bien chaud avant de commencer", ""),
        ("txt", "pour éliminer toute impureté et obtenir une texture parfaite.", "puis répartir dans 6 ramequins."),
        ("txt", "puis saupoudrer de sucre et caraméliser", "puis saupoudrer de 30 g de sucre et caraméliser"),
        ("txt", "Servir aussitôt dans des ramequins, garni d'une touche de vanille et d'un filet de caramel.", "Servir dès que le caramel a durci."),
    ],
    "dessert_crepes_bretonnes_7b9835": [
        ("txt", "avec 5 g de sel", "avec une pincée de sel"),
        ("txt", "500 ml de lait froide", "500 ml de lait froid"),
        ("txt", "La galette doit être fine", "La crêpe doit être fine"),
        ("txt", " Garnir immédiatement avec un caramel au beurre salé, en prenant soin de ne pas trop en mettre pour ne pas détruire la texture délicate des crêpes.",
         " Garnir selon vos envies : sucre, confiture ou caramel au beurre salé."),
    ],
}
