"""Lot 10 : tartes, tiramisu, dips, raviolis (gyoza, momos, pierogi), plats aux œufs."""

PATCHES = {
    "dessert_tarte_pommes_normande_f10299": [
        ("txt", "Éplucher et couper 4 pommes en lamelles fines. Les disposer sur un plat et les saupoudrer de sucre pour éviter qu'elles ne brunissent.",
         "Éplucher et couper 600 g de pommes en lamelles fines, puis les réserver sur un plat."),
    ],
    "dessert_tarte_tatin_9c0f67": [
        ("txt", " puis les faire revenir dans une poêle avec un peu de beurre pour les rendre tendres", ""),
        ("txt", "dans une poêle allant au four à 180°C", "dans une poêle allant au four"),
        ("txt", "Servir tiède, décorée de quelques feuilles de persil frais.", "Servir tiède."),
    ],
    "dessert_tarte_tatin_vegan_1ae13b": [
        ("txt", "Faire fondre 60 g d'huile", "Faire fondre 90 g de beurre végétal"),
    ],
    # café soluble compté en 250 g au lieu des 5 g nécessaires à 250 ml d'espresso
    "dessert_tiramisu_classique_ea8ddb": [
        ("qty", "coffee_powder_instant", 5, "g"),
        ("add", "water", 250, "ml", "liquid"),
        ("txt", "en mélangeant 250 ml d'espresso avec 50 ml de marsala", "en dissolvant 5 g de café soluble dans 250 ml d'eau chaude, puis en ajoutant 50 ml de marsala"),
    ],
    "dip_baba_ghanoush_dbd030": [
        ("ing", "lemon", "lemon_juice", 30, "ml"),
        ("txt", " et parsemer de paprika, de persil et de sésame", ""),
        ("step-", "Préparer le pain pita"),
    ],
    "dip_guacamole_970186": [
        ("qty", "tomato_raw_ripe", 200),
        ("qty", "white_onion_raw", 60),
        ("ing", "coriander_spice_seed", "coriander_raw_fresh_herb", 10),
        ("ing", "lime_raw", "lime_juice_fresh", 30, "ml"),
        ("txt", "Incorporer le jus de 140 g de citron vert", "Incorporer 30 ml de jus de citron vert"),
        ("txt", "ajouter 300 g d'oignon blanc haché très fin", "ajouter 60 g d'oignon blanc haché très fin"),
        ("txt", "Ciseler 3 g de coriandre moulue", "Ciseler 10 g de coriandre fraîche"),
        ("txt", "Ajouter 480 g de tomates fraîches hachées", "Ajouter 200 g de tomates fraîches hachées"),
    ],
    "dip_hummus_classic_v6_u4k9p2": [
        ("ing", "lemon", "lemon_juice", 40, "ml"),
        ("add", "water", 80, "ml", "liquid"),
        ("txt", "faites-les cuire 1 heure à 100°C dans l'eau bouillante", "faites-les cuire 1 heure dans l'eau bouillante"),
    ],
    "dumpling_gyoza_92d264": [
        ("qty", "green_cabbage_raw", 200),
        ("qty", "tofu_plain_pre_packaged", 200),
        ("txt", "en cisellant 400 g de chou vert émincé, 400 g de tofu ferme émietté", "en cisellant 200 g de chou vert émincé, 200 g de tofu ferme émietté"),
        ("txt", "Mélangez avec 45 ml de sauce soja et 15 ml d'huile de sésame", "Mélangez avec 25 ml de sauce soja et 15 ml d'huile de sésame"),
        ("txt", "Faites dorer les gyoza à 200°C pendant 3 minutes", "Faites dorer les gyoza à feu moyen-vif pendant 3 minutes"),
    ],
    "dumpling_momos_aux_legumes_0adb23": [
        ("qty", "water", 120),
        ("add", "coconut_oil_plant", 15, "ml", "fat"),
        ("add", "ginger_raw_root_fresh", 10, "g", "aromatic"),
        ("txt", "de chaque disque de pâte préparée avec de la farine tout usage",
         "de chaque disque de pâte (200 g de farine pétrie avec 120 ml d'eau et une pincée de sel)"),
    ],
    "dumpling_pierogi_aux_champignons_d86017": [
        ("add", "water", 120, "ml", "liquid"),
        ("txt", "avec 55 g d'œuf et de l'eau tiède", "avec 55 g d'œuf et 120 ml d'eau tiède"),
    ],
    "dumpling_pierogi_aux_champignons_v_beca85": [
        ("qty", "tofu_plain_pre_packaged", 100),
        ("qty", "olive_oil_extra_virgin_plant", 60),
        ("add", "water", 120, "ml", "liquid"),
        ("txt", "Pétrir une pâte souple avec 300g de farine, 5g de sel et 30ml d'huile d'olive extra vierge",
         "Pétrir une pâte souple avec 300g de farine, 5g de sel, 120 ml d'eau tiède et 30ml d'huile d'olive extra vierge"),
    ],
    "dumpling_pierogi_aux_pommes_de_ter_24a890": [
        ("del", "tofu_plain_pre_packaged"),
        ("del", "olive_oil_extra_virgin_plant"),
        ("qty", "olive_oil_plant", 80),
        ("add", "nutmeg_spice", 1, "g", "spice"),
        ("add", "water", 100, "ml", "liquid"),
        ("txt", "Ajouter progressivement de l'eau tiède pour obtenir une pâte souple", "Ajouter progressivement 100 ml d'eau tiède pour obtenir une pâte souple"),
        ("txt", "accompagnés d'une sauce à base de crème de coco et de noix de muscade", "arrosés de 30 g de beurre végétal fondu et d'une pointe de muscade"),
    ],
    "dumpling_pierogi_pommes_de_terre_ca9985": [
        ("qty", "egg_raw", 55),
        ("add", "water", 80, "ml", "liquid"),
        ("txt", "une pincée de sel et un œuf dans un grand bol", "une pincée de sel et 55 g d'œuf dans un grand bol"),
        ("txt", "Faites cuire 600 g de pommes de terre cuites à l'eau", "Faites cuire 600 g de pommes de terre à l'eau"),
        ("txt", "Incorporer 150 g de fromage râpé", "Incorporer 150 g de fromage blanc"),
    ],
    "dumpling_vegetable_dumplings_abb853": [
        ("qty", "green_cabbage_raw", 150),
        ("qty", "carrot_raw", 100),
        ("qty", "button_mushroom_raw", 100),
        ("qty", "silken_tofu_pre_packaged", 150),
        ("qty", "white_onion_raw", 100),
        ("add", "water", 80, "ml", "liquid"),
        ("txt", "le chou vert (400g), les carottes crues (200g), les champignons de Paris (300g) et les oignons blancs (300g)",
         "le chou vert (150g), les carottes crues (100g), les champignons de Paris (100g) et les oignons blancs (100g)"),
        ("txt", "Ajoutez le tofu soyeux (400g)", "Ajoutez le tofu soyeux (150g)"),
        ("txt", " Ajoutez les feuilles de gingembre frais pour parfumer.", ""),
        ("step-", "Pour une présentation plus élégante, vous pouvez servir les dumplings"),
        ("step-", "Lorsque vous êtes prêt"),
    ],
    "egg_baursak_68b192": [
        ("qty", "egg_raw", 110),
        ("dish", "snack"),
        ("txt", "7g de levure sèche", "7g de levure fraîche"),
        ("txt", "Chauffer 250ml de lait animal", "Chauffer 250ml de lait"),
        ("txt", "220g d'œuf battu", "110g d'œuf battu"),
        ("txt", "Pétrir la pâte pendant 8 minutes à feu doux", "Pétrir la pâte pendant 8 minutes"),
        ("txt", "jusqu'à dorure blonde et crépite légèrement", "jusqu'à dorure blonde"),
    ],
    "egg_crepe_coreenne_aux_oignons_ver_356ac2": [
        ("qty", "egg_raw", 110),
        ("txt", "mélanger 200g de farine avec 150ml d'eau glacée, 1 yaourt battu et une pincée de sel",
         "mélanger 200g de farine avec 150ml d'eau glacée, 110 g d'œufs battus, 125 g de yaourt et une pincée de sel"),
        ("txt", "à feu moyen-vif, à une. Verser la pâte", "à feu moyen-vif. Verser la pâte"),
        ("txt", "servir avec une sauce trempette à base de sauce soja, vinaigre de riz, huile de sésame et graines de sésame. Cette sauce ajoutera une touche de saveur asiatique à votre crêpe.",
         "servir avec une sauce trempette à la sauce soja."),
    ],
    "egg_galettes_aux_oignons_verts_ff5328": [
        ("add", "table_salt_unenriched", 5, "g", "seasoning"),
        ("add", "water", 120, "ml", "liquid"),
        ("qty", "soy_sauce_shoyu_reduced_sodium", 20),
        ("txt", "avec 10 ml d'huile de sésame", "avec 10 ml d'huile"),
    ],
    "egg_galettes_de_pommes_de_terre_su_0d7814": [
        ("add", "dill_weed_fresh_herb_leaf", 5, "g", "herb"),
        ("txt", " et quelques lingonberries", ""),
    ],
    "egg_galettes_de_pommes_de_terre_tc_4f360c": [
        ("qty", "wheat_all_purpose_flour_unenriched_unbleached", 60),
        ("qty", "egg_raw", 110),
        ("txt", "Mélangez les pommes de terre râpées avec de la farine de blé, du sel, de l'ail émincé et des herbes fraîches comme la marjolaine, en ajoutant l'œuf.",
         "Mélangez les pommes de terre râpées avec 60 g de farine de blé, du sel, de l'ail émincé, de la marjolaine et 110 g d'œuf battu."),
        ("txt", "Servir aussitôt dans des assiettes préchauffées, garni de ciboulette ciselée et d'un filet d'huile d'olive. Accompagner de pain complet tiède.",
         "Servir aussitôt, garni de ciboulette ciselée."),
    ],
    "egg_khachapuri_134434": [
        ("ing", "parmesan_grated_dried_cow", "cows_milk_mozzarella_cow", 200),
        ("add", "bakers_yeast_fresh", 5, "g", "leavening"),
        ("txt", "Mélanger 200g de farine de blé avec de la levure et 200g de yaourt", "Mélanger 200g de farine avec 5g de levure fraîche émiettée et 200g de yaourt"),
        ("txt", "Pétrir pendant 8 minutes à feu moyen", "Pétrir pendant 8 minutes"),
        ("txt", "Émulsionner le fromage avec de la levure pour obtenir une texture lisse et crémeuse.",
         "Mélanger le fromage râpé avec 180 g d'œuf battu, en réservant un jaune pour la finition."),
        ("txt", "jusqu'à ce que la pâtisserie soit dorée et crémeuse", "jusqu'à ce que la pâte soit dorée"),
        ("txt", "accompagné d'un peu de beurre fondu et de coriandre ciselée", "avec une noisette de beurre au centre"),
    ],
    "egg_makdous_cf5efa": [
        ("txt", "Saisir les aubergines avec 45 ml d'huile d'olive, en les faisant tourner pour qu'elles soient uniformément enrobées, puis les farcir",
         "Fendre les aubergines et les farcir"),
        ("txt", "les couvrir d'huile d'olive chaude à 80°C", "les arroser des 45 ml d'huile d'olive tiède"),
        ("txt", "Servir les aubergines farcies sans attendre", "Servir les aubergines farcies à température ambiante"),
        ("time", 11, 10080, 25),
    ],
    "egg_menemen_681f60": [
        ("steps", [
            "Faire revenir l'oignon émincé et le poivron vert en dés dans 45 ml d'huile d'olive à feu moyen pendant 6 minutes, jusqu'à légère coloration dorée.",
            "Ajouter les tomates concassées et le paprika, puis assaisonner de sel et de poivre. Laisser mijoter 8 à 10 minutes à feu moyen, jusqu'à obtenir une sauce épaisse et concentrée.",
            "Casser les œufs directement dans la poêle sur la sauce chaude, sans les battre au préalable.",
            "Remuer délicatement à la spatule pour brouiller les œufs tout en les incorporant partiellement à la sauce, pendant 3 à 4 minutes : ils doivent rester crémeux et légèrement coulants.",
            "Servir sans attendre, directement dans la poêle, avec du pain turc.",
        ]),
    ],
    "egg_ojja_5bdbea": [
        ("qty", "onion_raw", 150),
        ("txt", "Ajouter 300 g d'oignon blanc émincé", "Ajouter 150 g d'oignon émincé"),
        ("txt", "saler et poivrer légèrement, puis mélanger délicatement pour éviter de casser les œufs", "saler et poivrer légèrement, sans mélanger"),
        ("txt", "Servir aussitôt dans des bols préchauffés, parsemé", "Servir aussitôt, parsemé"),
    ],
}
