"""Lot 27 : pad krapow, paella, pancit, plov, poivrons farcis, poke, risottos."""

PATCHES = {
    "rice_pad_krapow_63acfb": [
        ("qty", "sunflower_oil_plant", 30),
        ("qty", "egg_raw", 220),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "Faire chauffer 2 cuillères à soupe d'huile de tournesol", "Faire chauffer 30 ml d'huile de tournesol"),
        ("txt", "Ajouter 400g de tofu ferme émietté, blanchir 2 minutes, puis nacrer les légumes 3 minutes, jusqu'à ce qu'ils soient légèrement croquants et aient une texture tendre, en remuant régulièrement.",
         "Ajouter 400g de tofu ferme émietté et faire sauter 5 minutes à feu vif, en remuant régulièrement, jusqu'à ce qu'il soit doré."),
        ("txt", "Ajouter une pincée de 5g de sel", "Ajouter 2g de sel"),
        ("txt", "Ajouter 55g d'oeuf battu, puis remuer pendant environ 1 minute, jusqu'à ce que l'oeuf soit bien mélangé avec les autres ingrédients.",
         "Faire frire 4 œufs au plat (220 g) dans une poêle à part, jaune coulant, pour les déposer sur le riz au moment de servir."),
        ("step-", "Réduire le feu, laisser reposer 2 minutes avant de servir"),
    ],
    "rice_paella_veg_c7m3x1": [
        ("txt", "Ajouter 200 g de poivron et 260 g de tomates.", "Ajouter 200 g de poivron, 150 g de haricots verts en tronçons et 260 g de tomates."),
        ("txt", "Dissoudre 1 g de safran dans 2 cs d'eau chaude végétale.", "Dissoudre 1 g de safran dans 2 cs d'eau chaude."),
        ("txt", "Verser 900 ml d'eau chaude végétale dans la poêle.", "Verser 900 ml d'eau chaude dans la poêle."),
        ("step-", "Ajouter des légumes supplémentaires si désiré"),
        ("step-", "Servir chaud, en accompagnant d'une salade verte ou d'un légume cru"),
    ],
    "rice_pancit_bfd33e": [
        ("qty", "sesame_oil_plant", 20),
        ("qty", "table_salt_unenriched", 2),
        ("add", "sunflower_oil_plant", 25, "ml", "fat"),
        ("add", "green_onion_raw", 40, "g", "garnish"),
        ("add", "lemon_juice", 15, "ml", "condiment"),
        ("txt", "Chauffer 45ml d'huile de sésame dans une grande poêle", "Chauffer 25ml d'huile de tournesol dans une grande poêle"),
        ("txt", " Incorporer les légumes supplémentaires si désiré, comme des haricots verts ou des poivrons.", ""),
        ("txt", "Assaisonner avec du sel (5g)", "Assaisonner avec du sel (2g) et 20 ml d'huile de sésame"),
    ],
    "rice_plov_903de4": [
        ("ing", "olive_oil_extra_virgin_plant", "sunflower_oil_plant"),
        ("add", "water", 500, "ml", "liquid"),
        ("txt", "Chauffer 45ml d'huile d'olive extra vierge", "Chauffer 45ml d'huile de tournesol"),
        ("txt", "et 400g de pois chiches en deux.", "et égoutter 400g de pois chiches."),
        ("step-", "Présenter le plov dans un plat large"),
    ],
    "rice_poivrons_farcis_au_riz_be3ddc": [
        ("qty", "red_bell_pepper_raw", 700),
        ("txt", "accompagné d'une sauce légère ou d'un yaourt", "accompagné d'une sauce tomate légère"),
    ],
    "rice_poke_bowl_ee65ef": [
        ("qty", "avocado_raw", 200),
        ("qty", "cucumber_raw_with_skin", 200),
        ("qty", "table_salt_unenriched", 3),
        ("add", "white_sugar", 10, "g", "seasoning"),
        ("txt", "en l'assaisonnant de vinaigre de riz jusqu'à absorption complète, tout en vérifiant la texture et la couleur du riz",
         "puis l'assaisonner hors du feu avec 30 ml de vinaigre de riz, 10 g de sucre et 3 g de sel, et le laisser tiédir"),
        ("txt", "Enfourner les graines de sésame pendant 5 minutes à 180°C, jusqu'à parfum dégagé et légère coloration, en observant la couleur et la texture.",
         "Torréfier les graines de sésame à sec 2 minutes à la poêle, jusqu'à parfum dégagé et légère coloration."),
        ("txt", "Servir chaud, en vérifiant la présentation et la température du plat, pour un service immédiat et une dégustation optimale.",
         "Servir aussitôt, le riz tiède et les garnitures fraîches."),
    ],
    # 20 g de cèpes SÉCHÉS étaient comptés sur la table des cèpes frais
    "rice_risotto_ai_funghi_395f00": [
        ("qty", "porcini_mushroom_raw", 150),
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("txt", "Réhydrater 20 g de cèpes séchés dans 200 ml d'eau chaude pendant 20 minutes. Filtrer et réserver le liquide parfumé, riche en arômes de champignons.",
         "Émincer 150 g de cèpes frais, les faire revenir à sec 3 minutes dans une poêle chaude pour évaporer leur eau, puis les réserver."),
        ("txt", "Ajouter 150 g de riz Arborio", "Ajouter 280 g de riz Arborio"),
        ("txt", "Ajouter les cèpes réhydratés et 200 g de champignons frais", "Ajouter les cèpes réservés et 200 g de champignons frais"),
        ("txt", "Servir aussitôt dans des bols préchauffés.", "Servir aussitôt, garni de persil frais."),
        ("step-", "Garnir de feuilles de persil frais et de tranches de champignons"),
        ("step-", "Accompagner d'un filet d'olive vierge extra"),
    ],
    "rice_risotto_ai_funghi_vegan_41360e": [
        ("qty", "porcini_mushroom_raw", 150),
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("qty", "nutritional_yeast_flakes", 30),
        ("qty", "olive_oil_extra_virgin_plant", 40),
        ("del", "olive_oil_plant"),
        ("del", "vegan_butter"),
        ("txt", "Réhydrater 20 g de cèpes séchés dans 200 ml d'eau chaude pendant 20 minutes. Filtrer et réserver le liquide parfumé. Chauffer 750 ml de bouillon de légumes + liquide des cèpes à frémissement constant, en veillant à maintenir une température constante.",
         "Émincer 150 g de cèpes frais. Chauffer 750 ml de bouillon de légumes à frémissement constant."),
        ("txt", "Ajouter les cèpes réhydratés et 15 g d'ail haché", "Ajouter les cèpes émincés et 15 g d'ail haché"),
        ("txt", "Incorporer 320 g de riz arborio", "Incorporer 280 g de riz arborio"),
        ("txt", "monter avec 30 ml d'huile d'olive et 90 g de levure nutritionnelle (en remplacement du parmesan)",
         "monter avec 15 ml d'huile d'olive et 30 g de levure maltée (en remplacement du parmesan)"),
        ("txt", "Servir sans attendre, pour préserver la chaleur et le croustillant, dans des bols préchauffés, avec un filet d'huile d'olive et une garniture d'oignon ciselé. Accompagner de pain toasté pour un repas complet.",
         "Servir sans attendre, avec un filet d'huile d'olive."),
    ],
    "rice_risotto_al_limone_4088e5": [
        ("ing", "lemon", "lemon_juice", 20, "ml"),
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("txt", "Chauffer 800 ml de bouillon végétal à 80°C pour une cuisson homogène.", "Chauffer 800 ml de bouillon végétal et le maintenir frémissant."),
        ("txt", "Ajouter 150 g de riz Arborio", "Ajouter 280 g de riz Arborio"),
    ],
    "rice_risotto_al_limone_vegan_a234ae": [
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("qty", "nutritional_yeast_flakes", 30),
        ("qty", "olive_oil_extra_virgin_plant", 40),
        ("qty", "table_salt_unenriched", 3),
        ("del", "olive_oil_plant"),
    ],
    "rice_risotto_aux_champignon_25ed38": [
        ("qty", "porcini_mushroom_raw", 150),
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("qty", "butter_sup80pct", 45),
        ("qty", "parmesan_grated_dried_cow", 40),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "Réhydratez 20 g de cèpes séchés dans 200 ml d'eau chaude pendant 20 minutes. Filtrez et réservez le liquide.",
         "Émincez 150 g de cèpes frais."),
        ("txt", "Faites revenir les champignons frais émincés dans 20 g de beurre", "Faites revenir les champignons et les cèpes émincés dans 20 g de beurre"),
        ('del', 'olive_oil_plant'),
        ('txt', 'Assaisonnez avec du sel et du poivre noir, et ajustez la saveur si nécessaire.', 'Assaisonnez avec 2 g de sel et du poivre noir.'),
    ],
    "rice_risotto_aux_champignons_v_13d611": [
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("qty", "nutritional_yeast_flakes", 30),
        ("qty", "olive_oil_extra_virgin_plant", 40),
        ("qty", "parsley_fresh_herb", 15),
        ("qty", "vegan_butter", 20),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Ajouter 320 g de riz arborio", "Ajouter 280 g de riz arborio"),
        ("txt", "ajouter 60 g de levure nutritionnelle et 30 g de beurre végétal", "ajouter 30 g de levure maltée et 20 g de beurre végétal"),
        ("txt", "garni de feuilles de persil frais et de tranches de citron, en profitant de la chaleur et de la fraîcheur des saveurs.",
         "garni de feuilles de persil frais."),
    ],
    "rice_risotto_citron_asperges_f2f765": [
        ("ing", "green_asparagus_boiled", "green_asparagus_raw"),
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("txt", "Ajouter 150g de riz arborio", "Ajouter 280g de riz arborio"),
        ("txt", "monter avec 20g de beurre fondu pour donner une texture crémeuse, en battant énergiquement pour incorporer l'air et rendre le risotto léger.",
         "monter avec 20g de beurre froid en dés pour donner une texture crémeuse."),
        ("step-", "Conserver les restes au réfrigérateur"),
    ],
    "rice_risotto_citron_asperges_v_e20e67": [
        ("qty", "white_rice_raw_seed_unenriched", 280),
        ("qty", "nutritional_yeast_flakes", 30),
        ("qty", "olive_oil_extra_virgin_plant", 40),
        ("qty", "asparagus_raw", 300),
        ("qty", "vegan_butter", 20),
        ("qty", "table_salt_unenriched", 3),
    ],
}
