"""Lot 30 : biryani coco, pulao, sushi, riz blanc, achichuk, salades andines, shopska."""

PATCHES = {
    # titré « à la noix de coco » sans noix de coco hors huile
    "rice_vegetable_biryani_160da2": [
        ("add", "coconut_milk_plant", 200, "ml", "liquid"),
        ("qty", "potato_raw_flesh", 400),
        ("txt", "les pommes de terre (600g)", "les pommes de terre (400g)"),
        ("txt", "Parsemer d'oignons frits et de coriandre fraîche (10g).", "Arroser de 200 ml de lait de coco, puis parsemer de coriandre fraîche (10g)."),
    ],
    "rice_vegetable_pulao_a0ed3e": [
        ("ing", "coconut_oil_plant", "sunflower_oil_plant"),
        ("ing", "snow_peas_raw", "green_peas_raw"),
        ("qty", "red_bell_pepper_raw", 150),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Faire chauffer 45 ml d'huile de coco", "Faire chauffer 45 ml d'huile de tournesol"),
        ("txt", "Incorporer 320 g de poivron rouge, 200 g de pois mange-tout", "Incorporer 150 g de poivron rouge, 200 g de petits pois"),
    ],
    # avocat 400 g + tofu 400 g : 706 kcal pour des makis
    "rice_vegetable_sushi_9aad8a": [
        ("qty", "avocado_raw", 200),
        ("qty", "tofu_plain_pre_packaged", 200),
        ("qty", "cucumber_raw_with_skin", 200),
        ("add", "soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
        ("txt", "Ciseler les avocats, les concombres et les carottes en bâtonnets réguliers de 5 mm, les faire julienne.",
         "Tailler l'avocat, le concombre et la carotte en bâtonnets réguliers de 5 mm. Couper le tofu en longues lanières et le saisir 2 minutes à la poêle dans 15 ml d'huile de sésame."),
        ("txt", "Servir frais, accompagné de sauce soja et de wasabi, jusqu'à crépitation légère.", "Servir frais, accompagné de 30 ml de sauce soja."),
        ("step-", "Ajouter des légumes supplémentaires, tels que du tofu ferme"),
        ("step-", "Présenter le sushi sur un plat ou un bol"),
    ],
    "rice_white_k1d1p1": [
        ("txt", "avec 1,2 fois le volume d'eau froide", "avec 450 ml d'eau froide (1,5 fois son volume)"),
        ("txt", "Servez chaud dans des assiettes préchauffées.", "Servez chaud."),
    ],
    "salad_achichuk_e3f0c9": [
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Julienne les tomates fraîches en fines lanières et les concombres en demi-lunes jusqu'à obtenir des morceaux réguliers, avec une texture ferme et une couleur vibrante, en prenant soin de conserver leur fraîcheur et leur humidité.",
         "Couper les tomates en fines tranches et les concombres en demi-lunes régulières."),
        ("txt", "Émincer l'oignon jaune en fines rondelles, rincer 2 min à l'eau froide pour enlever l'âcreté et blanchir légèrement, jusqu'à ce qu'il devienne translucide et perde son odeur piquante, en faisant attention à ne pas le rendre trop mou.",
         "Émincer l'oignon jaune en fines rondelles et le rincer 2 minutes à l'eau froide pour enlever son âcreté."),
        ("txt", "Brounoise les poivrons rouges en petits dés", "Tailler les poivrons rouges en petits dés"),
        ("txt", "assaisonner avec 5g de sel", "assaisonner avec 3g de sel"),
        ("txt", "Servir sans attendre, en garnissant de feuilles de persil frais et en accompagnant d'un pain croustillant, pour un repas léger et savoureux, car la fraîcheur des ingrédients et la texture du pain sont essentielles à cette salade, et il est important de servir immédiatement pour conserver toutes les saveurs et les textures.",
         "Servir sans attendre, garni de feuilles de persil frais et accompagné de pain croustillant."),
        ('dish', 'side'),
    ],
    # parmesan 150 g à la place du queso fresco, maïs cru
    "salad_andine_au_fromage_c537bd": [
        ("ing", "parmesan_grated_dried_cow", "queso_fresco_block_cow", 120),
        ("ing", "sweet_corn_raw_fresh", "sweet_corn_on_the_cob_cooked"),
        ("qty", "avocado_raw", 200),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Ciseler finement les oignons rouges pendant 2 minutes, jusqu'à ce qu'ils soient translucides et dégagent une odeur sucrée, puis les laisser refroidir.",
         "Émincer finement les oignons rouges et les rincer à l'eau froide. Égrener le maïs cuit."),
        ("txt", "Julienne les tomates fraîches pendant 2 minutes, jusqu'à ce qu'elles soient tendres et légèrement foncées, en prenant soin de ne pas les écraser.",
         "Couper les tomates en dés réguliers."),
        ("txt", "Broyer les avocats mûrs pendant 1 minute, jusqu'à ce qu'ils soient crémeux et aient une texture onctueuse, en utilisant une fourchette pour obtenir une consistance lisse.",
         "Couper les avocats en dés."),
        ("txt", "50 ml d'huile d'olive, 25 ml de vinaigre de vin blanc", "45 ml d'huile d'olive, 30 ml de vinaigre de vin blanc"),
        ("step-", "Réduire la vinaigrette à feu doux"),
        ("txt", "les oignons rouges et le parmesan râpé", "les oignons rouges et le queso fresco émietté"),
        ("time", 17, 0, 0),
    ],
    "salad_andine_au_fromage_vegan_566f05": [
        ("ing", "sweet_corn_raw_fresh", "sweet_corn_on_the_cob_cooked"),
        ("qty", "avocado_raw", 200),
        ("qty", "base_vegan_cheddar_024998", 120),
        ("qty", "olive_oil_plant", 45),
        ("qty", "white_vinegar_liquid_distilled", 30),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Couper 300 g de maïs en morceaux réguliers, 150 g d'oignon rouge en fines lamelles et 300 g de tomates en dés",
         "Égrener 300 g de maïs cuit, couper 150 g d'oignon rouge en fines lamelles et 300 g de tomates en dés"),
        ("txt", "Couper 400 g d'avocat en dés", "Couper 200 g d'avocat en dés"),
        ("txt", "Mélanger 46.2 ml d'huile d'olive, 29.7 ml de vinaigre de vin blanc", "Mélanger 45 ml d'huile d'olive, 30 ml de vinaigre de vin blanc"),
        ("txt", "Assaisonner avec 5 g de sel", "Assaisonner avec 3 g de sel"),
        ("txt", "Ajouter 150 g de fromage végétal râpé", "Ajouter 120 g de fromage végétal râpé"),
    ],
    "salad_asiatique_sesame_948f03": [
        ("qty", "soy_sauce_shoyu_reduced_sodium", 30),
        ("qty", "table_salt_unenriched", 2),
        ("add", "vinegar_liquid", 15, "ml", "condiment"),
        ("txt", "mélanger 15ml d'huile de sésame, 45ml de sauce soja, et 15g de gingembre râpé",
         "mélanger 15ml d'huile de sésame, 30ml de sauce soja, 15 ml de vinaigre de riz et 15g de gingembre râpé"),
        ("step-", "Laisser reposer 5 minutes pour permettre aux saveurs"),
        ('dish', 'side'),
    ],
    "salad_bulgarian_shopska_salad_v_adc716": [
        ("qty", "olive_oil_plant", 45),
        ("qty", "white_vinegar_liquid_distilled", 30),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Assaisonner avec 46,2 ml d'huile d'olive, 29,7 ml de vinaigre de vin blanc", "Assaisonner avec 45 ml d'huile d'olive, 30 ml de vinaigre de vin blanc"),
        ("txt", "Mélanger délicatement avec 150g de fromage végétal râpé, en veillant à ce qu'il soit bien réparti. Servir frais dans un bol, garni de quelques feuilles de persil frais.",
         "Parsemer de 150 g de tofu ferme émietté (en remplacement du sirene) et servir frais."),
    ],
}
