"""Lot 31 : caprese, salades chilienne, attiéké, aubergines, kısır, papaye, Kartoffelsalat."""

PATCHES = {
    "salad_caprese_classic_k21x9d": [
        ("qty", "basil_fresh_herb", 15),
        ("dish", "starter"),
        ("txt", "Sortir le mozzarella du réfrigérateur 20 minutes avant pour qu'il atteigne", "Sortir la mozzarella du réfrigérateur 20 minutes avant pour qu'elle atteigne"),
        ("txt", "Égoutter le mozzarella (250g)", "Égoutter la mozzarella (250g)"),
        ("txt", "les feuilles de basilic frais (100g)", "les feuilles de basilic frais (15g)"),
        ("step-", "Vérifier que les tomates sont tendres"),
        ("txt", "Servir sans attendre, car la chaleur et le croustillant du mozzarella sont essentiels à l'expérience gustative de cette salade végétarien.",
         "Servir sans attendre."),
    ],
    "salad_chilienne_tomateoignon_288941": [
        ("ing", "coriander_spice_seed", "coriander_raw_fresh_herb", 10),
        ("ing", "lemon_raw", "lemon_juice", 10, "ml"),
        ("qty", "table_salt_unenriched", 3),
        ("dish", "side"),
        ("txt", "les saler généreusement avec 5 g de sel", "les saler avec 3 g de sel"),
        ("txt", "Préparer la vinaigrette en mélangeant 10 ml de jus de citron, 45 ml d'huile d'olive, du sel et du poivre.",
         "Préparer la vinaigrette en mélangeant 10 ml de jus de citron et 45 ml d'huile d'olive."),
        ("txt", "Ciseler la coriandre fraîche jusqu'à obtenir des morceaux fins et parfumés, libérant ainsi tous les arômes de cette herbe aromatique.",
         "Ciseler finement 10 g de coriandre fraîche."),
    ],
    # vinaigrette à l'huile de coco (fige à froid), pita tiède, levure nutritionnelle
    "salad_dattieke_7824bf": [
        ("ing", "coconut_oil_plant", "sunflower_oil_plant"),
        ("ing", "lemon_raw", "lemon_juice", 50, "ml"),
        ("add", "coriander_raw_fresh_herb", 10, "g", "herb"),
        ("txt", "ciselez la coriandre ou le persil jusqu'à obtenir une texture fine, vous pouvez sentir le parfum frais des herbes",
         "ciselez finement 10 g de coriandre"),
        ("txt", "Préparez la vinaigrette en dissolvant une pincée de sel dans le jus de citron, puis ajoutez l'huile de noix de coco",
         "Préparez la vinaigrette en dissolvant 5 g de sel dans 50 ml de jus de citron, puis ajoutez 45 ml d'huile de tournesol"),
        ("step-", "Ajoutez un peu de levure nutritionnelle"),
        ("step-", "Vous pouvez garnir la salade de feuilles de coriandre"),
        ("step-", "Servir aussitôt, garni de coriandre ciselée et d'un filet d'huile de noix de coco"),
    ],
    "salad_daubergine_philippine_6f16b2": [
        ("qty", "sesame_oil_plant", 15),
        ("qty", "table_salt_unenriched", 3),
        ("txt", ", du vinaigre blanc et de la sauce soja.", " et du vinaigre blanc."),
        ("step-", "Faire cuire le mélange pendant 5 minutes à feu moyen"),
        ("step-", "Servir, garni d'un filet d'huile de sésame et d'une touche de coriandre"),
        ('dish', 'side'),
    ],
    # zaalouk : pas d'oignon, jus de citron cité mais absent
    "salad_daubergines_marocaine_03fd77": [
        ("del", "onion_raw"),
        ("add", "lemon_juice", 20, "ml", "condiment"),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Assaisonner de jus de citron, 5 grammes de sel", "Assaisonner de 20 ml de jus de citron, 3 grammes de sel"),
        ("step-", "Vérifier que la salade ait des notes fumées"),
        ("step-", "Ajouter des feuilles de persil frais hachées et des olives noires"),
        ('dish', 'side'),
    ],
    # kısır : oignon cru, concentré de tomate (présent mais jamais utilisé)
    "salad_de_boulgour_turque_f80124": [
        ("ing", "lemon_raw", "lemon_juice", 50, "ml"),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "laisser tiédir jusqu'à coloration blonde claire et texture légèrement sèche.", "laisser tiédir."),
        ("txt", "Saisir les oignons et les poivrons dans 20 ml d'huile d'olive à feu moyen, pendant environ 10 minutes, jusqu'à légère dorure et parfum caramélisé.",
         "Incorporer 20 g de concentré de tomate au boulgour tiède et bien mélanger pour le colorer uniformément."),
        ("txt", "Émulsionner la vinaigrette avec 100 grammes de jus de citron, 25 ml d'huile d'olive et 30 grammes de persil frais haché, réduire de moitié en remuant vivement pendant 2 minutes.",
         "Émulsionner la vinaigrette avec 50 ml de jus de citron, 45 ml d'huile d'olive et 30 grammes de persil frais haché."),
        ("txt", "en ajoutant 5 grammes de sel si nécessaire", "en ajoutant 3 grammes de sel"),
        ("time", 17, 20, 0),
    ],
    "salad_de_papaye_vietnamienne_add574": [
        ("ing", "lime_raw", "lime_juice_fresh", 60, "ml"),
        ("add", "coriander_raw_fresh_herb", 10, "g", "herb"),
        ("txt", "puis les plonger dans un bain d'eau glacée pour stopper la cuisson et conserver leur croquant",
         "puis les plonger 10 minutes dans l'eau glacée pour les rendre bien croquantes"),
        ("txt", "10g de sucre et le jus de 140g de citron vert", "10g de sucre et 60 ml de jus de citron vert"),
        ("step-", "Réduire la vinaigrette si nécessaire"),
        ("txt", "Servir sans attendre, en présentant la salade dans des bols individuels,", "Servir sans attendre, parsemé de 10 g de coriandre fraîche ciselée,"),
        ("time", 15, 10, 0),
        ('dish', 'side'),
        ("ing", "papaya_raw", "green_papaya"),  # fiche papaye verte ajoutée le 2026-09-22
    ],
    "salad_de_pommes_de_terre_allema_3cdeab": [
        ("ing", "olive_oil_extra_virgin_plant", "sunflower_oil_plant"),
        ("add", "vegetable_stock_dried", 1.3, "g", "ingredient"),
        ("add", "water", 100, "ml", "liquid"),
        ("txt", "dans l'eau bouillante salée à 100°C pendant 20 minutes", "dans l'eau bouillante salée pendant 20 minutes"),
        ("txt", "faites chauffer l'huile d'olive extra vierge à feu moyen", "faites chauffer 45 ml d'huile de tournesol à feu moyen"),
        ("txt", "et un peu de bouillon végétal. Remuez constamment pour éviter les grumeaux et faire épaissir la sauce.",
         "et 100 ml de bouillon végétal chaud. Porter à frémissement."),
    ],
}
