"""Lot 32 : kongnamul, quinoa, fattoush, gado-gado, grecques, mechouia, lentilles, niçoise, lyonnaise, shopska, taboulé."""

PATCHES = {
    # kongnamul : ni moutarde de Dijon ni sauce réduite
    "salad_de_pousses_de_soja_coreen_d07502": [
        ("del", "mustard"),
        ("qty", "soy_sauce_shoyu_reduced_sodium", 30),
        ("qty", "red_hot_chili_pepper_spice_dried", 3),
        ("qty", "sesame_raw_seed", 20),
        ("txt", "Émulsionner 45ml de sauce soja, 15g de moutarde de Dijon, 10g de piment coréen et 20g de graines de sésame dans un bol, en remuant vigoureusement, jusqu'à obtenir une sauce lisse et homogène.",
         "Mélanger dans un bol 30ml de sauce soja, 3g de piment coréen, l'ail revenu avec son huile et 20g de graines de sésame torréfiées."),
        ("step-", "Réduire la sauce soja pendant 2 minutes"),
        ("step-", "Ciseler 10g de graines de sésame supplémentaires"),
        ("txt", "Servir sans attendre, parsemé de sésame croustillant.", "Servir frais ou à température ambiante."),
        ("time", 11, 0, 5),
    ],
    "salad_de_quinoa_e74dea": [
        ("ing", "lemon_raw", "lemon_juice", 50, "ml"),
        ("txt", "dissoudre le sel dans 100g de jus de citron frais", "dissoudre 5 g de sel dans 50 ml de jus de citron frais"),
    ],
    "salad_fattoush_classic_x82m5c": [
        ("ing", "lemon", "lemon_juice", 60, "ml"),
        ("qty", "pain_pita", 200),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Toaster les morceaux de pain pita dans 25 ml d'huile d'olive", "Toaster 200 g de pain pita en morceaux avec 25 ml d'huile d'olive"),
        ("txt", "en mélangeant 60 g de jus de citron", "en mélangeant 60 ml de jus de citron"),
        ("step-", "Pour une touche finale, ajouter un peu de levure nutritionnelle"),
        ("step-", "Servir, garni de persil plat ciselé et d'un filet d'huile d'olive"),
    ],
    "salad_gadogado_indonesien_vegan_e4cd75": [
        ("del", "vegan_butter"),
        ("ing", "lime_raw", "lime_juice_fresh", 50, "ml"),
        ("qty", "potato_raw_flesh", 400),
        ("qty", "tofu_plain_pre_packaged", 300),
        ("qty", "soy_sauce_shoyu_reduced_sodium", 30),
        ("qty", "table_salt_unenriched", 2),
        ("add", "mung_bean_sprouts_raw_seed_sprouted", 150, "g", "vegetable"),
        ("add", "base_fried_onion_217e6a", 20, "g", "garnish"),
        ("add", "coconut_sugar", 10, "g", "sweetener"),
        ("txt", "50 ml de jus de citron, 1 cuillère à café de pâte de piment et 10 g de sucre de palme", "50 ml de jus de citron vert et 10 g de sucre de palme"),
        ("txt", "Cuire les 600 g de pommes de terre", "Cuire les 400 g de pommes de terre"),
        ("txt", "Presser le 400 g de tofu ferme", "Presser les 300 g de tofu ferme"),
        ("txt", "et préparer les pousses de soja", "et rincer 150 g de pousses de soja"),
        ("txt", "Parsemer d'oignons frits croustillants et de chips de krupuk.", "Parsemer de 20 g d'oignons frits croustillants."),
        ("txt", "Servir aussitôt, garni de feuilles de coriandre fraîche ciselée et accompagné de crackers de riz.", "Servir aussitôt."),
    ],
    "salad_grecque_classique_vegan_a9f9a4": [
        ("ing", "lemon_raw", "lemon_juice", 30, "ml"),
        ("qty", "olive_oil_plant", 45),
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("txt", "en mélangeant 46,2 ml d'huile d'olive", "en mélangeant 45 ml d'huile d'olive"),
        ("txt", "Ajouter 150 g de fromage végétal émietté, tel que du tofu ou des légumes grillés, et l'incorporer dans la salade pour ajouter une touche de saveur et de texture.",
         "Parsemer de 150 g de tofu ferme émietté (en remplacement de la feta)."),
        ("txt", "Assaisonner de sel et de poivre à votre goût, en ajustant la quantité pour équilibrer les saveurs et obtenir la saveur désirée.",
         "Assaisonner avec 3 g de sel et du poivre."),
    ],
    "salad_greek_classic_v2_t4m8q1": [
        ("qty", "black_olive_canned_in_oil", 60),
        ("qty", "table_salt_unenriched", 1),
        ("step-", "Vérifier que les légumes sont fermes et croquants"),
        ("txt", "en garnissant de feuilles de persil frais et en ajoutant une légère touche d'huile d'olive", "avec une légère touche d'huile d'olive"),
        ("step-", "Assaisonner au goût, en ajoutant éventuellement un peu de sel"),
    ],
    # mechouia : légumes grillés hachés, piments, ail ; étapes incohérentes
    "salad_grillee_tunisienne_dcb033": [
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("add", "chilli_pepper_raw", 30, "g", "spice"),
        ("add", "garlic_raw", 10, "g", "aromatic"),
        ("flag", "kid_friendly", False),
        ("steps", [
            "Griller les poivrons, les piments, les tomates et l'oignon entiers sous le gril du four à 250°C pendant 25 minutes, en les retournant, jusqu'à ce que la peau soit noircie.",
            "Les enfermer 10 minutes dans un saladier couvert, puis les peler et les épépiner.",
            "Hacher finement les légumes grillés au couteau.",
            "Piler 10 g d'ail avec 3 g de cumin et 5 g de sel.",
            "Mélanger les légumes hachés avec l'ail pilé, 40 ml de jus de citron et 45 ml d'huile d'olive.",
            "Servir tiède ou froid, avec du pain.",
        ]),
    ],
    # lentilles corail « entières » en salade : ce sont des lentilles vertes
    "salad_lentil_classic_v3_r7p2k8": [
        ("ing", "red_lentil_dried", "green_lentil_dried"),
        ("add", "parsley_fresh_herb", 10, "g", "herb"),
        ("txt", "Rincer 250g de lentilles corail", "Rincer 250g de lentilles vertes"),
        ("step-", "Vérifier que les lentilles sont entières"),
        ("txt", ", car la chaleur et le croustillant de l'oignon jaune sont essentiels pour cette salade végane de lentilles, garnie de feuilles de persil ou de ciboulette pour une présentation appétissante.",
         ", garnie de 10 g de persil ciselé."),
        ("step-", "Pour une touche finale, vous pouvez ajouter des noix"),
    ],
    "salad_mexicaine_aux_haricots_949e62": [
        ("ing", "coriander_spice_seed", "coriander_raw_fresh_herb", 10),
        ("ing", "lime_raw", "lime_juice_fresh", 40, "ml"),
        ("qty", "avocado_raw", 200),
        ("add", "cumin_spice_seed", 2, "g", "spice"),
        ("txt", "Saisir les haricots noirs pendant 2 minutes à feu vif, puis les égoutter et les sécher légèrement sur un torchon pour éviter l'excès d'humidité.",
         "Rincer et égoutter les haricots noirs cuits, puis les sécher légèrement sur un torchon."),
        ("txt", "puis le citronner immédiatement avec du jus de citron vert pour éviter l'oxydation, jusqu'à coloration verte uniforme",
         "puis l'arroser d'un peu de jus de citron vert pour éviter l'oxydation"),
        ("txt", "du jus de 2 citrons verts, 1 cc de cumin, du sel, du poivre et une pointe de piment", "40 ml de jus de citron vert, 2 g de cumin, 5 g de sel et du poivre"),
        ("txt", ", jusqu'à son crépitement léger et la cohésion des saveurs", ""),
        ("time", 15, 10, 0),
    ],
    "salad_mixed_structured_v2_p9x4m2": [
        ("txt", "assaisonner avec du poivre de Cayenne au goût, pour ajouter une touche de piquant,", "poivrer,"),
        ("txt", ", et en vérifiant que la salade soit servie à une température de 10°C pour une meilleure fraîcheur", ""),
        ("step-", "Garnir de feuilles de persil frais et de fleurs comestibles"),
        ("step-", "Déguster et ajuster l'assaisonnement si nécessaire"),
    ],
    # 220 g d'œufs jamais utilisés dans une niçoise
    "salad_nicoise_3b123f": [
        ("txt", "Disposer 300g de laitue, les tomates, les haricots verts, le tofu, et 80g d'olives",
         "Cuire les 220 g d'œufs 9 minutes à l'eau bouillante, les écaler et les couper en quartiers. Disposer 300g de laitue, les tomates, les haricots verts, le tofu, les œufs et 80g d'olives"),
        ("step-", "Rectifier l'assaisonnement si nécessaire et servir sans attendre"),
    ],
    # 4 ml d'huile, 2 ml de vinaigre pour 4 ; frisée comptée en endive
    "salad_salade_lyonnaise_f54cfd": [
        ("ing", "endive_raw", "green_chicory_raw"),
        ("qty", "olive_oil_plant", 30),
        ("qty", "red_wine_vinegar_liquid", 15),
        ("qty", "mustard", 10),
        ("add", "table_salt_unenriched", 2, "g", "seasoning"),
        ("txt", "dans 4ml d'huile d'olive", "dans 15ml d'huile d'olive"),
        ("txt", "dans un peu d'huile d'olive pendant 1 minute", "dans 15ml d'huile d'olive pendant 1 minute"),
        ("txt", "avec 2ml de vinaigre de vin rouge", "avec 15ml de vinaigre de vin rouge"),
        ("txt", "Ajouter 4,5ml de moutarde de Dijon", "Ajouter 10ml de moutarde de Dijon"),
        ("txt", "en ajoutant un peu de sel ou de poivre", "en ajoutant 2 g de sel et du poivre"),
    ],
    "salad_salade_mache_aux_noix_081567": [
        ("qty", "walnut_oil_plant", 30),
        ("qty", "balsamic_vinegar_liquid", 10),
        ("qty", "mustard", 5),
        ("txt", "3g d'huile de noix, 1g de vinaigre balsamique et 15g de moutarde de Dijon", "30g d'huile de noix, 10g de vinaigre balsamique et 5g de moutarde de Dijon"),
    ],
    # shopska : huile + vinaigre, sans citron ni moutarde
    "salad_shopska_04dd73": [
        ("ing", "lemon_raw", "red_wine_vinegar_liquid", 20, "ml"),
        ("del", "mustard"),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "45 millilitres d'huile d'olive, 100 grammes de jus de citron frais, 5 grammes de sel et 15 grammes de moutarde de Dijon",
         "45 millilitres d'huile d'olive, 20 millilitres de vinaigre de vin rouge et 2 grammes de sel"),
        ("txt", "Servir sans attendre, en garnissant de feuilles de persil frais ou de croûtons croustillants pour ajouter une touche de fraîcheur et de croustillant à la salade.",
         "Servir sans attendre."),
    ],
    "salad_shopska_vegan_001f9e": [
        ("ing", "lemon_raw", "red_wine_vinegar_liquid", 20, "ml"),
        ("del", "mustard"),
        ("qty", "olive_oil_plant", 45),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "assaisonner avec 46,2ml d'huile d'olive, 30ml de jus de citron frais, 5g de sel et 15g de moutarde de Dijon",
         "assaisonner avec 45 ml d'huile d'olive, 20 ml de vinaigre de vin rouge et 3 g de sel"),
        ("txt", " très finement, pour éviter la texture croquante,", " finement,"),
        ("txt", "avec 150g de fromage végétal émietté", "avec 150g de tofu ferme émietté"),
    ],
    # concombre 350 g jamais utilisé (absent du taboulé libanais)
    "salad_tabbouleh_f7x2p9": [
        ("del", "cucumber_raw_with_skin"),
        ("ing", "lemon", "lemon_juice", 50, "ml"),
        ("txt", "un filet d'huile d'olive chaude qui crépite légèrement", "45 ml d'huile d'olive"),
        ("txt", "Ajouter un filet de jus de citron frais", "Ajouter 50 ml de jus de citron frais"),
    ],
}
