"""Lot 36 : snacks (bannock → sandwich végétarien)."""

PATCHES = {
    # 500 ml d'eau pour 200 g de farine, sans levure
    "snack_bannock_vegan_46a1a8": [
        ("qty", "water", 150),
        ("qty", "table_salt_unenriched", 3),
        ("add", "baking_powder", 10, "g", "leavening"),
        ("add", "sunflower_oil_plant", 10, "ml", "fat"),
        ("serv", 4),
        ("txt", "mélangez 200g de farine et 5g de sel", "mélangez 200g de farine, 10 g de levure chimique et 3g de sel"),
        ("txt", "Versez 500ml d'eau petit à petit", "Versez 150ml d'eau petit à petit"),
        ("txt", "avec un peu d'huile, jusqu'à ce qu'elle brille", "avec 10 ml d'huile, jusqu'à ce qu'elle brille"),
        ("txt", "Servez chaud avec de la confiture ou de la charcuterie végétale, en profitant de la texture croustillante et de la saveur légèrement torréfiée.", "Servez chaud, avec de la confiture."),
        ("time", 7, 5, 20),
    ],
    # farine et parmesan jamais incorporés, « yaourt » à la place des œufs, tomate fraîche inutilisée
    "snack_cake_olives_et_herbes_d13d34": [
        ("del", "tomato_raw_ripe"),
        ("add", "baking_powder", 10, "g", "leavening"),
        ("steps", [
            "Préchauffer le four à 180°C et huiler un moule à cake de 23 cm.",
            "Battre les 165 g d'œufs avec 80 ml d'huile d'olive et 100 ml de lait.",
            "Incorporer 200 g de farine mélangée à 10 g de levure chimique, puis 60 g de parmesan râpé et 2 g de thym séché, sans trop travailler la pâte.",
            "Ajouter 100 g d'olives dénoyautées et 60 g de tomates séchées coupées en morceaux.",
            "Verser dans le moule et enfourner 40 minutes à 180°C, jusqu'à ce que la lame d'un couteau ressorte sèche.",
            "Laisser refroidir 10 minutes avant de démouler.",
        ]),
        ("time", 15, 10, 40),
    ],
    "snack_crackers_35f6a8": [
        ("serv", 6),
    ],
    "snack_crepe_coreenne_aux_oignon_a45536": [
        ("qty", "sesame_oil_plant", 30),
        ("serv", 4),
    ],
    "snack_empanadas_974cf2": [
        ("ing", "parmesan_grated_dried_cow", "queso_fresco_block_cow"),
        ("qty", "table_salt_unenriched", 2),
        ("add", "olive_oil_plant", 30, "ml", "fat"),
        ("txt", "dans un peu d'huile d'olive pendant 5 minutes", "dans 20 ml d'huile d'olive pendant 5 minutes"),
        ("txt", "Ajoutez le maïs et faites-le blanchir pendant 2 minutes à feu vif, en remuant constamment, jusqu'à ce qu'il soit légèrement doré et croustillant.",
         "Ajoutez le maïs et faites-le sauter 3 minutes à feu vif, en remuant."),
        ("txt", "ainsi que de fromage parmesan râpé et d'un œuf battu", "ainsi que de 150 g de queso fresco émietté et des 220 g d'œufs durs hachés (cuits 9 minutes)"),
        ("txt", "badigeonnez-les d'un peu d'huile d'olive", "badigeonnez-les de 10 ml d'huile d'olive"),
    ],
    # parmesan, 300 g d'oignon cru et 220 g d'œuf cru en farce
    "snack_empanadas_au_fromage_466bc4": [
        ("ing", "parmesan_grated_dried_cow", "queso_fresco_block_cow"),
        ("qty", "onion_raw", 150),
        ("qty", "egg_raw", 55),
        ("qty", "table_salt_unenriched", 2),
        ("txt", "Préparez la farce en mélangeant 150g de fromage parmesan râpé avec 300g d'oignon jaune haché finement et 220g d'œuf battu pour lier, jusqu'à obtenir une consistance homogène.",
         "Faites revenir 150 g d'oignon haché finement 8 minutes dans 15 ml d'huile d'olive, laissez tiédir, puis mélangez-le avec 150 g de queso fresco émietté et 55 g d'œuf battu pour lier."),
        ("txt", "avec un peu d'huile d'olive (environ 45ml)", "avec les 30 ml d'huile d'olive restants"),
        ("txt", "Servir aussitôt dans des assiettes préchauffées, garni d'un peu de persil frais ciselé et d'un filet d'huile d'olive. Accompagner de salade verte ou de légumes grillés.",
         "Servir aussitôt, avec une salade verte."),
    ],
    # « vegan » sur une pâte au beurre et à l'œuf
    "snack_empanadas_au_fromage_vega_79575a": [
        ("del", "base_empanada_dough_65661a"),
        ("add", "wheat_all_purpose_flour_unenriched_unbleached", 250, "g", "base"),
        ("add", "sunflower_oil_plant", 50, "ml", "fat"),
        ("add", "water", 100, "ml", "liquid"),
        ("ing", "coconut_oil_plant", "olive_oil_plant", 15),
        ("qty", "yellow_onion_raw", 150),
        ("flag", "vegan", True),
        ("flag", "lactose_free", True),
        ("steps", [
            "Préparer la pâte : mélanger 250 g de farine, 5 g de sel, 50 ml d'huile de tournesol et environ 100 ml d'eau tiède, pétrir brièvement, puis laisser reposer 30 minutes sous un linge.",
            "Faire revenir 150 g d'oignon émincé 10 minutes à feu doux dans une poêle antiadhésive, jusqu'à ce qu'il soit fondant et doré, puis le laisser tiédir et le mélanger aux 150 g de fromage végétal.",
            "Abaisser la pâte finement et y découper 12 disques de 12 cm.",
            "Garnir chaque disque d'une cuillerée de farce, plier en demi-lune et souder les bords à la fourchette.",
            "Badigeonner les empanadas de 15 ml d'huile d'olive et les enfourner 20 minutes à 200°C, jusqu'à ce qu'elles soient dorées.",
            "Laisser tiédir quelques minutes sur une grille avant de servir.",
        ]),
        ("time", 11, 30, 30),
    ],
    "snack_gozleme_aux_epinards_vega_6ff07b": [
        ("del", "white_onion_raw"),
        ("qty", "olive_oil_extra_virgin_plant", 20),
        ("add", "water", 180, "ml", "liquid"),
        ("add", "garlic_raw", 5, "g", "aromatic"),
        ("txt", "180 ml d'eau tiède à 30°C", "180 ml d'eau tiède"),
        ("txt", "1 g d'ail émincé", "5 g d'ail émincé"),
        ("txt", "dans une poêle sèche à feu moyen", "dans une poêle légèrement huilée (20 ml d'huile d'olive au total) à feu moyen"),
        ("txt", "servir sans attendre, dans des assiettes préchauffées.", "servir sans attendre."),
        ("step-", "Servir chaud, accompagné d'une salade verte"),
        ("time", 11, 30, 18),
    ],
    "snack_humita_andine_vegan_1f09bf": [
        ("qty", "onion_raw", 100),
        ("qty", "olive_oil_extra_virgin_plant", 20),
        ("qty", "table_salt_unenriched", 3),
        ("txt", " Vous devez sentir l'arôme sucré du maïs et voir une texture crémeuse commencer à apparaître.", ""),
        ("txt", "Faire revenir 150g d'oignon dans 45,7ml d'huile d'olive", "Faire revenir 100g d'oignon dans 20 ml d'huile d'olive"),
        ("txt", " Vous devez entendre le bruit de l'oignon qui caramélise.", ""),
        ("txt", "250ml de lait d'avoine et assaisonner avec 5g de sel.", "250ml de lait d'avoine et 150 g de fromage végétal en dés, puis assaisonner avec 3g de sel."),
        ("txt", " Vous devez sentir la texture douce de la feuille de maïs.", ""),
        ("txt", " à 100°C,", ","),
        ("txt", " Vous devez voir la vapeur s'échapper et entendre le son de l'eau qui bout.", ""),
        ("txt", "Servir chaud dans des assiettes. Vous devez sentir la chaleur du plat et voir la texture crémeuse de la pâte de maïs.", "Servir chaud, dans leurs feuilles."),
    ],
    "snack_rosti_vegan_be15a2": [
        ("del", "yellow_onion_raw"),
        ("serv", 4),
        ("txt", "Incorporez 300 g d'oignon jaune émincé, 1,5 g de thym frais", "Incorporez 1,5 g de thym frais"),
        ("txt", "Coupez en parts et servez chaud, dans des assiettes préchauffées, en vérifiant que les rösti soient croustillants et dorés, avec une texture qui se brise sous la dent.",
         "Coupez en parts et servez chaud."),
        ("time", 11, 10, 20),
    ],
    # 750 ml de bouillon pour 300 g de masa, sans matière grasse, 18 min de vapeur
    "snack_tamales_vegan_d7cbdc": [
        ("qty", "water", 300),
        ("qty", "vegetable_stock_dried", 3.8),
        ("qty", "white_onion_raw", 150),
        ("add", "sunflower_oil_plant", 70, "ml", "fat"),
        ("txt", "avec 750ml de bouillon végétal chaud", "avec 60 ml d'huile de tournesol et environ 300 ml de bouillon végétal chaud"),
        ("txt", "Faites revenir 300g d'oignon blanc émincé dans un peu d'huile", "Faites revenir 150g d'oignon blanc émincé dans 10 ml d'huile"),
        ("txt", "pendant 18 minutes à 100°C", "pendant 1 heure"),
        ("time", 17, 30, 60),
    ],
    # tomates séchées jamais utilisées, tomates fraîches qui détrempent la pâte
    "snack_tarte_soleil_pesto_46f867": [
        ("del", "tomato_raw_ripe"),
        ("txt", "Disposez 240 g de tomates fraîches coupées en dés sur le pesto et le parmesan", "Disposez 80 g de tomates séchées égouttées et hachées sur le pesto et le parmesan"),
    ],
    "snack_tostadas_vegan_f7257b": [
        ("qty", "avocado_raw", 200),
        ("qty", "tomato_raw_ripe", 300),
        ("qty", "cashew_butter_plain_plant", 40),
        ("qty", "table_salt_unenriched", 3),
        ("add", "cumin_spice_seed", 2, "g", "spice"),
        ("txt", "Faire frire les tortillas dans l'huile chaude à 180°C jusqu'à ce qu'elles soient dorées et croustillantes, ou les passer au four préchauffé à 180°C pendant 8 minutes",
         "Passer les tortillas au four préchauffé à 180°C pendant 8 minutes, jusqu'à ce qu'elles soient dorées et croustillantes"),
        ("txt", "un peu de cumin", "2 g de cumin"),
        ("txt", "ajouter de la crème de cashew", "ajouter 40 ml de crème de cajou détendue à l'eau"),
        ("step-", "Assaisonner avec du sel pour rehausser les saveurs"),
    ],
    # 150 g de beurre de cajou dans une farce de pommes de terre
    "snack_varenyky_pomme_de_terre_v_8b6240": [
        ("del", "cashew_butter_plain_plant"),
        ("add", "water", 120, "ml", "liquid"),
        ("flag", "nut_free", True),
        ("txt", "Ajouter 150g de crème de cajou à la farce pour un toucher crémeux et assaisonner avec du poivre noir.", "Assaisonner la farce avec du poivre noir."),
        ("txt", "en arrosant d'un peu d'huile végétale et de 40g de beurre végétal fondu pour un toucher croustillant et en les accompagnant d'une sauce à base de crème de cajou pour un contraste de textures.",
         "nappés de 40g de beurre végétal fondu."),
        ("step-", "Assaisonner avec du poivre noir si nécessaire"),
        ("step-", "Servir les varenyky chauds dans des bols préchauffés"),
        ("time", 15, 30, 25),
    ],
    "snack_veg_k3d2p1": [
        ("steps", [
            "Trancher le pain et le toaster 2 minutes à la poêle, à feu moyen-vif, jusqu'à ce qu'il soit doré.",
            "Étaler 30 g de mayonnaise sur les faces internes.",
            "Disposer la laitue sur la face inférieure.",
            "Ajouter les tomates en rondelles, égouttées sur du papier absorbant.",
            "Émietter 80 g de fromage de chèvre frais, saler avec 2 g de sel, poivrer et arroser de 10 ml d'huile d'olive.",
            "Refermer le sandwich en appuyant légèrement et servir aussitôt.",
        ]),
        ("time", 15, 0, 2),
    ],
}
