"""Lot 39 : soupes (pho → velouté de butternut)."""

PATCHES = {
    # épices du texte absentes, « 2 gousses » = 2 g, garnitures manquantes
    "soup_pho_ba7e1e": [
        ("qty", "garlic_raw", 10),
        ("add", "cinnamon", 3, "g", "spice"),
        ("add", "star_anise", 3, "g", "spice"),
        ("add", "cloves", 0.5, "g", "spice"),
        ("add", "mung_bean_sprouts_raw_seed_sprouted", 100, "g", "vegetable"),
        ("add", "basil_fresh_herb", 10, "g", "herb"),
        ("txt", "2 cuillères à café de cannelle, 2 cuillères à café d'anis étoilé, 2 clous de girofle et 1 badiane", "1 bâton de cannelle, 3 étoiles de badiane et 2 clous de girofle"),
        ("txt", "Ajoutez 2 gousses d'ail hachées", "Ajoutez 10 g d'ail haché"),
        ("txt", ", julienne les légumes frais comme les oignons jaunes et les champignons. Vous pouvez également ajouter d'autres légumes de votre choix, comme des carottes ou des poivrons.",
         " et rincer 100 g de pousses de soja."),
        ("txt", "garnir de coriandre fraîche ciselée et de quartiers de citron vert", "garnir des pousses de soja, de coriandre, de 10 g de basilic thaï et de quartiers de citron vert"),
        ("step-", "Ajoutez des herbes fraîches supplémentaires si vous le souhaitez"),
    ],
    "soup_potage_de_patate_douce_e4b521": [
        ("qty", "coconut_milk_plant", 80),
        ("add", "lemon_juice", 10, "ml", "condiment"),
        ("txt", "Faire revenir l'oignon jaune et le gingembre", "Faire revenir l'oignon jaune, 9 g d'ail et le gingembre"),
        ("txt", "mouiller avec 800 ml de bouillon", "mouiller avec 750 ml de bouillon"),
        ("txt", "Incorporer 80 ml de crème de coco et assaisonner de sel et de jus de citron, en ajoutant un filet de jus de citron si nécessaire,",
         "Incorporer 80 ml de lait de coco et 10 ml de jus de citron,"),
        ("txt", "Ajouter les 9 grammes d'ail haché pour parfumer le plat, puis servir chaud, en vérifiant la présentation et la température du plat, en ajoutant des herbes fraîches si nécessaire pour une touche de fraîcheur.",
         "Servir chaud."),
    ],
    "soup_potage_parmentier_9685a7": [
        ("qty", "olive_oil_plant", 15),
        ("add", "water", 900, "ml", "liquid"),
        ("add", "nutmeg_spice", 0.5, "g", "spice"),
        ("txt", "dans 2 ml d'huile d'olive", "dans 15 ml d'huile d'olive"),
        ("txt", "Assaisonnez de sel, poivre et noix de muscade.", "Assaisonnez avec 5 g de sel, du poivre et une pincée de muscade."),
        ("step-", "Vérifiez la température."),
    ],
    "soup_potage_saint_germain_e23f6b": [
        ("add", "table_salt_unenriched", 2, "g", "seasoning"),
        ("add", "white_bread_baguette", 40, "g", "garnish"),
        ("flag", "gluten_free", False),
        ("txt", "Assaisonnez de sel et poivre.", "Assaisonnez avec 2 g de sel et du poivre."),
        ("txt", "Faites chauffer 10 g d'huile d'olive dans une poêle à feu moyen, puis ajoutez des cubes de pain", "Faites chauffer 10 ml d'huile d'olive dans une poêle à feu moyen, puis ajoutez 40 g de pain en cubes"),
    ],
    "soup_pumpkin_k2d1p1": [
        ("add", "pumpkin_squash_raw_seed", 20, "g", "garnish"),
        ("txt", "Rectifier l'assaisonnement avec du sel de table et du poivre noir moulu.", "Rectifier l'assaisonnement."),
        ("txt", "Faire griller des graines de courge pour ajouter une touche de croquant.", "Faire griller 20 g de graines de courge à sec 3 minutes à la poêle."),
        ("step-", "Pour un service plus élégant"),
        ("step-", "Présenter le velouté dans des bols préchauffés"),
    ],
    # champignons et oignon jamais utilisés, tofu « doré » jamais cuit
    "soup_ramen_au_miso_f69c22": [
        ("qty", "garlic_raw", 10),
        ("qty", "soy_sauce_shoyu_reduced_sodium", 10),
        ("qty", "vegetable_stock_dried", 8),
        ("txt", "avec 2 cuillères à soupe de pâte de miso végétal et 20 ml de sauce soja sans gluten", "avec 30 g de miso et 10 ml de sauce soja"),
        ("txt", " Observez la couleur dorée du bouillon et son parfum umami.", ""),
        ("txt", "Ajouter 11,2 g de gingembre émincé frais et 2 g d'ail émincé dans le bouillon et laisser infuser pendant 2 minutes. Respirez l'arôme piquant du gingembre et de l'ail.",
         "Ajouter 11 g de gingembre frais émincé, 10 g d'ail émincé, 150 g d'oignon émincé et 200 g de champignons émincés dans le bouillon et laisser cuire 8 minutes."),
        ("txt", " Vérifiez la texture al dente des nouilles.", ""),
        ("txt", "verser le bouillon filtré à 80°C. Regardez la façon dont les nouilles absorbent le bouillon.", "verser le bouillon chaud."),
        ("txt", "Ajouter 200 g de tofu ferme doré, coupé en dés, et 10 g d'oignon vert émincé sur le dessus de chaque bol. Admirez la couleur dorée du tofu et la fraîcheur de l'oignon vert.",
         "Ajouter 200 g de tofu ferme coupé en dés et doré 5 minutes à la poêle dans 10 ml d'huile de sésame, puis 10 g d'oignon vert émincé."),
    ],
    "soup_soup_k3d2p1": [
        ("qty", "table_salt_unenriched", 2),
        ("add", "thyme_dried_herb", 1, "g", "herb"),
        ("add", "bay_leaf_spice", 1, "g", "herb"),
        ("txt", ", préparé avec des légumes frais et des herbes aromatiques", ""),
        ("txt", "Assaisonner avec 5 g de sel", "Assaisonner avec 2 g de sel"),
        ("txt", "préparés avec 120 g de pain complet et un filet de beurre", "préparés avec 120 g de baguette"),
        ("txt", "Servir aussitôt dans des bols préchauffés, accompagné de croutons supplémentaires ou d'une salade verte pour un repas complet.", "Servir aussitôt."),
        ("step-", "Pour un service plus élégant"),
    ],
    "soup_soupe_au_cresson_fce0c6": [
        ("qty", "olive_oil_plant", 15),
        ("add", "table_salt_unenriched", 2, "g", "seasoning"),
        ("txt", "dans 2ml d'huile d'olive", "dans 15ml d'huile d'olive"),
        ("txt", "Ajouter 300g de cresson de fontaine en grande quantité.", "Ajouter le cresson."),
        ("txt", "Rectifier l'assaisonnement avec du sel et du poivre. Servir aussitôt dans des bols préchauffés, en veillant à conserver la chaleur pour préserver la couleur intense et le goût piquant du cresson.",
         "Saler avec 2 g de sel, poivrer et servir aussitôt."),
    ],
    "soup_soupe_carottes_au_cumin_3903f8": [
        ("qty", "olive_oil_extra_virgin_plant", 15),
        ("ing", "lemon", "lemon_juice", 15, "ml"),
        ("add", "table_salt_unenriched", 2, "g", "seasoning"),
        ("txt", "dans 2ml d'huile d'olive", "dans 15ml d'huile d'olive"),
        ("txt", "Assaisonner de sel et poivre", "Assaisonner de 2 g de sel et de poivre"),
        ("txt", "Servir chaud dans des bols préchauffés, avec un filet de jus de citron frais pressé", "Servir chaud, avec 15 ml de jus de citron frais"),
    ],
    "soup_soupe_courge_butternut_2f5cf3": [
        ("qty", "olive_oil_plant", 15),
        ("qty", "curry", 3),
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("txt", "dans 2 ml d'huile d'olive", "dans 15 ml d'huile d'olive"),
        ("txt", "Assaisonner de sel et de poivre.", "Assaisonner avec 3 g de sel et du poivre."),
        ("txt", "d'un filet de crème de coco", "d'un filet de lait de coco"),
        ("step-", "Pour une présentation plus élégante"),
    ],
}
