"""Lot 41 : mercimek, udon miso, laksa, veloutés, vichyssoise, ajapsandali."""

PATCHES = {
    "soup_turkish_mercimek_soup_veg_f30ebc": [
        ("ing", "lemon_raw", "lemon_juice", 30, "ml"),
        ("qty", "mint_fresh_herb", 5),
        ("add", "paprika_powder", 2, "g", "spice"),
        ("add", "sunflower_oil_plant", 15, "ml", "fat"),
        ("txt", "Préparer la garniture en faisant fondre un peu d'huile, puis en ajoutant du paprika fumé hors du feu, en vérifiant que le paprika est bien réparti.",
         "Préparer la garniture en chauffant 15 ml d'huile, puis en ajoutant 2 g de paprika hors du feu."),
        ("txt", "en saupoudrant de menthe séchée pour une touche fraîche, en vérifiant que la soupe est servie à la bonne température", "en parsemant de 5 g de menthe ciselée"),
    ],
    # tofu « soyeux », ail cru ajouté en fin, 5 g de sel en plus du miso
    "soup_udon_miso_ef1ceb": [
        ("del", "table_salt_unenriched"),
        ("txt", " Observez la texture al dente des nouilles.", ""),
        ("txt", "porter 750ml de dashi végétal à frémissement, ajouter 15ml de sauce soja et 15ml de mirin", "porter 750ml de bouillon végétal à frémissement avec 20 g d'ail et 15 g de gingembre émincés, puis ajouter 15ml de sauce soja et 15ml de mirin"),
        ("txt", " Sentez l'arôme qui se dégage.", ""),
        ("txt", " Notez la couleur crémeuse qui se forme.", ""),
        ("txt", "400g de tofu soyeux en dés, 300g de champignons émincés et 60g de ciboulette hachée", "400g de tofu ferme en dés, 300g de champignons émincés et 60g d'oignon vert ciselé"),
        ("txt", " Écoutez le doux bouillonnement.", ""),
        ("step-", "Ajouter 20g d'ail émincé et 15g de gingembre émincé"),
        ("txt", "dans des bols profonds préchauffés, verser le bouillon chaud et les garnitures par-dessus. Observez la belle présentation et les couleurs vives.",
         "dans des bols profonds, verser le bouillon chaud et les garnitures par-dessus, puis servir sans attendre."),
        ("step-", "Vérifier que les udon ont une texture glissante"),
        ("step-", "Assaisonner avec 5g de sel"),
        ("step-", "Garnir avec des ciboulettes supplémentaires"),
    ],
    "soup_vegetable_laksa_ab0112": [
        ("ing", "base_green_curry_paste_250117", "base_laksa_paste_bc7fd5"),
        ("qty", "garlic_raw", 10),
        ("add", "table_salt_unenriched", 2, "g", "seasoning"),
        ("txt", "Ajoutez 2 g d'ail", "Ajoutez 10 g d'ail"),
        ("txt", "30 g de pâte de curry vert", "30 g de pâte de laksa"),
        ("txt", ", jusqu'à ce que le tofu soit bien cuit et les légumes soient tendres", ", jusqu'à ce que le tofu soit bien chaud"),
        ("txt", "Assaisonnez avec du sel et du poivre, puis laissez réduire pendant 2 minutes à feu doux, en remuant occasionnellement, jusqu'à ce que la sauce soit bien épaissie.", "Salez avec 2 g de sel."),
    ],
    "soup_veloute_d_asperges_7da98f": [
        ("ing", "lemon", "lemon_juice", 15, "ml"),
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("txt", "Incorporer la crème et le jus de citron", "Incorporer la crème, 15 ml de jus de citron et 3 g de sel"),
    ],
    "soup_veloute_de_celeri_rave_b33921": [
        ("qty", "hazelnut_oil_plant", 10),
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("txt", "Incorporer 100 ml de crème fraîche et quelques noisettes grillées, puis cuire pendant 2 minutes supplémentaires, en remuant constamment pour éviter la formation de grumeaux.",
         "Incorporer 100 ml de crème fraîche et réchauffer 2 minutes."),
        ("txt", "Rectifier l'assaisonnement avec de la noix de muscade fraîchement râpée", "Assaisonner avec 3 g de sel et la noix de muscade fraîchement râpée"),
        ("txt", "d'un filet d'huile de noisette", "de 10 ml d'huile de noisette"),
        ("step-", "Servir dans des bols préchauffés, en profitant"),
    ],
    "soup_veloute_de_potimarron_776ea1": [
        ("ing", "butternut_squash_raw", "red_kuri_squash_raw_skinless"),
        ("add", "table_salt_unenriched", 3, "g", "seasoning"),
        ("add", "nutmeg_spice", 0.5, "g", "spice"),
        ("txt", "dans l'beurre à feu moyen", "dans 25 g de beurre à feu moyen"),
        ("txt", "Assaisonner avec du sel, du poivre et de la muscade", "Assaisonner avec 3 g de sel, du poivre et une pincée de muscade"),
        ("txt", ", ainsi que d'une larme de crème fraîche pour enrichir la texture et les saveurs", ""),
        ("step-", "Pour terminer, ajouter un filet de beurre"),
    ],
    "soup_vichyssoise_d28d4b": [
        ("qty", "chives_raw_fresh", 5),
        ("add", "water", 800, "ml", "liquid"),
        ("txt", "dans l'beurre sans coloration", "dans 30 g de beurre sans coloration"),
        ("txt", "mouiller avec de l'eau", "mouiller avec 800 ml d'eau"),
        ("txt", "Assaisonner avec du sel à goût.", "Assaisonner avec 5 g de sel."),
        ("step-", "Pour un effet visuel supplémentaire"),
    ],
    "stew_ajapsandali_m8d4q1": [
        ("add", "basil_fresh_herb", 10, "g", "herb"),
        ("add", "chilli_pepper_raw", 5, "g", "spice"),
        ("txt", "la coriandre fraîche hachée et les épices géorgiennes", "10 g de coriandre fraîche, 10 g de basilic et 5 g de piment haché"),
        ("txt", "Assaisonnez et garnissez de persil frais. Préparez le pain végétal pour servir.", "Assaisonnez et garnissez de persil frais."),
        ("step-", "Vérifiez que les légumes sont tendres et que la sauce a épaissi"),
        ("txt", "accompagné de pain végétal et garni", "accompagné de pain et garni"),
    ],
}
