"""Lot 42 : ragoûts (cassoulet → plantain)."""

PATCHES = {
    "stew_cassoulet_938fd4": [
        ("add", "garlic_raw", 10, "g", "aromatic"),
        ("add", "breadcrumbs_dried", 40, "g", "garnish"),
        ("flag", "gluten_free", False),
        ("txt", "Faire revenir 200g d'oignon jaune émincé", "Faire revenir 150g d'oignon jaune émincé, 10 g d'ail haché"),
        ("txt", "couvrir de chapelure fine", "couvrir de 40 g de chapelure fine"),
        ("txt", "Goûter et rectifier l'assaisonnement avec du sel de mer et des herbes fraîches pour parfaire le goût et équilibrer les saveurs.", "Assaisonner avec 5 g de sel."),
        ("txt", "garni de persil frais haché et accompagné de pain grillé", "accompagné de pain grillé"),
        ("time", 15, 480, 135),
    ],
    "stew_croatian_bean_stew_4dfb05": [
        ("txt", "garni de persil haché et d'un filet d'huile d'olive", "arrosé d'un filet d'huile d'olive"),
        ("step-", "Déguster et apprécier les saveurs riches"),
        ("time", 17, 0, 85),
    ],
    "stew_eggplant_classic_5d46a1": [
        ("add", "basil_fresh_herb", 5, "g", "herb"),
        ("txt", "Assaisonner de sel, de levure nutritionnelle et d'herbes fraîches pour équilibrer les saveurs.", "Assaisonner avec 5 g de sel."),
        ("txt", "en ajoutant un filet d'huile d'olive pour une touche de fraîcheur et un peu de levure nutritionnelle pour rehausser les saveurs, en veillant à conserver la texture crémeuse et la saveur intense.",
         "garni de 5 g de feuilles de basilic."),
        ("step-", "Garnir de feuilles de basilic fraîches et de tranches de citron"),
        ("time", 30, 20, 45),
    ],
    "stew_georgian_vegetable_stew_1cb019": [
        ("add", "coriander_raw_fresh_herb", 15, "g", "herb"),
        ("add", "parsley_fresh_herb", 15, "g", "herb"),
        ("add", "water", 200, "ml", "liquid"),
        ("txt", "Faire revenir les oignons dans 30 ml d'huile de tournesol", "Faire revenir les oignons et 9 g d'ail émincé dans 45 ml d'huile de tournesol"),
        ("txt", "Ajouter des noix concassées et des herbes fraîches ciselées, comme du persil ou de la coriandre,", "Ajouter 80 g de noix concassées, 15 g de persil et 15 g de coriandre ciselés"),
        ("txt", "Assaisonner le ragoût avec du sel et du poivre pour ajuster les saveurs. Ajouter des gousses d'ail émincées pour renforcer le parfum.", "Assaisonner avec 5 g de sel et 2 g de poivre."),
        ("txt", ", et garni de coriandre fraîche ciselée pour un toucher de fraîcheur", ""),
    ],
    "stew_lentil_classic_v5_h9k3p2": [
        ("add", "parsley_fresh_herb", 10, "g", "herb"),
        ("txt", "garni de persil ciselé et de levure nutritionnelle râpée pour une touche de saveur et de texture additionnelles", "garni de 10 g de persil ciselé"),
    ],
    # ghormeh sabzi à 30 g de persil (≈ 350 g d'herbes attendus), Na 955
    "stew_persian_herb_stew_485f3e": [
        ("qty", "parsley_fresh_herb", 200),
        ("ing", "coriander_spice_seed", "coriander_raw_fresh_herb", 100),
        ("add", "chives_raw_fresh", 50, "g", "herb"),
        ("ing", "lemon_raw", "lemon_juice", 40, "ml"),
        ("qty", "table_salt_unenriched", 3),
        ("txt", "Incorporer 30g de persil frais haché, 3g de coriandre moulue et 3g de fenugrec", "Incorporer 200g de persil, 100g de coriandre et 50g de ciboulette finement hachés, ainsi que 3g de fenugrec séché"),
        ("txt", "Assaisonner avec 3g de curcuma, 5g de sel et 2g de poivre, ainsi que 100g de jus de citron frais", "Assaisonner avec 3g de curcuma, 3g de sel et 2g de poivre, ainsi que 40 ml de jus de citron frais"),
    ],
    # 250 g de quinoa + 600 g de pommes de terre : 653 kcal
    "stew_peruvian_quinoa_stew_1180bf": [
        ("qty", "quinoa_raw_dried", 150),
        ("qty", "potato_raw_flesh", 300),
        ("qty", "water", 900),
        ("qty", "vegetable_stock_dried", 11),
        ("add", "tomato_raw_ripe", 200, "g", "vegetable"),
        ("add", "chilli_pepper_raw", 10, "g", "spice"),
        ("txt", "Rincer 250g de quinoa cru à l'eau froide et toaster à sec dans une casserole 2 min à feu moyen, en écoutant le son sec des grains qui sautent.", "Rincer 150g de quinoa cru à l'eau froide et le toaster à sec 2 min dans une casserole à feu moyen."),
        ("txt", ", en sentant l'arôme piquant du cumin", ""),
        ("txt", "Incorporer 600g de pommes de terre crues coupées en dés, 300g de haricots noirs égouttés et 300g de maïs",
         "Incorporer 300g de pommes de terre crues coupées en dés, 300g de haricots noirs égouttés, 300g de maïs, 200 g de tomates concassées et 10 g d'ají (ou de piment) haché"),
        ("txt", "Verser 750ml de bouillon végétal chaud, en écoutant le son de la liquide qui coule, et porter à ébullition.", "Verser 900ml de bouillon végétal chaud et porter à ébullition."),
        ("txt", "couvrir et cuire 15 min, en vérifiant la texture :.", "couvrir et cuire 15 min à feu doux."),
        ("txt", "Assaisonner avec du sel et du poivre au goût, en rectifiant l'assaisonnement pour un équilibre parfait, et servir dans des bols préchauffés.", "Assaisonner avec 5 g de sel et du poivre."),
    ],
    "stew_ragout_de_haricots_et_mai_122538": [
        ("add", "garlic_raw", 10, "g", "aromatic"),
        ("add", "paprika_powder", 3, "g", "spice"),
        ("add", "water", 250, "ml", "liquid"),
        ("add", "vegetable_stock_dried", 3, "g", "ingredient"),
        ("add", "lemon_juice", 10, "ml", "condiment"),
        ("txt", "Faire revenir l'oignon 8 min à feu moyen, jusqu'à légère caramelisation et parfum dégagé, en sentant les arômes dégagés.",
         "Faire revenir l'oignon et 10 g d'ail émincés dans 45 ml d'huile d'olive, 8 min à feu moyen."),
        ("txt", "Ajouter les tomates concassées et les épices", "Ajouter les tomates concassées et 3 g de paprika"),
        ("txt", ", en écoutant le son de la cuisson", ""),
        ("txt", "en ajoutant un filet de jus de citron si nécessaire", "en ajoutant 10 ml de jus de citron"),
        ("txt", "Servir chaud, dans des bols préchauffés, en ajoutant des herbes fraîches si nécessaire, pour un plat réconfortant et savoureux.", "Servir chaud."),
    ],
    "stew_ragout_de_plantain_2140eb": [
        ("qty", "chilli_pepper_raw", 5),
        ("add", "water", 300, "ml", "liquid"),
        ("txt", ", en écoutant le son de l'huile qui chauffe et en sentant son arôme subtil", ""),
        ("txt", "15g de piment habanero haché", "5g de piment habanero haché"),
        ("txt", ", en écoutant le son de la sauce qui mijote", ""),
        ("txt", ", en écoutant le son de la liquide qui coule,", ","),
        ("txt", ", en rectifiant l'assaisonnement pour un équilibre parfait et en vérifiant la texture finale onctueuse.", ", puis laisser mijoter 15 minutes à couvert, jusqu'à ce que la banane plantain soit tendre."),
    ],
}
