"""Lot 43 : ratatouille, sundubu, pâte de tamarin, pizzas, moussaka, quiche, tempeh."""

PATCHES = {
    "stew_ratatouille_k8d2p4": [
        ("add", "basil_fresh_herb", 10, "g", "herb"),
        ("add", "black_pepper_spice", 1, "g", "spice"),
        ("txt", "Faites revenir chaque légume séparément dans 70 ml d'huile d'olive", "Faites revenir successivement chaque légume dans un peu d'huile d'olive (50 ml au total)"),
        ("txt", "faites confire l'oignon à feu doux", "faites confire l'oignon dans les 20 ml d'huile restants, à feu doux"),
        ("txt", "Assaisonnez avec du sel et ajoutez des herbes fraîches déchirées.", "Assaisonnez avec 6 g de sel et du poivre, puis ajoutez 10 g de basilic déchiré."),
        ("step-", "Vérifiez que les légumes soient tendres et la sauce nappe la cuillère"),
    ],
    # tofu ferme 200 g jamais utilisé, ragoût enfourné, gochujang « sans gluten »
    "stew_sundubu_tofu_stew_ebe50e": [
        ("del", "tofu_plain_pre_packaged"),
        ("qty", "green_zucchini_squash_raw", 200),
        ("flag", "gluten_free", False),
        ("txt", "Chauffer 2 cuillères à soupe d'huile dans un pot en terre cuite à feu moyen pendant 2 minutes, jusqu'à ce que l'huile commence à fumer et dégage un parfum subtil.",
         "Chauffer 30 ml d'huile de sésame dans un poêlon en terre à feu moyen."),
        ("txt", "Faire revenir 3 gousses d'ail émincé et 1 oignon émincé", "Faire revenir 9 g d'ail et l'oignon émincés"),
        ("txt", "Verser 750 ml de bouillon végétarien et porter à frémissement. Ensuite, enfourner à 200°C pendant 20 minutes, jusqu'à ce que le ragoût soit chaud et les saveurs soient bien intégrées.",
         "Verser 750 ml de dashi végétal et laisser frémir 10 minutes."),
        ("txt", "500 g de courgette crue en dés", "200 g de courgette en dés"),
        ("txt", ", et ciseler pendant 1 minute, jusqu'à ce que le tofu soit bien réparti dans le ragoût et les saveurs soient équilibrées", ", et laisser chauffer 2 minutes sans remuer"),
        ("txt", "Ajouter 220 g d'œuf battu et cuire pendant 2 minutes, jusqu'à ce que l'œuf soit pris et les saveurs soient bien intégrées.",
         "Casser les 4 œufs (220 g) à la surface et cuire 2 minutes, jusqu'à ce que les blancs soient pris."),
        ("txt", ", en garnissant de feuilles de coriandre fraîche si désiré, pour un repas complet et savoureux", ", avec du riz"),
        ("time", 17, 0, 20),
    ],
    "tamarind_paste_b740bb": [
        ("step-", "Avant de servir, vérifier que la pâte a une consistance lisse"),
        ("step-", "Servir sans attendre, en utilisant la pâte de tamarin"),
    ],
    # la pâte (base) était refaite dans le texte ; tomates fraîches pour une sauce
    "tarte_margherita_v7k2d1": [
        ("ing", "tomato_raw_ripe", "tomato_sauce_salted_canned", 150),
        ("qty", "table_salt_unenriched", 1),
        ("txt", "Préparer la pâte en mélangeant 300 g de farine de type 00, 5 g de levure sèche, 5 g de sel fin et 15 ml d'huile d'olive extra vierge. Ajouter 190 ml d'eau tiède progressivement. Pétrir pendant 10 minutes jusqu'à obtenir une pâte lisse et élastique. Laisser lever pendant 2 heures à température ambiante.",
         "Sortir 300 g de pâte à pizza levée (préparée 2 heures à l'avance) et la laisser revenir à température ambiante."),
        ("txt", "Napper de sauce tomate", "Napper de 150 g de sauce tomate"),
        ("txt", "Répartir des tranches de fromage mozzarella râpé sur la sauce tomate.", "Répartir 200 g de mozzarella égouttée en morceaux sur la sauce."),
        ("step-", "Observer la texture de la croûte"),
        ("txt", "Servir chaud, garni de feuilles de basilic frais et accompagné d'un filet d'huile d'olive extra vierge.", "Servir chaud."),
    ],
    # beurre de la béchamel absent, béchamel « à 70 °C », 3 étapes de remplissage
    "tarte_moussaka_veg_d55fa8": [
        ("add", "butter_sup80pct", 45, "g", "bechamel"),
        ("qty", "garlic_raw", 15),
        ("txt", "faire griller ou frire à feu vif pendant 2 à 3 minutes par face, jusqu'à doré, en sentant l'odeur des aubergines qui commencent à caraméliser.", "les faire griller avec 25 ml d'huile d'olive, 2 à 3 minutes par face, jusqu'à ce qu'elles soient dorées."),
        ("txt", "ajouter 30g d'ail haché", "ajouter 15g d'ail haché"),
        ("txt", "mijoter pendant 15 minutes à 80°C", "mijoter pendant 15 minutes à feu doux"),
        ("txt", "cuire pendant 5 minutes à 70°C", "cuire pendant 5 minutes à feu doux"),
        ("txt", ", en sentant l'odeur de la moussaka qui cuit et la voyant prendre forme", ""),
        ("step-", "Déguster et ajuster l'assaisonnement si nécessaire"),
        ("step-", "Vous pouvez accompagner la moussaka"),
        ("step-", "Présenter la moussaka dans un plat de service"),
        ("time", 45, 30, 60),
    ],
    "tarte_pizza_margherita_vegan_02bb9a": [
        ("qty", "tomato_sauce_salted_canned", 150),
        ("qty", "olive_oil_extra_virgin_plant", 20),
        ("del", "tomato_raw_ripe"),
        ("del", "table_salt_unenriched"),
        ("txt", "Préparer la pâte à pizza en mélangeant 300 g de farine T00, 7 g de levure, 5 g de sel de table, 10 ml d'huile d'olive vierge extra et 190 ml d'eau tiède. Pétrir pendant 10 minutes, jusqu'à obtenir une pâte lisse et élastique, puis laisser lever pendant 2 heures, ou jusqu'à ce que le volume ait doublé.",
         "Sortir 300 g de pâte à pizza levée (préparée 2 heures à l'avance) et la laisser revenir à température ambiante."),
        ("txt", "Napper de 400 g de sauce tomate salée", "Napper de 150 g de sauce tomate"),
        ("txt", "Répartir 250 g de tofu nature sur la sauce tomate, en utilisant un tofu à texture ferme pour une texture crémeuse.", "Répartir 250 g de tofu ferme émietté sur la sauce tomate."),
        ("txt", "Arroser d'un filet d'huile d'olive vierge extra", "Arroser de 20 ml d'huile d'olive vierge extra"),
        ("step-", "Ajouter des tomates fraîches coupées en dés"),
        ("txt", "Servir aussitôt dans des assiettes préchauffées, garni de feuilles de basilic frais et accompagné d'un filet d'huile d'olive vierge extra. Accompagner de riz, de pain ou d'une garniture de noix de coco et d'herbes fraîches, en laissant libre cours à la créativité pour trouver le meilleur accompagnement à cette pizza végétalienne.",
         "Servir aussitôt."),
        ("time", 11, 120, 10),
    ],
    # 80 g de pâte pour un moule de 26 cm, parmesan 120 g, oignon et huile du texte absents
    "tarte_quiche_vegetarienne_b849b0": [
        ("qty", "shortcrust_pastry_all_butter_raw_paste_pre_packaged", 230),
        ("qty", "parmesan_grated_dried_cow", 80),
        ("qty", "table_salt_unenriched", 2),
        ("add", "onion_raw", 100, "g", "aromatic"),
        ("add", "olive_oil_plant", 20, "ml", "fat"),
        ("txt", "Faire revenir les oignons et les légumes choisis dans 20 g d'huile d'olive", "Faire revenir 100 g d'oignon émincé et les légumes dans 20 ml d'huile d'olive"),
        ("txt", "Ajouter 120 g de parmesan râpé", "Ajouter 80 g de parmesan râpé"),
        ("step-", "Pour une présentation plus élégante, parsemer de feuilles de persil"),
    ],
    "tempeh_tempeh_frit_ccb7d2": [
        ("serv", 4),
        ("ing", "coriander_spice_leaf_dried", "coriander_spice_seed"),
        ("qty", "soy_sauce_tamari", 30),
        ("txt", "le tempeh fumé", "le tempeh"),
        ("txt", "mélanger 45 ml de sauce soja", "mélanger 30 ml de sauce soja"),
        ("step-", "Retourner et cuire jusqu'à ce que le tempeh soit croustillant"),
        ("txt", "Servir chaud dans des bols préchauffés, accompagné de riz et d'une sauce pimentée, pour un repas équilibré et savoureux, garni de coriandre fraîche ciselée pour une touche de fraîcheur.", "Servir chaud, avec du riz."),
    ],
    "tempeh_tempeh_teriyaki_da1952": [
        ("qty", "sesame_oil_plant", 20),
        ("add", "green_onion_raw", 20, "g", "garnish"),
        ("txt", "30 ml de sauce teriyaki, 20 ml d'huile de sésame et 10 ml d'huile de coco", "60 ml de sauce teriyaki et 20 ml d'huile de sésame"),
        ("txt", "Verser la marinade restante dans la poêle", "Ajouter 9 g d'ail haché, puis verser la marinade restante dans la poêle"),
        ("txt", "Ajouter 9 grammes d'ail haché finement et 20 grammes de graines de sésame grillées pour parsemer le tempeh.", "Parsemer de 20 grammes de graines de sésame grillées."),
        ("step-", "Faire chauffer 45 ml d'huile de sésame dans la poêle"),
        ("txt", "en ajoutant des oignons verts ciselés", "en ajoutant 20 g d'oignons verts ciselés"),
    ],
}
