"""Titres anglais des variantes (titles.en et titles.original), qui gardaient l'ancien nom du plat
et faussaient la recherche (ex. « Pizza Margherita (Vegan) » pour la pizza marinara)."""

TITLES_EN = {
    "dal_koshari_15670d": "Express Koshari with Red Lentils",
    "dal_koshari_egyptien_73828c": "Cairo Koshari with Chickpeas and Daqqa Sauce",
    "main_koshari_classic_v4_q7n5z2": "Festive Koshari with Shatta",
    "couscous_tfaya_classic_k1d1p6": "Fez Couscous Tfaya with Butter and Honey",
    "couscous_tfaya_vegan_65aba6": "Couscous Tfaya with Chickpeas and Sweet Potato (Vegan)",
    "dal_harira_822880": "Express Harira with Vermicelli",
    "soup_harira_classic_v3_p9x4k2": "Traditional Moroccan Harira with Tadouira",
    "dal_mujadara_2f5904": "Syrian Mujaddara Burghul",
    "dal_sambar_581de8": "Tamil Sambar with Eggplant and Okra",
    "dal_sambar_indien_fcf6d8": "Udupi Sambar with Coconut and Pumpkin",
    "dal_falafel_traditionnels_214e07": "Lebanese Sesame Falafel",
    "falafel_optimise_2f1451": "Egyptian Ta'ameya with Fava Beans",
    "falafel_bowl_de_falafel_vegan_f4fd40": "Baked Falafel Bowl with Rice and Tahini (Vegan)",
    "soup_borscht_classic_k39x2c": "Ukrainian Borscht with Kidney Beans and Dill",
    "soup_borscht_fd9212": "Clear Polish Barszcz with Mushrooms",
    "curry_japanese_classic_v3_m8q2z4": "Japanese Curry with Homemade Roux and Grated Apple",
    "curry_japanese_4533d1": "Japanese Curry with Pumpkin and Shiitake",
    "curry_japonais_1caddf": "Kare Raisu with Caramelized Onions",
    "dal_de_lentilles_corail_vegan_8cc6a7": "Bengali Masoor Dal with Panch Phoron",
    "dal_lentil_corail_classic_k1d1p1": "Punjabi Dal Tadka",
    "dal_lentilles_corail_au_lait_de_co_19d485": "Sri Lankan Parippu with Coconut Milk",
    "dal_lentil_shepherd_s_pie_477c76": "Vegetarian Lentil Cottage Pie with Cheddar",
    "dal_lentil_shepherd_pie_vegan_926ebd": "Lentil Pie with Sweet Potato Mash (Vegan)",
    "dal_lentil_shepherds_pie_vega_27455d": "Mushroom Shepherd's Pie with Celeriac Mash (Vegan)",
    "dessert_compote_de_pommes_maison_cdbdd0": "Vanilla Apple and Pear Compote",
    "base_applesauce_b0627b": "Plain Applesauce",
    "dumpling_pierogi_pommes_de_terre_ca9985": "Pierogi Ruskie with Potato and Farmer's Cheese",
    "pasta_pierogi_aux_pommes_de_6b3efe": "Lublin Pierogi with Buckwheat and Potato",
    "dumpling_pierogi_aux_pommes_de_ter_24a890": "Potato and Dill Pierogi (Vegan)",
    "dumpling_pierogi_aux_champignons_d86017": "Mushroom Pierogi with Sour Cream",
    "dumpling_pierogi_aux_champignons_v_beca85": "Christmas Eve Pierogi with Sauerkraut and Mushrooms (Vegan)",
    "main_tian_provencal_4c7999": "Provençal Tian Gratin with Goat Cheese",
    "side_tian_provencal_vegan_886a6d": "Niçoise Tian with Potatoes and Rosemary (Vegan)",
    "pasta_gnocchi_al_pesto_5bb01c": "Gnocchi with Pesto, Green Beans and Potatoes",
    "pasta_gnocchi_pesto_classic_v2_m7k2q4": "Gnocchi with Mortar-Pounded Genoese Pesto",
    "pasta_gnocchi_al_pesto_vegan_954303": "Gnocchi with Arugula and Walnut Pesto (Vegan)",
    "pasta_gnocchis_a_la_tomate_8e1632": "Gnocchi alla Sorrentina",
    "pasta_gnocchis_a_la_tomate_vega_ca281e": "Pan-Fried Gnocchi with Cherry Tomatoes and Basil (Vegan)",
    "main_gnocchi_f17041": "Homemade Gnocchi with Butter and Sage",
    "entry_taboule_libanais_a_la_gre_cae147": "Lebanese Tabbouleh with Pomegranate and Sumac",
    "side_tabbouleh_de_sarrasin_7e68ad": "Buckwheat Tabbouleh with Cucumber",
    "egg_sundubu_jjigae_bc21e0": "Baek Sundubu, Mild Silken Tofu Stew",
    "stew_sundubu_tofu_stew_ebe50e": "Spicy Kimchi Sundubu Jjigae",
    "pasta_pasta_puttanesca_e14266": "Neapolitan Spaghetti alla Puttanesca",
    "pasta_puttanesca_v1x9q2": "Puttanesca Pasta with Roasted Cherry Tomatoes and Garlic Crumbs",
    "egg_quiche_lorraine_vegetarienne_77343c": "Caramelized Onion and Fresh Goat Cheese Quiche",
    "tarte_quiche_vegetarienne_b849b0": "Summer Vegetable and Parmesan Quiche",
    "snack_empanadas_974cf2": "Salteña Humita Empanadas with Corn and Fresh Cheese",
    "snack_empanadas_au_fromage_466bc4": "Buenos Aires Cheese and Onion Empanadas",
    "snack_empanadas_au_fromage_vega_79575a": "Caramelized Onion and Vegan Cheddar Empanadas",
    "soup_minestrone_9116a2": "Summer Minestrone alla Genovese with Basil",
    "soup_minestrone_italienne_f98e05": "Milanese Winter Minestrone with Rice and Savoy Cabbage",
    "main_polenta_ai_funghi_b96235": "Creamy Polenta with Porcini and Parmesan",
    "main_polenta_aux_champignons_5af074": "Grilled Polenta with Mushrooms Trifolati",
    "main_polenta_ai_funghi_vegan_ab13cd": "Creamy Polenta with Mushroom Tomato Ragout (Vegan)",
    "main_polenta_aux_champignons_v_b0e1ad": "Baked Polenta Fries with Parsley Mushrooms (Vegan)",
    "rice_risotto_ai_funghi_395f00": "Risotto ai Porcini, Mantecato with Butter and Parmesan",
    "rice_risotto_aux_champignon_25ed38": "Woodland Risotto with Oyster Mushrooms and Thyme",
    "rice_risotto_ai_funghi_vegan_41360e": "Roasted Mushroom and Hazelnut Risotto (Vegan)",
    "rice_risotto_aux_champignons_v_13d611": "Mushroom and Spinach Risotto (Vegan)",
    "rice_risotto_al_limone_4088e5": "Amalfi Risotto al Limone",
    "rice_risotto_al_limone_vegan_a234ae": "Lemon and Fennel Risotto (Vegan)",
    "rice_risotto_citron_asperges_f2f765": "Bassano White Asparagus Risotto",
    "rice_risotto_citron_asperges_v_e20e67": "Green Asparagus, Pea and Mint Risotto (Vegan)",
    "main_bulgarian_shopska_salad_d473eb": "Sofia Shopska Salad with Sirene",
    "salad_shopska_04dd73": "Ovcharska Shepherd's Salad with Eggs and Mushrooms",
    "salad_bulgarian_shopska_salad_v_adc716": "Shopska Salad with Dill-Marinated Tofu (Vegan)",
    "salad_shopska_vegan_001f9e": "Shopska Salad with White Beans and Roasted Peppers (Vegan)",
    "wrap_quesadillas_au_fromage_511e1a": "Rajas Quesadillas with Chihuahua Cheese",
    "wrap_quesadillas_c8edf2": "Mushroom and Goat Cheese Quesadillas with Pico de Gallo",
    "wrap_quesadillas_au_fromage_ve_9794c7": "Black Bean and Vegan Cheddar Quesadillas",
    "wrap_quesadillas_vegan_f68baa": "Sweet Potato, Corn and Vegan Cheddar Quesadillas",
    "bread_buckwheat_crepe_03db22": "Breton Buckwheat Galettes, Water Batter",
    "main_galettes_sarrasin_ce9f40": "Forestière Complète Galette with Egg, Gruyère and Mushrooms",
    "brkf_galette_sarrasin_champign_f6a798": "Buckwheat Galette with Garlic-Thyme Mushrooms (Vegan)",
    "wok_thai_veg_eb92db": "Bangkok Pad Thai with Tofu and Egg",
    "protein_pad_thai_vegan_33c0f3": "Crunchy Vegetable Pad Thai (Vegan)",
    "noodle_pad_see_ew_classic_v3_n8x4p2": "Pad See Ew with Chinese Broccoli, Tofu and Egg",
    "noodle_pad_see_ew_vegan_162330": "Pad Kee Mao, Drunken Basil Noodles (Vegan)",
    "rice_pad_krapow_63acfb": "Tofu Pad Krapow with Jasmine Rice and Fried Egg",
    "wok_pad_krapow_vegetarien_565aa9": "Pad Krapow with Green Beans and Mushrooms (Vegan)",
    "main_arepas_fromage_e3a54c": "Colombian Arepas with Fresh Cheese and Butter",
    "main_arepas_fromage_vegan_3a4125": "Reina Pepiada Arepas with Avocado and Chickpeas (Vegan)",
    "main_parmigiana_di_melanzane_6bd49f": "Neapolitan Parmigiana di Melanzane",
    "main_aubergines_parmigiana_sim_e5028f": "Light Grilled Eggplant and Zucchini Parmigiana",
    "main_parmigiana_di_melanzane_v_8f8b8b": "Parmigiana with Vegan Mozzarella and Herb Crumbs",
    "main_aubergines_parmigiana_sim_ad314c": "Sicilian Eggplant Involtini (Vegan)",
    "main_baked_ziti_b9e13e": "New York Baked Ziti with Ricotta",
    "main_baked_ziti_vegan_ad57f8": "Pasta al Forno with Roasted Vegetables and Vegan Mozzarella",
    "pasta_lasagnes_8adf61": "Spinach and Ricotta Lasagna",
    "pasta_lasagnes_vegan_412e90": "Lentil Bolognese Lasagna (Vegan)",
    "pasta_lasagnes_de_legumes_ultra_9b6a4e": "Grilled Vegetable Lasagna with Coconut Béchamel (Vegan)",
    "pasta_mac_and_cheese_b3073b": "American Baked Cheddar Mac and Cheese",
    "pasta_mac_and_cheese_vegan_4acb30": "Butternut Squash Mac and Cheese (Vegan)",
    "tarte_margherita_v7k2d1": "Neapolitan Pizza Margherita with Fior di Latte",
    "tarte_pizza_margherita_vegan_02bb9a": "Pizza Marinara with Garlic and Oregano",
    "bread_bannock_e03ffe": "Oven-Baked Bannock, First Nations Bread",
    "snack_bannock_vegan_46a1a8": "Fried Blueberry Bannock (Vegan)",
    "dal_boulettes_suedoises_2ac55d": "Vegetarian Chickpea Köttbullar with Cream Sauce and Lingonberries",
    "dal_boulettes_suedoises_vegan_fea9f6": "Swedish Lentil-Mushroom Balls with Brown Gravy (Vegan)",
    "main_carottes_glacees_a_lerabl_87d5f0": "Quebec Butter and Maple Glazed Carrots",
    "side_carottes_glacees_a_lerabl_1d1c44": "Maple, Cumin and Sesame Roasted Carrots (Vegan)",
    "main_crumble_aux_myrtilles_5f7d47": "Apple-Blueberry Crumble with Salted Butter",
    "dessert_crumble_aux_myrtilles_veg_15390f": "Blueberry-Lemon Almond Oat Crumble (Vegan)",
    "egg_crepe_coreenne_aux_oignons_ver_356ac2": "Pajeon Scallion Pancake with Vinegar Soy Sauce",
    "snack_crepe_coreenne_aux_oignon_a45536": "Kimchijeon, Crispy Kimchi Pancake (Vegan)",
    "dal_dal_makhani_c9ce94": "Delhi Dal Makhani with Butter and Cream",
    "dal_makhani_vegan_259219": "Punjabi Rajma Masala (Vegan)",
    "bread_enchiladas_fe7221": "Enchiladas Rojas with Black Beans and Queso Fresco",
    "wrap_enchiladas_vegan_f70bca": "Enchiladas Verdes with Sweet Potato and Spinach (Vegan)",
    "main_farofa_bresilienne_29e38e": "Farofa de Ovo, Toasted Cassava Flour with Eggs",
    "side_farofa_bresilienne_vegan_45d889": "Plantain and Cashew Farofa (Vegan)",
    "egg_feijo_tropeiro_bb31e4": "Feijão Tropeiro Mineiro with Eggs and Kale",
    "side_feijo_tropeiro_vegan_ccc81d": "Tutu de Feijão, Black Bean and Cassava Purée (Vegan)",
    "protein_gadogado_indonesien_200c65": "Jakarta Gado-Gado with Eggs and Peanut Sauce",
    "salad_gadogado_indonesien_vegan_e4cd75": "Javanese Pecel with Spicy Peanut Sauce (Vegan)",
    "main_greek_briam_4091c5": "Greek Briam with Roasted Vegetables and Feta",
    "main_greek_briam_vegan_3fb054": "Chickpea Briam with Lemon and Dill (Vegan)",
    "main_gozleme_aux_epinards_66eccf": "Anatolian Spinach and Feta Gözleme",
    "snack_gozleme_aux_epinards_vega_6ff07b": "Spiced Potato and Parsley Gözleme (Vegan)",
    "main_humita_andine_fe7789": "Peruvian Humitas with Fresh Cheese in Corn Husks",
    "snack_humita_andine_vegan_1f09bf": "Argentine Humita en Olla with Corn and Squash (Vegan)",
    "rice_jeera_rice_a4633c": "Butter Jeera Rice with Cumin Seeds",
    "side_jeera_rice_vegan_694fd1": "Pea and Cumin Pulao (Vegan)",
    "dal_kadhi_pakora_078de2": "Punjabi Kadhi Pakora",
    "dal_kadhi_pakora_vegan_5cb5d4": "Sweet and Sour Gujarati Kadhi with Chickpeas (Vegan)",
    "bread_katsu_bf3f1e": "Tofu Katsu Curry with Panko and Japanese Roux",
    "curry_katsu_vegan_f2e6a3": "Eggplant Katsu Curry with Homemade Curry Sauce (Vegan)",
    "bread_mexican_enfrijoladas_578ae7": "Oaxacan Enfrijoladas with Queso Fresco",
    "main_mexican_enfrijoladas_vega_d6a9a8": "Roasted Vegetable Enmoladas (Vegan)",
    "rice_nasi_goreng_edfce4": "Nasi Goreng Kampung with Fried Egg",
    "rice_nasi_goreng_vegan_bcc9cb": "Tempeh and Green Bean Nasi Goreng (Vegan)",
    "egg_ojja_5bdbea": "Tunisian Ojja with Eggs, Peppers and Harissa",
    "brkf_ojja_vegan_dbbad8": "Chickpea and Scrambled Tofu Ojja with Caraway (Vegan)",
    "curry_palak_paneer_b4ca11": "Punjabi Palak Paneer with Ghee",
    "protein_palak_paneer_vegan_bdac46": "Chana Palak, Chickpeas with Spinach (Vegan)",
    "curry_paneer_butter_masala_9e638c": "Delhi Paneer Makhani (Paneer Butter Masala)",
    "protein_paneer_butter_masala_vega_6c63de": "Vegetable Korma with Tofu and Cashews (Vegan)",
    "protein_paneer_tikka_94f80a": "Tandoori Paneer Tikka with Peppers and Onions",
    "protein_paneer_tikka_vegan_8bf0a0": "Tandoori Cauliflower and Chickpeas with Mint Chutney (Vegan)",
    "main_pav_bhaji_e99df8": "Mumbai Butter Pav Bhaji",
    "main_pav_bhaji_vegan_c1437e": "Vada Pav, Potato Fritter in a Bun (Vegan)",
    "pasta_persian_ash_reshteh_8cb79c": "Tehran Ash Reshteh with Kashk and Fried Mint",
    "soup_persian_ash_reshteh_vegan_968f7d": "Ash-e Jo, Persian Barley and Herb Soup (Vegan)",
    "main_poutine_1344e1": "Quebec Poutine with Brown Gravy and Cheese Curds",
    "main_poutine_vegan_18f8c2": "Oven Fries Poutine with Mushroom Gravy (Vegan)",
    "main_pupusas_9d2c72": "Pupusas Revueltas with Cheese and Loroco",
    "main_pupusas_aux_haricots_fc8bfd": "Bean and Cheese Pupusas with Curtido",
    "main_pupusas_vegan_4595d8": "Squash and Black Bean Pupusas (Vegan)",
    "rice_riz_pilaf_turc_52cfe9": "Şehriyeli Pilav, Rice Pilaf with Toasted Vermicelli",
    "side_riz_pilaf_turc_vegan_3bb995": "İç Pilav with Currants, Pine Nuts and Cinnamon (Vegan)",
    "rice_kimchi_fried_rice_1f3e90": "Kimchi Bokkeumbap with Fried Egg",
    "rice_riz_saute_au_kimchi_vegan_af038b": "Kimchi Fried Rice with Tofu and Shiitake (Vegan)",
    "side_rosti_4ec9f8": "Bernese Butter Rösti",
    "snack_rosti_vegan_be15a2": "Root Vegetable and Chive Rösti (Vegan)",
    "rice_sabzi_polo_e099d2": "Nowruz Sabzi Polo with Tahdig",
    "side_sabzi_polo_vegan_7bf9df": "Baghali Polo with Fava Beans and Dill (Vegan)",
    "salad_andine_au_fromage_c537bd": "Arequipa Solterito with Fresh Cheese",
    "salad_andine_au_fromage_vegan_566f05": "Andean Quinoa, Avocado and Black Bean Salad (Vegan)",
    "bread_salmorejo_a156e9": "Salmorejo Cordobés with Hard-Boiled Egg",
    "entry_salmorejo_vegan_d0b7f7": "Málaga Ajo Blanco with Almonds and Grapes (Vegan)",
    "egg_shakshuka_eb137b": "Tunisian Shakshuka with Peppers and Feta",
    "brkf_shakshuka_vegan_81fa9a": "Eggplant Shakshuka with Silken Tofu and Sumac (Vegan)",
    "soup_tamales_7dd98a": "Tamales Rajas con Queso",
    "snack_tamales_vegan_d7cbdc": "Bean Tamales with Red Sauce (Vegan)",
    "bread_tostadas_06442e": "Black Bean, Avocado and Crema Tostadas",
    "snack_tostadas_vegan_f7257b": "Mushroom Tinga Tostadas (Vegan)",
    "dal_mercimek_koftesi_34f72d": "Mercimek Köftesi, Lentil and Bulgur Patties",
    "dal_turkish_mercimek_soup_a7afcf": "Istanbul Mercimek Çorbası with Chili Butter",
    "soup_turkish_mercimek_soup_veg_f30ebc": "Ezogelin Çorbası, Lentil, Bulgur and Mint Soup (Vegan)",
    "main_varenyky_pomme_de_terre_0bb7cf": "Ukrainian Potato and Dill Varenyky with Fried Onions",
    "snack_varenyky_pomme_de_terre_v_8b6240": "Sour Cherry Varenyky (Vegan)",
    "rice_kimchi_bokkeumbap_2cbfe6": "Cheesy Baked Kimchi Bokkeumbap",
    "main_rajma_masala_bce2a4": "Jammu Rajma Chawal, Kidney Beans and Rice",
    "tarte_moussaka_veg_d55fa8": "Greek Vegetarian Moussaka with Milk Béchamel",
    "main_moussaka_fcf86b": "Lentil and Potato Moussaka (Vegan)",
    "pasta_pasta_alla_norma_5cc26e": "Catania Pasta alla Norma with Ricotta Salata",
    "pasta_pasta_alla_norma_a_la_ric_d282a6": "Roasted Eggplant Pasta with Cherry Tomatoes and Cashew Ricotta (Vegan)",
    "salad_greek_classic_v2_t4m8q1": "Horiatiki, Greek Village Salad with Feta",
    "salad_grecque_classique_vegan_a9f9a4": "Greek Salad with Chickpeas and Oregano-Marinated Tofu (Vegan)",
    "soup_soup_k3d2p1": "Lyonnaise French Onion Soup with Comté",
    "soup_a_l_oignon_gratinee_vegan_826f59": "Cider Onion Soup with Garlic Croutons (Vegan)",
    "dessert_tarte_tatin_9c0f67": "Lamotte-Beuvron Tarte Tatin with Butter Caramel",
    "dessert_tarte_tatin_vegan_1ae13b": "Cardamom Pear Tatin with Puff Pastry (Vegan)",
    "side_dauphinois_vegan_c584cb": "Potato and Leek Gratin with Oat Cream (Vegan)",
    "soup_pumpkin_k2d1p1": "Roasted Butternut Velouté with Pumpkin Seeds",
    "soup_soupe_courge_butternut_2f5cf3": "Thai Butternut Soup with Coconut Milk and Ginger",
    "dal_soupe_de_lentilles_621239": "Country Green Lentil and Vegetable Soup",
    "dal_soupe_lentilles_turque_e797cb": "Shorbat Adas, Lebanese Red Lentil Soup with Lemon",
    "entry_terrine_de_legumes_e52466": "Spring Vegetable Terrine in Basil Jelly",
    "entry_terrine_legumes_du_soleil_e5e24a": "Provençal Grilled Vegetable Terrine with Goat Cheese",
    "base_cheddar_vegane_529b97": "Melty Coconut Milk Vegan Cheese",
    "base_vegan_cheddar_024998": "Cashew and Red Pepper Vegan Cheddar",
    "main_kimchi_1dc648": "Express Mak Kimchi with Soy Sauce",
    "base_kimchi_61791a": "Fermented Napa Cabbage Kimchi (Base)",
    "chili_paste_95cb92": "Fresh Chili and Ginger Paste",
    "base_pate_piment_b6904a": "Garlic Chili Paste (Base)",
    "samosa_dough_c03717": "Cumin-Spiced Samosa Dough",
    "base_samosa_77fac4": "Plain Samosa Dough (Base)",
    "main_fried_rice_a6e811": "Dan Chao Fan, Egg and Scallion Fried Rice",
    "base_fried_rice_f230b0": "Cantonese Fried Rice with Peas and Carrots",
    "base_curry_paste_49c97f": "Fresh Red Chili Curry Paste",
    "soup_tom_kha_cee413": "Tom Kha, Thai Coconut Mushroom Soup",
    "dal_lebanese_lentil_soup_eae561": "Adas bi Hamod, Lebanese Lentil Soup with Chard and Lemon",
    "dal_armenian_lentil_soup_0f1067": "Vospov Apur, Armenian Lentil Soup with Dried Apricots",
    "dal_persian_lentil_soup_71e221": "Adasi, Persian Lentil Soup with Turmeric and Dates",
    "dal_shorbat_adas_d4f98a": "Iraqi Shorbat Adas, Red Lentil Soup with Turmeric",
    "dal_soupe_lentilles_turque_e797cb": "Red Lentil Soup with Fried Onion and Lemon",
    "dal_hummus_traditionnel_7f6ccc": "Quick Hummus with Canned Chickpeas",
}
