"""Variantes 1 : koshari, couscous tfaya, harira — quasi-doublons différenciés en vraies variantes."""

VARIANTS = {
    # ── Koshari : express (une casserole) / du Caire (daqqa, pois chiches) / de fête (shatta) ──
    "dal_koshari_15670d": [
        ("title", "Koshari express aux lentilles corail"),
        ("desc", "Version rapide du koshari cuite en une seule casserole : lentilles corail, riz et vermicelles dorés, "
                 "nappés d'une sauce tomate au cumin et d'oignons frits."),
        ("compo", [
            ("red_lentil_dried", 150, "g", "plant_protein", "dried"),
            ("white_rice_raw_seed_unenriched", 200, "g", "carbohydrate"),
            ("rice_vermicelli_raw_dried", 50, "g", "ingredient"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("tomato_sauce_salted_canned", 400, "g", "condiment"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 1, "g", "spice"),
            ("white_vinegar_liquid_distilled", 20, "ml", "ingredient"),
            ("olive_oil_extra_virgin_plant", 40, "ml", "fat"),
            ("water", 700, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ]),
        ("steps", [
            "Émincer 200 g d'oignon et le faire dorer 12 minutes dans 25 ml d'huile d'olive, jusqu'à ce qu'il soit brun et croustillant. Réserver sur du papier absorbant.",
            "Dans la même casserole, avec 15 ml d'huile, dorer 50 g de vermicelles de riz brisés 2 minutes.",
            "Ajouter 200 g de riz et 150 g de lentilles corail rincés, 700 ml d'eau et 3 g de sel. Couvrir et cuire 18 minutes à feu doux, jusqu'à absorption.",
            "Pendant ce temps, chauffer 400 g de sauce tomate avec 9 g d'ail haché, 3 g de cumin et 1 g de piment, 8 minutes, puis ajouter 20 ml de vinaigre.",
            "Servir le riz aux lentilles nappé de sauce et parsemé d'oignons frits.",
        ]),
        ("time", 10, 0, 30),
    ],
    "dal_koshari_egyptien_73828c": [
        ("title", "Koshari du Caire aux pois chiches, sauce daqqa"),
        ("desc", "Le koshari des échoppes du Caire : riz, lentilles brunes, macaronis et pois chiches en couches, "
                 "sauce tomate épicée, daqqa à l'ail et au vinaigre, et oignons frits croustillants."),
        ("compo", [
            ("green_lentil_dried", 150, "g", "plant_protein", "dried"),
            ("white_rice_raw_seed_unenriched", 150, "g", "carbohydrate"),
            ("pasta_raw_dried", 150, "g", "ingredient"),
            ("chickpea_boiled", 150, "g", "plant_protein", "cooked"),
            ("yellow_onion_raw", 300, "g", "aromatic_base"),
            ("tomato_sauce_salted_canned", 400, "g", "condiment"),
            ("tomato_raw_ripe", 240, "g", "vegetable"),
            ("garlic_raw", 20, "g", "aromatic"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("white_vinegar_liquid_distilled", 40, "ml", "ingredient"),
            ("sunflower_oil_plant", 45, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ]),
        ("steps", [
            "Cuire séparément à l'eau bouillante 150 g de lentilles brunes (25 minutes), 150 g de riz (12 minutes) et 150 g de macaronis (8 minutes). Égoutter.",
            "Émincer 300 g d'oignons en fines rondelles et les frire 20 minutes dans 30 ml d'huile de tournesol, jusqu'à ce qu'ils soient bruns et croustillants.",
            "Sauce : faire revenir 10 g d'ail haché dans 15 ml d'huile, ajouter 240 g de tomates concassées, 400 g de sauce tomate, 2 g de cumin et 2 g de sel, puis cuire 15 minutes.",
            "Daqqa : écraser 10 g d'ail avec 2 g de cumin et 1 g de sel, puis délayer avec 40 ml de vinaigre et 2 cuillerées d'eau.",
            "Réchauffer 150 g de pois chiches dans la sauce les 5 dernières minutes.",
            "Monter les bols en couches (riz, lentilles, macaronis), napper de sauce aux pois chiches, arroser de daqqa et couvrir d'oignons frits.",
        ]),
        ("time", 20, 0, 40),
    ],
    "main_koshari_classic_v4_q7n5z2": [
        ("title", "Koshari de fête à la shatta"),
        ("desc", "Koshari généreux des repas de fête : riz aux vermicelles, lentilles, pâtes, sauce tomate longuement "
                 "réduite et shatta, la sauce pimentée égyptienne, pour relever le tout."),
        ("compo", [
            ("white_rice_raw_seed_unenriched", 200, "g", "base"),
            ("rice_vermicelli_raw_dried", 30, "g", "ingredient"),
            ("green_lentil_dried", 200, "g", "protein", "dried"),
            ("pasta_raw_dried", 100, "g", "texture"),
            ("onion_raw", 300, "g", "garnish"),
            ("tomato_raw_ripe", 400, "g", "sauce"),
            ("garlic_raw", 20, "g", "aromatic"),
            ("chilli_pepper_raw", 20, "g", "spice"),
            ("white_vinegar_liquid_distilled", 30, "ml", "balanced_acidity"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("coriander_spice_seed", 2, "g", "spice"),
            ("sunflower_oil_plant", 60, "ml", "fat_cooking"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Cuire 200 g de lentilles vertes 25 minutes et 100 g de petites pâtes 8 minutes à l'eau bouillante. Égoutter.",
            "Dorer 30 g de vermicelles dans 10 ml d'huile, ajouter 200 g de riz, 400 ml d'eau et 2 g de sel, couvrir et cuire 15 minutes à feu doux.",
            "Frire 300 g d'oignons émincés dans 40 ml d'huile de tournesol 20 minutes, jusqu'à ce qu'ils soient bruns et croustillants.",
            "Sauce : faire revenir 10 g d'ail, 3 g de cumin et 2 g de coriandre moulue dans 10 ml d'huile, ajouter 400 g de tomates concassées et 2 g de sel, puis réduire 25 minutes.",
            "Shatta : mixer 20 g de piment frais avec 10 g d'ail, 30 ml de vinaigre et une pincée de sel.",
            "Dresser riz, lentilles et pâtes, napper de sauce tomate, couvrir d'oignons frits et servir la shatta à part.",
        ]),
        ("time", 35, 0, 50),
    ],

    # ── Couscous tfaya : de Fès au beurre et au miel / vegan aux pois chiches et patate douce ──
    "couscous_tfaya_classic_k1d1p6": [
        ("title", "Couscous tfaya de Fès au beurre et au miel"),
        ("desc", "Le couscous tfaya des grandes occasions à Fès : semoule roulée au beurre et cuite deux fois à la vapeur, "
                 "oignons confits au miel, à la cannelle et aux raisins, amandes grillées et fleur d'oranger."),
        ("compo", [
            ("couscous_to_cook_seed_dried", 300, "g", "base"),
            ("red_onion_raw", 450, "g", "vegetable"),
            ("grape_dried", 100, "g", "sweet_garnish", "hydrated"),
            ("butter_sup80pct", 40, "g", "fat"),
            ("olive_oil_plant", 20, "ml", "fat"),
            ("honey", 40, "g", "sweetener"),
            ("cinnamon", 4.5, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("almond_raw_with_skin_unsalted", 60, "g", "garnish", "toasted"),
            ("orange_blossom_water", 5, "g", "aromatic"),
            ("water", 380, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Arroser 300 g de semoule de 300 ml d'eau salée tiède, laisser gonfler 5 minutes puis l'égrener avec 20 g de beurre.",
            "Cuire la semoule 10 minutes à la vapeur du couscoussier, l'égrener à nouveau à la main, puis la cuire encore 10 minutes.",
            "Tfaya : faire fondre 450 g d'oignons rouges émincés dans 20 ml d'huile d'olive et 20 g de beurre, 30 minutes à feu doux, jusqu'à ce qu'ils soient confits.",
            "Ajouter 2 g de curcuma, 4,5 g de cannelle, 40 g de miel, 100 g de raisins secs et 80 ml d'eau, puis laisser réduire 10 minutes jusqu'à consistance sirupeuse.",
            "Torréfier 60 g d'amandes à sec 3 minutes.",
            "Dresser la semoule en dôme, déposer la tfaya au centre, parsemer d'amandes et arroser de 5 g d'eau de fleur d'oranger.",
        ]),
        ("time", 30, 5, 55),
    ],
    "couscous_tfaya_vegan_65aba6": [
        ("title", "Couscous tfaya aux pois chiches et patate douce (vegan)"),
        ("desc", "Couscous végétal complet : semoule vapeur, patate douce rôtie à la cannelle, pois chiches et tfaya "
                 "d'oignons caramélisés au sirop d'érable et au gingembre, parsemés d'amandes."),
        ("compo", [
            ("couscous_to_cook_seed_dried", 250, "g", "grain"),
            ("sweet_potato_raw", 400, "g", "vegetable"),
            ("chickpea_boiled", 240, "g", "plant_protein", "cooked"),
            ("yellow_onion_raw", 400, "g", "aromatic_base"),
            ("grape_dried", 60, "g", "sweetener"),
            ("maple_syrup", 30, "ml", "sweetener"),
            ("ginger_raw_root_fresh", 5, "g", "aromatic"),
            ("cinnamon", 3, "g", "spice"),
            ("olive_oil_extra_virgin_plant", 50, "ml", "fat"),
            ("almond_raw_with_skin_unsalted", 40, "g", "garnish", "toasted"),
            ("water", 300, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("black_pepper_spice", 1, "g", "spice"),
        ]),
        ("steps", [
            "Préchauffer le four à 200°C. Couper 400 g de patate douce en cubes, les mélanger avec 15 ml d'huile d'olive, 1 g de cannelle et 1 g de sel, puis les rôtir 25 minutes.",
            "Tfaya : faire fondre 400 g d'oignons émincés avec 5 g de gingembre râpé dans 25 ml d'huile d'olive, 25 minutes à feu doux.",
            "Ajouter 2 g de cannelle, 30 ml de sirop d'érable, 60 g de raisins secs et 240 g de pois chiches, puis mijoter 10 minutes.",
            "Arroser 250 g de semoule de 300 ml d'eau bouillante salée, couvrir 5 minutes, puis l'égrener avec 10 ml d'huile d'olive.",
            "Torréfier 40 g d'amandes à sec 3 minutes.",
            "Dresser la semoule, disposer la patate douce et la tfaya aux pois chiches, parsemer d'amandes et poivrer.",
        ]),
        ("time", 20, 0, 40),
    ],

    # ── Harira : express aux vermicelles / traditionnelle à la tadouira ──
    "dal_harira_822880": [
        ("title", "Harira express aux vermicelles"),
        ("desc", "Harira de semaine, prête en 45 minutes : pois chiches, lentilles, tomates et céleri, "
                 "vermicelles cuits dans le bouillon, herbes fraîches et citron, sans liaison à la farine."),
        ("dish", "soup"),
        ("compo", [
            ("chickpea_boiled", 300, "g", "plant_protein", "cooked"),
            ("green_lentil_dried", 100, "g", "plant_protein", "dried"),
            ("pasta_raw_dried", 50, "g", "carbohydrate"),
            ("celery_stalk_raw", 80, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("vegetable_stock_dried", 12, "g", "ingredient"),
            ("water", 1200, "ml", "liquid"),
            ("turmeric_powder", 3, "g", "spice"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("cinnamon", 2, "g", "spice"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("parsley_fresh_herb", 15, "g", "herb"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("olive_oil_extra_virgin_plant", 30, "ml", "fat"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ]),
        ("steps", [
            "Faire revenir 150 g d'oignon et 80 g de céleri émincés dans 30 ml d'huile d'olive, 5 minutes à feu moyen.",
            "Ajouter 3 g de curcuma, 10 g de gingembre râpé et 2 g de cannelle, puis cuire 1 minute.",
            "Ajouter 300 g de tomates concassées, 100 g de lentilles vertes rincées et 1,2 L de bouillon, puis mijoter 25 minutes.",
            "Ajouter 300 g de pois chiches et 50 g de vermicelles, puis cuire encore 8 minutes.",
            "Hors du feu, ajouter 15 g de coriandre et 15 g de persil ciselés et 20 ml de jus de citron. Servir chaud.",
        ]),
        ("time", 15, 0, 40),
    ],
    "soup_harira_classic_v3_p9x4k2": [
        ("title", "Harira marocaine traditionnelle à la tadouira"),
        ("desc", "La harira du ftour de Ramadan : lentilles corail, pois chiches et tomates longuement mijotés, "
                 "liés en fin de cuisson par la tadouira (farine délayée), relevés d'herbes fraîches et de citron."),
    ],
}
