"""Variantes 2 : mujadara, sambar, falafel, bortsch."""

VARIANTS = {
    # ── Mujadara : libanaise au riz / syrienne au boulgour ──
    "dal_mujadara_2f5904": [
        ("title", "Mujaddara burghul syrienne au boulgour"),
        ("desc", "Version syrienne de la mujadara : lentilles brunes et gros boulgour cuits ensemble, "
                 "parfumés au cumin et au piment de la Jamaïque, couverts d'oignons frits bien bruns."),
        ("origin", {"cuisine": "syrian", "country": "syria", "region": "alep", "city": "alep"}),
        ("compo", [
            ("green_lentil_dried", 200, "g", "plant_protein", "dried"),
            ("bulgur_raw_dried", 200, "g", "carbohydrate"),
            ("onion_raw", 350, "g", "aromatic_base"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("allspice_powder", 1, "g", "spice"),
            ("olive_oil_plant", 50, "ml", "fat"),
            ("water", 900, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("black_pepper_spice", 1, "g", "spice"),
        ]),
        ("steps", [
            "Cuire 200 g de lentilles brunes rincées dans 600 ml d'eau, 15 minutes à frémissement : elles doivent rester fermes.",
            "Émincer 350 g d'oignons en demi-rondelles et les frire dans 50 ml d'huile d'olive, 25 minutes à feu moyen, jusqu'à ce qu'ils soient brun foncé.",
            "Retirer les deux tiers des oignons et les réserver sur du papier absorbant. Dans le reste, faire revenir 4 g de cumin et 1 g de piment de la Jamaïque 1 minute.",
            "Ajouter 200 g de gros boulgour, remuer 1 minute, puis ajouter les lentilles avec leur eau, 300 ml d'eau, 4 g de sel et 1 g de poivre.",
            "Couvrir et cuire 15 minutes à feu très doux, puis laisser reposer 10 minutes hors du feu.",
            "Égrener à la fourchette et servir couvert des oignons frits réservés.",
        ]),
        ("time", 10, 10, 55),
    ],
    "rice_mujadara_classic_ee2456": [
        ("desc", "La mujadara de Beyrouth : lentilles vertes et riz long cuits ensemble dans l'huile des oignons, "
                 "relevés de cumin torréfié et couronnés d'oignons confits brun acajou."),
    ],

    # ── Sambar : tamoul aux légumes / d'Udupi à la noix de coco ──
    "dal_sambar_581de8": [
        ("title", "Sambar tamoul aux aubergines et gombos"),
        ("desc", "Sambar des cantines de Chennai : lentilles fondues, aubergines, gombos et pilons de moringa "
                 "dans un bouillon au tamarin et à la poudre de sambar, tempérés de moutarde et de feuilles de curry."),
        ("origin", {"cuisine": "indian"}),
        ("compo", [
            ("red_lentil_dried", 200, "g", "plant_protein", "dried"),
            ("eggplant_raw", 200, "g", "vegetable"),
            ("okra_raw", 150, "g", "vegetable"),
            ("drumstick_horseradish_tree_raw_pod", 100, "g", "vegetable"),
            ("shallot_raw", 100, "g", "aromatic_base"),
            ("tomato_raw_ripe", 200, "g", "fruit"),
            ("sambar_powder", 20, "g", "spice"),
            ("tamarind", 30, "ml", "ingredient"),
            ("turmeric_powder", 2, "g", "spice"),
            ("yellow_mustard_spice_seed", 3, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("coconut_oil_plant", 30, "ml", "fat"),
            ("water", 1000, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Cuire 200 g de lentilles corail rincées avec 2 g de curcuma dans 600 ml d'eau, 15 minutes, puis les écraser au fouet.",
            "Dans une grande casserole, porter à frémissement 400 ml d'eau avec 30 ml de pâte de tamarin, 4 g de sel, 200 g d'aubergine en cubes, 100 g de pilons de moringa en tronçons de 5 cm et 100 g d'échalotes entières. Cuire 10 minutes.",
            "Ajouter 150 g de gombos en tronçons, 200 g de tomates en quartiers et 20 g de poudre de sambar, puis cuire 8 minutes.",
            "Verser les lentilles et laisser mijoter 5 minutes : le sambar doit être fluide.",
            "Tempérage : chauffer 30 ml d'huile de coco, y faire éclater 3 g de graines de moutarde, ajouter 5 g de feuilles de curry, puis verser le tout sur le sambar.",
            "Servir chaud, avec du riz ou des idlis.",
        ]),
        ("time", 20, 0, 35),
    ],
    "dal_sambar_indien_fcf6d8": [
        ("title", "Sambar d'Udupi à la noix de coco et au potiron"),
        ("desc", "Sambar du Karnataka, plus doux que la version tamoule : lentilles corail, potiron et carotte "
                 "dans une pâte de noix de coco grillée aux épices, adoucie d'une touche de sucre roux."),
        ("origin", {"cuisine": "indian", "region": "karnataka", "city": "udupi"}),
        ("compo", [
            ("red_lentil_dried", 200, "g", "plant_protein", "dried"),
            ("pumpkin_raw", 300, "g", "vegetable"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("tomato_raw_ripe", 200, "g", "fruit"),
            ("coconut_flesh_dried", 40, "g", "ingredient"),
            ("sambar_powder", 15, "g", "spice"),
            ("tamarind", 20, "ml", "ingredient"),
            ("brown_sugar", 10, "g", "sweetener"),
            ("turmeric_powder", 2, "g", "spice"),
            ("yellow_mustard_spice_seed", 3, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("coconut_oil_plant", 25, "ml", "fat"),
            ("water", 1000, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Cuire 200 g de lentilles corail rincées avec 2 g de curcuma dans 600 ml d'eau, 15 minutes, puis les écraser.",
            "Faire griller à sec 40 g de noix de coco râpée avec 15 g de poudre de sambar, 2 minutes, puis les mixer avec 100 ml d'eau en pâte lisse.",
            "Cuire 300 g de potiron et 150 g de carotte en cubes dans 300 ml d'eau avec 4 g de sel, 10 minutes.",
            "Ajouter 200 g de tomates concassées, 20 ml de tamarin, 10 g de sucre roux, la pâte de coco et les lentilles, puis mijoter 10 minutes.",
            "Tempérage : chauffer 25 ml d'huile de coco, y faire éclater 3 g de graines de moutarde avec 5 g de feuilles de curry, puis verser sur le sambar.",
            "Servir chaud, avec du riz.",
        ]),
        ("time", 15, 0, 35),
    ],

    # ── Falafel : libanais au sésame / ta'amiya égyptienne aux fèves / bowl au four ──
    "dal_falafel_traditionnels_214e07": [
        ("title", "Falafel libanais au sésame"),
        ("desc", "Falafel de Beyrouth aux pois chiches trempés, persil, coriandre et cumin, roulés dans le sésame "
                 "puis frits jusqu'à former une croûte dorée."),
        ("compo", [
            ("chickpea_raw_dried", 400, "g", "plant_protein", "soaked"),
            ("onion_raw", 100, "g", "aromatic"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("parsley_fresh_herb", 30, "g", "herb"),
            ("coriander_spice_seed", 6, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("sesame_seed_hulled_dried", 20, "g", "garnish"),
            ("sunflower_oil_plant", 45, "ml", "fat"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ]),
        ("steps", [
            "Faire tremper 400 g de pois chiches secs 12 heures dans l'eau froide, puis les égoutter et les sécher.",
            "Mixer par impulsions les pois chiches avec 100 g d'oignon, 9 g d'ail, 30 g de persil, 6 g de coriandre moulue, 3 g de cumin et 5 g de sel, jusqu'à une texture de sable humide.",
            "Réfrigérer l'appareil 30 minutes pour le raffermir.",
            "Former des palets de 35 g et les rouler d'un côté dans 20 g de graines de sésame.",
            "Frire les falafels par petites quantités dans l'huile à 175°C, 3 à 4 minutes, jusqu'à ce qu'ils soient bien dorés (environ 45 ml d'huile absorbée). Égoutter sur du papier absorbant.",
            "Servir chaud, avec du pain pita et une sauce tahini.",
        ]),
        ("time", 20, 750, 15),
    ],
    "falafel_optimise_2f1451": [
        ("title", "Ta'amiya égyptienne aux fèves"),
        ("desc", "Le falafel du Caire, à base de fèves sèches décortiquées plutôt que de pois chiches : "
                 "un intérieur vert vif aux herbes fraîches et une croûte fine et croustillante."),
        ("compo", [
            ("broadbeans_fava_beans_raw_dried", 300, "g", "protein_base", "soaked"),
            ("yellow_onion_raw", 120, "g", "vegetable"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("parsley_fresh_herb", 30, "g", "herb"),
            ("coriander_raw_fresh_herb", 40, "g", "herb"),
            ("dill_weed_fresh_herb_leaf", 10, "g", "herb"),
            ("cumin_spice_seed", 5, "g", "spice"),
            ("coriander_spice_seed", 3, "g", "spice"),
            ("sesame_seed_hulled_dried", 15, "g", "garnish"),
            ("sunflower_oil_plant", 60, "ml", "fat"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ]),
        ("steps", [
            "Faire tremper 300 g de fèves sèches décortiquées 12 heures, puis les égoutter et les sécher soigneusement.",
            "Mixer les fèves avec 120 g d'oignon, 15 g d'ail, 30 g de persil, 40 g de coriandre fraîche, 10 g d'aneth, 5 g de cumin, 3 g de coriandre moulue et 5 g de sel, jusqu'à une pâte verte fine mais non liquide.",
            "Réfrigérer 30 minutes.",
            "Former des galettes aplaties de 30 g et les parsemer de 15 g de graines de sésame.",
            "Frire par lots dans l'huile de tournesol à 175°C, 3 minutes, jusqu'à ce qu'elles soient dorées (environ 60 ml d'huile absorbée). Égoutter.",
            "Servir chaud dans du pain baladi ou pita, avec de la salade et de la tahina.",
        ]),
        ("time", 25, 750, 15),
    ],
    "falafel_bowl_de_falafel_vegan_f4fd40": [
        ("title", "Bowl de falafels au four, riz et tahini (vegan)"),
        ("desc", "Bowl complet et plus léger : falafels de pois chiches cuits au four, riz, concombre, tomate, "
                 "laitue et cornichons, nappés d'une sauce tahini citronnée."),
        ("compo", [
            ("chickpea_boiled", 400, "g", "plant_protein", "cooked"),
            ("chickpea_flour", 30, "g", "binder"),
            ("white_rice_raw_seed_unenriched", 200, "g", "carbohydrate"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("cucumber_raw", 250, "g", "vegetable"),
            ("lettuce", 150, "g", "vegetable"),
            ("pickles_cucumber_canned_in_vinegar", 60, "g", "condiment"),
            ("sesame_tahini_raw_butter_seed_plant", 45, "ml", "condiment"),
            ("lemon_juice", 30, "ml", "fruit"),
            ("olive_oil_plant", 30, "ml", "fat"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("parsley_fresh_herb", 20, "g", "herb"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("water", 330, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Préchauffer le four à 200°C. Cuire 200 g de riz dans 300 ml d'eau salée, 12 minutes à couvert et à feu très doux.",
            "Mixer 400 g de pois chiches cuits avec 30 g de farine de pois chiches, 10 g d'ail, 20 g de persil, 3 g de cumin et 3 g de sel, jusqu'à une pâte granuleuse qui se tient.",
            "Former 16 boulettes aplaties, les badigeonner de 30 ml d'huile d'olive et les cuire 20 minutes au four en les retournant à mi-cuisson.",
            "Sauce : mélanger 45 ml de tahini, 30 ml de jus de citron, 2 g d'ail râpé et 30 ml d'eau froide jusqu'à ce qu'elle soit lisse.",
            "Dresser dans quatre bols le riz, 150 g de laitue, 300 g de tomates et 250 g de concombre en dés, 60 g de cornichons émincés, puis les falafels.",
            "Napper de sauce tahini et servir.",
        ]),
        ("time", 20, 0, 25),
    ],

    # ── Bortsch : ukrainien aux haricots / barszcz polonais clair ──
    "soup_borscht_classic_k39x2c": [
        ("title", "Bortsch ukrainien aux haricots rouges et à l'aneth"),
        ("desc", "Bortsch de Kiev épais et complet : betterave, chou, pommes de terre et haricots rouges, "
                 "relevé d'ail et de vinaigre, servi avec de l'aneth et une cuillerée de crème aigre."),
        ("origin", {"cuisine": "ukrainian", "region": "kyiv", "city": "kyiv"}),
        ("compo", [
            ("beetroot_raw_root", 400, "g", "vegetable"),
            ("green_cabbage_raw", 250, "g", "vegetable"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("yellow_onion_raw", 120, "g", "aromatic"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("potato_raw_flesh", 250, "g", "structure"),
            ("kidney_bean_boiled", 240, "g", "plant_protein", "cooked"),
            ("tomato_paste_unsalted_canned", 30, "g", "umami"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("white_vinegar_liquid_distilled", 20, "ml", "acidity"),
            ("white_sugar", 5, "g", "balance"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("vegetable_stock_dried", 10, "g", "base"),
            ("water", 1400, "ml", "base"),
            ("black_pepper_spice", 1, "g", "seasoning"),
            ("dill_weed_fresh_herb_leaf", 10, "g", "garnish"),
            ("cream", None, "1 cuillère à soupe", "serving_suggestion"),
        ]),
        ("steps", [
            "Porter à ébullition 1,4 L d'eau avec 10 g de bouillon déshydraté et 1 g de laurier. Ajouter 250 g de pommes de terre en cubes et cuire 10 minutes.",
            "Pendant ce temps, faire revenir 120 g d'oignon émincé et 120 g de carotte râpée dans 30 ml d'huile de tournesol, 5 minutes.",
            "Ajouter 400 g de betterave crue en julienne, 30 g de concentré de tomate, 20 ml de vinaigre et 5 g de sucre, puis étuver 10 minutes à couvert : le vinaigre fixe la couleur.",
            "Ajouter 250 g de chou émincé dans le bouillon et cuire 5 minutes, puis y verser la betterave et 240 g de haricots rouges. Mijoter 10 minutes.",
            "Hors du feu, ajouter 15 g d'ail pilé et 1 g de poivre, couvrir et laisser reposer 10 minutes.",
            "Servir parsemé de 10 g d'aneth ciselé, avec une cuillerée de crème aigre.",
        ]),
        ("time", 25, 10, 40),
    ],
    "soup_borscht_fd9212": [
        ("title", "Barszcz polonais clair aux champignons"),
        ("desc", "Le barszcz czerwony du réveillon polonais : un bouillon limpide de betterave et de légumes racines, "
                 "parfumé aux cèpes, à la marjolaine et à l'ail, acidulé au citron et servi en tasse."),
        ("compo", [
            ("beetroot_raw_root", 800, "g", "base"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("celeriac_raw", 100, "g", "vegetable"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("porcini_mushroom_raw", 100, "g", "umami"),
            ("garlic_raw", 10, "g", "aromatic"),
            ("vegetable_stock_dried", 10, "g", "cooking_liquid"),
            ("water", 1500, "ml", "cooking_liquid"),
            ("marjoram_spice_dried", 2, "g", "herb"),
            ("allspice_powder", 1, "g", "spice"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("lemon_juice", 40, "ml", "acidifier"),
            ("white_sugar", 5, "g", "balance"),
            ("black_pepper_spice", 1, "g", "spice"),
        ]),
        ("steps", [
            "Mettre dans une grande casserole 150 g de carotte, 100 g de céleri-rave et 100 g d'oignon coupés en gros morceaux, 100 g de cèpes émincés, 1 g de laurier, 1 g de piment de la Jamaïque, 10 g de bouillon déshydraté et 1,5 L d'eau. Mijoter 30 minutes.",
            "Ajouter 800 g de betteraves crues épluchées et coupées en fines lamelles, puis cuire 20 minutes à petit frémissement, sans bouillir, pour garder la couleur.",
            "Filtrer le bouillon à travers une passoire fine en pressant légèrement les légumes.",
            "Ajouter 10 g d'ail pilé, 2 g de marjolaine, 40 ml de jus de citron, 5 g de sucre et 1 g de poivre, puis laisser infuser 10 minutes hors du feu.",
            "Réchauffer sans faire bouillir et servir le barszcz clair, en tasse, avec les cèpes.",
        ]),
        ("time", 20, 10, 55),
    ],
}
