"""Variantes 3 : curry japonais, dal de lentilles corail, hachis de lentilles, compote de pommes."""

VARIANTS = {
    # ── Curry japonais : roux fait maison / potiron et champignons / kare raisu aux oignons caramélisés ──
    "curry_japanese_classic_v3_m8q2z4": [
        ("title", "Curry japonais au roux maison et à la pomme râpée"),
        ("desc", "Curry japonais préparé sans tablette : roux brun au beurre, poudre de curry et garam masala, "
                 "adouci de pomme râpée et de miel, avec pommes de terre et carottes fondantes."),
        ("compo", [
            ("onion_raw", 220, "g", "base"),
            ("potato_raw_flesh", 400, "g", "texture"),
            ("carrot_raw", 200, "g", "texture"),
            ("apple_raw", 120, "g", "sweetener"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 35, "g", "binding"),
            ("butter_sup80pct", 60, "g", "roux_support"),
            ("vegetable_stock_dried", 10, "g", "cooking_medium"),
            ("water", 850, "ml", "cooking_medium"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("ginger_raw_root_fresh", 15, "g", "aromatic"),
            ("honey", 10, "g", "sweetener"),
            ("soy_sauce_shoyu_reduced_sodium", 15, "ml", "seasoning"),
            ("curry_powder", 8, "g", "spice"),
            ("garam_masala", 4, "g", "spice"),
            ("white_rice_short_grain_seed_dried", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Faire fondre 25 g de beurre dans une cocotte et y faire revenir 220 g d'oignon émincé 8 minutes. Ajouter 15 g d'ail et 15 g de gingembre hachés, puis cuire 1 minute.",
            "Ajouter 400 g de pommes de terre et 200 g de carottes en gros cubes, 850 ml d'eau chaude et 10 g de bouillon déshydraté. Mijoter 15 minutes.",
            "Roux : faire fondre 35 g de beurre, ajouter 35 g de farine et cuire 6 à 8 minutes en remuant, jusqu'à ce qu'il soit couleur noisette. Hors du feu, ajouter 8 g de poudre de curry et 4 g de garam masala.",
            "Délayer le roux dans une louche de bouillon et le verser dans la cocotte avec 120 g de pomme râpée, 10 g de miel et 15 ml de sauce soja.",
            "Mijoter 10 minutes à feu doux en remuant, jusqu'à ce que la sauce soit épaisse et brillante.",
            "Servir sur du riz japonais.",
        ]),
        ("time", 20, 0, 40),
    ],
    "curry_japanese_4533d1": [
        ("title", "Curry japonais au potiron et aux shiitakés"),
        ("desc", "Curry d'automne à la mode d'Hokkaido : potiron, shiitakés et pommes de terre mijotés dans une "
                 "sauce au roux de curry, naturellement douce grâce au potiron."),
        ("origin", {"region": "hokkaido", "city": "sapporo"}),
        ("compo", [
            ("pumpkin_raw", 400, "g", "vegetable"),
            ("shiitake_mushroom_raw", 150, "g", "vegetable"),
            ("potato_raw_flesh", 250, "g", "ingredient"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("base_japanese_curry_roux_385e52", 80, "g", "ingredient"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 700, "ml", "ingredient"),
            ("sunflower_oil_plant", 20, "ml", "fat"),
            ("white_rice_short_grain_seed_dried", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Faire revenir 150 g d'oignon émincé dans 20 ml d'huile de tournesol, 5 minutes, puis ajouter 9 g d'ail haché et 150 g de shiitakés émincés et cuire 3 minutes.",
            "Ajouter 250 g de pommes de terre et 120 g de carotte en cubes, 700 ml d'eau et 8 g de bouillon déshydraté, puis mijoter 10 minutes.",
            "Ajouter 400 g de potiron en gros cubes et cuire encore 10 minutes, jusqu'à ce qu'il soit tendre sans se défaire.",
            "Hors du feu, dissoudre 80 g de roux de curry japonais, puis remettre sur feu doux 5 minutes en remuant, jusqu'à ce que la sauce épaississe.",
            "Servir sur du riz japonais.",
        ]),
        ("time", 15, 0, 30),
    ],
    "curry_japonais_1caddf": [
        ("title", "Kare raisu aux oignons caramélisés"),
        ("desc", "Le kare raisu des cantines japonaises : oignons longuement caramélisés, pommes de terre et carottes "
                 "dans une sauce au roux de curry, servi à côté d'un riz japonais."),
        ("origin", {"region": "kanto", "city": "yokosuka"}),
        ("compo", [
            ("onion_raw", 300, "g", "aromatic_base"),
            ("potato_raw_flesh", 450, "g", "ingredient"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("base_japanese_curry_roux_385e52", 80, "g", "ingredient"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1060, "ml", "ingredient"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("white_rice_short_grain_seed_dried", 300, "g", "carbohydrate"),
        ]),
        ("steps", [
            "Émincer finement 300 g d'oignons et les caraméliser dans 25 ml d'huile de tournesol, 25 minutes à feu moyen-doux, jusqu'à ce qu'ils soient brun ambré.",
            "Ajouter 450 g de pommes de terre et 200 g de carottes en cubes, puis faire revenir 3 minutes.",
            "Verser 700 ml d'eau et 8 g de bouillon déshydraté, puis mijoter 15 minutes.",
            "Pendant ce temps, rincer 300 g de riz japonais et le cuire à couvert dans 360 ml d'eau, 12 minutes, puis le laisser reposer 10 minutes.",
            "Hors du feu, dissoudre 80 g de roux de curry dans la sauce, puis mijoter 5 minutes en remuant.",
            "Servir dans des assiettes creuses, le riz d'un côté et le curry de l'autre.",
        ]),
        ("time", 15, 10, 45),
    ],

    # ── Dal de lentilles corail : bengali au panch phoron / tadka du Pendjab / parippu sri lankais ──
    "dal_de_lentilles_corail_vegan_8cc6a7": [
        ("title", "Masoor dal bengali au panch phoron"),
        ("desc", "Dal fluide de Calcutta : lentilles corail au curcuma, tempérées au panch phoron (moutarde, cumin, "
                 "fenugrec, fenouil) grésillé dans l'huile, avec un filet de citron."),
        ("origin", {"region": "bengale_occidental", "city": "kolkata"}),
        ("compo", [
            ("red_lentil_dried", 250, "g", "protein", "dried"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 10, "g", "aromatic"),
            ("tomato_raw_ripe", 150, "g", "fruit"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("turmeric_powder", 3, "g", "spice"),
            ("yellow_mustard_spice_seed", 2, "g", "spice"),
            ("cumin_spice_seed", 2, "g", "spice"),
            ("fenugreek_spice_seed", 1, "g", "spice"),
            ("fennel_spice_seed", 2, "g", "spice"),
            ("lemon_juice", 15, "ml", "condiment"),
            ("water", 900, "ml", "cooking_liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Rincer 250 g de lentilles corail et les cuire dans 900 ml d'eau avec 3 g de curcuma et 4 g de sel, 20 minutes, puis les fouetter : le dal doit rester fluide.",
            "Chauffer 30 ml d'huile et y faire grésiller le panch phoron (2 g de moutarde, 2 g de cumin, 1 g de fenugrec et 2 g de fenouil en graines) 30 secondes.",
            "Ajouter 100 g d'oignon émincé et 8 g de piment vert fendu, puis cuire 5 minutes. Ajouter 10 g d'ail haché et 150 g de tomate en dés, puis cuire 3 minutes.",
            "Verser ce tempérage sur le dal et laisser frémir 3 minutes.",
            "Hors du feu, ajouter 15 ml de jus de citron. Servir avec du riz.",
        ]),
        ("time", 15, 0, 30),
    ],
    "dal_lentil_corail_classic_k1d1p1": [
        ("title", "Dal tadka du Pendjab"),
        ("desc", "Le dal tadka des dhabas du Pendjab : lentilles corail épaisses aux tomates, gingembre et ail, "
                 "finies par un tadka de cumin et de piment grésillé, et de la coriandre fraîche."),
        ("compo", [
            ("red_lentil_dried", 250, "g", "base", "dried"),
            ("onion_raw", 140, "g", "aromatic"),
            ("garlic_raw", 20, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("tomato_raw_ripe", 250, "g", "sauce_base"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("cumin_spice_seed", 5, "g", "spice"),
            ("turmeric_powder", 3, "g", "spice"),
            ("coriander_spice_seed", 4, "g", "spice"),
            ("garam_masala", 2, "g", "spice"),
            ("chilli_pepper_raw", 10, "g", "spice"),
            ("coriander_raw_fresh_herb", 10, "g", "garnish"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("water", 700, "ml", "liquid"),
            ("lime_juice_fresh", 15, "ml", "acid"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Rincer 250 g de lentilles corail et les cuire dans 700 ml d'eau avec 3 g de curcuma, 20 minutes, jusqu'à ce qu'elles se défassent.",
            "Chauffer 25 ml d'huile et faire revenir 140 g d'oignon émincé 8 minutes, jusqu'à ce qu'il soit doré. Ajouter 15 g d'ail et 10 g de gingembre hachés, puis 4 g de coriandre moulue et 2 g de garam masala, et cuire 1 minute.",
            "Ajouter 250 g de tomates concassées et 4 g de sel, puis réduire 5 minutes. Verser sur les lentilles et mijoter 5 minutes.",
            "Tadka : chauffer 15 ml d'huile, y faire grésiller 5 g de graines de cumin, 5 g d'ail émincé et 10 g de piment vert fendu, 1 minute, puis verser sur le dal.",
            "Ajouter 15 ml de jus de citron vert, parsemer de 10 g de coriandre fraîche ciselée et servir avec du riz.",
        ]),
        ("time", 20, 0, 35),
    ],
    "dal_lentilles_corail_au_lait_de_co_19d485": [
        ("title", "Parippu sri lankais au lait de coco"),
        ("desc", "Le dhal curry de Colombo : lentilles corail cuites dans le lait de coco avec curcuma, cannelle et "
                 "piment vert, tempérées à l'huile de coco, aux feuilles de curry et aux oignons."),
        ("origin", {"cuisine": "sri_lankan", "country": "sri_lanka", "region": "province_occidentale", "city": "colombo"}),
        ("compo", [
            ("red_lentil_dried", 200, "g", "base", "dried"),
            ("onion_raw", 120, "g", "aromatic"),
            ("garlic_raw", 10, "g", "aromatic"),
            ("tomato_raw_ripe", 100, "g", "vegetable"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("coconut_milk_plant", 300, "ml", "liquid"),
            ("water", 400, "ml", "liquid"),
            ("turmeric_powder", 2, "g", "spice"),
            ("cinnamon", 1, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("yellow_mustard_spice_seed", 2, "g", "spice"),
            ("coconut_oil_plant", 20, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Rincer 200 g de lentilles corail et les mettre dans une casserole avec 400 ml d'eau, 60 g d'oignon émincé, 8 g de piment vert fendu, 100 g de tomate en dés, 2 g de curcuma et 1 g de cannelle.",
            "Porter à ébullition et cuire 15 minutes, jusqu'à ce que les lentilles soient tendres.",
            "Ajouter 300 ml de lait de coco et 4 g de sel, puis mijoter 5 minutes à feu doux sans faire bouillir.",
            "Tempérage : chauffer 20 ml d'huile de coco, y faire éclater 2 g de graines de moutarde, puis ajouter 60 g d'oignon émincé, 10 g d'ail et 5 g de feuilles de curry, et faire dorer 4 minutes.",
            "Verser le tempérage sur le dhal et servir avec du riz.",
        ]),
        ("time", 15, 0, 30),
    ],

    # ── Hachis de lentilles : cottage pie au cheddar / patate douce (vegan) / champignons et céleri-rave (vegan) ──
    "dal_lentil_shepherd_s_pie_477c76": [
        ("title", "Cottage pie végétarien aux lentilles et au cheddar"),
        ("desc", "Cottage pie à l'anglaise : lentilles vertes mijotées au thym avec carottes, petits pois et tomate, "
                 "couvertes d'une purée au beurre gratinée au cheddar."),
        ("compo", [
            ("green_lentil_dried", 200, "g", "plant_protein", "dried"),
            ("potato_raw_flesh", 700, "g", "ingredient"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("green_peas_raw", 120, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("tomato_paste_unsalted_canned", 30, "g", "umami"),
            ("thyme_dried_herb", 1, "g", "herb"),
            ("butter_sup80pct", 40, "g", "fat_cooking"),
            ("milk_liquid_uht_3_5pct", 150, "ml", "ingredient"),
            ("cheddar_cow", 60, "g", "topping"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 700, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
            ("black_pepper_spice", 1, "g", "spice"),
        ]),
        ("steps", [
            "Faire revenir 150 g d'oignon et 150 g de carotte en dés dans 10 g de beurre, 8 minutes.",
            "Ajouter 200 g de lentilles vertes rincées, 30 g de concentré de tomate, 1 g de thym, 700 ml d'eau et 8 g de bouillon déshydraté. Mijoter 25 minutes, jusqu'à ce que les lentilles soient tendres et le liquide presque absorbé, puis ajouter 120 g de petits pois.",
            "Pendant ce temps, cuire 700 g de pommes de terre à l'eau salée 20 minutes, puis les écraser avec 30 g de beurre, 150 ml de lait chaud, 2 g de sel et 1 g de poivre.",
            "Préchauffer le four à 200°C. Verser les lentilles dans un plat, couvrir de purée et strier à la fourchette.",
            "Parsemer de 60 g de cheddar râpé et enfourner 20 minutes, jusqu'à ce que le dessus soit doré.",
        ]),
        ("time", 20, 0, 55),
    ],
    "dal_lentil_shepherd_pie_vegan_926ebd": [
        ("title", "Hachis de lentilles à la patate douce (vegan)"),
        ("desc", "Hachis végétal aux lentilles vertes, carottes et thym, recouvert d'une purée de patate douce "
                 "au paprika fumé et au lait d'avoine, gratinée au four."),
        ("compo", [
            ("green_lentil_dried", 200, "g", "plant_protein", "dried"),
            ("sweet_potato_raw", 700, "g", "ingredient"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("tomato_paste_unsalted_canned", 30, "g", "umami"),
            ("thyme_fresh_herb", 5, "g", "herb"),
            ("paprika", 2, "g", "spice"),
            ("vegan_butter", 25, "g", "fat_cooking"),
            ("oat_milk_refrigerated_plain_plant", 100, "ml", "ingredient"),
            ("olive_oil_plant", 15, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 700, "ml", "ingredient"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ]),
        ("steps", [
            "Faire revenir 150 g d'oignon en dés dans 15 ml d'huile d'olive 5 minutes, puis ajouter 200 g de carottes en dés et 6 g d'ail haché, et cuire 3 minutes.",
            "Ajouter 200 g de lentilles vertes rincées, 30 g de concentré de tomate, 5 g de thym, 700 ml d'eau et 8 g de bouillon déshydraté, puis mijoter 25 minutes jusqu'à ce que le liquide soit presque absorbé.",
            "Cuire 700 g de patates douces en cubes à la vapeur 15 minutes, puis les écraser avec 25 g de beurre végétal, 100 ml de lait d'avoine, 2 g de paprika fumé et 2 g de sel.",
            "Préchauffer le four à 200°C. Étaler les lentilles dans un plat et les couvrir de purée de patate douce.",
            "Enfourner 20 minutes, jusqu'à ce que les bords soient dorés. Servir chaud.",
        ]),
        ("time", 20, 0, 60),
    ],
    "dal_lentil_shepherds_pie_vega_27455d": [
        ("title", "Shepherd's pie vegan aux champignons, purée au céleri-rave"),
        ("desc", "Garniture de lentilles et de champignons au romarin et à la sauce soja, sous une purée légère "
                 "mi-pomme de terre mi-céleri-rave au lait de soja."),
        ("compo", [
            ("green_lentil_dried", 150, "g", "plant_protein", "dried"),
            ("button_mushroom_raw", 300, "g", "vegetable"),
            ("potato_raw_with_skin", 400, "g", "ingredient"),
            ("celeriac_raw", 300, "g", "ingredient"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("rosemary_fresh_herb", 3, "g", "herb"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "seasoning"),
            ("vegan_butter", 30, "g", "fat_cooking"),
            ("olive_oil_plant", 15, "ml", "fat"),
            ("soybean_milk_unsweetened_plant", 120, "ml", "ingredient"),
            ("vegetable_stock_dried", 6, "g", "ingredient"),
            ("water", 600, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ]),
        ("steps", [
            "Cuire 150 g de lentilles vertes rincées dans 600 ml d'eau avec 6 g de bouillon déshydraté, 25 minutes, puis les égoutter.",
            "Faire dorer 300 g de champignons émincés dans 15 ml d'huile d'olive à feu vif 6 minutes. Ajouter 150 g d'oignon et 150 g de carotte en dés, 6 g d'ail et 3 g de romarin hachés, puis cuire 8 minutes.",
            "Ajouter les lentilles et 20 ml de sauce soja, puis mijoter 5 minutes.",
            "Cuire 400 g de pommes de terre et 300 g de céleri-rave en cubes à l'eau salée 20 minutes, puis les écraser avec 30 g de beurre végétal, 120 ml de lait de soja chaud et 2 g de sel.",
            "Préchauffer le four à 200°C. Étaler la garniture dans un plat, couvrir de purée et strier à la fourchette.",
            "Enfourner 20 minutes, jusqu'à ce que le dessus soit doré.",
        ]),
        ("time", 25, 0, 50),
    ],

    # ── Compote : pommes nature (préparation de base) / pommes-poires vanillée ──
    "dessert_compote_de_pommes_maison_cdbdd0": [
        ("title", "Compote pommes-poires à la vanille"),
        ("desc", "Compote gourmande de pommes et de poires fondantes, parfumée à la vanille et à la cannelle, "
                 "peu sucrée, à servir tiède ou froide."),
        ("compo", [
            ("chantecler_apple_raw_skinless", 600, "g", "main_fruit"),
            ("pear_raw_with_skin", 400, "g", "main_fruit"),
            ("lemon_juice", 15, "ml", "acidifier"),
            ("vanilla_extract", 5, "ml", "aromatic"),
            ("cinnamon", 1, "g", "spice"),
            ("white_sugar", 20, "g", "sweetener"),
            ("water", 30, "ml", "liquid"),
            ("base_soy_cream_4dc027", None, "1 cuillère à soupe", "serving_suggestion"),
        ]),
        ("steps", [
            "Éplucher, épépiner et couper en morceaux 600 g de pommes Chantecler et 400 g de poires.",
            "Les mettre dans une casserole avec 15 ml de jus de citron, 30 ml d'eau, 20 g de sucre et 1 g de cannelle.",
            "Couvrir et cuire 20 minutes à feu doux en remuant de temps en temps, jusqu'à ce que les fruits se défassent.",
            "Hors du feu, ajouter 5 ml d'extrait de vanille et écraser à la fourchette, en gardant quelques morceaux.",
            "Servir tiède ou froid.",
        ]),
        ("time", 10, 0, 20),
    ],
    "base_applesauce_b0627b": [
        ("title", "Compote de pommes nature"),
        ("desc", "Compote de pommes simple, peu sucrée, qui sert de base aux desserts et aux goûters : "
                 "pommes cuites lentement avec un peu de citron, écrasées ou mixées."),
    ],
}
