"""Variantes 11 : kadhi, katsu curry, enfrijoladas, nasi goreng, ojja, palak, paneer butter masala."""

VARIANTS = {
    # ── Kadhi : pakora du Pendjab / gujarati vegan ──
    "dal_kadhi_pakora_078de2": [
        ("title", "Kadhi pakora du Pendjab"),
        ("desc", "Sauce onctueuse de yaourt et de farine de pois chiches mijotée au curcuma et au fenugrec, "
                 "dans laquelle on plonge des pakoras d'oignon croustillants, tempérée au cumin et au piment."),
        ("compo", [
            ("yogurt_plain_3pct", 400, "g", "ingredient"),
            ("chickpea_flour", 180, "g", "carbohydrate"),
            ("yellow_onion_raw", 200, "g", "aromatic_base"),
            ("chickpea_boiled", 150, "g", "plant_protein", "cooked"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("turmeric_powder", 3, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("fenugreek_spice_seed", 1, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("sunflower_oil_plant", 50, "ml", "fat"),
            ("water", 900, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Fouetter 400 g de yaourt avec 60 g de farine de pois chiches, 3 g de curcuma, 3 g de sel et 800 ml d'eau.",
            "Porter à ébullition en remuant, puis ajouter 6 g d'ail et 10 g de gingembre râpés et mijoter 30 minutes à feu doux : le kadhi doit napper la cuillère.",
            "Pakoras : mélanger 120 g de farine de pois chiches, 200 g d'oignon émincé, 150 g de pois chiches écrasés, 10 g de coriandre, 2 g de sel et 100 ml d'eau en une pâte épaisse.",
            "Frire des cuillerées de pâte dans l'huile chaude, 4 minutes, jusqu'à ce qu'elles soient dorées (environ 40 ml d'huile absorbée), puis les plonger dans le kadhi.",
            "Tempérage : chauffer 10 ml d'huile, y faire grésiller 3 g de cumin, 1 g de fenugrec et 2 g de piment, puis verser sur le kadhi. Servir avec du riz.",
        ]),
        ("time", 25, 0, 45),
    ],
    "dal_kadhi_pakora_vegan_5cb5d4": [
        ("title", "Kadhi gujarati sucré-acidulé aux pois chiches (vegan)"),
        ("desc", "Le kadhi du Gujarat, plus fluide et légèrement sucré : yaourt de soja et farine de pois chiches "
                 "au gingembre et au piment vert, pois chiches, tempérage de moutarde et feuilles de curry."),
        ("origin", {"region": "gujarat", "city": "ahmedabad"}),
        ("compo", [
            ("soybean_yogurt_plain_plant", 400, "g", "ingredient"),
            ("chickpea_flour", 50, "g", "carbohydrate"),
            ("chickpea_boiled", 300, "g", "plant_protein", "cooked"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("brown_sugar", 15, "g", "sweetener"),
            ("turmeric_powder", 2, "g", "spice"),
            ("yellow_mustard_spice_seed", 2, "g", "spice"),
            ("cumin_spice_seed", 2, "g", "spice"),
            ("cinnamon", 1, "g", "spice"),
            ("cloves", 0.5, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("sunflower_oil_plant", 20, "ml", "fat"),
            ("water", 700, "ml", "liquid"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Fouetter 400 g de yaourt de soja avec 50 g de farine de pois chiches, 2 g de curcuma, 4 g de sel et 700 ml d'eau.",
            "Ajouter 12 g de gingembre et 6 g de piment vert pilés, et 15 g de sucre roux, puis porter à ébullition en remuant.",
            "Ajouter 300 g de pois chiches et mijoter 15 minutes à feu doux : le kadhi doit rester fluide.",
            "Tempérage : chauffer 20 ml d'huile, y faire éclater 2 g de moutarde et 2 g de cumin, ajouter 1 g de cannelle, 0,5 g de clous de girofle et 5 g de feuilles de curry, puis verser sur le kadhi.",
            "Parsemer de 10 g de coriandre et servir avec du riz.",
        ]),
        ("time", 15, 0, 25),
    ],

    # ── Katsu curry : tofu pané à l'œuf et roux japonais / aubergine panée vegan ──
    "bread_katsu_bf3f1e": [
        ("title", "Tofu katsu curry, panure panko et roux japonais"),
        ("desc", "Tranches de tofu ferme panées à l'œuf et au panko, frites jusqu'à être croustillantes, servies "
                 "sur du riz avec une sauce au roux de curry japonais, carottes et pommes de terre."),
        ("compo", [
            ("tofu_plain_pre_packaged", 400, "g", "protein"),
            ("breadcrumbs_dried", 60, "g", "ingredient"),
            ("rice_flour", 40, "g", "carbohydrate"),
            ("egg_raw", 110, "g", "ingredient"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("potato_raw_flesh", 200, "g", "vegetable"),
            ("base_japanese_curry_roux_385e52", 80, "g", "ingredient"),
            ("water", 600, "ml", "ingredient"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("white_rice_short_grain_seed_dried", 250, "g", "carbohydrate"),
        ]),
        ("steps", [
            "Cuire 250 g de riz japonais rincé dans 300 ml d'eau, 12 minutes à couvert, puis laisser reposer.",
            "Sauce : faire revenir 150 g d'oignon dans 10 ml d'huile, ajouter 120 g de carotte et 200 g de pommes de terre en dés et 600 ml d'eau, puis cuire 15 minutes. Hors du feu, dissoudre 80 g de roux de curry, puis mijoter 5 minutes.",
            "Couper 400 g de tofu pressé en 8 tranches, les passer dans 40 g de farine de riz, puis dans 2 œufs battus (110 g) et enfin dans 60 g de panko.",
            "Frire les tranches dans l'huile chaude, 3 minutes de chaque côté, jusqu'à ce qu'elles soient dorées (environ 30 ml d'huile absorbée).",
            "Servir le tofu tranché sur le riz, nappé de sauce curry.",
        ]),
        ("time", 25, 10, 30),
    ],
    "curry_katsu_vegan_f2e6a3": [
        ("title", "Katsu curry d'aubergine, sauce curry maison (vegan)"),
        ("desc", "Tranches d'aubergine panées au panko sans œuf (pâte de farine et d'eau) et dorées, servies sur "
                 "du riz avec une sauce curry maison à la pomme, sans beurre."),
        ("compo", [
            ("eggplant_raw", 500, "g", "vegetable"),
            ("breadcrumbs_dried", 90, "g", "ingredient"),
            ("rice_flour", 60, "g", "carbohydrate"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("apple_raw", 80, "g", "sweetener"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("curry_powder", 8, "g", "spice"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 25, "g", "binder"),
            ("soy_sauce_shoyu_reduced_sodium", 15, "ml", "seasoning"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 850, "ml", "ingredient"),
            ("sunflower_oil_plant", 60, "ml", "fat"),
            ("white_rice_short_grain_seed_dried", 300, "g", "carbohydrate"),
        ]),
        ("steps", [
            "Cuire 300 g de riz japonais rincé dans 360 ml d'eau, 12 minutes à couvert.",
            "Sauce : faire revenir 150 g d'oignon et 120 g de carotte dans 15 ml d'huile, 8 minutes, ajouter 9 g d'ail, 25 g de farine et 8 g de curry, puis 400 ml d'eau, 8 g de bouillon, 80 g de pomme râpée et 15 ml de sauce soja. Mijoter 15 minutes et mixer.",
            "Couper 500 g d'aubergines en tranches épaisses de 1,5 cm. Délayer 60 g de farine de riz dans 90 ml d'eau.",
            "Tremper les tranches dans la pâte, puis les enrober de 90 g de panko.",
            "Les dorer dans 45 ml d'huile, 4 minutes de chaque côté à feu moyen, jusqu'à ce qu'elles soient tendres à cœur.",
            "Servir sur le riz, nappé de sauce curry.",
        ]),
        ("time", 25, 0, 35),
    ],

    # ── Enfrijoladas d'Oaxaca / enmoladas vegan aux légumes rôtis ──
    "bread_mexican_enfrijoladas_578ae7": [
        ("title", "Enfrijoladas d'Oaxaca au queso fresco"),
        ("desc", "Tortillas repliées et nappées d'une sauce veloutée de haricots noirs à l'avocatier et au piment, "
                 "garnies de queso fresco, d'oignon rouge et de coriandre."),
        ("origin", {"region": "oaxaca", "city": "oaxaca"}),
        ("compo", [
            ("base_tortilla_92c2a6", 320, "g", "ingredient"),
            ("black_bean_boiled", 450, "g", "plant_protein", "cooked"),
            ("queso_fresco_block_cow", 100, "g", "ingredient"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("ancho_pepper_spice_dried", 10, "g", "spice", "dry"),
            ("cumin_spice_seed", 2, "g", "spice"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("olive_oil_extra_virgin_plant", 30, "ml", "fat"),
            ("water", 350, "ml", "liquid"),
            ("red_onion_raw", 50, "g", "garnish"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ]),
        ("steps", [
            "Faire tremper 10 g de piment ancho épépiné dans l'eau chaude 10 minutes.",
            "Mixer 450 g de haricots noirs avec 350 ml d'eau, le piment, 100 g d'oignon, 6 g d'ail, 2 g de cumin et 3 g de sel.",
            "Cuire la sauce 10 minutes dans 20 ml d'huile avec 1 g de laurier : elle doit être veloutée et nappante.",
            "Réchauffer les tortillas une à une dans 10 ml d'huile, les tremper dans la sauce et les replier en quatre dans les assiettes.",
            "Napper du reste de sauce et garnir de 100 g de queso fresco émietté, de 50 g d'oignon rouge émincé et de 10 g de coriandre.",
        ]),
        ("time", 15, 10, 20),
    ],
    "main_mexican_enfrijoladas_vega_d6a9a8": [
        ("title", "Enmoladas aux légumes rôtis (vegan)"),
        ("desc", "Tortillas garnies de patate douce, courgette et haricots noirs rôtis, roulées et nappées de "
                 "mole au chocolat et aux piments, parsemées de sésame et d'oignon rouge."),
        ("origin", {"region": "puebla", "city": "puebla"}),
        ("compo", [
            ("base_tortilla_92c2a6", 320, "g", "ingredient"),
            ("base_mole_d0034f", 250, "ml", "ingredient"),
            ("sweet_potato_raw", 300, "g", "vegetable"),
            ("green_zucchini_squash_raw", 200, "g", "vegetable"),
            ("black_bean_boiled", 200, "g", "plant_protein", "cooked"),
            ("yellow_onion_raw", 100, "g", "aromatic_base"),
            ("olive_oil_extra_virgin_plant", 30, "ml", "fat"),
            ("sesame_seed_hulled_dried", 8, "g", "garnish"),
            ("red_onion_raw", 40, "g", "garnish"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ]),
        ("steps", [
            "Préchauffer le four à 210°C. Rôtir 300 g de patate douce et 200 g de courgette en dés avec 100 g d'oignon, 25 ml d'huile d'olive et 2 g de sel, 25 minutes.",
            "Mélanger les légumes rôtis avec 200 g de haricots noirs.",
            "Réchauffer 250 ml de mole et les tortillas (dans 5 ml d'huile).",
            "Garnir et rouler les tortillas, les disposer dans les assiettes et les napper de mole chaud.",
            "Parsemer de 8 g de sésame grillé, de 40 g d'oignon rouge émincé et de 10 g de coriandre.",
        ]),
        ("time", 20, 0, 30),
    ],

    # ── Nasi goreng : kampung à l'œuf au plat / vegan au tempeh et haricots verts ──
    "rice_nasi_goreng_edfce4": [
        ("title", "Nasi goreng kampung à l'œuf au plat"),
        ("desc", "Riz sauté des villages javanais : riz de la veille sauté avec échalotes, ail, piment et sauce "
                 "soja sucrée, chou et carotte, surmonté d'un œuf au plat et d'oignons frits."),
        ("compo", [
            ("white_rice_cooked_long_grain_seed", 600, "g", "carbohydrate", "cooked"),
            ("shallot_raw", 80, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("green_cabbage_raw", 200, "g", "vegetable"),
            ("tofu_plain_pre_packaged", 200, "g", "protein"),
            ("egg_raw", 220, "g", "ingredient"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("brown_sugar", 10, "g", "sweetener"),
            ("base_fried_onion_217e6a", 30, "g", "ingredient"),
            ("coconut_oil_plant", 40, "ml", "fat"),
            ("cucumber_raw_with_skin", 150, "g", "vegetable"),
        ]),
        ("steps", [
            "Piler 80 g d'échalotes, 9 g d'ail et 6 g de piment en pâte.",
            "Dorer 200 g de tofu en dés dans 15 ml d'huile de coco, puis réserver.",
            "Faire revenir la pâte dans 15 ml d'huile, 2 minutes, ajouter 120 g de carotte et 200 g de chou émincés, puis sauter 3 minutes.",
            "Ajouter 600 g de riz cuit froid, 30 ml de sauce soja mélangée à 10 g de sucre roux, et le tofu, puis sauter 4 minutes à feu vif.",
            "Cuire 4 œufs (220 g) au plat dans 10 ml d'huile.",
            "Servir le riz surmonté d'un œuf, parsemé de 30 g d'oignons frits, avec 150 g de concombre en rondelles.",
        ]),
        ("time", 15, 0, 15),
    ],
    "rice_nasi_goreng_vegan_bcc9cb": [
        ("title", "Nasi goreng au tempeh et aux haricots verts (vegan)"),
        ("desc", "Riz sauté indonésien végétal : tempeh doré, haricots verts et chou sautés avec une pâte "
                 "d'échalote, d'ail et de piment, sauce soja sucrée et oignons frits."),
        ("compo", [
            ("white_rice_cooked_long_grain_seed", 600, "g", "carbohydrate", "cooked"),
            ("tempeh_tempe_raw_fermented", 200, "g", "protein"),
            ("french_bean_raw", 200, "g", "vegetable"),
            ("green_cabbage_raw", 150, "g", "vegetable"),
            ("shallot_raw", 80, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("brown_sugar", 10, "g", "sweetener"),
            ("base_fried_onion_217e6a", 30, "g", "ingredient"),
            ("coconut_oil_plant", 40, "ml", "fat"),
            ("lime_juice_fresh", 10, "ml", "condiment"),
        ]),
        ("steps", [
            "Piler 80 g d'échalotes, 12 g d'ail et 6 g de piment en pâte.",
            "Couper 200 g de tempeh en dés et le dorer dans 20 ml d'huile de coco, 6 minutes. Réserver.",
            "Faire revenir la pâte dans 20 ml d'huile, 2 minutes, ajouter 200 g de haricots verts en tronçons et 150 g de chou émincé, puis sauter 4 minutes.",
            "Ajouter 600 g de riz cuit froid, 30 ml de sauce soja mélangée à 10 g de sucre roux, et le tempeh, puis sauter 4 minutes à feu vif.",
            "Arroser de 10 ml de jus de citron vert et parsemer de 30 g d'oignons frits.",
        ]),
        ("time", 15, 0, 20),
    ],

    # ── Ojja : aux œufs / aux pois chiches et tofu vegan ──
    "egg_ojja_5bdbea": [
        ("title", "Ojja tunisienne aux œufs, poivrons et harissa"),
        ("desc", "Plat de Tunis mijoté : poivrons et tomates fondus à l'ail, à la harissa et au carvi, "
                 "œufs cassés dans la sauce et cuits juste pris, à saucer avec du pain."),
    ],
    "brkf_ojja_vegan_dbbad8": [
        ("title", "Ojja aux pois chiches et tofu brouillé au carvi (vegan)"),
        ("desc", "Ojja végétale : sauce de tomates et poivrons à la harissa, au carvi et à l'ail, pois chiches "
                 "et tofu émietté mijotés dedans, servie avec du pain."),
        ("compo", [
            ("tomato_raw_ripe", 400, "g", "fruit"),
            ("red_bell_pepper_raw", 250, "g", "vegetable"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("tofu_plain_pre_packaged", 200, "g", "ingredient"),
            ("chickpea_boiled", 150, "g", "plant_protein", "cooked"),
            ("base_harissa_ef842f", 12, "g", "ingredient"),
            ("caraway_spice_seed", 1, "g", "spice"),
            ("turmeric_powder", 1, "g", "spice"),
            ("olive_oil_extra_virgin_plant", 25, "ml", "fat"),
            ("parsley_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
            ("white_bread_baguette", None, "1 tranche", "serving_suggestion"),
        ]),
        ("steps", [
            "Faire revenir 100 g d'oignon et 250 g de poivron émincés dans 25 ml d'huile d'olive, 6 minutes.",
            "Ajouter 6 g d'ail, 12 g de harissa et 1 g de carvi moulu, puis cuire 1 minute.",
            "Ajouter 400 g de tomates concassées et 2 g de sel, puis mijoter 10 minutes.",
            "Ajouter 150 g de pois chiches et 200 g de tofu émietté avec 1 g de curcuma, puis cuire 5 minutes.",
            "Parsemer de 10 g de persil et servir avec du pain.",
        ]),
        ("time", 10, 0, 22),
    ],

    # ── Palak : paneer au ghee / chana palak vegan ──
    "curry_palak_paneer_b4ca11": [
        ("title", "Palak paneer du Pendjab au ghee"),
        ("desc", "Paneer maison en cubes dans une purée d'épinards blanchis, relevée d'ail, de gingembre, "
                 "de cumin et de garam masala, montée au ghee."),
    ],
    "protein_palak_paneer_vegan_bdac46": [
        ("title", "Chana palak, pois chiches aux épinards (vegan)"),
        ("desc", "Curry du nord de l'Inde : pois chiches mijotés dans une sauce d'épinards, de tomate, d'oignon "
                 "et de gingembre, parfumée au cumin et au garam masala."),
        ("compo", [
            ("chickpea_boiled", 360, "g", "plant_protein", "cooked"),
            ("spinach_raw_baby", 400, "g", "vegetable"),
            ("tomato_raw_ripe", 200, "g", "fruit"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 5, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("garam_masala", 3, "g", "spice"),
            ("coconut_milk_plant", 60, "ml", "ingredient"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("water", 150, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Blanchir 400 g d'épinards 1 minute, les refroidir et les mixer avec 150 ml d'eau.",
            "Faire grésiller 3 g de cumin dans 30 ml d'huile, ajouter 150 g d'oignon haché et le dorer 8 minutes.",
            "Ajouter 12 g d'ail, 12 g de gingembre et 5 g de piment hachés, puis 2 g de curcuma, et cuire 1 minute. Ajouter 200 g de tomates concassées et cuire 5 minutes.",
            "Ajouter 360 g de pois chiches, la purée d'épinards et 4 g de sel, puis mijoter 10 minutes.",
            "Terminer avec 60 ml de lait de coco et 3 g de garam masala. Servir avec du riz.",
        ]),
        ("time", 15, 0, 30),
    ],

    # ── Paneer makhani / korma de légumes vegan ──
    "curry_paneer_butter_masala_9e638c": [
        ("title", "Paneer makhani de Delhi (paneer butter masala)"),
        ("desc", "Paneer maison mijoté dans une sauce veloutée de tomates, beurre, crème et cajou, relevée de "
                 "gingembre et de garam masala, douce et légèrement sucrée."),
        ("origin", {"region": "delhi", "city": "delhi"}),
    ],
    "protein_paneer_butter_masala_vega_6c63de": [
        ("title", "Korma de légumes au tofu et à la noix de cajou (vegan)"),
        ("desc", "Navratan korma végétal : chou-fleur, carotte, petits pois, pomme de terre et tofu dans une "
                 "sauce douce de cajou et de lait de coco, parfumée à la cardamome et à la cannelle."),
        ("compo", [
            ("tofu_plain_pre_packaged", 250, "g", "ingredient"),
            ("cauliflower_raw_flower", 250, "g", "vegetable"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("potato_raw_flesh", 200, "g", "vegetable"),
            ("green_peas_raw", 120, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 10, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("cashew_nuts_raw", 50, "g", "thickener"),
            ("coconut_milk_plant", 200, "ml", "ingredient"),
            ("cardamom", 1, "g", "spice"),
            ("cinnamon", 1, "g", "spice"),
            ("garam_masala", 2, "g", "spice"),
            ("sunflower_oil_plant", 30, "ml", "fat_cooking"),
            ("water", 200, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
        ]),
        ("steps", [
            "Faire tremper 50 g de noix de cajou 15 minutes dans l'eau chaude, puis les mixer avec 200 ml d'eau en crème lisse.",
            "Dorer 250 g de tofu en dés dans 15 ml d'huile, puis réserver.",
            "Faire revenir 150 g d'oignon, 10 g d'ail et 10 g de gingembre hachés dans 15 ml d'huile, 6 minutes, avec 1 g de cardamome et 1 g de cannelle.",
            "Ajouter 200 g de pommes de terre, 150 g de carotte et 250 g de chou-fleur en petits morceaux, la crème de cajou, 200 ml de lait de coco et 4 g de sel, puis mijoter 15 minutes à couvert.",
            "Ajouter 120 g de petits pois, le tofu et 2 g de garam masala, puis cuire 5 minutes. Parsemer de 10 g de coriandre.",
        ]),
        ("time", 20, 15, 30),
    ],
}
