"""Variantes 12 : paneer tikka, pav bhaji, ash persan, poutine, pupusas, pilaf turc, riz sauté au kimchi."""

VARIANTS = {
    # ── Paneer tikka / tandoori de chou-fleur vegan ──
    "protein_paneer_tikka_94f80a": [
        ("title", "Paneer tikka tandoori aux poivrons et oignons"),
        ("desc", "Brochettes de paneer, poivron et oignon marinées au yaourt, gingembre, ail et épices tandoori, "
                 "grillées à feu vif jusqu'à être légèrement noircies, arrosées de citron."),
    ],
    "protein_paneer_tikka_vegan_8bf0a0": [
        ("title", "Tandoori de chou-fleur et pois chiches, chutney à la menthe (vegan)"),
        ("desc", "Chou-fleur et pois chiches marinés dans un yaourt de soja aux épices tandoori, rôtis au four "
                 "jusqu'à être dorés, servis avec un chutney vert à la menthe et à la coriandre."),
        ("compo", [
            ("cauliflower_raw_flower", 600, "g", "vegetable"),
            ("chickpea_boiled", 240, "g", "plant_protein", "cooked"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("soybean_yogurt_plain_plant", 150, "g", "ingredient"),
            ("paprika_powder", 4, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("garam_masala", 3, "g", "spice"),
            ("turmeric_powder", 1, "g", "spice"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("lemon_juice", 30, "ml", "fruit"),
            ("olive_oil_extra_virgin_plant", 30, "ml", "fat"),
            ("mint_fresh_herb", 15, "g", "herb"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("chilli_pepper_raw", 4, "g", "spice"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("basmati_rice_raw_seed", None, "1 portion", "serving_suggestion"),
        ]),
        ("steps", [
            "Marinade : mélanger 150 g de yaourt de soja avec 4 g de paprika, 3 g de cumin, 3 g de garam masala, 1 g de curcuma, 6 g d'ail et 10 g de gingembre râpés, 15 ml de jus de citron, 20 ml d'huile et 3 g de sel.",
            "Enrober 600 g de chou-fleur en bouquets, 240 g de pois chiches et 150 g d'oignon en quartiers, puis laisser mariner 30 minutes.",
            "Préchauffer le four à 230°C. Étaler sur une plaque et rôtir 25 minutes, jusqu'à ce que les bords soient noircis.",
            "Chutney : mixer 15 g de menthe, 15 g de coriandre, 4 g de piment vert, 3 g d'ail, 15 ml de jus de citron, 10 ml d'huile, 1 g de sel et 2 cuillerées d'eau.",
            "Servir le tandoori chaud avec le chutney.",
        ]),
        ("time", 20, 30, 25),
    ],

    # ── Pav bhaji de Mumbai / vada pav vegan ──
    "main_pav_bhaji_e99df8": [
        ("title", "Pav bhaji de Mumbai au beurre"),
        ("desc", "Le plat de rue de Mumbai : purée épicée de pommes de terre, chou-fleur, petits pois, poivron et "
                 "tomate cuite au beurre sur une plaque, servie avec des petits pains dorés au beurre et du citron."),
        ("origin", {"cuisine": "indian", "country": "india", "region": "maharashtra", "city": "mumbai"}),
        ("compo", [
            ("potato_raw_flesh", 400, "g", "ingredient"),
            ("cauliflower_raw_flower", 200, "g", "vegetable"),
            ("green_peas_boiled_frozen_salted", 150, "g", "vegetable"),
            ("red_bell_pepper_raw", 150, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("ginger_raw_root_fresh", 9, "g", "aromatic"),
            ("butter_sup80pct", 50, "g", "fat_cooking"),
            ("garam_masala", 4, "g", "spice"),
            ("paprika_powder", 3, "g", "spice"),
            ("cumin_spice_seed", 2, "g", "spice"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("white_bread_unsalted", 320, "g", "carbohydrate"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("water", 150, "ml", "liquid"),
        ]),
        ("steps", [
            "Cuire 400 g de pommes de terre, 200 g de chou-fleur et 150 g de petits pois à l'eau, 15 minutes, puis les écraser.",
            "Faire fondre 30 g de beurre et y revenir 150 g d'oignon haché 5 minutes, puis 9 g d'ail, 9 g de gingembre et 150 g de poivron hachés, 4 minutes.",
            "Ajouter 300 g de tomates concassées, 4 g de garam masala, 3 g de paprika, 2 g de cumin et 4 g de sel, puis cuire 8 minutes.",
            "Ajouter les légumes écrasés et 150 ml d'eau, puis écraser encore et mijoter 10 minutes en remuant. Terminer avec 20 ml de jus de citron et 10 g de coriandre.",
            "Ouvrir 320 g de petits pains moelleux et les dorer dans 20 g de beurre. Servir avec la bhaji.",
        ]),
        ("time", 20, 0, 40),
    ],
    "main_pav_bhaji_vegan_c1437e": [
        ("title", "Vada pav, beignet de pomme de terre en petit pain (vegan)"),
        ("desc", "Le burger des rues de Mumbai : boulette de pommes de terre épicée à la moutarde et aux feuilles "
                 "de curry, enrobée de pâte de pois chiches et frite, servie dans un petit pain avec un chutney "
                 "sec à l'ail et à la noix de coco."),
        ("origin", {"region": "maharashtra", "city": "mumbai"}),
        ("compo", [
            ("potato_raw_flesh", 600, "g", "ingredient"),
            ("chickpea_flour", 120, "g", "carbohydrate"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("yellow_mustard_spice_seed", 2, "g", "spice"),
            ("curry_leaf", 4, "g", "herb"),
            ("turmeric_powder", 2, "g", "spice"),
            ("coconut_flesh_dried", 20, "g", "ingredient"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("sunflower_oil_plant", 50, "ml", "fat_cooking"),
            ("white_bread_unsalted", 320, "g", "carbohydrate"),
            ("water", 140, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Cuire 600 g de pommes de terre à l'eau 20 minutes et les écraser.",
            "Chauffer 10 ml d'huile, y faire éclater 2 g de moutarde avec 4 g de feuilles de curry, ajouter 10 g d'ail, 10 g de gingembre et 6 g de piment pilés, puis 1 g de curcuma. Mélanger aux pommes de terre avec 3 g de sel et former 8 boulettes.",
            "Pâte : fouetter 120 g de farine de pois chiches, 1 g de curcuma, 1 g de sel et 140 ml d'eau.",
            "Tremper les boulettes dans la pâte et les frire dans l'huile chaude, 4 minutes, jusqu'à ce qu'elles soient dorées (environ 40 ml d'huile absorbée).",
            "Chutney sec : griller à sec 20 g de noix de coco, 5 g d'ail et 2 g de piment séché, puis les piler.",
            "Glisser chaque vada dans un petit pain (320 g au total) parsemé de chutney.",
        ]),
        ("time", 30, 0, 35),
    ],

    # ── Ash persan : reshteh au kashk / ash-e jo à l'orge vegan ──
    "pasta_persian_ash_reshteh_8cb79c": [
        ("title", "Ash reshteh de Téhéran au kashk et à la menthe frite"),
        ("desc", "La grande soupe persane de Norouz : herbes, épinards, pois chiches, haricots et lentilles, "
                 "nouilles reshteh, servie avec du kashk et des oignons à la menthe frite."),
        ("origin", {"cuisine": "persian", "country": "iran", "region": "tehran", "city": "tehran"}),
        ("dish", "soup"),
    ],
    "soup_persian_ash_reshteh_vegan_968f7d": [
        ("title", "Ash-e jo, soupe persane à l'orge et aux herbes (vegan)"),
        ("desc", "Soupe iranienne d'hiver à l'orge perlé, lentilles, pois chiches et haricots, carotte, épinards "
                 "et herbes, finie au yaourt de soja et aux oignons frits à la menthe."),
        ("origin", {"cuisine": "persian", "country": "iran", "region": "tehran", "city": "tehran"}),
        ("compo", [
            ("pearl_barley_raw_seed", 120, "g", "carbohydrate"),
            ("green_lentil_boiled", 150, "g", "ingredient", "cooked"),
            ("chickpea_boiled", 200, "g", "ingredient", "cooked"),
            ("white_bean_boiled", 150, "g", "ingredient", "cooked"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("spinach_raw_mature", 200, "g", "ingredient"),
            ("parsley_fresh_herb", 40, "g", "herb"),
            ("coriander_raw_fresh_herb", 30, "g", "herb"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("turmeric_powder", 3, "g", "spice"),
            ("tomato_paste_unsalted_canned", 20, "g", "ingredient"),
            ("dried_mint_herb", 3, "g", "herb"),
            ("soybean_yogurt_plain_plant", 100, "g", "ingredient"),
            ("olive_oil_plant", 45, "ml", "fat"),
            ("vegetable_stock_dried", 10, "g", "ingredient"),
            ("water", 1600, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "ingredient"),
        ]),
        ("steps", [
            "Faire revenir 100 g d'oignon haché dans 15 ml d'huile, 5 minutes, avec 3 g de curcuma et 20 g de concentré de tomate.",
            "Ajouter 120 g d'orge perlé rincé, 150 g de carotte en dés, 1,6 L d'eau et 10 g de bouillon, puis mijoter 40 minutes.",
            "Ajouter 150 g de lentilles, 200 g de pois chiches, 150 g de haricots blancs, 200 g d'épinards, 40 g de persil et 30 g de coriandre hachés, et 2 g de sel. Mijoter 15 minutes.",
            "Garniture : frire 100 g d'oignon émincé dans 30 ml d'huile jusqu'à ce qu'il soit brun, ajouter 9 g d'ail puis, hors du feu, 3 g de menthe séchée.",
            "Servir la soupe avec une cuillerée de yaourt de soja (100 g au total) et la garniture à la menthe.",
        ]),
        ("time", 20, 0, 65),
    ],

    # ── Poutine québécoise / vegan frites au four et sauce aux champignons ──
    "main_poutine_1344e1": [
        ("title", "Poutine québécoise, sauce brune et fromage en grains"),
        ("desc", "Le classique du Québec : frites dorées, fromage en grains qui fait « couic » et sauce brune "
                 "bien chaude versée au dernier moment."),
        ("origin", {"region": "quebec", "city": "montreal"}),
        ("compo", [
            ("potato_raw_flesh", 800, "g", "ingredient"),
            ("base_fromage_en_grain_a00941", 150, "g", "ingredient"),
            ("vegetable_stock_dried", 6, "g", "sauce"),
            ("water", 300, "ml", "sauce"),
            ("soy_sauce_shoyu_reduced_sodium", 10, "ml", "sauce"),
            ("butter_sup80pct", 15, "g", "sauce"),
            ("cornstarch", 15, "g", "thickener"),
            ("sunflower_oil_plant", 60, "ml", "fat_frying"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
            ("black_pepper_spice", 1, "g", "spice"),
        ]),
        ("steps", [
            "Couper 800 g de pommes de terre en frites, les rincer et les sécher.",
            "Les frire une première fois à 160°C, 6 minutes, puis une seconde fois à 180°C, 3 minutes, jusqu'à ce qu'elles soient dorées (environ 60 ml d'huile absorbée). Saler avec 1 g de sel.",
            "Sauce brune : faire mousser 15 g de beurre, ajouter 300 ml d'eau, 6 g de bouillon, 10 ml de sauce soja et 1 g de poivre, puis lier avec 15 g de fécule délayée dans un peu d'eau froide.",
            "Répartir les frites, parsemer de 150 g de fromage en grains et napper de sauce bouillante.",
        ]),
        ("time", 15, 30, 25),
    ],
    "main_poutine_vegan_18f8c2": [
        ("title", "Poutine aux frites au four et sauce aux champignons (vegan)"),
        ("desc", "Poutine végétale plus légère : frites rustiques cuites au four, sauce brune aux champignons et "
                 "à la sauce soja, cheddar végétal fondant."),
        ("compo", [
            ("potato_raw_with_skin", 800, "g", "ingredient"),
            ("base_vegan_cheddar_024998", 100, "g", "ingredient"),
            ("button_mushroom_raw", 200, "g", "sauce"),
            ("onion_raw", 60, "g", "sauce"),
            ("vegetable_stock_dried", 5, "g", "sauce"),
            ("water", 300, "ml", "sauce"),
            ("soy_sauce_shoyu_reduced_sodium", 15, "ml", "sauce"),
            ("cornstarch", 15, "g", "thickener"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("thyme_dried_herb", 1, "g", "herb"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
            ("black_pepper_spice", 1, "g", "spice"),
        ]),
        ("steps", [
            "Préchauffer le four à 220°C. Couper 800 g de pommes de terre avec la peau en frites, les mélanger avec 30 ml d'huile et 2 g de sel, puis les cuire 35 minutes en les retournant.",
            "Sauce : faire revenir 60 g d'oignon et 200 g de champignons hachés dans 10 ml d'huile, 8 minutes, avec 1 g de thym.",
            "Ajouter 300 ml d'eau, 5 g de bouillon, 15 ml de sauce soja et 1 g de poivre, puis lier avec 15 g de fécule délayée dans un peu d'eau froide.",
            "Répartir les frites, parsemer de 100 g de cheddar végétal et napper de sauce bouillante.",
        ]),
        ("time", 15, 0, 40),
    ],

    # ── Pupusas : revueltas au loroco / frijol con queso et curtido / ayote vegan ──
    "main_pupusas_9d2c72": [
        ("title", "Pupusas revueltas au fromage et au loroco"),
        ("desc", "Pupusas du Salvador farcies d'un mélange de haricots noirs, de fromage frais et de loroco, "
                 "fleur aromatique d'Amérique centrale, cuites sur une plaque et servies avec une sauce tomate."),
        ("origin", {"cuisine": "salvadoran"}),
    ],
    "main_pupusas_aux_haricots_fc8bfd": [
        ("title", "Pupusas de frijol con queso et curtido"),
        ("desc", "Pupusas aux haricots noirs et au fromage fondant, servies avec le curtido, salade de chou et "
                 "de carotte marinée au vinaigre et à l'origan."),
        ("origin", {"cuisine": "salvadoran", "country": "el_salvador"}),
        ("compo", [
            ("masa_harina", 300, "g", "ingredient"),
            ("water", 400, "ml", "ingredient"),
            ("black_bean_boiled", 300, "g", "plant_protein", "cooked"),
            ("cows_milk_mozzarella_cow", 120, "g", "ingredient"),
            ("green_cabbage_raw", 250, "g", "vegetable"),
            ("carrot_raw", 80, "g", "vegetable"),
            ("onion_raw", 40, "g", "aromatic"),
            ("white_vinegar_liquid_distilled", 40, "ml", "condiment"),
            ("oregano_spice_dried", 1, "g", "herb"),
            ("vegetable_oil_plant", 20, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Curtido : mélanger 250 g de chou émincé finement, 80 g de carotte râpée et 40 g d'oignon avec 40 ml de vinaigre, 1 g d'origan, 1 g de sel et 60 ml d'eau chaude. Laisser mariner au moins 1 heure.",
            "Mixer 300 g de haricots noirs en purée épaisse avec 1 g de sel.",
            "Pétrir 300 g de masa harina avec 400 ml d'eau tiède et 2 g de sel jusqu'à obtenir une pâte souple.",
            "Former 8 boules, creuser chacune, garnir de purée et de 15 g de fromage râpé, refermer et aplatir en galettes de 1 cm.",
            "Cuire sur une plaque légèrement huilée (20 ml en tout), 4 minutes de chaque côté. Servir avec le curtido.",
        ]),
        ("time", 30, 60, 20),
    ],
    "main_pupusas_vegan_4595d8": [
        ("title", "Pupusas de ayote et haricots noirs (vegan)"),
        ("origin", {"country": "el_salvador"}),
        ("desc", "Pupusas végétales farcies de courgette (ayote) sautée à l'oignon et de haricots noirs écrasés, "
                 "servies avec une salsa de tomate crue."),
        ("compo", [
            ("masa_harina", 300, "g", "ingredient"),
            ("water", 400, "ml", "ingredient"),
            ("black_bean_boiled", 250, "g", "plant_protein", "cooked"),
            ("green_zucchini_squash_raw", 250, "g", "vegetable"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("loroco", 30, "g", "vegetable"),
            ("tomato_raw_ripe", 250, "g", "fruit"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("vegetable_oil_plant", 30, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ]),
        ("steps", [
            "Faire revenir 60 g d'oignon et 250 g de courgette râpée et pressée dans 10 ml d'huile, 6 minutes, puis mélanger avec 250 g de haricots noirs écrasés, 30 g de loroco haché et 1 g de sel.",
            "Pétrir 300 g de masa harina avec 400 ml d'eau tiède et 2 g de sel.",
            "Former 8 boules, les creuser, garnir, refermer et aplatir en galettes de 1 cm.",
            "Cuire sur une plaque légèrement huilée (20 ml en tout), 4 minutes de chaque côté.",
            "Salsa : mélanger 250 g de tomates en dés, 40 g d'oignon, 10 g de coriandre et 1 g de sel. Servir avec les pupusas.",
        ]),
        ("time", 30, 0, 25),
    ],

    # ── Pilaf turc : aux vermicelles / iç pilav vegan ──
    "rice_riz_pilaf_turc_52cfe9": [
        ("title", "Şehriyeli pilav, riz pilaf aux vermicelles grillés"),
        ("desc", "Le pilaf de tous les jours en Turquie : vermicelles dorés au beurre, riz nacré puis cuit "
                 "dans le bouillon jusqu'à ce que les grains soient bien séparés."),
        ("dish", "side"),
        ("compo", [
            ("white_rice_raw_seed_unenriched", 280, "g", "carbohydrate"),
            ("pasta_raw_dried", 40, "g", "ingredient"),
            ("butter_sup80pct", 35, "g", "fat_cooking"),
            ("vegetable_stock_dried", 6, "g", "ingredient"),
            ("water", 480, "ml", "ingredient"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ]),
        ("steps", [
            "Rincer 280 g de riz et le laisser tremper 20 minutes dans l'eau tiède, puis l'égoutter.",
            "Faire fondre 35 g de beurre et y dorer 40 g de vermicelles 2 minutes, jusqu'à ce qu'ils soient bruns.",
            "Ajouter le riz et le nacrer 2 minutes.",
            "Verser 480 ml d'eau bouillante avec 6 g de bouillon et 1 g de sel, couvrir et cuire 15 minutes à feu très doux.",
            "Laisser reposer 10 minutes sous un linge, puis égrener.",
        ]),
        ("time", 5, 30, 20),
    ],
    "side_riz_pilaf_turc_vegan_3bb995": [
        ("title", "İç pilav aux raisins, pignons et cannelle (vegan)"),
        ("desc", "Pilaf épicé d'Istanbul : riz cuit à l'huile d'olive avec oignon, pignons grillés, raisins de "
                 "Corinthe, cannelle, piment de la Jamaïque et aneth frais."),
        ("origin", {"region": "istanbul", "city": "istanbul"}),
        ("compo", [
            ("white_rice_raw_seed_unenriched", 280, "g", "carbohydrate"),
            ("white_onion_raw", 120, "g", "aromatic_base"),
            ("pine_nuts_raw", 25, "g", "ingredient"),
            ("grape_dried", 30, "g", "ingredient"),
            ("cinnamon", 1, "g", "spice"),
            ("allspice_powder", 1, "g", "spice"),
            ("dill_weed_fresh_herb_leaf", 10, "g", "herb"),
            ("olive_oil_plant", 35, "ml", "fat_cooking"),
            ("vegetable_stock_dried", 6, "g", "ingredient"),
            ("water", 480, "ml", "ingredient"),
        ]),
        ("steps", [
            "Rincer 280 g de riz et le laisser tremper 20 minutes, puis l'égoutter.",
            "Dorer 25 g de pignons dans 35 ml d'huile d'olive, ajouter 120 g d'oignon haché et le faire fondre 6 minutes.",
            "Ajouter le riz, 1 g de cannelle et 1 g de piment de la Jamaïque, puis nacrer 2 minutes.",
            "Ajouter 30 g de raisins secs, 480 ml d'eau bouillante et 6 g de bouillon, couvrir et cuire 15 minutes à feu très doux.",
            "Laisser reposer 10 minutes, puis égrener avec 10 g d'aneth ciselé.",
        ]),
        ("time", 10, 20, 25),
    ],

    # ── Riz sauté au kimchi : bokkeumbap à l'œuf / tofu-shiitakés vegan ──
    "rice_kimchi_fried_rice_1f3e90": [
        ("title", "Kimchi bokkeumbap à l'œuf au plat"),
        ("desc", "Riz sauté coréen au kimchi bien fermenté et à l'oignon, relevé de sauce soja et d'huile de "
                 "sésame, couronné d'un œuf au plat au jaune coulant."),
        ("compo", [
            ("base_kimchi_61791a", 250, "g", "ingredient"),
            ("white_rice_cooked_long_grain_seed", 600, "g", "carbohydrate", "cooked"),
            ("egg_raw", 220, "g", "ingredient"),
            ("soy_sauce_tamari", 15, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("sweet_onion_raw", 120, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("green_onion_raw", 30, "g", "garnish"),
            ("vegetable_oil_plant", 30, "ml", "fat"),
            ("sesame_seed_hulled_dried", 5, "g", "garnish"),
        ]),
        ("steps", [
            "Faire revenir 120 g d'oignon et 9 g d'ail hachés dans 20 ml d'huile, 3 minutes.",
            "Ajouter 250 g de kimchi haché avec son jus et le faire sauter 4 minutes.",
            "Ajouter 600 g de riz cuit froid et 15 ml de tamari, puis sauter 4 minutes à feu vif. Hors du feu, arroser de 15 ml d'huile de sésame.",
            "Cuire 4 œufs (220 g) au plat dans 10 ml d'huile.",
            "Servir le riz surmonté d'un œuf, parsemé de 30 g d'oignons verts et de 5 g de sésame.",
        ]),
        ("time", 10, 0, 15),
    ],
    "rice_riz_saute_au_kimchi_vegan_af038b": [
        ("title", "Riz sauté au kimchi, tofu et shiitakés (vegan)"),
        ("desc", "Riz sauté végétal au kimchi, tofu doré et shiitakés, relevé de sauce soja et d'huile de "
                 "sésame, parsemé d'oignons verts."),
        ("compo", [
            ("base_kimchi_61791a", 250, "g", "ingredient"),
            ("white_rice_short_grain_seed_dried", 280, "g", "carbohydrate"),
            ("tofu_plain_pre_packaged", 200, "g", "protein"),
            ("shiitake_mushroom_raw", 120, "g", "vegetable"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("green_onion_raw", 30, "g", "garnish"),
            ("water", 340, "ml", "liquid"),
        ]),
        ("steps", [
            "Cuire 280 g de riz rond rincé dans 340 ml d'eau, 12 minutes à couvert, puis l'étaler pour le refroidir.",
            "Dorer 200 g de tofu en dés dans 15 ml d'huile de tournesol, puis réserver.",
            "Faire revenir 100 g d'oignon, 9 g d'ail et 120 g de shiitakés émincés dans 10 ml d'huile, 4 minutes, puis 250 g de kimchi haché, 3 minutes.",
            "Ajouter le riz, le tofu et 20 ml de sauce soja, puis sauter 4 minutes à feu vif.",
            "Hors du feu, arroser de 15 ml d'huile de sésame et parsemer de 30 g d'oignons verts.",
        ]),
        ("time", 15, 0, 25),
    ],
}
