import json

file_path = 'c:/Users/Samijo/Downloads/project_final_v6_migrated/project_final_v6_migrated/frontend/src/translations.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
    "celery_root": "Céleri-rave",
    "cooked_rice": "Riz cuit",
    "caraway": "Carvi",
    "acai_puree": "Purée d'açaï",
    "berbere_sauce": "Sauce berbère",
    "puff_pastry": "Pâte feuilletée",
    "broth": "Bouillon",
    "instant_yeast": "Levure instantanée",
    "pearl_sugar": "Sucre perlé",
    "tarragon": "Estragon",
    "sliced_almond": "Amandes effilées",
    "sherry_vinegar": "Vinaigre de Xérès",
    "teff_flour": "Farine de teff",
    "light_cream": "Crème légère",
    "salted_butter": "Beurre salé",
    "nutmeg_whole": "Noix de muscade entière",
    "rye_flour": "Farine de seigle",
    "apple_cider_vinegar": "Vinaigre de cidre",
    "frying_oil": "Huile de friture",
    "dark_chocolate_chips": "Pépites de chocolat noir",
    "egg_yolk": "Jaune d'œuf",
    "amarillo_chili": "Piment amarillo",
    "buckwheat_flour": "Farine de sarrasin",
    "coconut_yogurt": "Yaourt à la noix de coco",
    "multigrain_bread": "Pain aux céréales",
    "red_bean_paste": "Pâte de haricots rouges",
    "cacao_powder": "Poudre de cacao",
    "hazelnut_oil": "Huile de noisette",
    "pearl_onion": "Oignon grelot",
    "peanut": "Cacahuète",
    "cashew_cream": "Crème de noix de cajou",
    "zucchini_blossom": "Fleur de courgette",
    "anise_seeds": "Graines d'anis",
    "salted_butter_caramel": "Caramel au beurre salé",
    "matcha": "Matcha",
    "dill": "Aneth",
    "flageolet_bean": "Flageolets",
    "green_cabbage": "Chou vert",
    "sourdough_starter": "Levain",
    "gherkin": "Cornichon",
    "passion_fruit": "Fruit de la passion",
    "shallot": "Échalote",
    "mixed_berries": "Fruits rouges",
    "soy_cream": "Crème de soja",
    "bread_flour": "Farine T65",
    "spaetzle": "Spätzle",
    "powdered_sugar": "Sucre glace",
    "glutinous_rice_flour": "Farine de riz gluant",
    "frozen_banana": "Banane congelée",
    "curly_endive": "Chicorée frisée",
    "dried_cranberry": "Canneberges séchées",
    "roasted_chickpea": "Pois chiches grillés",
    "chocolate_chips": "Pépites de chocolat",
    "wakame_dried": "Wakame séché",
    "almond_butter": "Beurre d'amande",
    "fresh_tome_cheese": "Tome fraîche",
    "walnut_oil": "Huile de noix",
    "sprouts": "Germes",
    "chestnut": "Châtaigne",
    "juniper_berry": "Baie de genièvre",
    "potato_starch": "Fécule de pomme de terre",
    "ground_flaxseed": "Graines de lin moulues",
    "ground_ginger": "Gingembre en poudre",
    "granola": "Granola",
    "puy_lentil": "Lentilles du Puy",
    "coriander_seeds": "Graines de coriandre",
    "porcini": "Cèpes",
    "strawberry_coulis": "Coulis de fraise",
    "chili_paste": "Pâte de piment",
    "raspberry": "Framboise",
    "sushi_rice": "Riz à sushi",
    "peas": "Petits pois",
    "digestive_biscuit": "Biscuit digestif",
    "strawberry_jam": "Confiture de fraise",
    "buckwheat": "Sarrasin",
    "sourdough_bread": "Pain au levain",
    "lamb_lettuce": "Mâche",
    "greek_yogurt": "Yaourt grec",
    "hemp_seeds": "Graines de chanvre",
    "cherry_jam": "Confiture de cerise",
    "apple_juice": "Jus de pomme",
    "okonomiyaki_sauce": "Sauce okonomiyaki",
    "endive": "Endive",
    "chili_pepper": "Piment",
    "orange_juice": "Jus d'orange",
    "black_bean_sauce": "Sauce aux haricots noirs",
    "grapefruit": "Pamplemousse",
    "dried_yeast": "Levure sèche",
    "chervil": "Cerfeuil",
    "plant_yogurt": "Yaourt végétal",
    "parsnip": "Panais",
    "basil_pesto": "Pesto au basilic",
    "pie_dough": "Pâte à tarte",
    "miso_soup_base": "Base pour soupe miso",
    "goat_cheese": "Fromage de chèvre",
    "rhubarb": "Rhubarbe",
    "arugula": "Roquette",
    "filo_pastry": "Pâte filo",
    "round_grain_rice": "Riz rond",
    "butternut_squash": "Courge butternut",
    "candied_fruit": "Fruits confits",
    "marjoram": "Marjolaine",
    "watercress": "Cresson",
    "whole_grain_bread": "Pain complet",
    "smoked_paprika": "Paprika fumé",
    "egg_white": "Blanc d'œuf",
    "green_peas": "Petits pois",
    "jerusalem_artichoke": "Topinambour",
    "truffle_oil": "Huile de truffe",
    "beluga_lentil": "Lentilles beluga",
    "agave_syrup": "Sirop d'agave",
    "spice_mix": "Mélange d'épices",
    "pearl_barley": "Orge perlé",
    "spice_blend": "Mélange d'épices",
    "black_olive": "Olive noire",
    "celery": "Céleri",
    "cherry_tomato": "Tomate cerise",
    "chicory": "Chicorée",
    "chinese_cabbage": "Chou chinois",
    "corn": "Maïs",
    "cucumber": "Concombre",
    "green_bell_pepper": "Poivron vert",
    "green_papaya": "Papaye verte",
    "hominy_corn": "Maïs hominy",
    "jackfruit": "Jacquier",
    "lettuce": "Laitue",
    "pomegranate": "Grenade",
    "pumpkin": "Potiron",
    "radish": "Radis",
    "red_bell_pepper": "Poivron rouge",
    "red_onion": "Oignon rouge",
    "sweet_potato": "Patate douce",
    "swiss_chard": "Blette",
    "fava_bean": "Fève",
    "breadcrumbs": "Chapelure",
    "noodles": "Nouilles",
    "pasta": "Pâtes",
    "banana": "Banane",
    "orange": "Orange",
    "coconut_oil": "Huile de coco",
    "sesame_oil": "Huile de sésame",
    "sunflower_oil": "Huile de tournesol",
    "fried_onion": "Oignon frit",
    "honey": "Miel",
    "sparkling_water": "Eau gazeuse",
    "green_chili": "Piment vert",
    "fennel": "Fenouil",
    "artichoke": "Artichaut",
    "green_tea": "Thé vert",
    "lentils": "Lentilles",
    "egg": "Oeuf",
    "white_bean": "Haricots blancs",
    "lemon_zest": "Zeste de citron",
    "white_wine": "Vin blanc",
    "mustard_seeds": "Graines de moutarde",
    "green_beans": "Haricots verts",
    "strawberry": "Fraise",
    "cornstarch": "Fécule de maïs",
    "vanilla": "Vanille",
    "mango": "Mangue",
    "nutmeg": "Noix de muscade",
    "sage": "Sauge",
    "cloves": "Clous de girofle",
    "coconut_milk": "Lait de coco",
    "brown_rice": "Riz complet",
    "red_cabbage": "Chou rouge",
    "sweet_corn": "Maïs doux",
    "yellow_bell_pepper": "Poivron jaune",
    "peach": "Pêche",
    "apricot": "Abricot",
    "papaya": "Papaye",
    "date": "Datte",
    "pecan": "Noix de pécan",
    "macadamia": "Noix de macadamia",
    "flax_seeds": "Graines de lin",
    "poppy_seeds": "Graines de pavot",
    "mustard": "Moutarde",
    "brown_sugar": "Cassonade",
    "chocolate": "Chocolat",
    "jam": "Confiture",
    "gelatin": "Gélatine",
    "coffee": "Café",
    "tea": "Thé",
    "green_olive": "Olive verte",
    "yam": "Igname",
    "coconut": "Noix de coco",
    "chili": "Piment",
    "jalapeno": "Piment jalapeño",
    "watermelon": "Pastèque",
    "quince": "Coing",
    "lychee": "Litchi",
    "caramel": "Caramel",
    "praline": "Praliné",
    "nougatine": "Nougatine",
    "biscuit": "Biscuit",
    "madeleine": "Madeleine",
    "financier": "Financier",
    "croissant": "Croissant",
    "brioche": "Brioche"
}

for key, value in translations.items():
    if key in data:
        data[key] = value

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Translations applied successfully.")
