"""Lot 1 de nouvelles recettes : Afrique (Éthiopie, Nigeria, Ghana, Sénégal, Côte d'Ivoire, Kenya, Maroc).

L'Afrique ne comptait que 32 plats sur 635 au recomptage du 2026-09-22.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="dal_shiro_wot_5c71b8", fr="Shiro wot, purée de pois chiches au berbéré",
        en="Shiro Wot, Spiced Chickpea Flour Stew",
        cuisine="ethiopian", country="ethiopia", region="addis_abeba", city="addis_abeba",
        dish="main", prep=10, cook=25, spice=2, kid_friendly=False,
        desc="Le plat de tous les jours en Éthiopie : farine de pois chiches délayée dans un bouillon "
             "à l'oignon et au berbéré, cuite jusqu'à une purée onctueuse servie bouillonnante.",
        texture=("cremeux",), taste=("epice", "noisette"),
        compo=[
            ("chickpea_flour", 180, "g", "plant_protein"),
            ("onion_raw", 250, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("ginger_raw_root_fresh", 8, "g", "aromatic"),
            ("berbere", 15, "g", "spice"),
            ("tomato_raw_ripe", 150, "g", "fruit"),
            ("sunflower_oil_plant", 45, "ml", "fat"),
            ("water", 900, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("crepe_galette_de_teff_a1a8d3", None, "1 galette", "serving_suggestion"),
        ],
        steps=[
            "Faire revenir 250 g d'oignon haché dans 45 ml d'huile, 10 minutes, jusqu'à ce qu'il soit doré.",
            "Ajouter 12 g d'ail et 8 g de gingembre râpés, 15 g de berbéré et 150 g de tomate râpée, puis cuire 3 minutes.",
            "Verser 900 ml d'eau et porter à ébullition avec 4 g de sel.",
            "Verser 180 g de farine de pois chiches en pluie en fouettant sans arrêt pour éviter les grumeaux.",
            "Cuire 12 minutes à feu doux en remuant, jusqu'à ce que le shiro épaississe et que l'huile remonte.",
            "Servir brûlant, avec de l'injera.",
        ]),
    recipe(
        rid="side_gomen_ethiopien_4d10a7", fr="Gomen, chou cavalier éthiopien à l'ail",
        en="Gomen, Ethiopian Collard Greens with Garlic",
        cuisine="ethiopian", country="ethiopia", region="amhara", city="",
        dish="side", prep=10, cook=25,
        desc="Feuilles de chou cavalier braisées avec oignon, ail et gingembre jusqu'à être fondantes, "
             "relevées d'un peu de piment vert : l'accompagnement obligé des plats en sauce éthiopiens.",
        texture=("fondant",), taste=("vegetal", "ail"),
        compo=[
            ("collard_raw", 700, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("ginger_raw_root_fresh", 8, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("water", 200, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Laver 700 g de chou cavalier, retirer les côtes dures et émincer les feuilles en lanières.",
            "Faire revenir 150 g d'oignon émincé dans 30 ml d'huile, 6 minutes.",
            "Ajouter 12 g d'ail, 8 g de gingembre et 8 g de piment vert hachés, puis cuire 1 minute.",
            "Ajouter le chou et 200 ml d'eau, saler avec 3 g de sel, couvrir et cuire 20 minutes à feu doux.",
            "Découvrir et laisser évaporer le liquide restant avant de servir.",
        ]),
    recipe(
        rid="side_atakilt_wat_2f66c9", fr="Atakilt wat, chou, carotte et pommes de terre au curcuma",
        en="Atakilt Wat, Cabbage, Carrot and Potato with Turmeric",
        cuisine="ethiopian", country="ethiopia", region="addis_abeba", city="",
        dish="side", prep=15, cook=30,
        desc="Légumes éthiopiens mijotés doucement à l'huile, au curcuma et au gingembre : chou, carottes "
             "et pommes de terre restent en morceaux et prennent une belle couleur dorée.",
        texture=("fondant",), taste=("doux", "epice"),
        compo=[
            ("cabbage_raw", 400, "g", "vegetable"),
            ("carrot_raw", 250, "g", "vegetable"),
            ("potato_raw_flesh", 350, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("ginger_raw_root_fresh", 8, "g", "aromatic"),
            ("turmeric_powder", 3, "g", "spice"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("water", 150, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 150 g d'oignon émincé dans 40 ml d'huile, 6 minutes, puis ajouter 9 g d'ail, 8 g de gingembre et 3 g de curcuma.",
            "Ajouter 250 g de carotte en bâtonnets et 350 g de pommes de terre en quartiers, puis remuer pour les enrober.",
            "Ajouter 400 g de chou émincé, 150 ml d'eau et 4 g de sel.",
            "Couvrir et cuire 25 minutes à feu doux, en remuant délicatement, jusqu'à ce que les légumes soient tendres mais entiers.",
            "Servir tiède ou chaud.",
        ]),
    recipe(
        rid="dal_moin_moin_6e4a13", fr="Moin moin, flan de doliques à la vapeur",
        en="Moin Moin, Steamed Black-Eyed Pea Pudding",
        cuisine="nigerian", country="nigeria", region="lagos", city="",
        dish="main", prep=25, rest=480, cook=45, spice=1,
        desc="Doliques à œil noir trempés, pelés et mixés avec oignon, poivron et piment, puis cuits à la "
             "vapeur en ramequins jusqu'à obtenir un flan moelleux et protéiné.",
        texture=("moelleux",), taste=("epice", "legumineuse"),
        compo=[
            ("black_eyed_peas_cowpeas_dried", 300, "g", "plant_protein", "dried"),
            ("red_bell_pepper_raw", 200, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("tomato_paste_unsalted_canned", 20, "g", "ingredient"),
            ("sunflower_oil_plant", 45, "ml", "fat"),
            ("vegetable_stock_dried", 6, "g", "ingredient"),
            ("water", 300, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 300 g de doliques à œil noir 8 heures, puis les frotter entre les mains pour retirer les peaux et les rincer.",
            "Les mixer avec 200 g de poivron rouge, 150 g d'oignon, 8 g de piment et 300 ml d'eau, jusqu'à obtenir une pâte lisse et aérée.",
            "Incorporer 45 ml d'huile, 20 g de concentré de tomate, 6 g de bouillon déshydraté et 4 g de sel en fouettant.",
            "Répartir dans des ramequins huilés en les remplissant aux trois quarts.",
            "Cuire 45 minutes à la vapeur, jusqu'à ce qu'une lame ressorte propre.",
            "Laisser tiédir 5 minutes avant de démouler.",
        ]),
    recipe(
        rid="snack_akara_7d9c26", fr="Akara, beignets de doliques à œil noir",
        en="Akara, Black-Eyed Pea Fritters",
        cuisine="nigerian", country="nigeria", region="lagos", city="",
        dish="snack", servings=6, prep=20, rest=480, cook=15, spice=1,
        desc="Beignets du petit-déjeuner ouest-africain : purée de doliques pelés, montée en mousse avec "
             "oignon et piment, frite en boules dorées et croustillantes.",
        texture=("croustillant", "moelleux"), taste=("legumineuse", "epice"),
        compo=[
            ("black_eyed_peas_cowpeas_dried", 350, "g", "plant_protein", "dried"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("sunflower_oil_plant", 60, "ml", "fat"),
            ("water", 150, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 350 g de doliques 8 heures, les frotter pour retirer les peaux et les rincer.",
            "Les mixer avec 100 g d'oignon, 8 g de piment, 4 g de sel et 150 ml d'eau, en pâte épaisse.",
            "Fouetter la pâte 3 minutes à la main ou au batteur pour l'aérer : elle doit doubler de volume et flotter dans l'eau.",
            "Ajouter 50 g d'oignon haché finement.",
            "Frire des cuillerées de pâte dans l'huile chaude à 175°C, 4 minutes, en les retournant, jusqu'à ce qu'elles soient bien dorées (environ 60 ml d'huile absorbée).",
            "Égoutter sur du papier absorbant et servir chaud.",
        ]),
    recipe(
        rid="main_red_red_ghaneen_1c8f70", fr="Red red, doliques à l'huile de palme et plantain frit",
        en="Red Red, Black-Eyed Peas with Palm Oil and Fried Plantain",
        cuisine="african", country="ghana", region="accra", city="accra",
        dish="main", prep=15, cook=35, spice=1,
        desc="Plat emblématique du Ghana : ragoût de doliques à œil noir à la tomate et à l'huile de palme, "
             "servi avec des tranches de banane plantain mûre frites, sucrées et fondantes.",
        texture=("fondant", "croustillant"), taste=("tomate", "sucre"),
        compo=[
            ("black_eyed_peas_cowpeas_boiled", 450, "g", "plant_protein", "cooked"),
            ("plantain_banana_raw_ripe", 400, "g", "carbohydrate"),
            ("tomato_raw_ripe", 400, "g", "fruit"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("ginger_raw_root_fresh", 8, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("tomato_paste_unsalted_canned", 30, "g", "ingredient"),
            ("palm_oil_refined_plant", 30, "ml", "fat"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("water", 200, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 180 g d'oignon émincé dans 30 ml d'huile de palme, 6 minutes.",
            "Ajouter 9 g d'ail, 8 g de gingembre et 8 g de piment hachés, puis 30 g de concentré de tomate, et cuire 2 minutes.",
            "Ajouter 400 g de tomates concassées et 3 g de sel, puis réduire 10 minutes.",
            "Ajouter 450 g de doliques cuits et 200 ml d'eau, puis mijoter 15 minutes.",
            "Couper 400 g de plantain mûr en biseaux et les frire dans 30 ml d'huile de tournesol, 3 minutes par face, jusqu'à ce qu'ils soient dorés.",
            "Servir le ragoût avec les plantains frits.",
        ]),
    recipe(
        rid="rice_waakye_3a5e88", fr="Waakye, riz et haricots ghanéen",
        en="Waakye, Ghanaian Rice and Beans",
        cuisine="african", country="ghana", region="accra", city="",
        dish="main", prep=15, rest=480, cook=50,
        desc="Riz et haricots rouges cuits ensemble avec des feuilles de sorgho qui leur donnent leur couleur "
             "brun-rouge ; ici la couleur vient du bicarbonate et des haricots, servis avec une sauce piquante.",
        texture=("moelleux",), taste=("legumineuse", "doux"),
        compo=[
            ("kidney_bean_dried", 200, "g", "plant_protein", "dried"),
            ("white_rice_raw_seed_unenriched", 300, "g", "carbohydrate"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("water", 1400, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("base_pate_piment_b6904a", None, "1 cuillère à soupe", "serving_suggestion"),
        ],
        steps=[
            "Faire tremper 200 g de haricots rouges 8 heures, puis les égoutter.",
            "Les cuire dans 1,4 L d'eau avec 1 g de laurier, 10 minutes à gros bouillons puis 40 minutes à feu doux, jusqu'à ce qu'ils soient tendres.",
            "Faire revenir 150 g d'oignon émincé dans 25 ml d'huile, 6 minutes, et l'ajouter aux haricots avec 4 g de sel.",
            "Ajouter 300 g de riz rincé dans la casserole, le liquide doit dépasser d'un centimètre ; compléter d'eau chaude si nécessaire.",
            "Couvrir et cuire 18 minutes à feu très doux, puis laisser reposer 10 minutes.",
            "Égrener et servir avec une sauce pimentée.",
        ]),
    recipe(
        rid="soup_arachide_legumes_5f21b4", fr="Soupe d'arachide aux légumes",
        en="West African Groundnut Soup with Vegetables",
        cuisine="west_african", country="ghana", region="ashanti", city="",
        dish="soup", prep=15, cook=35, spice=1,
        desc="Soupe ouest-africaine onctueuse : beurre d'arachide délayé dans un bouillon de tomate et "
             "de gingembre, avec patate douce et aubergine, relevée de piment.",
        texture=("cremeux",), taste=("arachide", "epice"),
        compo=[
            ("peanut_butter_natural_plant", 120, "g", "plant_protein"),
            ("sweet_potato_raw", 400, "g", "vegetable"),
            ("eggplant_raw", 250, "g", "vegetable"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("tomato_paste_unsalted_canned", 30, "g", "ingredient"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1200, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 180 g d'oignon dans 25 ml d'huile, 6 minutes, puis ajouter 9 g d'ail, 12 g de gingembre, 8 g de piment et 30 g de concentré de tomate.",
            "Ajouter 300 g de tomates concassées et cuire 5 minutes.",
            "Délayer 120 g de beurre d'arachide avec 200 ml d'eau chaude, puis l'ajouter à la casserole avec 1 L d'eau et 8 g de bouillon déshydraté.",
            "Ajouter 400 g de patate douce et 250 g d'aubergine en cubes, puis mijoter 25 minutes à feu doux en remuant de temps en temps.",
            "Saler avec 2 g de sel : la soupe doit napper la cuillère et l'huile d'arachide remonter légèrement.",
            "Servir chaud, avec du riz si désiré.",
        ]),
    recipe(
        rid="main_mafe_legumes_9c40d7", fr="Mafé de légumes à l'arachide",
        en="Vegetable Mafé with Peanut Sauce",
        cuisine="west_african", country="senegal", region="dakar", city="dakar",
        dish="main", prep=20, cook=45, spice=1,
        desc="Le mafé sénégalais en version légumes : chou, carotte, patate douce et navet mijotés dans une "
             "sauce épaisse à la pâte d'arachide et à la tomate, servi avec du riz.",
        texture=("fondant", "nappant"), taste=("arachide", "tomate"),
        compo=[
            ("peanut_butter_natural_plant", 150, "g", "plant_protein"),
            ("cabbage_raw", 300, "g", "vegetable"),
            ("carrot_raw", 250, "g", "vegetable"),
            ("sweet_potato_raw", 300, "g", "vegetable"),
            ("turnip_raw", 200, "g", "vegetable"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("tomato_paste_unsalted_canned", 60, "g", "ingredient"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1100, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Faire revenir 180 g d'oignon émincé dans 30 ml d'huile, 8 minutes, puis ajouter 9 g d'ail et 60 g de concentré de tomate, et cuire 3 minutes.",
            "Délayer 150 g de pâte d'arachide avec 300 ml d'eau chaude et l'ajouter à la cocotte avec 800 ml d'eau, 8 g de bouillon, 1 g de laurier et 6 g de piment entier.",
            "Mijoter 15 minutes à feu doux en remuant, jusqu'à ce que la sauce épaississe.",
            "Ajouter 250 g de carotte, 200 g de navet et 300 g de patate douce en gros morceaux, puis cuire 20 minutes.",
            "Ajouter 300 g de chou en quartiers et cuire encore 10 minutes, jusqu'à ce que tous les légumes soient tendres. Saler avec 3 g de sel.",
            "Servir sur du riz blanc.",
        ]),
    recipe(
        rid="side_attieke_legumes_2b77f5", fr="Attiéké aux légumes et à l'avocat",
        en="Attiéké with Vegetables and Avocado",
        cuisine="west_african", country="ivory_coast", region="abidjan", city="abidjan",
        dish="side", prep=20, cook=10,
        desc="Semoule de manioc fermentée ivoirienne, réchauffée à la vapeur et servie avec une salade de "
             "tomate, oignon et concombre, de l'avocat et un filet de citron.",
        texture=("grain_separe", "fondant"), taste=("acidule", "frais"),
        compo=[
            ("attieke", 500, "g", "carbohydrate"),
            ("tomato_raw_ripe", 300, "g", "vegetable"),
            ("cucumber_raw_with_skin", 200, "g", "vegetable"),
            ("red_onion_raw", 120, "g", "aromatic"),
            ("avocado_raw", 200, "g", "fruit"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("lemon_juice", 30, "ml", "condiment"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("parsley_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Humidifier 500 g d'attiéké avec 50 ml d'eau et le réchauffer 10 minutes à la vapeur, puis l'égrener à la fourchette.",
            "Couper 300 g de tomates, 200 g de concombre et 200 g d'avocat en dés, émincer 120 g d'oignon rouge.",
            "Mélanger les légumes avec 30 ml de jus de citron, 30 ml d'huile, 6 g de piment haché, 10 g de persil et 3 g de sel.",
            "Servir l'attiéké tiède, couvert de la salade et de l'avocat.",
        ]),
    recipe(
        rid="side_sukuma_wiki_8e6031", fr="Sukuma wiki, chou cavalier à la tomate",
        en="Sukuma Wiki, Collard Greens with Tomato",
        cuisine="african", country="kenya", region="nairobi", city="nairobi",
        dish="side", prep=10, cook=20,
        desc="L'accompagnement quotidien au Kenya : chou cavalier émincé sauté avec oignon et tomate, "
             "juste assez cuit pour rester vert, servi avec l'ugali ou du riz.",
        texture=("tendre",), taste=("vegetal", "tomate"),
        compo=[
            ("collard_raw", 600, "g", "vegetable"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("lemon_juice", 15, "ml", "condiment"),
            ("water", 100, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Émincer 600 g de chou cavalier en fines lanières après avoir retiré les côtes.",
            "Faire revenir 150 g d'oignon dans 30 ml d'huile, 5 minutes, puis ajouter 9 g d'ail.",
            "Ajouter 300 g de tomates concassées et 3 g de sel, puis cuire 5 minutes.",
            "Ajouter le chou et 100 ml d'eau, couvrir et cuire 8 minutes en remuant, jusqu'à ce qu'il soit tendre mais encore vert.",
            "Arroser de 15 ml de jus de citron et servir.",
        ]),
    recipe(
        rid="salad_kachumbari_6c2d94", fr="Kachumbari, salade kényane tomate-oignon",
        en="Kachumbari, Kenyan Tomato and Onion Salad",
        cuisine="african", country="kenya", region="nairobi", city="",
        dish="starter", prep=15, rest=10, cook=0,
        desc="Salade fraîche d'Afrique de l'Est : tomates et oignon rouge dégorgé, coriandre, piment et "
             "citron, servie en accompagnement des plats en sauce.",
        texture=("croquant",), taste=("acidule", "frais"),
        compo=[
            ("tomato_raw_ripe", 500, "g", "vegetable"),
            ("red_onion_raw", 150, "g", "vegetable"),
            ("cucumber_raw_with_skin", 200, "g", "vegetable"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("lemon_juice", 40, "ml", "condiment"),
            ("olive_oil_plant", 20, "ml", "fat"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Émincer 150 g d'oignon rouge très finement et le laisser tremper 10 minutes dans l'eau froide, puis l'égoutter.",
            "Couper 500 g de tomates et 200 g de concombre en dés.",
            "Mélanger avec 6 g de piment haché, 15 g de coriandre ciselée, 40 ml de jus de citron, 20 ml d'huile et 2 g de sel.",
            "Servir frais.",
        ]),
    recipe(
        rid="snack_kelewele_5b9d38", fr="Kelewele, plantain frit épicé du Ghana",
        en="Kelewele, Ghanaian Spiced Fried Plantain",
        cuisine="african", country="ghana", region="accra", city="",
        dish="snack", servings=4, prep=10, rest=15, cook=10, spice=2, kid_friendly=False,
        desc="Le snack de rue d'Accra : dés de banane plantain bien mûre marinés au gingembre, au piment "
             "et aux épices, frits jusqu'à être caramélisés dehors et fondants dedans.",
        texture=("croustillant", "fondant"), taste=("sucre", "epice"),
        compo=[
            ("plantain_banana_raw_ripe", 600, "g", "carbohydrate"),
            ("ginger_raw_root_fresh", 20, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("onion_raw", 60, "g", "aromatic"),
            ("cloves", 0.5, "g", "spice"),
            ("nutmeg_spice", 1, "g", "spice"),
            ("sunflower_oil_plant", 50, "ml", "fat"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
            ("peanut_roasted_salted_dry", 40, "g", "garnish"),
        ],
        steps=[
            "Couper 600 g de plantain bien mûr en dés de 3 cm.",
            "Mixer 20 g de gingembre, 8 g de piment, 60 g d'oignon, 0,5 g de clous de girofle, 1 g de muscade et 2 g de sel avec 2 cuillerées d'eau.",
            "Enrober les dés de cette pâte et laisser mariner 15 minutes.",
            "Frire par petites quantités dans l'huile chaude à 175°C, 4 minutes, jusqu'à ce qu'ils soient bruns et caramélisés (environ 50 ml d'huile absorbée).",
            "Égoutter sur du papier absorbant et servir chaud avec 40 g de cacahuètes grillées.",
        ]),
    recipe(
        rid="base_ugali_7c4e15", fr="Ugali, pâte de maïs d'Afrique de l'Est",
        en="Ugali, East African Maize Meal",
        cuisine="african", country="kenya", region="nairobi", city="",
        dish="base", servings=4, prep=5, cook=20,
        desc="La base des repas en Afrique de l'Est : semoule de maïs versée en pluie dans l'eau bouillante "
             "et travaillée à la spatule jusqu'à former une pâte ferme qui se découpe en parts.",
        texture=("ferme",), taste=("cereale",),
        compo=[
            ("cornmeal_whole_dried", 300, "g", "carbohydrate"),
            ("water", 900, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Porter 900 ml d'eau à ébullition avec 2 g de sel.",
            "Verser 300 g de semoule de maïs en pluie en fouettant, pour éviter les grumeaux.",
            "Réduire le feu et travailler la pâte à la spatule 15 minutes, en l'écrasant contre les parois, jusqu'à ce qu'elle se détache de la casserole.",
            "Tasser dans un bol humide, retourner sur une assiette et servir chaud, en parts à détacher à la main.",
        ]),
    recipe(
        rid="side_chakalaka_3d6b27", fr="Chakalaka, légumes relevés d'Afrique du Sud",
        en="Chakalaka, South African Spiced Vegetable Relish",
        cuisine="african", country="south_africa", region="gauteng", city="johannesburg",
        dish="side", servings=4, prep=15, cook=20, spice=2, kid_friendly=False,
        desc="Le condiment-accompagnement sud-africain : carottes râpées, poivrons et haricots blancs "
             "mijotés au curry et au piment, servi avec le pap ou le pain.",
        texture=("croquant", "nappant"), taste=("epice", "tomate"),
        compo=[
            ("carrot_raw", 300, "g", "vegetable"),
            ("red_bell_pepper_raw", 200, "g", "vegetable"),
            ("green_bell_pepper_raw", 150, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("chilli_pepper_raw", 10, "g", "spice"),
            ("white_bean_canned", 240, "g", "plant_protein", "cooked"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("curry_powder", 6, "g", "spice"),
            ("paprika_powder", 2, "g", "spice"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 150 g d'oignon émincé dans 30 ml d'huile, 5 minutes, puis ajouter 9 g d'ail et 10 g de piment hachés.",
            "Ajouter 6 g de curry et 2 g de paprika, puis cuire 1 minute.",
            "Ajouter 200 g de poivron rouge et 150 g de poivron vert en dés, et cuire 5 minutes.",
            "Ajouter 300 g de carotte râpée et 300 g de tomates concassées, puis mijoter 8 minutes.",
            "Ajouter 240 g de haricots blancs égouttés et 3 g de sel, réchauffer 3 minutes et servir tiède.",
        ]),
]
