"""Lot 2 de nouvelles recettes : Asie du Sud-Est (Thaïlande, Vietnam, Indonésie, Malaisie, Philippines).

L'Asie du Sud-Est ne comptait que 30 plats sur 635 au recomptage du 2026-09-22.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="noodle_khao_soi_vegetarien_6b2f19", fr="Khao soi aux légumes et nouilles croustillantes",
        en="Vegetarian Khao Soi with Crispy Noodles",
        cuisine="thai", country="thailand", region="chiang_mai", city="chiang_mai",
        dish="main", prep=20, cook=25, spice=2, kid_friendly=False,
        desc="La soupe de nouilles du nord de la Thaïlande : bouillon au curry et au lait de coco, tofu et "
             "légumes, nouilles de blé dedans et une poignée de nouilles frites croustillantes dessus.",
        texture=("cremeux", "croustillant"), taste=("coco", "epice"),
        compo=[
            ("pasta_raw_dried", 300, "g", "carbohydrate"),
            ("tofu_plain_pre_packaged", 250, "g", "protein"),
            ("coconut_milk_plant", 400, "ml", "liquid"),
            ("base_curry_paste_49c97f", 40, "g", "ingredient"),
            ("shallot_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("turmeric_powder", 3, "g", "spice"),
            ("curry_powder", 4, "g", "spice"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("coconut_sugar", 10, "g", "sweetener"),
            ("lime_juice_fresh", 25, "ml", "condiment"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("peanut_oil_plant", 45, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 700, "ml", "liquid"),
        ],
        steps=[
            "Réserver 50 g de nouilles crues et les frire dans 20 ml d'huile d'arachide, 1 minute, jusqu'à ce qu'elles gonflent et dorent. Égoutter.",
            "Faire revenir 100 g d'échalotes et 9 g d'ail hachés dans 25 ml d'huile, 4 minutes, puis ajouter 40 g de pâte de curry, 3 g de curcuma et 4 g de curry, et cuire 2 minutes.",
            "Verser 400 ml de lait de coco et laisser frémir 5 minutes, jusqu'à ce que l'huile perle en surface.",
            "Ajouter 700 ml d'eau, 8 g de bouillon déshydraté, 25 ml de sauce soja et 10 g de sucre de coco, puis mijoter 10 minutes. Ajouter 250 g de tofu en cubes.",
            "Cuire 250 g de nouilles à l'eau bouillante selon leur temps, puis les répartir dans les bols.",
            "Verser le bouillon, arroser de 25 ml de jus de citron vert et garnir de nouilles frites, de 40 g d'oignons verts et de 15 g de coriandre.",
        ]),
    recipe(
        rid="curry_massaman_legumes_9d51a6", fr="Massaman de légumes aux cacahuètes",
        en="Vegetable Massaman Curry with Peanuts",
        cuisine="thai", country="thailand", region="bangkok", city="",
        dish="main", prep=20, cook=35, spice=1,
        desc="Le curry thaï le plus doux, d'influence persane : pommes de terre, patate douce et oignons "
             "mijotés au lait de coco avec cannelle, cardamome et cacahuètes.",
        texture=("fondant", "nappant"), taste=("coco", "doux"),
        compo=[
            ("potato_raw_flesh", 450, "g", "vegetable"),
            ("sweet_potato_raw", 250, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("tofu_plain_pre_packaged", 250, "g", "protein"),
            ("coconut_milk_plant", 400, "ml", "liquid"),
            ("base_curry_paste_49c97f", 40, "g", "ingredient"),
            ("peanut_roasted_salted_dry", 60, "g", "garnish"),
            ("cinnamon", 2, "g", "spice"),
            ("cardamom", 1, "g", "spice"),
            ("star_anise", 1, "g", "spice"),
            ("tamarind", 20, "ml", "condiment"),
            ("coconut_sugar", 15, "g", "sweetener"),
            ("base_vegetarian_fish_sauce_536a33", 20, "ml", "condiment"),
            ("peanut_oil_plant", 25, "ml", "fat"),
            ("water", 300, "ml", "liquid"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Faire revenir 40 g de pâte de curry dans 25 ml d'huile d'arachide, 2 minutes, puis verser 200 ml de lait de coco et laisser réduire 5 minutes.",
            "Ajouter 2 g de cannelle, 1 g de cardamome et 1 g de badiane, puis 200 g d'oignon en quartiers.",
            "Ajouter 450 g de pommes de terre et 250 g de patate douce en gros cubes, 200 ml de lait de coco et 300 ml d'eau.",
            "Mijoter 25 minutes à couvert, jusqu'à ce que les légumes soient tendres.",
            "Ajouter 250 g de tofu, 20 ml de tamarin, 15 g de sucre de coco et 20 ml de sauce « poisson » végétale, puis cuire 5 minutes.",
            "Parsemer de 60 g de cacahuètes concassées et servir avec du riz.",
        ]),
    recipe(
        rid="salad_larb_champignons_2c7b40", fr="Larb de champignons et tofu",
        en="Mushroom and Tofu Larb",
        cuisine="thai", country="thailand", region="isan", city="",
        dish="starter", prep=15, cook=10, spice=2, kid_friendly=False,
        desc="Salade tiède de l'Isan : champignons et tofu émiettés, sautés puis assaisonnés de riz grillé "
             "moulu, citron vert, piment et beaucoup d'herbes, servis avec des feuilles de salade.",
        texture=("croquant",), taste=("acidule", "epice"),
        compo=[
            ("button_mushroom_raw", 400, "g", "vegetable"),
            ("tofu_plain_pre_packaged", 200, "g", "protein"),
            ("white_glutinous_rice_seed_dried", 20, "g", "ingredient"),
            ("shallot_raw", 80, "g", "aromatic"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("mint_fresh_herb", 15, "g", "herb"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("lime_juice_fresh", 45, "ml", "condiment"),
            ("base_vegetarian_fish_sauce_536a33", 25, "ml", "condiment"),
            ("coconut_sugar", 6, "g", "sweetener"),
            ("peanut_oil_plant", 20, "ml", "fat"),
            ("lettuce", 150, "g", "vegetable"),
        ],
        steps=[
            "Griller 20 g de riz gluant à sec dans une poêle, 5 minutes, jusqu'à ce qu'il soit brun, puis le piler en poudre grossière.",
            "Hacher 400 g de champignons et émietter 200 g de tofu, puis les sauter dans 20 ml d'huile à feu vif, 6 minutes, jusqu'à évaporation de l'eau.",
            "Hors du feu, ajouter 80 g d'échalotes émincées, 45 ml de jus de citron vert, 25 ml de sauce « poisson » végétale, 6 g de sucre de coco et 8 g de piment.",
            "Ajouter le riz grillé moulu, 15 g de menthe, 15 g de coriandre et 40 g d'oignons verts.",
            "Servir tiède avec 150 g de feuilles de salade.",
        ]),
    recipe(
        rid="dessert_riz_gluant_mangue_7a3e55", fr="Riz gluant à la mangue",
        en="Mango Sticky Rice",
        cuisine="thai", country="thailand", region="bangkok", city="",
        dish="dessert", prep=10, rest=240, cook=25,
        desc="Le dessert thaï par excellence : riz gluant cuit à la vapeur puis imbibé de lait de coco sucré "
             "et salé, servi tiède avec des tranches de mangue bien mûre.",
        texture=("moelleux",), taste=("sucre", "coco"),
        compo=[
            ("white_glutinous_rice_seed_dried", 250, "g", "carbohydrate"),
            ("mango_raw", 500, "g", "fruit"),
            ("coconut_milk_plant", 300, "ml", "liquid"),
            ("white_sugar", 60, "g", "sweetener"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
            ("water", 500, "ml", "liquid"),
        ],
        steps=[
            "Rincer 250 g de riz gluant et le laisser tremper 4 heures dans l'eau froide, puis l'égoutter.",
            "Le cuire 25 minutes à la vapeur, dans un linge, jusqu'à ce qu'il soit translucide et tendre.",
            "Chauffer 200 ml de lait de coco avec 50 g de sucre et 1 g de sel, sans bouillir, puis le verser sur le riz chaud et laisser absorber 20 minutes à couvert.",
            "Chauffer le reste du lait de coco avec 10 g de sucre et 1 g de sel pour la sauce.",
            "Servir le riz tiède avec 500 g de mangue en tranches, nappé de sauce coco et parsemé de 10 g de sésame grillé.",
        ]),
    recipe(
        rid="curry_ca_ri_chay_5d90c8", fr="Cà ri chay, curry vietnamien au lait de coco",
        en="Cà Ri Chay, Vietnamese Coconut Curry",
        cuisine="vietnamese", country="vietnam", region="mekong", city="",
        dish="main", prep=20, cook=35, spice=1,
        desc="Curry végétarien du sud du Vietnam : patate douce, taro et carotte mijotés au lait de coco, "
             "citronnelle et curry doux, servis avec de la baguette ou des vermicelles.",
        texture=("fondant",), taste=("coco", "citronnelle"),
        compo=[
            ("sweet_potato_raw", 350, "g", "vegetable"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("potato_raw_flesh", 250, "g", "vegetable"),
            ("tofu_plain_pre_packaged", 250, "g", "protein"),
            ("coconut_milk_plant", 400, "ml", "liquid"),
            ("lemon_grass_fresh_herb", 30, "g", "aromatic"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("curry_powder", 10, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("coconut_sugar", 10, "g", "sweetener"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("peanut_oil_plant", 30, "ml", "fat"),
            ("water", 500, "ml", "liquid"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("white_bread_baguette", None, "1 morceau", "serving_suggestion"),
        ],
        steps=[
            "Dorer 250 g de tofu en cubes dans 15 ml d'huile, 5 minutes. Réserver.",
            "Faire revenir 150 g d'oignon, 9 g d'ail et 30 g de citronnelle hachés dans 15 ml d'huile, 5 minutes, puis ajouter 10 g de curry et 2 g de curcuma.",
            "Ajouter 250 g de pommes de terre, 350 g de patate douce et 200 g de carotte en morceaux, puis 500 ml d'eau.",
            "Mijoter 20 minutes, jusqu'à ce que les légumes soient presque tendres.",
            "Ajouter 400 ml de lait de coco, le tofu, 10 g de sucre de coco et 25 ml de sauce soja, puis cuire 10 minutes à feu doux.",
            "Parsemer de 15 g de coriandre et servir avec de la baguette.",
        ]),
    recipe(
        rid="dessert_che_chuoi_1f6a84", fr="Chè chuối, bananes au lait de coco et tapioca",
        en="Chè Chuối, Banana in Coconut Milk with Tapioca",
        cuisine="vietnamese", country="vietnam", region="saigon", city="",
        dish="dessert", prep=10, cook=20,
        desc="Dessert vietnamien réconfortant : bananes pochées dans un lait de coco sucré épaissi aux perles "
             "de tapioca, parsemé de cacahuètes grillées et de sésame.",
        texture=("cremeux",), taste=("sucre", "coco"),
        compo=[
            ("banana_raw", 500, "g", "fruit"),
            ("coconut_milk_plant", 400, "ml", "liquid"),
            ("tapioca_raw_dried", 60, "g", "thickener"),
            ("white_sugar", 50, "g", "sweetener"),
            ("peanut_roasted_salted_dry", 40, "g", "garnish"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
            ("water", 500, "ml", "liquid"),
        ],
        steps=[
            "Cuire 60 g de perles de tapioca dans 500 ml d'eau bouillante, 12 minutes, jusqu'à ce qu'elles soient translucides.",
            "Ajouter 400 ml de lait de coco, 50 g de sucre et 1 g de sel, puis chauffer sans bouillir.",
            "Ajouter 500 g de bananes en tronçons et pocher 5 minutes à feu doux.",
            "Servir tiède, parsemé de 40 g de cacahuètes concassées et de 10 g de sésame grillé.",
        ]),
    recipe(
        rid="noodle_vermicelles_tofu_citronnelle_8c33d1",
        fr="Vermicelles de riz au tofu citronnelle et herbes fraîches",
        en="Rice Vermicelli with Lemongrass Tofu and Fresh Herbs",
        cuisine="vietnamese", country="vietnam", region="saigon", city="",
        dish="main", prep=25, rest=20, cook=15, spice=1,
        desc="Bol froid du Sud vietnamien : vermicelles de riz, tofu mariné à la citronnelle et poêlé, "
             "crudités, herbes et cacahuètes, arrosés d'une sauce nuoc cham végétale.",
        texture=("croquant", "frais"), taste=("acidule", "citronnelle"),
        compo=[
            ("rice_vermicelli_raw_dried", 250, "g", "carbohydrate"),
            ("tofu_plain_pre_packaged", 300, "g", "protein"),
            ("lemon_grass_fresh_herb", 30, "g", "aromatic"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("cucumber_raw_with_skin", 200, "g", "vegetable"),
            ("lettuce", 150, "g", "vegetable"),
            ("mint_fresh_herb", 15, "g", "herb"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("mung_bean_sprouts_raw_seed_sprouted", 100, "g", "vegetable"),
            ("peanut_roasted_salted_dry", 40, "g", "garnish"),
            ("base_vegetarian_fish_sauce_536a33", 40, "ml", "condiment"),
            ("lime_juice_fresh", 40, "ml", "condiment"),
            ("coconut_sugar", 20, "g", "sweetener"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("peanut_oil_plant", 25, "ml", "fat"),
            ("white_vinegar_liquid_distilled", 20, "ml", "condiment"),
        ],
        steps=[
            "Mariner 300 g de tofu en tranches avec 30 g de citronnelle hachée, 6 g d'ail, 10 ml d'huile et 10 g de sucre de coco, 20 minutes.",
            "Cuire 250 g de vermicelles 4 minutes à l'eau bouillante, les rincer à l'eau froide et les égoutter.",
            "Nuoc cham : mélanger 40 ml de sauce « poisson » végétale, 40 ml de jus de citron vert, 20 ml de vinaigre, 10 g de sucre de coco, 3 g d'ail et 6 g de piment hachés, et 80 ml d'eau.",
            "Dorer le tofu dans 15 ml d'huile, 4 minutes par face.",
            "Tailler 150 g de carotte et 200 g de concombre en julienne, émincer 150 g de laitue.",
            "Monter les bols : vermicelles, crudités, 100 g de pousses de soja, tofu, herbes et 40 g de cacahuètes, puis arroser de nuoc cham.",
        ]),
    recipe(
        rid="stew_sayur_lodeh_6f2c93", fr="Sayur lodeh, légumes indonésiens au lait de coco",
        en="Sayur Lodeh, Indonesian Vegetables in Coconut Milk",
        cuisine="indonesian", country="indonesia", region="jawa_tengah", city="",
        dish="main", prep=20, cook=25, spice=1,
        desc="Ragoût javanais de légumes au lait de coco : chou, haricots verts, carotte et tofu mijotés "
             "dans une pâte d'échalote, ail, curcuma et galanga.",
        texture=("fondant",), taste=("coco", "epice"),
        compo=[
            ("cabbage_raw", 250, "g", "vegetable"),
            ("french_bean_raw", 200, "g", "vegetable"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("eggplant_raw", 200, "g", "vegetable"),
            ("tofu_plain_pre_packaged", 250, "g", "protein"),
            ("tempeh_tempe_raw_fermented", 150, "g", "protein"),
            ("coconut_milk_plant", 400, "ml", "liquid"),
            ("shallot_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("galangal", 15, "g", "aromatic"),
            ("turmeric_powder", 3, "g", "spice"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("kaffir_lime_leaf", 1, "g", "aromatic"),
            ("coconut_oil_plant", 25, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 600, "ml", "liquid"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Piler 100 g d'échalotes, 12 g d'ail, 8 g de piment et 3 g de curcuma en pâte.",
            "La faire revenir dans 25 ml d'huile de coco, 4 minutes, avec 15 g de galanga et 1 g de feuille de combava.",
            "Ajouter 600 ml d'eau et 8 g de bouillon déshydraté, puis 200 g de carotte et 200 g d'aubergine en morceaux, et cuire 10 minutes.",
            "Ajouter 200 g de haricots verts et 250 g de chou, puis cuire 5 minutes.",
            "Ajouter 400 ml de lait de coco, 250 g de tofu et 150 g de tempeh en cubes, puis mijoter 8 minutes sans faire bouillir.",
            "Servir avec du riz.",
        ]),
    recipe(
        rid="side_tempeh_orek_4b18d7", fr="Tempeh orek, tempeh caramélisé sucré-salé",
        en="Tempeh Orek, Sweet and Savoury Caramelised Tempeh",
        cuisine="indonesian", country="indonesia", region="jawa_tengah", city="",
        dish="side", prep=10, cook=20, spice=1,
        desc="Bâtonnets de tempeh frits puis enrobés d'un caramel de sucre de coco, ail, échalote et piment, "
             "jusqu'à devenir brillants et légèrement collants.",
        texture=("croustillant",), taste=("sucre", "umami"),
        compo=[
            ("tempeh_tempe_raw_fermented", 400, "g", "protein"),
            ("shallot_raw", 80, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("coconut_sugar", 30, "g", "sweetener"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("tamarind", 10, "ml", "condiment"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("peanut_oil_plant", 45, "ml", "fat"),
            ("water", 80, "ml", "liquid"),
        ],
        steps=[
            "Couper 400 g de tempeh en bâtonnets fins et les frire dans 35 ml d'huile, 6 minutes, jusqu'à ce qu'ils soient dorés. Réserver.",
            "Dans 10 ml d'huile, faire revenir 80 g d'échalotes, 12 g d'ail et 8 g de piment émincés, 4 minutes.",
            "Ajouter 30 g de sucre de coco, 30 ml de sauce soja, 10 ml de tamarin, 1 g de laurier et 80 ml d'eau, puis laisser réduire 4 minutes en sirop.",
            "Remettre le tempeh et remuer 2 minutes, jusqu'à ce qu'il soit enrobé et brillant.",
            "Servir tiède ou froid, avec du riz.",
        ]),
    recipe(
        rid="snack_perkedel_kentang_3e70a2", fr="Perkedel, galettes de pommes de terre indonésiennes",
        en="Perkedel, Indonesian Potato Patties",
        cuisine="indonesian", country="indonesia", region="jakarta", city="jakarta",
        dish="snack", servings=6, prep=20, cook=20,
        desc="Petites galettes de pommes de terre écrasées aux échalotes frites, ail et céleri, frites "
             "jusqu'à être dorées, croustillantes dehors et fondantes dedans.",
        texture=("croustillant", "fondant"), taste=("doux", "umami"),
        compo=[
            ("potato_raw_flesh", 700, "g", "carbohydrate"),
            ("shallot_raw", 80, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("celery_stalk_raw", 50, "g", "herb"),
            ("green_onion_raw", 30, "g", "herb"),
            ("nutmeg_spice", 1, "g", "spice"),
            ("white_pepper_spice", 1, "g", "spice"),
            ("egg_raw", 55, "g", "binder"),
            ("sunflower_oil_plant", 50, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Couper 700 g de pommes de terre en cubes et les frire 8 minutes dans 20 ml d'huile, jusqu'à ce qu'elles soient dorées et tendres, puis les écraser.",
            "Faire revenir 80 g d'échalotes et 9 g d'ail émincés dans 10 ml d'huile, 4 minutes.",
            "Mélanger la purée avec les échalotes, 50 g de céleri et 30 g d'oignon vert hachés, 1 g de muscade, 1 g de poivre blanc, 4 g de sel et 1 œuf (55 g).",
            "Former 12 galettes de 6 cm.",
            "Les dorer dans 20 ml d'huile, 3 minutes de chaque côté, et les égoutter sur du papier absorbant.",
        ]),
    recipe(
        rid="rice_nasi_lemak_vegetarien_9e4c60", fr="Nasi lemak végétarien",
        en="Vegetarian Nasi Lemak",
        cuisine="malaysian", country="malaysia", region="kuala_lumpur", city="kuala_lumpur",
        dish="main", prep=20, cook=30, spice=2, kid_friendly=False, allow_similar=("nasi",),
        desc="Le plat national malaisien : riz cuit au lait de coco et au pandan, servi avec un sambal "
             "d'échalotes au tamarin, des cacahuètes grillées, du concombre et un œuf dur.",
        texture=("moelleux", "croquant"), taste=("coco", "epice"),
        compo=[
            ("white_rice_raw_seed_unenriched", 300, "g", "carbohydrate"),
            ("coconut_milk_plant", 250, "ml", "liquid"),
            ("shallot_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 20, "g", "spice"),
            ("tamarind", 20, "ml", "condiment"),
            ("coconut_sugar", 15, "g", "sweetener"),
            ("egg_raw", 220, "g", "protein"),
            ("cucumber_raw_with_skin", 200, "g", "vegetable"),
            ("peanut_roasted_salted_dry", 60, "g", "garnish"),
            ("peanut_oil_plant", 35, "ml", "fat"),
            ("ginger_raw_root_fresh", 8, "g", "aromatic"),
            ("water", 300, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Rincer 300 g de riz, puis le cuire à couvert 15 minutes avec 250 ml de lait de coco, 300 ml d'eau, 8 g de gingembre et 3 g de sel. Laisser reposer 10 minutes.",
            "Cuire 4 œufs (220 g) 9 minutes, les refroidir et les écaler.",
            "Sambal : piler 150 g d'échalotes, 12 g d'ail et 20 g de piment, puis les faire revenir dans 35 ml d'huile, 10 minutes à feu doux.",
            "Ajouter 20 ml de tamarin et 15 g de sucre de coco, et cuire 5 minutes jusqu'à ce que le sambal fonce et que l'huile se sépare.",
            "Dresser le riz avec le sambal, 60 g de cacahuètes, 200 g de concombre en rondelles et les œufs coupés en deux.",
        ]),
    recipe(
        rid="bread_roti_canai_5a2b71", fr="Roti canai, pain feuilleté malaisien",
        en="Roti Canai, Malaysian Flaky Flatbread",
        cuisine="malaysian", country="malaysia", region="kuala_lumpur", city="",
        dish="bread", servings=6, prep=25, rest=240, cook=20,
        desc="Pain plat feuilleté d'origine indienne : pâte souple huilée, reposée, étirée très finement "
             "puis enroulée avant d'être cuite à la plancha, croustillante et moelleuse.",
        texture=("feuillete", "croustillant"), taste=("cereale",),
        compo=[
            ("wheat_all_purpose_flour_unenriched_unbleached", 400, "g", "carbohydrate"),
            ("water", 230, "ml", "liquid"),
            ("sunflower_oil_plant", 60, "ml", "fat"),
            ("vegan_butter", 40, "g", "fat"),
            ("white_sugar", 10, "g", "sweetener"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Pétrir 400 g de farine avec 230 ml d'eau tiède, 10 g de sucre et 5 g de sel, 8 minutes, jusqu'à obtenir une pâte lisse.",
            "Diviser en 6 boules, les enduire de 30 ml d'huile et les laisser reposer 4 heures à couvert.",
            "Étirer chaque boule à la main sur un plan huilé, en une feuille presque transparente.",
            "Replier les bords vers le centre, puis enrouler en escargot et aplatir légèrement.",
            "Cuire à la poêle chaude avec 30 ml d'huile et 40 g de beurre végétal, 3 minutes de chaque côté, jusqu'à ce que le pain soit doré et feuilleté.",
            "Froisser le roti entre les mains à la sortie de la poêle pour détacher les couches.",
        ]),
    recipe(
        rid="protein_tofu_adobo_8d40f3", fr="Adobo de tofu et pommes de terre",
        en="Tofu and Potato Adobo",
        cuisine="philippine", country="philippines", region="luzon", city="manille",
        dish="main", prep=15, rest=20, cook=30,
        desc="La marinade-cuisson emblématique des Philippines : vinaigre, sauce soja, ail, laurier et "
             "poivre, dans laquelle le tofu et les pommes de terre mijotent jusqu'à être glacés.",
        texture=("fondant",), taste=("acidule", "umami"),
        compo=[
            ("tofu_plain_pre_packaged", 400, "g", "protein"),
            ("potato_raw_flesh", 400, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 20, "g", "aromatic"),
            ("white_vinegar_liquid_distilled", 60, "ml", "condiment"),
            ("soy_sauce_shoyu_reduced_sodium", 45, "ml", "condiment"),
            ("bay_leaf", 2, "g", "aromatic"),
            ("black_pepper_spice", 3, "g", "spice"),
            ("coconut_sugar", 10, "g", "sweetener"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("water", 300, "ml", "liquid"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Couper 400 g de tofu en cubes et les mariner 20 minutes avec 25 ml de sauce soja.",
            "Les dorer dans 20 ml d'huile, 5 minutes, puis réserver.",
            "Faire revenir 150 g d'oignon et 20 g d'ail émincés dans 10 ml d'huile, 5 minutes.",
            "Ajouter 60 ml de vinaigre et laisser frémir 2 minutes sans remuer, puis ajouter 20 ml de sauce soja, 300 ml d'eau, 2 g de laurier, 3 g de poivre concassé et 10 g de sucre de coco.",
            "Ajouter 400 g de pommes de terre en cubes et mijoter 20 minutes, jusqu'à ce qu'elles soient tendres et la sauce sirupeuse.",
            "Remettre le tofu, réchauffer 3 minutes et servir avec du riz.",
        ]),
    recipe(
        rid="salad_yam_woon_sen_2d95e8", fr="Yam woon sen, salade thaïe de vermicelles de soja",
        en="Yam Woon Sen, Thai Glass Noodle Salad",
        cuisine="thai", country="thailand", region="bangkok", city="",
        dish="starter", prep=20, cook=10, spice=2, kid_friendly=False,
        desc="Salade tiède très relevée : vermicelles de soja, champignons et tofu, céleri et tomates, "
             "dans une sauce citron vert, piment et sucre de coco.",
        texture=("glissant", "croquant"), taste=("acidule", "epice"),
        compo=[
            ("glass_noodles_soy_vermicelli_raw_dried", 150, "g", "carbohydrate"),
            ("tofu_plain_pre_packaged", 200, "g", "protein"),
            ("button_mushroom_raw", 150, "g", "vegetable"),
            ("cherry_tomato_raw", 200, "g", "vegetable"),
            ("celery_stalk_raw", 80, "g", "vegetable"),
            ("red_onion_raw", 80, "g", "aromatic"),
            ("green_onion_raw", 30, "g", "garnish"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("peanut_roasted_salted_dry", 40, "g", "garnish"),
            ("lime_juice_fresh", 50, "ml", "condiment"),
            ("base_vegetarian_fish_sauce_536a33", 30, "ml", "condiment"),
            ("coconut_sugar", 12, "g", "sweetener"),
            ("chilli_pepper_raw", 10, "g", "spice"),
            ("peanut_oil_plant", 15, "ml", "fat"),
        ],
        steps=[
            "Faire tremper 150 g de vermicelles de soja 10 minutes dans l'eau chaude, puis les blanchir 1 minute et les rafraîchir.",
            "Sauter 200 g de tofu en dés et 150 g de champignons émincés dans 15 ml d'huile, 6 minutes.",
            "Sauce : mélanger 50 ml de jus de citron vert, 30 ml de sauce « poisson » végétale, 12 g de sucre de coco et 10 g de piment haché.",
            "Mélanger les vermicelles, le tofu et les champignons tièdes avec 200 g de tomates cerises, 80 g de céleri en tronçons et 80 g d'oignon rouge émincé.",
            "Ajouter la sauce, 15 g de coriandre, 30 g d'oignons verts et 40 g de cacahuètes concassées, puis servir aussitôt.",
        ]),
    recipe(
        rid="wok_pad_pak_ruam_4f27b6", fr="Pad pak ruam, sauté de légumes thaï",
        en="Pad Pak Ruam, Thai Stir-Fried Mixed Vegetables",
        cuisine="thai", country="thailand", region="bangkok", city="",
        dish="main", prep=10, cook=8, spice=1, allow_similar=("pak",),
        desc="Sauté express de légumes croquants au wok — brocoli, carotte, chou et champignons — "
             "avec du tofu, de l'ail et une sauce soja légèrement sucrée.",
        texture=("croquant",), taste=("umami", "ail"), technique=("wok",),
        compo=[
            ("broccoli_raw", 250, "g", "vegetable"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("green_cabbage_raw", 200, "g", "vegetable"),
            ("button_mushroom_raw", 150, "g", "vegetable"),
            ("tofu_plain_pre_packaged", 250, "g", "protein"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("base_vegetarian_oyster_sauce_b74b21", 25, "ml", "condiment"),
            ("coconut_sugar", 8, "g", "sweetener"),
            ("peanut_oil_plant", 30, "ml", "fat"),
            ("water", 60, "ml", "liquid"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Couper 250 g de brocoli en petits bouquets, 150 g de carotte en fines rondelles, 200 g de chou en lanières et 150 g de champignons en quartiers.",
            "Dorer 250 g de tofu en dés dans 15 ml d'huile à feu vif, 3 minutes, puis réserver.",
            "Faire sauter 15 g d'ail et 6 g de piment hachés dans 15 ml d'huile, 30 secondes, puis ajouter carotte et brocoli et sauter 2 minutes.",
            "Ajouter le chou, les champignons et 60 ml d'eau, puis sauter 2 minutes à couvert.",
            "Ajouter le tofu, 30 ml de sauce soja, 25 ml de sauce « huître » végétale et 8 g de sucre de coco, puis sauter 1 minute.",
            "Servir aussitôt avec du riz, les légumes doivent rester croquants.",
        ]),
]
