"""Lot 3 de nouvelles recettes : recettes rapides et petits-déjeuners.

Au recomptage du 2026-09-22 il n'y avait que 35 plats en 20 minutes ou moins (5 %)
et 29 petits-déjeuners.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="pasta_aglio_olio_6d2b95", fr="Spaghetti aglio e olio",
        en="Spaghetti Aglio e Olio",
        cuisine="italian", country="italy", region="lazio", city="rome",
        dish="main", prep=5, cook=12, spice=1,
        desc="Le plat de minuit romain : ail doré lentement dans l'huile d'olive avec du piment, "
             "spaghetti liés à l'eau de cuisson et beaucoup de persil.",
        texture=("enrobe",), taste=("ail", "epice"),
        compo=[
            ("pasta_raw_dried", 360, "g", "carbohydrate"),
            ("garlic_raw", 20, "g", "aromatic"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("olive_oil_extra_virgin_plant", 60, "ml", "fat"),
            ("parsley_fresh_herb", 20, "g", "herb"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Cuire 360 g de spaghetti dans l'eau bouillante salée avec 3 g de sel, 1 minute de moins que le temps indiqué. Réserver une louche d'eau de cuisson.",
            "Pendant ce temps, chauffer 60 ml d'huile d'olive à feu doux avec 20 g d'ail en fines lamelles, 4 minutes : l'ail doit blondir sans brunir.",
            "Ajouter 2 g de piment séché écrasé et couper le feu.",
            "Égoutter les pâtes, les verser dans la poêle avec un peu d'eau de cuisson et remuer vivement 1 minute pour émulsionner.",
            "Ajouter 20 g de persil ciselé et servir aussitôt.",
        ]),
    recipe(
        rid="pasta_cacio_e_pepe_8f3417", fr="Cacio e pepe",
        en="Cacio e Pepe",
        cuisine="italian", country="italy", region="lazio", city="rome",
        dish="main", prep=5, cook=12,
        desc="Trois ingrédients et un tour de main : poivre torréfié, pecorino romano et eau de cuisson "
             "fouettés en crème qui enrobe les pâtes, sans jamais chauffer le fromage directement.",
        texture=("cremeux",), taste=("fromage", "poivre"),
        compo=[
            ("pasta_raw_dried", 360, "g", "carbohydrate"),
            ("pecorino_sheep", 150, "g", "protein"),
            ("black_pepper_spice", 6, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Concasser grossièrement 6 g de poivre noir et le torréfier 1 minute à sec dans une grande poêle.",
            "Cuire 360 g de pâtes dans peu d'eau bouillante salée avec 2 g de sel, pour que l'eau soit bien amidonnée.",
            "Râper finement 150 g de pecorino et le mélanger, dans un bol, avec 60 ml d'eau de cuisson tiède, jusqu'à obtenir une crème lisse.",
            "Égoutter les pâtes 2 minutes avant la fin et les finir dans la poêle avec le poivre et une louche d'eau.",
            "Hors du feu, ajouter la crème de pecorino et remuer vivement jusqu'à ce que les pâtes soient nappées. Servir immédiatement.",
        ]),
    recipe(
        rid="pasta_al_limone_2a68d3", fr="Pâtes au citron et au basilic",
        en="Pasta al Limone with Basil",
        cuisine="italian", country="italy", region="campania", city="sorrente",
        dish="main", prep=8, cook=12, allow_similar=("limone",),
        desc="Pâtes de la côte amalfitaine : crème, zeste et jus de citron montés avec du parmesan, "
             "relevés de basilic, prêts le temps que les pâtes cuisent.",
        texture=("cremeux",), taste=("citron", "fromage"),
        compo=[
            ("pasta_raw_dried", 360, "g", "carbohydrate"),
            ("cream_liquid_uht", 150, "ml", "sauce"),
            ("parmesan_grated_dried_cow", 60, "g", "protein"),
            ("lemon_peel_raw", 8, "g", "aromatic"),
            ("lemon_juice", 40, "ml", "condiment"),
            ("basil_fresh_herb", 15, "g", "herb"),
            ("olive_oil_plant", 20, "ml", "fat"),
            ("black_pepper_spice", 2, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Cuire 360 g de pâtes dans l'eau bouillante salée avec 2 g de sel.",
            "Chauffer 150 ml de crème avec 8 g de zeste de citron et 20 ml d'huile d'olive, 3 minutes à feu doux, sans bouillir.",
            "Hors du feu, ajouter 60 g de parmesan râpé et 40 ml de jus de citron en fouettant.",
            "Égoutter les pâtes et les mélanger à la sauce avec un peu d'eau de cuisson, jusqu'à ce qu'elles soient nappées.",
            "Poivrer avec 2 g de poivre, ajouter 15 g de basilic ciselé et servir.",
        ]),
    recipe(
        rid="soup_sopa_de_fideo_7b91c4", fr="Sopa de fideo mexicaine",
        en="Mexican Sopa de Fideo",
        cuisine="mexican", country="mexico", region="ciudad_de_mexico", city="",
        dish="soup", prep=10, cook=15,
        desc="Soupe de tous les jours au Mexique : vermicelles dorés à l'huile puis mijotés dans un bouillon "
             "de tomate, ail et oignon, servis avec du citron vert et de l'avocat.",
        texture=("moelleux",), taste=("tomate", "doux"),
        compo=[
            ("pasta_raw_dried", 180, "g", "carbohydrate"),
            ("tomato_raw_ripe", 500, "g", "fruit"),
            ("onion_raw", 120, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1100, "ml", "liquid"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("avocado_raw", 150, "g", "garnish"),
            ("lime_juice_fresh", 20, "ml", "condiment"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
        ],
        steps=[
            "Mixer 500 g de tomates avec 120 g d'oignon et 9 g d'ail, puis filtrer.",
            "Dorer 180 g de vermicelles dans 25 ml d'huile, 3 minutes, en remuant, jusqu'à ce qu'ils soient bruns.",
            "Verser la purée de tomates et cuire 3 minutes, puis ajouter 1,1 L d'eau et 8 g de bouillon déshydraté.",
            "Mijoter 8 minutes, jusqu'à ce que les vermicelles soient tendres.",
            "Servir avec 150 g d'avocat en dés, 20 ml de jus de citron vert et 10 g de coriandre.",
        ]),
    recipe(
        rid="soup_oeufs_mais_chinoise_5c30a8", fr="Soupe chinoise aux œufs et au maïs",
        en="Chinese Egg Drop and Sweetcorn Soup",
        cuisine="chinese", country="china", region="guangdong", city="",
        dish="soup", prep=5, cook=10,
        desc="Soupe express : bouillon au gingembre lié à la fécule, maïs doux, et œufs battus versés en "
             "filet pour former des rubans soyeux.",
        texture=("soyeux",), taste=("doux", "umami"),
        compo=[
            ("sweet_corn_canned", 250, "g", "vegetable"),
            ("egg_raw", 165, "g", "protein"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("cornstarch_flour", 15, "g", "thickener"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "condiment"),
            ("sesame_oil_plant", 10, "ml", "fat"),
            ("vegetable_stock_dried", 9, "g", "ingredient"),
            ("water", 1000, "ml", "liquid"),
            ("white_pepper_spice", 1, "g", "spice"),
        ],
        steps=[
            "Porter 1 L d'eau à ébullition avec 9 g de bouillon déshydraté et 10 g de gingembre râpé.",
            "Ajouter 250 g de maïs égoutté et 20 ml de sauce soja, puis cuire 3 minutes.",
            "Délayer 15 g de fécule dans 40 ml d'eau froide et l'incorporer en fouettant : la soupe doit légèrement napper.",
            "Battre 3 œufs (165 g) et les verser en filet fin en remuant lentement, puis couper le feu.",
            "Ajouter 10 ml d'huile de sésame, 1 g de poivre blanc et 40 g d'oignons verts, puis servir.",
        ]),
    recipe(
        rid="soup_sopa_de_ajo_9e12b7", fr="Sopa de ajo castillane",
        en="Castilian Garlic Soup",
        cuisine="spanish", country="spain", region="castille", city="", allow_similar=("ajo",),
        dish="soup", prep=10, cook=20,
        desc="Soupe de pauvre de Castille, devenue un classique : ail doré dans l'huile d'olive, paprika "
             "fumé, pain rassis et un œuf poché dans le bouillon.",
        texture=("moelleux",), taste=("ail", "fume"),
        compo=[
            ("garlic_raw", 40, "g", "aromatic"),
            ("white_bread_baguette", 200, "g", "carbohydrate"),
            ("paprika_powder", 5, "g", "spice"),
            ("egg_raw", 220, "g", "protein"),
            ("olive_oil_extra_virgin_plant", 45, "ml", "fat"),
            ("vegetable_stock_dried", 9, "g", "ingredient"),
            ("water", 1200, "ml", "liquid"),
            ("parsley_fresh_herb", 10, "g", "herb"),
        ],
        steps=[
            "Faire dorer 40 g d'ail en lamelles dans 45 ml d'huile d'olive, 3 minutes à feu doux.",
            "Ajouter 200 g de pain rassis en morceaux et le faire revenir 2 minutes.",
            "Hors du feu, ajouter 5 g de paprika fumé, puis verser 1,2 L d'eau chaude et 9 g de bouillon déshydraté.",
            "Mijoter 12 minutes, jusqu'à ce que le pain se défasse.",
            "Casser 4 œufs (220 g) dans la soupe frémissante et pocher 3 minutes.",
            "Parsemer de 10 g de persil et servir brûlant.",
        ]),
    recipe(
        rid="brkf_gallo_pinto_3d47f2", fr="Gallo pinto, riz et haricots du Costa Rica",
        en="Gallo Pinto, Costa Rican Rice and Beans",
        cuisine="latin_american", country="costa_rica", region="san_jose", city="",
        dish="breakfast", prep=10, cook=15,
        desc="Le petit-déjeuner costaricien : riz de la veille sauté avec des haricots noirs, poivron, "
             "oignon et coriandre, relevé d'une sauce brune type Lizano.",
        texture=("moelleux",), taste=("umami", "doux"),
        compo=[
            ("white_rice_cooked_long_grain_seed", 500, "g", "carbohydrate", "cooked"),
            ("black_bean_boiled", 300, "g", "plant_protein", "cooked"),
            ("red_bell_pepper_raw", 120, "g", "vegetable"),
            ("onion_raw", 120, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "condiment"),
            ("cumin_spice_seed", 2, "g", "spice"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("egg_raw", 220, "g", "protein"),
        ],
        steps=[
            "Faire revenir 120 g d'oignon et 120 g de poivron en petits dés dans 15 ml d'huile, 5 minutes, puis ajouter 9 g d'ail et 2 g de cumin.",
            "Ajouter 300 g de haricots noirs avec 2 cuillerées de leur jus et 20 ml de sauce soja, puis cuire 3 minutes.",
            "Ajouter 500 g de riz cuit froid et mélanger 4 minutes à feu vif, jusqu'à ce que le riz prenne la couleur des haricots.",
            "Ajouter 15 g de coriandre ciselée.",
            "Cuire 4 œufs (220 g) au plat dans 10 ml d'huile et les servir sur le gallo pinto.",
        ]),
    recipe(
        rid="brkf_huevos_rancheros_6a80e5", fr="Huevos rancheros",
        en="Huevos Rancheros",
        cuisine="mexican", country="mexico", region="ciudad_de_mexico", city="",
        dish="breakfast", prep=10, cook=15, spice=2, kid_friendly=False,
        desc="Le petit-déjeuner des fermes mexicaines : tortillas de maïs poêlées, haricots noirs écrasés, "
             "œufs au plat et sauce tomate au piment, avec coriandre et avocat.",
        texture=("moelleux",), taste=("epice", "tomate"),
        compo=[
            ("base_tortilla_92c2a6", 240, "g", "carbohydrate"),
            ("egg_raw", 220, "g", "protein"),
            ("black_bean_boiled", 250, "g", "plant_protein", "cooked"),
            ("tomato_raw_ripe", 350, "g", "fruit"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("jalapeno_pepper_raw", 20, "g", "spice"),
            ("avocado_raw", 150, "g", "garnish"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 100 g d'oignon, 6 g d'ail et 20 g de jalapeño hachés dans 10 ml d'huile, 4 minutes.",
            "Ajouter 350 g de tomates concassées et 2 g de sel, puis cuire 8 minutes en écrasant.",
            "Réchauffer 250 g de haricots noirs et les écraser grossièrement avec 1 g de sel.",
            "Poêler les tortillas (240 g) 1 minute par face dans 10 ml d'huile.",
            "Cuire 4 œufs (220 g) au plat dans 10 ml d'huile.",
            "Dresser : tortilla, haricots, œuf, sauce tomate, puis 150 g d'avocat et 10 g de coriandre.",
        ]),
    recipe(
        rid="brkf_upma_semoule_4c5e77", fr="Upma, semoule indienne aux légumes",
        en="Upma, Indian Semolina with Vegetables",
        cuisine="indian", country="india", region="karnataka", city="",
        dish="breakfast", prep=10, cook=15, spice=1,
        desc="Petit-déjeuner du sud de l'Inde : semoule torréfiée puis gonflée dans l'eau avec un tempérage "
             "de moutarde, feuilles de curry, gingembre et légumes croquants.",
        texture=("moelleux",), taste=("epice", "citron"),
        compo=[
            ("wheat_semolina_raw", 200, "g", "carbohydrate"),
            ("onion_raw", 120, "g", "aromatic_base"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("green_peas_raw", 100, "g", "vegetable"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("yellow_mustard_spice_seed", 3, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("cashew_nuts_raw", 30, "g", "garnish"),
            ("sunflower_oil_plant", 35, "ml", "fat"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("water", 600, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Torréfier 200 g de semoule à sec 4 minutes, jusqu'à ce qu'elle sente la noisette, puis la réserver.",
            "Chauffer 35 ml d'huile, y faire éclater 3 g de graines de moutarde avec 5 g de feuilles de curry et 30 g de noix de cajou.",
            "Ajouter 120 g d'oignon, 10 g de gingembre et 6 g de piment hachés, puis cuire 3 minutes.",
            "Ajouter 120 g de carotte en petits dés et 100 g de petits pois, puis 600 ml d'eau et 4 g de sel, et porter à ébullition.",
            "Verser la semoule en pluie en remuant sans arrêt, puis cuire 3 minutes à feu doux et laisser reposer 3 minutes à couvert.",
            "Ajouter 20 ml de jus de citron et 10 g de coriandre, puis servir chaud.",
        ]),
    recipe(
        rid="brkf_congee_gingembre_8b5d24", fr="Congee au gingembre et aux champignons",
        en="Ginger and Mushroom Congee",
        cuisine="chinese", country="china", region="guangdong", city="",
        dish="breakfast", prep=10, cook=50,
        desc="Bouillie de riz cantonaise cuite longuement jusqu'à devenir crémeuse, parfumée au gingembre, "
             "garnie de champignons sautés, d'oignons verts et d'un filet d'huile de sésame.",
        texture=("cremeux",), taste=("doux", "umami"),
        compo=[
            ("white_rice_raw_seed_unenriched", 180, "g", "carbohydrate"),
            ("shiitake_mushroom_raw", 200, "g", "vegetable"),
            ("ginger_raw_root_fresh", 20, "g", "aromatic"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("peanut_oil_plant", 15, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1800, "ml", "liquid"),
            ("white_pepper_spice", 1, "g", "spice"),
        ],
        steps=[
            "Rincer 180 g de riz et le mettre dans une grande casserole avec 1,8 L d'eau, 8 g de bouillon déshydraté et 10 g de gingembre en lamelles.",
            "Porter à ébullition puis cuire 45 minutes à feu doux en remuant de temps en temps, jusqu'à ce que les grains éclatent et que le congee nappe la cuillère.",
            "Faire sauter 200 g de shiitakés émincés dans 15 ml d'huile d'arachide avec 10 g de gingembre râpé, 5 minutes.",
            "Assaisonner le congee avec 25 ml de sauce soja et 1 g de poivre blanc.",
            "Servir garni de champignons, de 40 g d'oignons verts et d'un filet d'huile de sésame (15 ml).",
        ]),
    recipe(
        rid="brkf_porridge_millet_coco_2f94a1", fr="Porridge de millet au lait de coco et à la mangue",
        en="Millet Porridge with Coconut Milk and Mango",
        cuisine="international", country="international", region="world", city="",
        dish="breakfast", prep=5, cook=20,
        desc="Petit-déjeuner sans gluten : millet cuit dans un lait de coco légèrement sucré à la cardamome, "
             "servi avec de la mangue fraîche et des amandes grillées.",
        texture=("cremeux",), taste=("coco", "sucre"),
        compo=[
            ("millet_raw_whole_seed", 180, "g", "carbohydrate"),
            ("coconut_milk_plant", 300, "ml", "liquid"),
            ("water", 500, "ml", "liquid"),
            ("mango_raw", 300, "g", "fruit"),
            ("almond_raw_with_skin_unsalted", 40, "g", "garnish"),
            ("maple_syrup", 30, "ml", "sweetener"),
            ("cardamom", 1, "g", "spice"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Rincer 180 g de millet et le faire griller 2 minutes à sec dans une casserole.",
            "Ajouter 500 ml d'eau, 1 g de cardamome et 1 g de sel, puis cuire 15 minutes à couvert et à feu doux.",
            "Ajouter 300 ml de lait de coco et cuire encore 5 minutes en remuant, jusqu'à obtenir une texture crémeuse.",
            "Sucrer avec 30 ml de sirop d'érable.",
            "Servir avec 300 g de mangue en dés et 40 g d'amandes concassées et grillées.",
        ]),
    recipe(
        rid="protein_paneer_bhurji_7e3c50", fr="Paneer bhurji, paneer émietté aux épices",
        en="Paneer Bhurji, Spiced Crumbled Paneer",
        cuisine="indian", country="india", region="punjab", city="",
        dish="main", prep=10, cook=15, spice=1,
        desc="Paneer émietté sauté avec oignon, tomate, gingembre et garam masala, comme des œufs brouillés "
             "épicés : prêt en un quart d'heure, à manger avec des rotis.",
        texture=("moelleux",), taste=("epice", "doux"),
        compo=[
            ("base_paneer_04e1db", 350, "g", "protein"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("tomato_raw_ripe", 250, "g", "fruit"),
            ("green_bell_pepper_raw", 100, "g", "vegetable"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("garam_masala", 3, "g", "spice"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
            ("indian_bread_naan", None, "1 pièce", "serving_suggestion"),
        ],
        steps=[
            "Faire grésiller 3 g de cumin dans 30 ml d'huile, puis ajouter 150 g d'oignon haché et le dorer 5 minutes.",
            "Ajouter 9 g d'ail, 10 g de gingembre et 6 g de piment hachés, puis 100 g de poivron en dés, et cuire 3 minutes.",
            "Ajouter 250 g de tomates concassées, 2 g de curcuma et 3 g de sel, puis cuire 4 minutes.",
            "Émietter 350 g de paneer dans la poêle et mélanger 3 minutes à feu moyen.",
            "Ajouter 3 g de garam masala et 15 g de coriandre, puis servir avec des rotis ou du naan.",
        ]),
    recipe(
        rid="soup_avgolemono_vegetarien_5a71e9", fr="Avgolemono, soupe grecque au citron et à l'œuf",
        en="Avgolemono, Greek Lemon and Egg Soup",
        cuisine="greek", country="greece", region="attique", city="athenes",
        dish="soup", prep=10, cook=20,
        desc="Soupe grecque veloutée : bouillon de légumes et riz, lié hors du feu avec des œufs battus "
             "au jus de citron, sans jamais bouillir pour rester soyeux.",
        texture=("soyeux",), taste=("citron", "doux"),
        compo=[
            ("white_rice_raw_seed_unenriched", 120, "g", "carbohydrate"),
            ("egg_raw", 165, "g", "protein"),
            ("lemon_juice", 70, "ml", "condiment"),
            ("carrot_raw", 120, "g", "vegetable"),
            ("celery_stalk_raw", 80, "g", "vegetable"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("olive_oil_plant", 25, "ml", "fat"),
            ("dill_weed_fresh_herb_leaf", 10, "g", "herb"),
            ("vegetable_stock_dried", 10, "g", "ingredient"),
            ("water", 1300, "ml", "liquid"),
            ("black_pepper_spice", 1, "g", "spice"),
        ],
        steps=[
            "Faire suer 100 g d'oignon, 120 g de carotte et 80 g de céleri en dés dans 25 ml d'huile d'olive, 5 minutes.",
            "Ajouter 1,3 L d'eau et 10 g de bouillon déshydraté, porter à ébullition, puis ajouter 120 g de riz et cuire 15 minutes.",
            "Battre 3 œufs (165 g) avec 70 ml de jus de citron.",
            "Verser lentement deux louches de bouillon chaud sur les œufs en fouettant, pour les tempérer.",
            "Reverser le mélange dans la casserole hors du feu, en remuant : la soupe doit épaissir sans bouillir.",
            "Poivrer avec 1 g de poivre, ajouter 10 g d'aneth et servir aussitôt.",
        ]),
    recipe(
        rid="salad_haricots_blancs_roquette_9c5b02", fr="Salade de haricots blancs, roquette et tomates confites",
        en="White Bean Salad with Arugula and Sun-Dried Tomatoes",
        cuisine="italian", country="italy", region="toscane", city="",
        dish="starter", prep=10, cook=0,
        desc="Salade toscane sans cuisson : haricots blancs, roquette poivrée, tomates séchées et oignon "
             "rouge, assaisonnés au citron, à l'huile d'olive et à l'origan.",
        texture=("fondant", "croquant"), taste=("acidule", "umami"),
        compo=[
            ("white_bean_canned", 400, "g", "plant_protein", "cooked"),
            ("arugula_raw", 100, "g", "vegetable"),
            ("tomato_dried", 60, "g", "vegetable"),
            ("red_onion_raw", 80, "g", "aromatic"),
            ("lemon_juice", 30, "ml", "condiment"),
            ("olive_oil_extra_virgin_plant", 40, "ml", "fat"),
            ("oregano_spice_dried", 1, "g", "herb"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Rincer et égoutter 400 g de haricots blancs.",
            "Émincer 80 g d'oignon rouge et le laisser tremper 5 minutes dans l'eau froide, puis l'égoutter.",
            "Couper 60 g de tomates séchées en lanières.",
            "Mélanger les haricots, l'oignon et les tomates avec 30 ml de jus de citron, 40 ml d'huile d'olive, 1 g d'origan, 2 g de sel et 1 g de poivre.",
            "Ajouter 100 g de roquette au dernier moment et servir.",
        ]),
    recipe(
        rid="starter_balila_pois_chiches_3f62d8", fr="Balila, pois chiches chauds au cumin et au citron",
        en="Balila, Warm Chickpeas with Cumin and Lemon",
        cuisine="lebanese", country="lebanon", region="beyrouth", city="beyrouth",
        dish="starter", prep=5, cook=10,
        desc="Mezze libanais du matin : pois chiches réchauffés dans leur eau, écrasés du bout de la "
             "cuillère, assaisonnés d'ail, de cumin, de citron et d'huile d'olive.",
        texture=("fondant",), taste=("citron", "cumin"),
        compo=[
            ("chickpea_boiled", 500, "g", "plant_protein", "cooked"),
            ("garlic_raw", 10, "g", "aromatic"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("lemon_juice", 45, "ml", "condiment"),
            ("olive_oil_extra_virgin_plant", 40, "ml", "fat"),
            ("parsley_fresh_herb", 15, "g", "herb"),
            ("water", 150, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
            ("white_pita_bread", None, "1 pain", "serving_suggestion"),
        ],
        steps=[
            "Réchauffer 500 g de pois chiches cuits dans 150 ml d'eau, 5 minutes à feu doux.",
            "Piler 10 g d'ail avec 2 g de sel et 4 g de cumin.",
            "Égoutter partiellement les pois chiches, puis les mélanger à la pâte d'ail, à 45 ml de jus de citron et à 40 ml d'huile d'olive.",
            "Écraser légèrement une partie des pois chiches à la cuillère pour lier l'ensemble.",
            "Parsemer de 15 g de persil et servir tiède avec du pain pita.",
        ]),
]
