"""Lot 4 de nouvelles recettes : Amérique latine et Caraïbes.

50 plats sur 635 au recomptage du 2026-09-22, dont beaucoup de mexicain.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="soup_sopa_de_tortilla_5e28c1", fr="Sopa de tortilla",
        en="Tortilla Soup",
        cuisine="mexican", country="mexico", region="ciudad_de_mexico", city="",
        dish="soup", prep=15, cook=25, spice=2, kid_friendly=False,
        desc="Bouillon de tomate grillée aux piments pasilla, dans lequel on plonge des lanières de tortilla "
             "frites, avec avocat, fromage frais et crème.",
        texture=("croustillant",), taste=("fume", "tomate"),
        compo=[
            ("tomato_raw_ripe", 600, "g", "fruit"),
            ("base_tortilla_92c2a6", 200, "g", "carbohydrate"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("ancho_pepper_spice_dried", 20, "g", "spice", "dry"),
            ("avocado_raw", 150, "g", "garnish"),
            ("queso_fresco_block_cow", 80, "g", "garnish"),
            ("sour_cream_fermented_18pct", 60, "g", "garnish"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("sunflower_oil_plant", 45, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1000, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Couper 200 g de tortillas en lanières et les frire dans 25 ml d'huile, 3 minutes, jusqu'à ce qu'elles soient croustillantes. Égoutter.",
            "Griller 600 g de tomates, 150 g d'oignon et 12 g d'ail à sec dans une poêle, 8 minutes, jusqu'à ce qu'ils soient tachés de noir.",
            "Faire tremper 20 g de piments ancho épépinés 10 minutes dans l'eau chaude, puis mixer le tout avec 200 ml d'eau.",
            "Cuire cette purée 5 minutes dans 20 ml d'huile, puis ajouter 800 ml d'eau, 8 g de bouillon déshydraté et 2 g de sel, et mijoter 12 minutes.",
            "Servir le bouillon sur les lanières de tortilla, avec 150 g d'avocat, 80 g de fromage frais, 60 g de crème et 15 g de coriandre.",
        ]),
    recipe(
        rid="side_rajas_con_crema_2d9f74", fr="Rajas con crema, poivrons à la crème",
        en="Rajas con Crema, Pepper Strips in Cream",
        cuisine="mexican", country="mexico", region="puebla", city="",
        dish="side", prep=15, cook=20, spice=1,
        desc="Lanières de poivrons grillés et pelés, fondues avec de l'oignon, du maïs et de la crème, "
             "à glisser dans des tortillas ou à servir avec du riz.",
        texture=("fondant",), taste=("doux", "fume"),
        compo=[
            ("green_bell_pepper_raw", 400, "g", "vegetable"),
            ("red_bell_pepper_raw", 200, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("sweet_corn_canned", 150, "g", "vegetable"),
            ("sour_cream_fermented_18pct", 150, "g", "sauce"),
            ("queso_fresco_block_cow", 80, "g", "protein"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Griller 400 g de poivron vert et 200 g de poivron rouge sous le gril du four, 15 minutes, puis les enfermer 10 minutes dans un saladier couvert, les peler et les couper en lanières.",
            "Faire fondre 200 g d'oignon émincé dans 25 ml d'huile, 8 minutes, puis ajouter 9 g d'ail.",
            "Ajouter les lanières de poivron, 150 g de maïs et 3 g de sel, puis cuire 5 minutes.",
            "Hors du feu, incorporer 150 g de crème et 80 g de fromage frais émietté, et réchauffer 2 minutes sans bouillir.",
        ]),
    recipe(
        rid="snack_esquites_7b40e6", fr="Esquites, maïs à la mexicaine en gobelet",
        en="Esquites, Mexican Street Corn Cups",
        cuisine="mexican", country="mexico", region="ciudad_de_mexico", city="",
        dish="snack", prep=10, cook=12, spice=1,
        desc="Le maïs de rue mexicain servi à la cuillère : grains sautés au beurre avec de l'épazote, "
             "mêlés de mayonnaise, de fromage cotija, de piment en poudre et de citron vert.",
        texture=("croquant", "cremeux"), taste=("acidule", "fromage"),
        compo=[
            ("sweet_corn_raw_fresh", 600, "g", "vegetable"),
            ("base_mayonnaise_0d3e4e", 80, "g", "sauce"),
            ("cotija_block_cow", 80, "g", "protein"),
            ("butter_sup80pct", 25, "g", "fat"),
            ("lime_juice_fresh", 40, "ml", "condiment"),
            ("paprika_powder", 3, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire sauter 600 g de grains de maïs dans 25 g de beurre à feu vif, 8 minutes, jusqu'à ce qu'ils soient dorés par endroits.",
            "Saler avec 2 g de sel et laisser tiédir 5 minutes.",
            "Mélanger avec 80 g de mayonnaise, 40 ml de jus de citron vert et 15 g de coriandre ciselée.",
            "Répartir en gobelets, couvrir de 80 g de cotija râpé, de 3 g de paprika et de 2 g de piment en poudre.",
        ]),
    recipe(
        rid="entry_causa_limena_9c61b8", fr="Causa limeña à l'avocat",
        en="Causa Limeña with Avocado",
        cuisine="peruvian", country="peru", region="lima", city="lima",
        dish="starter", prep=25, rest=60, cook=25, spice=2, kid_friendly=False,
        desc="Entrée péruvienne montée en couches : purée de pommes de terre au citron et au piment jaune, "
             "garniture d'avocat et de tomate, servie bien fraîche.",
        texture=("fondant",), taste=("citron", "epice"),
        compo=[
            ("potato_raw_flesh", 600, "g", "carbohydrate"),
            ("avocado_raw", 250, "g", "fruit"),
            ("tomato_raw_ripe", 200, "g", "vegetable"),
            ("base_mayonnaise_0d3e4e", 40, "g", "sauce"),
            ("lime_juice_fresh", 50, "ml", "condiment"),
            ("chilli_pepper_raw", 10, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("olive_oil_plant", 35, "ml", "fat"),
            ("red_onion_raw", 60, "g", "aromatic"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Cuire 600 g de pommes de terre à l'eau salée 25 minutes, les éplucher chaudes et les écraser finement.",
            "Mixer 10 g de piment avec 2 g de curcuma, 35 ml d'huile d'olive et 30 ml de jus de citron vert, puis l'incorporer à la purée avec 3 g de sel.",
            "Écraser 250 g d'avocat avec 20 ml de jus de citron vert et 1 g de sel ; couper 200 g de tomates en dés et émincer 60 g d'oignon rouge.",
            "Dans un cercle ou un petit plat, alterner purée, avocat, tomate et oignon, en terminant par la purée.",
            "Lisser avec 40 g de mayonnaise, réfrigérer 1 heure et servir frais, parsemé de 10 g de coriandre.",
        ]),
    recipe(
        rid="rice_quinoa_chaufa_4f7d21", fr="Quinoa chaufa, quinoa sauté à la péruvienne",
        en="Quinoa Chaufa, Peruvian Stir-Fried Quinoa",
        cuisine="peruvian", country="peru", region="lima", city="",
        dish="main", prep=15, cook=20,
        desc="Rencontre du Pérou et de la Chine : quinoa sauté au wok avec sauce soja, gingembre, œufs, "
             "poivron et oignons verts, comme un arroz chaufa sans riz.",
        texture=("grain_separe",), taste=("umami", "gingembre"),
        compo=[
            ("quinoa_raw_dried", 250, "g", "carbohydrate"),
            ("egg_raw", 165, "g", "protein"),
            ("red_bell_pepper_raw", 150, "g", "vegetable"),
            ("green_peas_raw", 120, "g", "vegetable"),
            ("green_onion_raw", 50, "g", "garnish"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("soy_sauce_shoyu_reduced_sodium", 35, "ml", "condiment"),
            ("sesame_oil_plant", 10, "ml", "fat"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("water", 500, "ml", "liquid"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
        ],
        steps=[
            "Rincer 250 g de quinoa et le cuire 12 minutes dans 500 ml d'eau, puis l'égrener et le laisser refroidir.",
            "Battre 3 œufs (165 g) et les cuire en omelette fine dans 10 ml d'huile, puis les couper en lanières.",
            "Sauter 150 g de poivron en dés dans 15 ml d'huile à feu vif, 3 minutes, puis ajouter 12 g d'ail et 12 g de gingembre hachés.",
            "Ajouter le quinoa, 120 g de petits pois et 35 ml de sauce soja, puis sauter 4 minutes.",
            "Ajouter l'omelette, 50 g d'oignons verts et 10 ml d'huile de sésame, mélanger et servir avec 10 g de coriandre.",
        ]),
    recipe(
        rid="stew_porotos_granados_6a35c9", fr="Porotos granados, haricots, maïs et courge",
        en="Porotos Granados, Chilean Bean, Corn and Squash Stew",
        cuisine="chilean", country="chile", region="santiago", city="",
        dish="main", prep=20, cook=40,
        desc="Le ragoût d'été chilien : haricots blancs frais, maïs râpé et courge fondue, parfumés au "
             "basilic et au paprika, épais comme une purée.",
        texture=("fondant",), taste=("doux", "basilic"),
        compo=[
            ("white_bean_canned", 500, "g", "plant_protein", "cooked"),
            ("sweet_corn_raw_fresh", 300, "g", "vegetable"),
            ("butternut_squash_raw_skinless", 400, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("paprika_powder", 4, "g", "spice"),
            ("basil_fresh_herb", 20, "g", "herb"),
            ("olive_oil_plant", 35, "ml", "fat"),
            ("vegetable_stock_dried", 5, "g", "ingredient"),
            ("water", 700, "ml", "liquid"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 200 g d'oignon haché dans 35 ml d'huile d'olive, 8 minutes, puis ajouter 9 g d'ail et 4 g de paprika.",
            "Ajouter 400 g de courge en cubes, 700 ml d'eau et 5 g de bouillon déshydraté, puis cuire 20 minutes, jusqu'à ce que la courge se défasse.",
            "Mixer grossièrement 200 g de maïs et l'ajouter avec 100 g de grains entiers.",
            "Ajouter 500 g de haricots blancs et 1 g de sel, puis mijoter 12 minutes en remuant : le ragoût doit épaissir.",
            "Hors du feu, ajouter 20 g de basilic ciselé et servir.",
        ]),
    recipe(
        rid="main_pastel_de_choclo_8d52a4", fr="Pastel de choclo végétarien",
        en="Vegetarian Pastel de Choclo",
        cuisine="chilean", country="chile", region="santiago", city="santiago",
        dish="main", prep=25, cook=45,
        desc="Gratin chilien : garniture de lentilles, oignons et olives sous une épaisse crème de maïs au "
             "basilic, caramélisée au four avec un voile de sucre.",
        texture=("fondant", "gratine"), taste=("doux", "umami"),
        compo=[
            ("sweet_corn_raw_fresh", 700, "g", "vegetable"),
            ("green_lentil_dried", 150, "g", "plant_protein", "dried"),
            ("onion_raw", 250, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("black_olive_canned_in_brine", 50, "g", "garnish"),
            ("egg_raw", 110, "g", "protein"),
            ("milk_liquid_uht_3_5pct", 150, "ml", "sauce"),
            ("basil_fresh_herb", 20, "g", "herb"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("paprika_powder", 3, "g", "spice"),
            ("white_sugar", 15, "g", "sweetener"),
            ("olive_oil_plant", 30, "ml", "fat"),
            ("water", 500, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Cuire 150 g de lentilles vertes dans 500 ml d'eau, 25 minutes, puis les égoutter.",
            "Faire revenir 250 g d'oignon haché dans 30 ml d'huile, 10 minutes, avec 9 g d'ail, 3 g de cumin, 3 g de paprika et 2 g de sel, puis mélanger aux lentilles.",
            "Mixer 700 g de maïs avec 150 ml de lait, 20 g de basilic et 2 g de sel, puis cuire cette crème 8 minutes en remuant, jusqu'à épaississement.",
            "Préchauffer le four à 200°C. Étaler la garniture dans un plat, parsemer de 50 g d'olives et de 2 œufs durs (110 g) en rondelles.",
            "Couvrir de crème de maïs, saupoudrer de 15 g de sucre et cuire 25 minutes, jusqu'à ce que le dessus soit caramélisé.",
        ]),
    recipe(
        rid="stew_locro_courge_mais_3c7e90", fr="Locro de courge et maïs",
        en="Squash and Corn Locro",
        cuisine="argentinian", country="argentina", region="buenos_aires", city="",
        dish="main", prep=20, rest=480, cook=60, spice=1,
        desc="Ragoût andin des jours de fête, ici sans viande : maïs blanc et haricots trempés, courge qui "
             "fond et lie le bouillon, servi avec une huile au paprika fumé.",
        texture=("fondant", "nappant"), taste=("fume", "doux"),
        compo=[
            ("hominy_boiled_flour_canned", 350, "g", "carbohydrate"),
            ("white_bean_canned", 300, "g", "plant_protein", "cooked"),
            ("butternut_squash_raw_skinless", 500, "g", "vegetable"),
            ("sweet_potato_raw", 250, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("paprika_powder", 6, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("vegetable_stock_dried", 6, "g", "ingredient"),
            ("water", 1300, "ml", "liquid"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 200 g d'oignon haché dans 20 ml d'huile, 8 minutes, avec 12 g d'ail et 3 g de cumin.",
            "Ajouter 350 g de maïs blanc égoutté, 1,3 L d'eau et 6 g de bouillon déshydraté, puis mijoter 30 minutes.",
            "Ajouter 500 g de courge et 250 g de patate douce en cubes, puis cuire 25 minutes : la courge doit se défaire et épaissir le bouillon.",
            "Ajouter 300 g de haricots blancs et 1 g de sel, puis mijoter 5 minutes.",
            "Huile au paprika : chauffer 20 ml d'huile hors du feu avec 6 g de paprika et 40 g d'oignons verts émincés.",
            "Servir le locro nappé de cette huile parfumée.",
        ]),
    recipe(
        rid="entry_provoleta_origan_5b81c7", fr="Provoleta grillée à l'origan",
        en="Grilled Provoleta with Oregano",
        cuisine="argentinian", country="argentina", region="buenos_aires", city="buenos_aires",
        dish="starter", prep=5, cook=8,
        desc="L'entrée du barbecue argentin : une tranche épaisse de provolone saisie jusqu'à former une "
             "croûte, fondante à cœur, parfumée à l'origan et au piment.",
        texture=("fondant", "croustillant"), taste=("fromage", "origan"),
        compo=[
            ("provolone_paste_cow", 300, "g", "protein"),
            ("oregano_spice_dried", 3, "g", "herb"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("olive_oil_extra_virgin_plant", 20, "ml", "fat"),
            ("white_bread_baguette", 160, "g", "carbohydrate"),
            ("black_pepper_spice", 1, "g", "spice"),
        ],
        steps=[
            "Couper 300 g de provolone en quatre tranches épaisses de 2 cm et les laisser 10 minutes à température ambiante.",
            "Chauffer une poêle en fonte à feu vif avec 10 ml d'huile d'olive.",
            "Saisir les tranches 3 minutes de chaque côté, sans les bouger, jusqu'à ce qu'une croûte dorée se forme.",
            "Parsemer de 3 g d'origan, 2 g de piment et 1 g de poivre, arroser de 10 ml d'huile.",
            "Servir brûlant avec 160 g de pain grillé.",
        ]),
    recipe(
        rid="sauce_chimichurri_2e64f8", fr="Chimichurri",
        en="Chimichurri",
        cuisine="argentinian", country="argentina", region="buenos_aires", city="",
        dish="sauce", servings=8, prep=10, rest=60, cook=0,
        desc="La sauce crue des grillades argentines : persil, ail et origan hachés, vinaigre de vin rouge, "
             "huile et piment, laissée reposer pour que les saveurs se lient.",
        texture=("liquide",), taste=("acidule", "ail"),
        compo=[
            ("parsley_fresh_herb", 60, "g", "herb"),
            ("garlic_raw", 25, "g", "aromatic"),
            ("oregano_spice_dried", 4, "g", "herb"),
            ("red_hot_chili_pepper_spice_dried", 3, "g", "spice"),
            ("red_wine_vinegar_liquid", 60, "ml", "acidity"),
            ("olive_oil_extra_virgin_plant", 150, "ml", "fat"),
            ("water", 40, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Hacher 60 g de persil et 25 g d'ail au couteau, sans les mixer.",
            "Dissoudre 4 g de sel dans 60 ml de vinaigre et 40 ml d'eau tiède, puis ajouter 4 g d'origan et 3 g de piment écrasé.",
            "Ajouter le persil et l'ail, puis 150 ml d'huile d'olive en remuant.",
            "Laisser reposer au moins 1 heure à température ambiante avant de servir.",
        ]),
    recipe(
        rid="main_vatapa_legumes_7d19c3", fr="Vatapá de légumes au lait de coco",
        en="Vegetable Vatapá with Coconut Milk",
        cuisine="brazilian", country="brazil", region="bahia", city="salvador",
        dish="main", prep=20, cook=30, spice=1,
        desc="Crème bahianaise épaissie au pain et aux cacahuètes, parfumée au lait de coco, au gingembre et "
             "à l'huile de palme, avec des légumes et servie sur du riz.",
        texture=("cremeux",), taste=("arachide", "coco"),
        compo=[
            ("white_bread_unsalted", 150, "g", "thickener"),
            ("peanut_butter_natural_plant", 80, "g", "plant_protein"),
            ("coconut_milk_plant", 400, "ml", "liquid"),
            ("cashew_nuts_raw", 60, "g", "plant_protein"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("tomato_raw_ripe", 300, "g", "fruit"),
            ("red_bell_pepper_raw", 150, "g", "vegetable"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("palm_oil_refined_plant", 25, "ml", "fat"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("water", 400, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Faire tremper 150 g de pain rassis dans 400 ml d'eau, 10 minutes, puis le mixer avec 60 g de noix de cajou.",
            "Faire revenir 180 g d'oignon, 150 g de poivron, 12 g d'ail et 12 g de gingembre hachés dans 25 ml d'huile de palme, 8 minutes.",
            "Ajouter 300 g de tomates concassées et cuire 5 minutes.",
            "Ajouter le pain mixé, 80 g de beurre de cacahuète, 400 ml de lait de coco et 4 g de sel.",
            "Cuire 15 minutes à feu doux en remuant sans arrêt, jusqu'à obtenir une crème épaisse qui se détache de la cuillère.",
            "Parsemer de 15 g de coriandre et servir sur du riz.",
        ]),
    recipe(
        rid="side_tostones_mojo_9f57b2", fr="Tostones et mojo à l'ail",
        en="Tostones with Garlic Mojo",
        cuisine="caribbean", country="cuba", region="la_havane", city="",
        dish="side", prep=10, cook=15,
        desc="Rondelles de plantain vert frites deux fois, écrasées entre les deux cuissons pour rester "
             "croustillantes, servies avec un mojo d'ail et de citron vert.",
        texture=("croustillant",), taste=("ail", "acidule"),
        compo=[
            ("plantain_banana_raw", 700, "g", "carbohydrate"),
            ("garlic_raw", 25, "g", "aromatic"),
            ("lime_juice_fresh", 40, "ml", "condiment"),
            ("olive_oil_plant", 30, "ml", "fat"),
            ("sunflower_oil_plant", 60, "ml", "fat"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Éplucher 700 g de plantains verts et les couper en rondelles de 2 cm.",
            "Les frire dans l'huile de tournesol à 160°C, 4 minutes, jusqu'à ce qu'elles soient tendres sans colorer, puis les égoutter.",
            "Les écraser entre deux feuilles de papier cuisson pour obtenir des galettes de 1 cm.",
            "Les frire une seconde fois à 190°C, 3 minutes, jusqu'à ce qu'elles soient dorées et croustillantes (environ 60 ml d'huile absorbée), puis les saler avec 3 g de sel.",
            "Mojo : piler 25 g d'ail avec 1 g de sel, puis ajouter 40 ml de jus de citron vert, 30 ml d'huile d'olive et 10 g de coriandre.",
            "Servir les tostones chauds avec le mojo.",
        ]),
    recipe(
        rid="brkf_cachapa_fromage_4a2c85", fr="Cachapa au fromage frais",
        en="Cachapa with Fresh Cheese",
        cuisine="latin_american", country="venezuela", region="caracas", city="",
        dish="breakfast", prep=15, cook=15,
        desc="Crêpe épaisse de maïs frais vénézuélienne, légèrement sucrée, pliée sur du fromage frais qui "
             "fond à la chaleur.",
        texture=("moelleux",), taste=("doux", "fromage"),
        compo=[
            ("sweet_corn_raw_fresh", 600, "g", "carbohydrate"),
            ("queso_fresco_block_cow", 200, "g", "protein"),
            ("corn_flour_seed", 60, "g", "carbohydrate"),
            ("milk_liquid_uht_3_5pct", 80, "ml", "liquid"),
            ("white_sugar", 15, "g", "sweetener"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Mixer 600 g de grains de maïs avec 80 ml de lait, 60 g de farine de maïs, 15 g de sucre et 3 g de sel, jusqu'à obtenir une pâte épaisse et granuleuse.",
            "Chauffer une poêle antiadhésive avec un peu de beurre (30 g en tout).",
            "Verser une louche de pâte et l'étaler en galette de 1 cm, puis cuire 4 minutes de chaque côté à feu moyen.",
            "Déposer 50 g de fromage frais sur une moitié, replier et laisser fondre 1 minute.",
            "Répéter pour les quatre cachapas et servir chaud.",
        ]),
    recipe(
        rid="rice_moros_y_cristianos_6c83d1", fr="Moros y cristianos, riz aux haricots noirs cubain",
        en="Moros y Cristianos, Cuban Rice and Black Beans",
        cuisine="caribbean", country="cuba", region="la_havane", city="la_havane",
        dish="main", prep=15, cook=35,
        desc="Riz cubain cuit avec les haricots noirs et leur jus, dans un sofrito d'oignon, poivron, ail, "
             "cumin et laurier, jusqu'à prendre une couleur sombre.",
        texture=("moelleux",), taste=("umami", "cumin"),
        compo=[
            ("white_rice_raw_seed_unenriched", 320, "g", "carbohydrate"),
            ("black_bean_boiled", 400, "g", "plant_protein", "cooked"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("green_bell_pepper_raw", 150, "g", "vegetable"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("oregano_spice_dried", 2, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("white_vinegar_liquid_distilled", 15, "ml", "condiment"),
            ("olive_oil_plant", 40, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 650, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 180 g d'oignon et 150 g de poivron vert en dés dans 40 ml d'huile d'olive, 8 minutes.",
            "Ajouter 15 g d'ail, 4 g de cumin, 2 g d'origan et 1 g de laurier, puis cuire 1 minute.",
            "Ajouter 320 g de riz rincé et le nacrer 2 minutes.",
            "Ajouter 400 g de haricots noirs avec leur jus, 650 ml d'eau, 8 g de bouillon déshydraté, 15 ml de vinaigre et 3 g de sel.",
            "Couvrir et cuire 20 minutes à feu très doux, puis laisser reposer 10 minutes et égrener.",
        ]),
    recipe(
        rid="soup_ajiaco_legumes_8e40b6", fr="Ajiaco de légumes aux trois pommes de terre",
        en="Vegetable Ajiaco with Three Potatoes",
        cuisine="colombian", country="colombia", region="bogota", city="bogota",
        dish="soup", prep=20, cook=45,
        desc="Soupe épaisse de Bogotá : trois sortes de pommes de terre dont une se défait pour lier le "
             "bouillon, maïs en épis, coriandre et câpres, servie avec de la crème et de l'avocat.",
        texture=("nappant",), taste=("doux", "herbe"),
        compo=[
            ("potato_raw_flesh", 600, "g", "carbohydrate"),
            ("potato_raw_with_skin", 300, "g", "carbohydrate"),
            ("sweet_corn_on_the_cob_cooked", 300, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("coriander_raw_fresh_herb", 25, "g", "herb"),
            ("capers_canned_in_vinegar", 20, "g", "condiment"),
            ("sour_cream_fermented_18pct", 100, "g", "garnish"),
            ("avocado_raw", 150, "g", "garnish"),
            ("olive_oil_plant", 25, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 1400, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire suer 150 g d'oignon et 12 g d'ail hachés dans 25 ml d'huile d'olive, 6 minutes.",
            "Ajouter 1,4 L d'eau, 8 g de bouillon déshydraté et 600 g de pommes de terre en fines rondelles, puis cuire 25 minutes : elles doivent se défaire et épaissir le bouillon.",
            "Ajouter 300 g de pommes de terre en cubes et 300 g de maïs en tronçons, puis cuire 15 minutes.",
            "Saler avec 3 g de sel et ajouter 20 g de câpres et 15 g de coriandre.",
            "Servir avec 100 g de crème, 150 g d'avocat et le reste de coriandre.",
        ]),
]
