"""Lot 5 de nouvelles recettes : Amérique du Nord (États-Unis, Sud, Québec).

19 plats seulement sur 635 au recomptage du 2026-09-22.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="bread_cornbread_5f81a2", fr="Cornbread au babeurre",
        en="Buttermilk Cornbread",
        cuisine="american", country="united_states", region="sud", city="",
        dish="bread", servings=8, prep=10, cook=25,
        desc="Pain de maïs du Sud cuit dans une poêle en fonte brûlante : mie dense et humide, croûte dorée "
             "au beurre, à peine sucré.",
        texture=("moelleux", "croustillant"), taste=("cereale", "beurre"),
        compo=[
            ("cornmeal_whole_dried", 250, "g", "carbohydrate"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 100, "g", "carbohydrate"),
            ("buttermilk_1pct", 350, "ml", "liquid"),
            ("egg_raw", 110, "g", "binder"),
            ("butter_sup80pct", 60, "g", "fat"),
            ("white_sugar", 20, "g", "sweetener"),
            ("baking_powder", 10, "g", "leavening"),
            ("baking_soda_powder", 3, "g", "leavening"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Préchauffer le four à 220°C avec une poêle en fonte à l'intérieur.",
            "Mélanger 250 g de semoule de maïs, 100 g de farine, 10 g de poudre à lever, 3 g de bicarbonate, 20 g de sucre et 4 g de sel.",
            "Fouetter 350 ml de babeurre avec 2 œufs (110 g) et 40 g de beurre fondu, puis les incorporer aux poudres sans trop travailler.",
            "Faire fondre 20 g de beurre dans la poêle brûlante, verser la pâte : elle doit grésiller.",
            "Cuire 25 minutes, jusqu'à ce qu'une lame ressorte sèche, puis laisser tiédir 10 minutes avant de couper en parts.",
        ]),
    recipe(
        rid="side_succotash_7c40d8", fr="Succotash de maïs et haricots de Lima",
        en="Corn and Lima Bean Succotash",
        cuisine="american", country="united_states", region="sud", city="",
        dish="side", prep=10, cook=15,
        desc="Plat d'origine amérindienne : maïs et haricots de Lima sautés au beurre avec poivron et oignon, "
             "finis à la ciboulette et au citron.",
        texture=("croquant",), taste=("doux", "beurre"),
        compo=[
            ("sweet_corn_raw_fresh", 400, "g", "vegetable"),
            ("lima_bean_boiled_canned", 300, "g", "plant_protein", "cooked"),
            ("red_bell_pepper_raw", 150, "g", "vegetable"),
            ("onion_raw", 120, "g", "aromatic_base"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("chives_raw_fresh", 15, "g", "herb"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 120 g d'oignon et 150 g de poivron en dés dans 30 g de beurre, 6 minutes.",
            "Ajouter 400 g de grains de maïs et sauter 5 minutes à feu vif.",
            "Ajouter 300 g de haricots de Lima égouttés, 2 g de sel et 1 g de poivre, puis réchauffer 3 minutes.",
            "Hors du feu, ajouter 20 ml de jus de citron et 15 g de ciboulette ciselée.",
        ]),
    recipe(
        rid="soup_corn_chowder_3b95e1", fr="Corn chowder à la pomme de terre",
        en="Potato Corn Chowder",
        cuisine="american", country="united_states", region="nouvelle_angleterre", city="",
        dish="soup", prep=15, cook=25,
        desc="Soupe crémeuse de Nouvelle-Angleterre : maïs et pommes de terre mijotés au lait et au thym, "
             "une partie mixée pour épaissir, servie avec de la ciboulette.",
        texture=("cremeux",), taste=("doux", "beurre"),
        compo=[
            ("sweet_corn_raw_fresh", 450, "g", "vegetable"),
            ("potato_raw_flesh", 400, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("celery_stalk_raw", 80, "g", "vegetable"),
            ("milk_liquid_uht_3_5pct", 400, "ml", "liquid"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 20, "g", "thickener"),
            ("thyme_dried_herb", 1, "g", "herb"),
            ("chives_raw_fresh", 15, "g", "herb"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 600, "ml", "liquid"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire fondre 30 g de beurre et y suer 150 g d'oignon et 80 g de céleri en dés, 6 minutes.",
            "Saupoudrer de 20 g de farine et remuer 1 minute, puis verser 600 ml d'eau et 8 g de bouillon déshydraté.",
            "Ajouter 400 g de pommes de terre en cubes et 1 g de thym, puis cuire 15 minutes.",
            "Ajouter 450 g de maïs et 400 ml de lait, puis mijoter 5 minutes sans bouillir.",
            "Mixer un tiers de la soupe et la reverser, saler avec 2 g de sel et poivrer.",
            "Servir avec 15 g de ciboulette ciselée.",
        ]),
    recipe(
        rid="main_black_bean_burger_9d27c4", fr="Burger de haricots noirs et maïs",
        en="Black Bean and Corn Burger",
        cuisine="american", country="united_states", region="", city="",
        dish="main", prep=20, rest=30, cook=15, spice=1,
        desc="Steak végétal de haricots noirs écrasés, maïs et flocons d'avoine, relevé au cumin et au "
             "paprika fumé, doré à la poêle et servi en pain avec crudités.",
        texture=("moelleux", "croustillant"), taste=("fume", "legumineuse"),
        compo=[
            ("black_bean_boiled", 450, "g", "plant_protein", "cooked"),
            ("sweet_corn_canned", 150, "g", "vegetable"),
            ("oat_flakes_whole_seed", 80, "g", "binder"),
            ("onion_raw", 120, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("paprika_powder", 3, "g", "spice"),
            ("hot_dog_bun_pre_packaged", 240, "g", "carbohydrate"),
            ("tomato_raw_ripe", 150, "g", "vegetable"),
            ("lettuce", 80, "g", "vegetable"),
            ("base_mayonnaise_0d3e4e", 40, "g", "sauce"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Égoutter 450 g de haricots noirs et les écraser grossièrement à la fourchette.",
            "Faire revenir 120 g d'oignon haché et 9 g d'ail dans 10 ml d'huile, 5 minutes, puis les ajouter aux haricots avec 150 g de maïs, 80 g de flocons d'avoine, 3 g de cumin, 3 g de paprika fumé et 3 g de sel.",
            "Former 4 galettes épaisses et les réfrigérer 30 minutes pour qu'elles se tiennent.",
            "Les cuire dans 20 ml d'huile, 5 minutes de chaque côté, jusqu'à ce qu'une croûte se forme.",
            "Garnir les pains (240 g) de mayonnaise, laitue, tomate et galette, puis servir aussitôt.",
        ]),
    recipe(
        rid="main_sloppy_joe_lentilles_6e13f7", fr="Sloppy joe de lentilles",
        en="Lentil Sloppy Joes",
        cuisine="american", country="united_states", region="", city="",
        dish="main", prep=15, cook=35,
        desc="Le sandwich américain revisité : lentilles mijotées en sauce tomate sucrée-acidulée à la "
             "moutarde et à la mélasse, servies débordant d'un pain moelleux.",
        texture=("nappant",), taste=("sucre", "acidule"),
        compo=[
            ("green_lentil_dried", 200, "g", "plant_protein", "dried"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("red_bell_pepper_raw", 150, "g", "vegetable"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("tomato_paste_unsalted_canned", 60, "g", "ingredient"),
            ("tomato_crushed_canned", 300, "g", "ingredient"),
            ("molasses", 20, "g", "sweetener"),
            ("mustard", 15, "g", "condiment"),
            ("white_vinegar_liquid_distilled", 20, "ml", "condiment"),
            ("paprika_powder", 3, "g", "spice"),
            ("hot_dog_bun_pre_packaged", 240, "g", "carbohydrate"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("water", 600, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 180 g d'oignon et 150 g de poivron en petits dés dans 25 ml d'huile, 8 minutes, puis ajouter 9 g d'ail.",
            "Ajouter 60 g de concentré de tomate et 3 g de paprika, puis cuire 2 minutes.",
            "Ajouter 200 g de lentilles rincées, 300 g de tomates concassées, 600 ml d'eau et 3 g de sel.",
            "Mijoter 30 minutes, jusqu'à ce que les lentilles soient tendres et la sauce épaisse.",
            "Ajouter 20 g de mélasse, 15 g de moutarde et 20 ml de vinaigre, puis cuire 3 minutes.",
            "Garnir les pains (240 g) de préparation bien chaude et servir.",
        ]),
    recipe(
        rid="rice_jambalaya_vegetarien_2a71d6", fr="Jambalaya végétarien aux haricots rouges",
        en="Vegetarian Red Bean Jambalaya",
        cuisine="creole", country="united_states", region="louisiane", city="new_orleans",
        dish="main", prep=20, cook=40, spice=2, kid_friendly=False,
        desc="Riz de Louisiane cuit dans son bouillon avec la trinité céleri-poivron-oignon, haricots rouges, "
             "tomate et épices cajun.",
        texture=("moelleux",), taste=("epice", "fume"),
        compo=[
            ("white_rice_raw_seed_unenriched", 320, "g", "carbohydrate"),
            ("kidney_bean_boiled", 400, "g", "plant_protein", "cooked"),
            ("celery_stalk_raw", 120, "g", "vegetable"),
            ("green_bell_pepper_raw", 200, "g", "vegetable"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("tomato_crushed_canned", 400, "g", "ingredient"),
            ("paprika_powder", 6, "g", "spice"),
            ("thyme_dried_herb", 2, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("red_hot_chili_pepper_spice_dried", 3, "g", "spice"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("sunflower_oil_plant", 35, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 650, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 180 g d'oignon, 120 g de céleri et 200 g de poivron en dés dans 35 ml d'huile, 8 minutes.",
            "Ajouter 12 g d'ail, 6 g de paprika fumé, 2 g de thym, 1 g de laurier et 3 g de piment, puis cuire 2 minutes.",
            "Ajouter 400 g de tomates concassées et cuire 5 minutes.",
            "Ajouter 320 g de riz, 650 ml d'eau, 8 g de bouillon déshydraté et 2 g de sel, puis porter à ébullition.",
            "Couvrir et cuire 20 minutes à feu très doux, puis ajouter 400 g de haricots rouges et laisser reposer 10 minutes.",
            "Égrener à la fourchette et parsemer de 40 g d'oignons verts.",
        ]),
    recipe(
        rid="soup_gumbo_z_herbes_8c52b3", fr="Gumbo z'herbes aux légumes verts",
        en="Gumbo z'Herbes with Greens",
        cuisine="creole", country="united_states", region="louisiane", city="new_orleans",
        dish="soup", prep=20, cook=50, spice=2, kid_friendly=False,
        desc="Le gumbo de Carême, sans viande : roux brun à l'huile, sept verdures (chou cavalier, épinards, "
             "chou, navet) longuement mijotées avec gombos et épices cajun.",
        texture=("nappant",), taste=("vegetal", "epice"),
        compo=[
            ("collard_raw", 300, "g", "vegetable"),
            ("spinach_raw_mature", 250, "g", "vegetable"),
            ("green_cabbage_raw", 200, "g", "vegetable"),
            ("turnip_raw", 150, "g", "vegetable"),
            ("okra_raw", 200, "g", "vegetable"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("celery_stalk_raw", 100, "g", "vegetable"),
            ("green_bell_pepper_raw", 150, "g", "vegetable"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 40, "g", "thickener"),
            ("sunflower_oil_plant", 50, "ml", "fat"),
            ("paprika_powder", 5, "g", "spice"),
            ("thyme_dried_herb", 2, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("red_hot_chili_pepper_spice_dried", 3, "g", "spice"),
            ("vegetable_stock_dried", 10, "g", "ingredient"),
            ("water", 1400, "ml", "liquid"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Faire un roux brun : cuire 40 g de farine dans 50 ml d'huile, 10 minutes à feu moyen en remuant sans arrêt, jusqu'à une couleur de chocolat au lait.",
            "Ajouter 180 g d'oignon, 100 g de céleri et 150 g de poivron hachés, puis cuire 6 minutes.",
            "Ajouter 15 g d'ail, 5 g de paprika, 2 g de thym, 1 g de laurier et 3 g de piment.",
            "Verser 1,4 L d'eau et 10 g de bouillon déshydraté, puis ajouter 300 g de chou cavalier, 200 g de chou, 150 g de navet et 200 g de gombos.",
            "Mijoter 30 minutes, puis ajouter 250 g d'épinards et cuire 5 minutes.",
            "Servir sur du riz blanc.",
        ]),
    recipe(
        rid="main_hoppin_john_4d80a9", fr="Hoppin' John, riz et doliques du Sud",
        en="Hoppin' John, Southern Rice and Cowpeas",
        cuisine="american", country="united_states", region="caroline_du_sud", city="",
        dish="main", prep=15, cook=40, spice=1,
        desc="Plat du Nouvel An dans le Sud : doliques à œil noir et riz cuits ensemble avec céleri, poivron "
             "et paprika fumé, servis avec des oignons verts et du vinaigre.",
        texture=("moelleux",), taste=("fume", "legumineuse"),
        compo=[
            ("black_eyed_peas_cowpeas_boiled", 450, "g", "plant_protein", "cooked"),
            ("white_rice_raw_seed_unenriched", 300, "g", "carbohydrate"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("celery_stalk_raw", 100, "g", "vegetable"),
            ("green_bell_pepper_raw", 150, "g", "vegetable"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("paprika_powder", 5, "g", "spice"),
            ("thyme_dried_herb", 1, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("white_vinegar_liquid_distilled", 15, "ml", "condiment"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 620, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire revenir 150 g d'oignon, 100 g de céleri et 150 g de poivron en dés dans 30 ml d'huile, 8 minutes.",
            "Ajouter 12 g d'ail, 5 g de paprika fumé, 1 g de thym et 1 g de laurier.",
            "Ajouter 300 g de riz, 620 ml d'eau, 8 g de bouillon déshydraté et 2 g de sel, puis porter à ébullition.",
            "Couvrir et cuire 18 minutes à feu très doux, puis ajouter 450 g de doliques et laisser reposer 10 minutes.",
            "Arroser de 15 ml de vinaigre, parsemer de 40 g d'oignons verts et servir.",
        ]),
    recipe(
        rid="side_coleslaw_maison_7f21c8", fr="Coleslaw au chou blanc et à la carotte",
        en="Classic Cabbage and Carrot Coleslaw",
        cuisine="american", country="united_states", region="", city="",
        dish="side", prep=15, rest=30, cook=0,
        desc="Salade de chou américaine : chou blanc et carotte râpés, sauce crémeuse à la mayonnaise, "
             "vinaigre de cidre et graines de céleri, reposée pour s'attendrir.",
        texture=("croquant",), taste=("acidule", "doux"),
        compo=[
            ("white_cabbage_raw", 600, "g", "vegetable"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("red_onion_raw", 60, "g", "aromatic"),
            ("base_mayonnaise_0d3e4e", 120, "g", "sauce"),
            ("cider_vinegar_liquid", 30, "ml", "condiment"),
            ("white_sugar", 15, "g", "sweetener"),
            ("mustard", 10, "g", "condiment"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Râper 600 g de chou blanc et 200 g de carotte, émincer 60 g d'oignon rouge.",
            "Saler avec 3 g de sel et laisser dégorger 15 minutes, puis presser légèrement.",
            "Mélanger 120 g de mayonnaise, 30 ml de vinaigre de cidre, 15 g de sucre, 10 g de moutarde et 1 g de poivre.",
            "Mélanger les légumes à la sauce et réfrigérer 30 minutes avant de servir.",
        ]),
    recipe(
        rid="side_baked_beans_melasse_5c93e7", fr="Baked beans à la mélasse",
        en="Molasses Baked Beans",
        cuisine="american", country="united_states", region="nouvelle_angleterre", city="boston",
        dish="side", prep=15, rest=480, cook=120,
        desc="Haricots blancs de Boston cuits très longuement au four dans une sauce mélasse-moutarde, "
             "jusqu'à devenir fondants et sirupeux.",
        texture=("fondant",), taste=("sucre", "fume"),
        compo=[
            ("white_bean_raw", 350, "g", "plant_protein", "dried"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("molasses", 60, "g", "sweetener"),
            ("tomato_paste_unsalted_canned", 40, "g", "ingredient"),
            ("mustard", 15, "g", "condiment"),
            ("paprika_powder", 3, "g", "spice"),
            ("cider_vinegar_liquid", 20, "ml", "condiment"),
            ("olive_oil_plant", 25, "ml", "fat"),
            ("water", 1200, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 350 g de haricots blancs 8 heures, puis les égoutter.",
            "Les cuire 45 minutes dans 1,2 L d'eau, jusqu'à ce qu'ils soient presque tendres. Garder l'eau de cuisson.",
            "Préchauffer le four à 150°C. Faire revenir 180 g d'oignon dans 25 ml d'huile, 8 minutes.",
            "Mélanger les haricots, l'oignon, 60 g de mélasse, 40 g de concentré de tomate, 15 g de moutarde, 3 g de paprika fumé, 3 g de sel et 500 ml d'eau de cuisson dans une cocotte.",
            "Couvrir et cuire 1 heure 15 au four, en ajoutant un peu d'eau si nécessaire.",
            "Ajouter 20 ml de vinaigre de cidre avant de servir.",
        ]),
    recipe(
        rid="snack_chou_fleur_buffalo_9a48d5", fr="Chou-fleur buffalo pané au four",
        en="Baked Buffalo Cauliflower",
        cuisine="american", country="united_states", region="new_york", city="",
        dish="snack", prep=15, cook=30, spice=2, kid_friendly=False,
        desc="Bouquets de chou-fleur panés et rôtis, enrobés d'une sauce piquante au beurre et au vinaigre, "
             "à tremper dans une sauce au yaourt et à la ciboulette.",
        texture=("croustillant",), taste=("epice", "acidule"),
        compo=[
            ("cauliflower_raw_flower", 700, "g", "vegetable"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 100, "g", "carbohydrate"),
            ("milk_liquid_uht_3_5pct", 150, "ml", "liquid"),
            ("paprika_powder", 4, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 4, "g", "spice"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("white_vinegar_liquid_distilled", 25, "ml", "condiment"),
            ("yogurt_greek_plain_4pct", 150, "g", "sauce"),
            ("chives_raw_fresh", 15, "g", "herb"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Préchauffer le four à 220°C. Fouetter 100 g de farine, 150 ml de lait, 4 g de paprika et 2 g de sel en pâte fluide.",
            "Enrober 700 g de bouquets de chou-fleur de pâte, les étaler sur une plaque huilée (25 ml) et rôtir 20 minutes.",
            "Sauce piquante : faire fondre 30 g de beurre avec 4 g de piment, 25 ml de vinaigre et 1 g de sel.",
            "Napper le chou-fleur de sauce et remettre 10 minutes au four.",
            "Mélanger 150 g de yaourt grec et 15 g de ciboulette, et servir en trempette.",
        ]),
    recipe(
        rid="brkf_grits_cheddar_3e60f4", fr="Grits au cheddar",
        en="Cheddar Grits",
        cuisine="american", country="united_states", region="sud", city="",
        dish="breakfast", prep=5, cook=25,
        desc="Bouillie de maïs du Sud cuite lentement dans le lait, montée au beurre et au cheddar, "
             "servie avec du poivre et de la ciboulette.",
        texture=("cremeux",), taste=("fromage", "cereale"),
        compo=[
            ("cornmeal_whole_dried", 200, "g", "carbohydrate"),
            ("milk_liquid_uht_3_5pct", 500, "ml", "liquid"),
            ("cheddar", 120, "g", "protein"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("chives_raw_fresh", 15, "g", "herb"),
            ("black_pepper_spice", 2, "g", "spice"),
            ("water", 500, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Porter 500 ml d'eau et 500 ml de lait à frémissement avec 3 g de sel.",
            "Verser 200 g de semoule de maïs en pluie en fouettant.",
            "Cuire 20 minutes à feu très doux en remuant souvent, jusqu'à ce que les grits soient crémeux.",
            "Hors du feu, incorporer 30 g de beurre et 120 g de cheddar râpé.",
            "Poivrer avec 2 g de poivre et parsemer de 15 g de ciboulette.",
        ]),
    recipe(
        rid="brkf_biscuits_gravy_vegetarien_6b74a1", fr="Biscuits et sauce blanche aux champignons",
        en="Biscuits and Mushroom White Gravy",
        cuisine="american", country="united_states", region="sud", city="",
        dish="breakfast", prep=20, cook=25,
        desc="Petits pains au babeurre très feuilletés, fendus et noyés dans une sauce blanche aux "
             "champignons et au poivre, comme dans les diners du Sud.",
        texture=("feuillete", "nappant"), taste=("beurre", "poivre"),
        compo=[
            ("wheat_all_purpose_flour_unenriched_unbleached", 350, "g", "carbohydrate"),
            ("butter_sup80pct", 100, "g", "fat"),
            ("buttermilk_1pct", 200, "ml", "liquid"),
            ("baking_powder", 12, "g", "leavening"),
            ("button_mushroom_raw", 300, "g", "vegetable"),
            ("milk_liquid_uht_3_5pct", 400, "ml", "sauce"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("black_pepper_spice", 4, "g", "spice"),
            ("thyme_dried_herb", 1, "g", "herb"),
            ("sunflower_oil_plant", 15, "ml", "fat"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Préchauffer le four à 220°C. Sabler 300 g de farine, 12 g de poudre à lever et 3 g de sel avec 80 g de beurre très froid.",
            "Ajouter 200 ml de babeurre, rassembler la pâte sans la pétrir, l'aplatir et la plier trois fois.",
            "Découper 8 pains de 5 cm et les cuire 15 minutes, jusqu'à ce qu'ils soient dorés et levés.",
            "Sauce : faire revenir 100 g d'oignon et 300 g de champignons hachés dans 20 g de beurre et 15 ml d'huile, 8 minutes.",
            "Saupoudrer de 50 g de farine, remuer 1 minute, puis verser 400 ml de lait et cuire 5 minutes jusqu'à épaississement. Assaisonner de 4 g de poivre, 1 g de thym et 2 g de sel.",
            "Fendre les pains et les napper de sauce brûlante.",
        ]),
    recipe(
        rid="brkf_burrito_dejeuner_8d05c2", fr="Burrito du matin aux œufs brouillés et haricots",
        en="Breakfast Burrito with Scrambled Eggs and Beans",
        cuisine="american", country="united_states", region="californie", city="",
        dish="breakfast", prep=15, cook=15, spice=1,
        desc="Grande tortilla roulée serrée sur des œufs brouillés, des haricots noirs épicés, des pommes de "
             "terre sautées, du cheddar et de l'avocat.",
        texture=("moelleux",), taste=("epice", "fromage"),
        compo=[
            ("base_tortilla_92c2a6", 320, "g", "carbohydrate"),
            ("egg_raw", 220, "g", "protein"),
            ("black_bean_boiled", 250, "g", "plant_protein", "cooked"),
            ("potato_raw_flesh", 300, "g", "vegetable"),
            ("cheddar", 100, "g", "protein"),
            ("avocado_raw", 150, "g", "fruit"),
            ("onion_raw", 100, "g", "aromatic_base"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("paprika_powder", 3, "g", "spice"),
            ("sunflower_oil_plant", 35, "ml", "fat"),
            ("coriander_raw_fresh_herb", 10, "g", "herb"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Couper 300 g de pommes de terre en petits dés et les sauter dans 20 ml d'huile, 10 minutes, avec 100 g d'oignon, 3 g de paprika et 2 g de sel.",
            "Réchauffer 250 g de haricots noirs avec 3 g de cumin et les écraser grossièrement.",
            "Brouiller 4 œufs (220 g) dans 15 ml d'huile, 2 minutes, en les gardant crémeux.",
            "Réchauffer les tortillas (320 g) 30 secondes par face.",
            "Garnir chaque tortilla de pommes de terre, haricots, œufs, 100 g de cheddar râpé, avocat et coriandre, puis rouler serré en repliant les côtés.",
        ]),
    recipe(
        rid="dessert_pumpkin_pie_4f85b0", fr="Tarte au potiron et aux épices",
        en="Spiced Pumpkin Pie",
        cuisine="american", country="united_states", region="", city="",
        dish="dessert", servings=8, prep=20, rest=30, cook=55,
        desc="La tarte de Thanksgiving : purée de potiron rôtie mêlée d'œufs, de lait concentré, de cannelle, "
             "de gingembre et de muscade, sur une pâte brisée.",
        texture=("fondant",), taste=("sucre", "epice"),
        compo=[
            ("shortcrust_pastry_all_butter_raw_paste_pre_packaged", 250, "g", "carbohydrate"),
            ("pumpkin_raw", 900, "g", "fruit"),
            ("condensed_milk_concentrated_sweetened_canned_whole", 250, "g", "sauce"),
            ("egg_raw", 165, "g", "binder"),
            ("brown_sugar", 60, "g", "sweetener"),
            ("cinnamon", 4, "g", "spice"),
            ("ginger_raw_root_fresh", 8, "g", "spice"),
            ("nutmeg_spice", 1, "g", "spice"),
            ("cloves", 0.5, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Préchauffer le four à 200°C. Couper 900 g de potiron en morceaux et les rôtir 35 minutes, puis les mixer en purée lisse et laisser tiédir.",
            "Foncer un moule de 26 cm avec 250 g de pâte brisée et le réfrigérer 30 minutes.",
            "Mélanger 600 g de purée de potiron avec 250 g de lait concentré sucré, 3 œufs (165 g), 60 g de sucre roux, 4 g de cannelle, 8 g de gingembre râpé, 1 g de muscade, 0,5 g de girofle et 2 g de sel.",
            "Verser sur la pâte et cuire 20 minutes à 200°C, puis baisser à 170°C et poursuivre 35 minutes : le centre doit encore trembler légèrement.",
            "Laisser refroidir complètement avant de trancher.",
        ]),
    recipe(
        rid="dessert_pecan_pie_7a29e6", fr="Tarte aux noix de pécan et sirop d'érable",
        en="Maple Pecan Pie",
        cuisine="american", country="united_states", region="sud", city="",
        dish="dessert", servings=8, prep=20, cook=45,
        desc="Tarte du Sud au caramel de sirop d'érable et de sucre roux, garnie de noix de pécan entières "
             "qui forment une croûte craquante.",
        texture=("croquant", "fondant"), taste=("sucre", "noisette"),
        compo=[
            ("shortcrust_pastry_all_butter_raw_paste_pre_packaged", 250, "g", "carbohydrate"),
            ("pecans_nuts_raw", 200, "g", "ingredient"),
            ("maple_syrup", 180, "ml", "sweetener"),
            ("brown_sugar", 80, "g", "sweetener"),
            ("egg_raw", 165, "g", "binder"),
            ("butter_sup80pct", 60, "g", "fat"),
            ("vanilla_extract", 5, "ml", "aromatic"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Préchauffer le four à 180°C et foncer un moule de 24 cm avec 250 g de pâte brisée.",
            "Faire fondre 60 g de beurre, puis le mélanger avec 180 ml de sirop d'érable, 80 g de sucre roux, 5 ml de vanille et 2 g de sel.",
            "Ajouter 3 œufs (165 g) battus, sans faire mousser.",
            "Répartir 200 g de noix de pécan sur le fond de tarte et verser l'appareil dessus.",
            "Cuire 45 minutes, jusqu'à ce que la garniture soit prise sur les bords et encore souple au centre.",
            "Laisser refroidir complètement : la tarte prend en refroidissant.",
        ]),
    recipe(
        rid="dessert_key_lime_pie_2c47d9", fr="Tarte au citron vert de Floride",
        en="Florida Key Lime Pie",
        cuisine="american", country="united_states", region="floride", city="",
        dish="dessert", servings=8, prep=20, rest=180, cook=20,
        desc="Crème très acidulée de jus de citron vert et de lait concentré sucré, prise à la cuisson sur "
             "une pâte sablée, servie bien froide.",
        texture=("cremeux",), taste=("acidule", "sucre"),
        compo=[
            ("shortcrust_pastry_all_butter_raw_paste_pre_packaged", 250, "g", "carbohydrate"),
            ("condensed_milk_concentrated_sweetened_canned_whole", 400, "g", "sauce"),
            ("lime_juice_fresh", 150, "ml", "condiment"),
            ("egg_raw", 110, "g", "binder"),
            ("cream_heavy_refrigerated_30pct", 150, "ml", "garnish"),
            ("white_sugar", 20, "g", "sweetener"),
        ],
        steps=[
            "Préchauffer le four à 180°C, foncer un moule de 24 cm avec 250 g de pâte et la précuire 12 minutes.",
            "Fouetter 400 g de lait concentré sucré avec 2 jaunes d'œufs (110 g au total) et 150 ml de jus de citron vert : la crème épaissit.",
            "Verser sur le fond précuit et cuire 8 minutes, juste pour la prendre.",
            "Réfrigérer au moins 3 heures.",
            "Fouetter 150 ml de crème avec 20 g de sucre et en garnir la tarte avant de servir.",
        ]),
    recipe(
        rid="soup_soupe_aux_pois_quebecoise_5d39a7", fr="Soupe aux pois cassés québécoise",
        en="Quebec Split Pea Soup",
        cuisine="canadian", country="canada", region="quebec", city="",
        dish="soup", prep=15, rest=480, cook=75,
        desc="La soupe d'hiver du Québec, ici sans lard : pois cassés jaunes fondus avec carotte, céleri, "
             "oignon et sarriette, épaisse à tenir la cuillère.",
        texture=("nappant",), taste=("legumineuse", "herbe"),
        compo=[
            ("split_peas_dried", 350, "g", "plant_protein", "dried"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("celery_stalk_raw", 120, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("thyme_dried_herb", 2, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("olive_oil_plant", 30, "ml", "fat"),
            ("vegetable_stock_dried", 10, "g", "ingredient"),
            ("water", 1800, "ml", "liquid"),
            ("black_pepper_spice", 2, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 350 g de pois cassés 8 heures, puis les égoutter.",
            "Faire suer 200 g d'oignon, 200 g de carotte et 120 g de céleri en dés dans 30 ml d'huile, 8 minutes, puis ajouter 9 g d'ail.",
            "Ajouter les pois, 1,8 L d'eau, 10 g de bouillon déshydraté, 2 g de thym et 1 g de laurier.",
            "Mijoter 1 heure 10 à feu doux, en remuant de temps en temps, jusqu'à ce que les pois se défassent.",
            "Saler avec 2 g de sel, poivrer avec 2 g de poivre et servir très chaud.",
        ]),
    recipe(
        rid="dessert_tarte_au_sucre_9b18e3", fr="Tarte au sucre du Québec",
        en="Quebec Sugar Pie",
        cuisine="canadian", country="canada", region="quebec", city="",
        dish="dessert", servings=8, prep=15, cook=35,
        desc="Tarte québécoise très simple : cassonade et crème cuites sur une pâte brisée jusqu'à former "
             "un caramel à peine pris, à manger tiède.",
        texture=("fondant",), taste=("sucre", "caramel"),
        compo=[
            ("shortcrust_pastry_all_butter_raw_paste_pre_packaged", 250, "g", "carbohydrate"),
            ("brown_sugar", 250, "g", "sweetener"),
            ("cream_heavy_refrigerated_30pct", 200, "ml", "sauce"),
            ("butter_sup80pct", 40, "g", "fat"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 20, "g", "thickener"),
            ("vanilla_extract", 5, "ml", "aromatic"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Préchauffer le four à 190°C et foncer un moule de 24 cm avec 250 g de pâte brisée.",
            "Mélanger 250 g de cassonade avec 20 g de farine et 1 g de sel.",
            "Ajouter 200 ml de crème, 40 g de beurre fondu et 5 ml de vanille, puis fouetter.",
            "Verser sur la pâte et cuire 35 minutes : le centre doit encore trembler.",
            "Laisser tiédir au moins 30 minutes avant de servir, la garniture prend en refroidissant.",
        ]),
]
