"""Lot 6 de nouvelles recettes : Europe de l'Est et Caucase.

Pologne, Hongrie, Tchéquie, Roumanie, Bulgarie, Russie, Géorgie.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="soup_zurek_vegetarien_7d41c9", fr="Żurek végétarien au levain de seigle",
        en="Vegetarian Żurek, Polish Sour Rye Soup",
        cuisine="polish", country="poland", region="masovia", city="",
        dish="soup", prep=15, rest=4320, cook=35,
        desc="La soupe aigre polonaise : un levain de farine de seigle fermenté trois jours donne son acidité "
             "au bouillon de légumes, avec pommes de terre, champignons, marjolaine et œuf dur.",
        texture=("nappant",), taste=("acidule", "herbe"),
        compo=[
            ("rye_flour", 100, "g", "ingredient"),
            ("potato_raw_flesh", 400, "g", "vegetable"),
            ("button_mushroom_raw", 250, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("marjoram_spice_dried", 3, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("allspice_powder", 1, "g", "spice"),
            ("egg_raw", 220, "g", "protein"),
            ("cream_heavy_refrigerated_18pct", 100, "ml", "sauce"),
            ("sunflower_oil_plant", 25, "ml", "fat"),
            ("vegetable_stock_dried", 10, "g", "ingredient"),
            ("water", 1500, "ml", "liquid"),
            ("black_pepper_spice", 2, "g", "spice"),
        ],
        steps=[
            "Levain : mélanger 100 g de farine de seigle et 300 ml d'eau tiède dans un bocal, couvrir d'un linge et laisser fermenter 3 jours à température ambiante, en remuant chaque jour.",
            "Faire revenir 150 g d'oignon et 250 g de champignons émincés dans 25 ml d'huile, 8 minutes.",
            "Ajouter 1,2 L d'eau, 10 g de bouillon déshydraté, 400 g de pommes de terre en cubes, 1 g de laurier et 1 g de piment de la Jamaïque, puis cuire 20 minutes.",
            "Cuire 4 œufs (220 g) 9 minutes, les refroidir et les écaler.",
            "Verser le levain filtré dans la soupe, ajouter 15 g d'ail pilé et 3 g de marjolaine, puis chauffer 5 minutes sans bouillir.",
            "Incorporer 100 ml de crème hors du feu, poivrer avec 2 g de poivre et servir avec un demi-œuf par assiette.",
        ]),
    recipe(
        rid="side_kopytka_4b28e5", fr="Kopytka, gnocchi de pomme de terre polonais",
        en="Kopytka, Polish Potato Dumplings",
        cuisine="polish", country="poland", region="masovia", city="",
        dish="side", prep=25, cook=25,
        desc="« Petits sabots » de pomme de terre et de farine, pochés puis dorés au beurre avec de la "
             "chapelure, servis en accompagnement des plats en sauce.",
        texture=("moelleux",), taste=("beurre", "cereale"),
        compo=[
            ("potato_raw_flesh", 800, "g", "carbohydrate"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 200, "g", "binding"),
            ("egg_raw", 55, "g", "binder"),
            ("butter_sup80pct", 40, "g", "fat"),
            ("breadcrumbs_dried", 30, "g", "garnish"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Cuire 800 g de pommes de terre à l'eau salée 25 minutes, les éplucher chaudes et les passer au presse-purée.",
            "Ajouter 200 g de farine, 1 œuf (55 g) et 2 g de sel, puis travailler juste assez pour former une pâte souple.",
            "Rouler en boudins de 2 cm et couper des losanges de 2 cm.",
            "Les pocher dans l'eau bouillante salée : ils sont cuits 1 minute après avoir remonté.",
            "Dorer 30 g de chapelure dans 40 g de beurre et y rouler les kopytka avant de servir.",
        ]),
    recipe(
        rid="side_mizeria_concombre_9e73b1", fr="Mizeria, salade de concombre à la crème",
        en="Mizeria, Polish Cucumber Cream Salad",
        cuisine="polish", country="poland", region="masovia", city="",
        dish="side", prep=15, rest=20, cook=0,
        desc="Salade polonaise très simple : concombre en fines rondelles dégorgé, crème aigre, aneth et un "
             "trait de vinaigre, servie bien froide.",
        texture=("croquant",), taste=("acidule", "frais"),
        compo=[
            ("cucumber_raw_with_skin", 700, "g", "vegetable"),
            ("sour_cream_fermented_18pct", 150, "g", "sauce"),
            ("dill_weed_fresh_herb_leaf", 15, "g", "herb"),
            ("white_vinegar_liquid_distilled", 15, "ml", "condiment"),
            ("white_sugar", 5, "g", "sweetener"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Tailler 700 g de concombre en rondelles très fines, les saler avec 3 g de sel et laisser dégorger 20 minutes.",
            "Les presser doucement pour retirer l'eau.",
            "Mélanger 150 g de crème aigre avec 15 ml de vinaigre, 5 g de sucre, 1 g de poivre et 1 g de sel.",
            "Mélanger au concombre avec 15 g d'aneth ciselé et servir frais.",
        ]),
    recipe(
        rid="side_buraczki_betteraves_2c56f8", fr="Buraczki, betteraves râpées à la polonaise",
        en="Buraczki, Polish Grated Beetroot",
        cuisine="polish", country="poland", region="masovia", city="",
        dish="side", prep=15, cook=30,
        desc="Betteraves cuites puis râpées et réchauffées au beurre avec un peu de farine, de citron et de "
             "sucre : l'accompagnement aigre-doux des plats polonais.",
        texture=("fondant",), taste=("sucre", "acidule"),
        compo=[
            ("beetroot_raw_root", 700, "g", "vegetable"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 15, "g", "thickener"),
            ("lemon_juice", 25, "ml", "condiment"),
            ("white_sugar", 10, "g", "sweetener"),
            ("caraway_spice_seed", 2, "g", "spice"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Cuire 700 g de betteraves entières 30 minutes à l'eau bouillante, puis les peler et les râper.",
            "Faire fondre 30 g de beurre, ajouter 15 g de farine et remuer 1 minute.",
            "Ajouter les betteraves râpées, 2 g de carvi, 3 g de sel et 1 g de poivre, puis réchauffer 5 minutes.",
            "Terminer avec 25 ml de jus de citron et 10 g de sucre, et servir chaud.",
        ]),
    recipe(
        rid="main_paprikas_krumpli_6f19a4", fr="Paprikás krumpli, pommes de terre au paprika",
        en="Paprikás Krumpli, Hungarian Paprika Potatoes",
        cuisine="hungarian", country="hungary", region="pest", city="",
        dish="main", prep=15, cook=35, spice=1,
        desc="Ragoût hongrois de pommes de terre : beaucoup d'oignon fondu, paprika doux hors du feu, "
             "poivrons et tomates, une sauce rouge qui nappe les pommes de terre.",
        texture=("fondant", "nappant"), taste=("paprika", "doux"),
        compo=[
            ("potato_raw_flesh", 900, "g", "carbohydrate"),
            ("onion_raw", 300, "g", "aromatic_base"),
            ("red_bell_pepper_raw", 200, "g", "vegetable"),
            ("tomato_raw_ripe", 250, "g", "fruit"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("paprika_powder", 8, "g", "spice"),
            ("caraway_spice_seed", 2, "g", "spice"),
            ("sour_cream_fermented_18pct", 100, "g", "sauce"),
            ("sunflower_oil_plant", 35, "ml", "fat"),
            ("vegetable_stock_dried", 8, "g", "ingredient"),
            ("water", 700, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Faire fondre 300 g d'oignon émincé dans 35 ml d'huile, 12 minutes à feu doux, jusqu'à ce qu'il soit translucide et sucré.",
            "Hors du feu, ajouter 8 g de paprika, 12 g d'ail haché et 2 g de carvi, puis remuer.",
            "Ajouter 200 g de poivron en lanières, 250 g de tomates concassées et 900 g de pommes de terre en gros cubes.",
            "Verser 700 ml d'eau avec 8 g de bouillon déshydraté et 3 g de sel, puis mijoter 25 minutes à couvert.",
            "Écraser quelques pommes de terre pour lier la sauce, ajouter 100 g de crème aigre hors du feu et servir.",
        ]),
    recipe(
        rid="dessert_palacsinta_5a82d7", fr="Palacsinta au fromage blanc et aux raisins",
        en="Palacsinta, Hungarian Crêpes with Sweet Cheese",
        cuisine="hungarian", country="hungary", region="pest", city="budapest",
        dish="dessert", servings=6, prep=20, rest=30, cook=25,
        desc="Crêpes hongroises fines roulées sur un mélange de fromage blanc sucré, de zeste de citron et de "
             "raisins secs, gratinées quelques minutes et saupoudrées de sucre.",
        texture=("moelleux",), taste=("sucre", "citron"),
        compo=[
            ("wheat_all_purpose_flour_unenriched_unbleached", 200, "g", "carbohydrate"),
            ("milk_liquid_uht_3_5pct", 400, "ml", "liquid"),
            ("egg_raw", 165, "g", "binder"),
            ("cottage_cheese_4pct_cow", 400, "g", "protein"),
            ("grape_dried", 60, "g", "ingredient"),
            ("white_sugar", 70, "g", "sweetener"),
            ("lemon_peel_raw", 6, "g", "aromatic"),
            ("butter_sup80pct", 40, "g", "fat"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Fouetter 200 g de farine, 3 œufs (165 g), 400 ml de lait et 2 g de sel, puis laisser reposer 30 minutes.",
            "Cuire 8 crêpes fines dans une poêle beurrée (40 g de beurre en tout).",
            "Mélanger 400 g de fromage blanc égoutté avec 50 g de sucre, 6 g de zeste de citron et 60 g de raisins secs.",
            "Garnir chaque crêpe, la rouler et la ranger dans un plat beurré.",
            "Passer 8 minutes à 200°C, saupoudrer de 20 g de sucre et servir tiède.",
        ]),
    recipe(
        rid="entry_korozott_3e94b2", fr="Körözött, tartinade de fromage au paprika",
        en="Körözött, Hungarian Paprika Cheese Spread",
        cuisine="hungarian", country="hungary", region="pest", city="",
        dish="starter", prep=10, rest=30, cook=0,
        desc="Tartinade hongroise : fromage blanc écrasé au beurre, paprika, oignon et carvi, servie bien "
             "froide avec du pain de seigle.",
        texture=("cremeux",), taste=("paprika", "fromage"),
        compo=[
            ("cottage_cheese_4pct_cow", 400, "g", "protein"),
            ("butter_sup80pct", 60, "g", "fat"),
            ("paprika_powder", 6, "g", "spice"),
            ("onion_raw", 60, "g", "aromatic"),
            ("caraway_spice_seed", 2, "g", "spice"),
            ("chives_raw_fresh", 15, "g", "herb"),
            ("rye_bread", 200, "g", "carbohydrate"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Laisser 60 g de beurre ramollir, puis le travailler en pommade.",
            "Écraser 400 g de fromage blanc bien égoutté à la fourchette et l'incorporer au beurre.",
            "Ajouter 6 g de paprika, 60 g d'oignon très finement haché, 2 g de carvi moulu et 3 g de sel.",
            "Réfrigérer 30 minutes, parsemer de 15 g de ciboulette et servir avec 200 g de pain de seigle.",
        ]),
    recipe(
        rid="soup_bramborova_polevka_8c41d6", fr="Bramborová polévka, soupe tchèque aux champignons",
        en="Bramborová Polévka, Czech Potato and Mushroom Soup",
        cuisine="czech", country="czechia", region="boheme", city="prague",
        dish="soup", prep=15, cook=30,
        desc="Soupe bohémienne épaisse : pommes de terre, champignons séchés réhydratés, racines et "
             "marjolaine, liée d'un roux léger.",
        texture=("nappant",), taste=("champignon", "herbe"),
        compo=[
            ("potato_raw_flesh", 600, "g", "vegetable"),
            ("porcini_mushroom_raw", 150, "g", "vegetable"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("celeriac_raw", 120, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 25, "g", "thickener"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("marjoram_spice_dried", 2, "g", "herb"),
            ("bay_leaf", 1, "g", "aromatic"),
            ("vegetable_stock_dried", 10, "g", "ingredient"),
            ("water", 1400, "ml", "liquid"),
            ("parsley_fresh_herb", 10, "g", "herb"),
            ("black_pepper_spice", 2, "g", "spice"),
        ],
        steps=[
            "Faire revenir 150 g d'oignon dans 30 g de beurre, 5 minutes, puis ajouter 150 g de cèpes émincés et cuire 5 minutes.",
            "Saupoudrer de 25 g de farine et remuer 1 minute.",
            "Verser 1,4 L d'eau avec 10 g de bouillon déshydraté, puis ajouter 600 g de pommes de terre, 150 g de carotte et 120 g de céleri-rave en cubes, 1 g de laurier et 9 g d'ail.",
            "Mijoter 20 minutes, jusqu'à ce que les légumes soient tendres.",
            "Ajouter 2 g de marjolaine et 2 g de poivre, puis servir avec 10 g de persil.",
        ]),
    recipe(
        rid="side_knedliky_7b53c2", fr="Knedlíky, quenelles de pain tchèques",
        en="Knedlíky, Czech Bread Dumplings",
        cuisine="czech", country="czechia", region="boheme", city="",
        dish="side", servings=6, prep=20, rest=60, cook=25,
        desc="Grosses quenelles cuites à l'eau, à la mie de pain et à la farine, tranchées au fil pour "
             "accompagner les plats en sauce.",
        texture=("moelleux",), taste=("cereale",),
        compo=[
            ("wheat_all_purpose_flour_unenriched_unbleached", 400, "g", "carbohydrate"),
            ("white_bread_unsalted", 150, "g", "carbohydrate"),
            ("milk_liquid_uht_3_5pct", 250, "ml", "liquid"),
            ("egg_raw", 110, "g", "binder"),
            ("baking_powder", 8, "g", "leavening"),
            ("table_salt_unenriched", 6, "g", "seasoning"),
        ],
        steps=[
            "Couper 150 g de pain rassis en petits dés.",
            "Mélanger 400 g de farine, 8 g de poudre à lever et 6 g de sel, puis ajouter 2 œufs (110 g) et 250 ml de lait tiède.",
            "Travailler la pâte 5 minutes, incorporer les dés de pain et laisser reposer 1 heure.",
            "Former deux gros boudins et les pocher 25 minutes dans une grande casserole d'eau frémissante, en les retournant à mi-cuisson.",
            "Les trancher au fil ou avec un couteau à pain et servir chaud.",
        ]),
    recipe(
        rid="side_mamaliga_branza_4d67e8", fr="Mămăligă cu brânză, polenta roumaine au fromage",
        en="Mămăligă cu Brânză, Romanian Polenta with Cheese",
        cuisine="romanian", country="romania", region="moldavie", city="",
        dish="side", prep=5, cook=30,
        desc="La polenta roumaine, plus ferme que l'italienne, servie en parts avec de la brânză (fromage de "
             "brebis salé) émiettée et de la crème aigre.",
        texture=("ferme",), taste=("fromage", "cereale"),
        compo=[
            ("cornmeal_whole_dried", 250, "g", "carbohydrate"),
            ("feta", 150, "g", "protein"),
            ("sour_cream_fermented_18pct", 120, "g", "sauce"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("water", 1000, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Porter 1 L d'eau à ébullition avec 3 g de sel.",
            "Verser 250 g de semoule de maïs en pluie en fouettant.",
            "Cuire 25 minutes à feu doux en remuant régulièrement, jusqu'à ce que la mămăligă se détache des parois.",
            "Incorporer 30 g de beurre, puis la renverser sur une planche et la couper au fil.",
            "Servir avec 150 g de fromage de brebis émietté et 120 g de crème aigre.",
        ]),
    recipe(
        rid="main_sarmale_de_post_9f24b7", fr="Sarmale de post, choux farcis au riz",
        en="Sarmale de Post, Lenten Cabbage Rolls",
        cuisine="romanian", country="romania", region="transylvanie", city="",
        dish="main", prep=35, cook=90,
        desc="Feuilles de chou roulées sur une farce de riz, oignon, carotte et aneth, mijotées longuement "
             "dans un jus de tomate à l'huile : la version de jeûne, sans viande.",
        texture=("fondant",), taste=("acidule", "aneth"),
        compo=[
            ("green_cabbage_raw", 1000, "g", "vegetable"),
            ("white_rice_raw_seed_unenriched", 250, "g", "carbohydrate"),
            ("onion_raw", 250, "g", "aromatic_base"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("tomato_paste_unsalted_canned", 60, "g", "ingredient"),
            ("tomato_crushed_canned", 300, "g", "ingredient"),
            ("dill_weed_fresh_herb_leaf", 20, "g", "herb"),
            ("thyme_dried_herb", 1, "g", "herb"),
            ("bay_leaf", 2, "g", "aromatic"),
            ("sunflower_oil_plant", 45, "ml", "fat"),
            ("water", 700, "ml", "liquid"),
            ("black_pepper_spice", 2, "g", "spice"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Blanchir 1 kg de chou entier 10 minutes à l'eau bouillante, puis détacher les feuilles et retirer les côtes épaisses.",
            "Faire revenir 250 g d'oignon et 150 g de carotte râpée dans 30 ml d'huile, 8 minutes, puis ajouter 250 g de riz rincé, 30 g de concentré de tomate, 20 g d'aneth, 4 g de sel et 2 g de poivre.",
            "Déposer une cuillerée de farce sur chaque feuille et rouler en serrant, en rentrant les côtés.",
            "Ranger les rouleaux serrés dans une cocotte, ajouter 300 g de tomates concassées, 30 g de concentré, 2 g de laurier, 1 g de thym, 15 ml d'huile et 700 ml d'eau.",
            "Couvrir et cuire 1 heure 20 à feu très doux, jusqu'à ce que le chou soit fondant et le riz cuit.",
            "Laisser reposer 15 minutes avant de servir.",
        ]),
    recipe(
        rid="soup_tarator_bulgare_2b78f5", fr="Tarator, soupe froide bulgare au yaourt",
        en="Tarator, Bulgarian Cold Yogurt Soup",
        cuisine="bulgarian", country="bulgaria", region="sofia", city="",
        dish="soup", prep=15, rest=60, cook=0,
        desc="Soupe froide d'été : yaourt battu à l'eau glacée, concombre râpé, ail, aneth et noix concassées, "
             "un filet d'huile pour finir.",
        texture=("liquide",), taste=("acidule", "frais"),
        compo=[
            ("yogurt_plain_3pct", 600, "g", "protein"),
            ("cucumber_raw_with_skin", 500, "g", "vegetable"),
            ("garlic_raw", 10, "g", "aromatic"),
            ("walnut_shelled_dried", 60, "g", "garnish"),
            ("dill_weed_fresh_herb_leaf", 20, "g", "herb"),
            ("olive_oil_plant", 30, "ml", "fat"),
            ("water", 300, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Battre 600 g de yaourt avec 300 ml d'eau glacée jusqu'à obtenir une texture fluide.",
            "Râper ou couper 500 g de concombre en très petits dés et l'ajouter au yaourt.",
            "Piler 10 g d'ail avec 3 g de sel et l'incorporer, puis ajouter 20 g d'aneth ciselé.",
            "Réfrigérer 1 heure.",
            "Servir très froid avec 60 g de noix concassées et un filet d'huile d'olive (30 ml).",
        ]),
    recipe(
        rid="main_banitsa_fromage_6c92a3", fr="Banitsa au fromage et au yaourt",
        en="Banitsa, Bulgarian Cheese Filo Pie",
        cuisine="bulgarian", country="bulgaria", region="sofia", city="sofia",
        dish="main", prep=25, cook=45,
        desc="Feuilleté bulgare en spirale : pâte filo badigeonnée de beurre, garnie de fromage de brebis "
             "battu aux œufs et au yaourt, cuite jusqu'à être dorée et croustillante.",
        texture=("croustillant",), taste=("fromage", "beurre"),
        compo=[
            ("phyllo_filo_pastry_raw_paste", 400, "g", "carbohydrate"),
            ("feta", 250, "g", "protein"),
            ("egg_raw", 165, "g", "binder"),
            ("yogurt_plain_3pct", 250, "g", "sauce"),
            ("butter_sup80pct", 80, "g", "fat"),
            ("baking_soda_powder", 2, "g", "leavening"),
            ("black_pepper_spice", 1, "g", "spice"),
        ],
        steps=[
            "Préchauffer le four à 190°C. Écraser 250 g de fromage de brebis à la fourchette.",
            "Fouetter 3 œufs (165 g) avec 250 g de yaourt, 2 g de bicarbonate et 1 g de poivre, puis mélanger au fromage.",
            "Faire fondre 80 g de beurre. Badigeonner une feuille de filo, la garnir d'une bande de farce et la rouler en boudin.",
            "Enrouler les boudins en spirale dans un moule rond, en continuant jusqu'à épuisement (400 g de filo).",
            "Badigeonner du beurre restant et cuire 45 minutes, jusqu'à ce que la banitsa soit dorée.",
            "Laisser reposer 10 minutes avant de couper.",
        ]),
    recipe(
        rid="soup_okrochka_5e17d4", fr="Okrochka, soupe froide russe au kéfir",
        en="Okroshka, Russian Cold Kefir Soup",
        cuisine="russian", country="russia", region="moscou", city="moscou",
        dish="soup", prep=20, rest=60, cook=15,
        desc="Soupe froide russe : kéfir allongé d'eau, pommes de terre et œufs durs en dés, concombre, "
             "radis et beaucoup d'aneth, avec une pointe de moutarde.",
        texture=("liquide",), taste=("acidule", "frais"),
        compo=[
            ("kefir_fermented", 700, "ml", "liquid"),
            ("potato_raw_flesh", 300, "g", "vegetable"),
            ("egg_raw", 220, "g", "protein"),
            ("cucumber_raw_with_skin", 250, "g", "vegetable"),
            ("black_radish_raw", 150, "g", "vegetable"),
            ("green_onion_raw", 60, "g", "garnish"),
            ("dill_weed_fresh_herb_leaf", 20, "g", "herb"),
            ("mustard", 10, "g", "condiment"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("water", 200, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Cuire 300 g de pommes de terre en cubes 12 minutes et 4 œufs (220 g) 9 minutes, puis les refroidir.",
            "Couper les pommes de terre, les œufs, 250 g de concombre et 150 g de radis noir en petits dés.",
            "Battre 700 ml de kéfir avec 200 ml d'eau froide, 10 g de moutarde, 20 ml de jus de citron et 3 g de sel.",
            "Ajouter les dés, 60 g d'oignons verts et 20 g d'aneth.",
            "Réfrigérer 1 heure et servir très froid.",
        ]),
    recipe(
        rid="salad_olivier_vegetarienne_8d35c7", fr="Salade Olivier végétarienne",
        en="Vegetarian Olivier Salad",
        cuisine="russian", country="russia", region="moscou", city="",
        dish="starter", prep=25, rest=60, cook=20,
        desc="La salade des fêtes russes : pommes de terre, carottes et petits pois en dés, œufs durs et "
             "cornichons, liés à la mayonnaise et à l'aneth.",
        texture=("fondant",), taste=("acidule", "doux"),
        compo=[
            ("potato_raw_flesh", 400, "g", "vegetable"),
            ("carrot_raw", 250, "g", "vegetable"),
            ("green_peas_raw", 200, "g", "vegetable"),
            ("egg_raw", 220, "g", "protein"),
            ("pickles_cucumber_canned_in_vinegar", 150, "g", "condiment"),
            ("base_mayonnaise_0d3e4e", 100, "g", "sauce"),
            ("dill_weed_fresh_herb_leaf", 15, "g", "herb"),
            ("onion_raw", 60, "g", "aromatic"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Cuire 400 g de pommes de terre et 250 g de carottes entières 20 minutes à l'eau salée, puis les refroidir et les couper en petits dés.",
            "Cuire 4 œufs (220 g) 9 minutes, les écaler et les couper en dés.",
            "Blanchir 200 g de petits pois 3 minutes. Couper 150 g de cornichons en dés et émincer 60 g d'oignon.",
            "Mélanger tous les éléments avec 100 g de mayonnaise, 15 g d'aneth, 3 g de sel et 1 g de poivre.",
            "Réfrigérer 1 heure avant de servir.",
        ]),
    recipe(
        rid="side_kacha_sarrasin_champignons_3a86e2", fr="Kacha de sarrasin aux champignons",
        en="Buckwheat Kasha with Mushrooms",
        cuisine="russian", country="russia", region="moscou", city="",
        dish="side", prep=10, cook=25,
        desc="Gruau de sarrasin grillé cuit par absorption, mêlé d'oignons et de champignons dorés au beurre : "
             "l'accompagnement russe le plus courant.",
        texture=("grain_separe",), taste=("champignon", "noisette"),
        compo=[
            ("buckwheat_groats_roasted_dried_dry", 250, "g", "carbohydrate"),
            ("button_mushroom_raw", 300, "g", "vegetable"),
            ("onion_raw", 180, "g", "aromatic_base"),
            ("butter_sup80pct", 40, "g", "fat"),
            ("parsley_fresh_herb", 15, "g", "herb"),
            ("water", 500, "ml", "liquid"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Rincer 250 g de gruau de sarrasin et le cuire dans 500 ml d'eau salée avec 3 g de sel, 15 minutes à couvert, puis laisser reposer 5 minutes.",
            "Faire dorer 180 g d'oignon émincé dans 20 g de beurre, 8 minutes.",
            "Ajouter 300 g de champignons émincés et cuire 8 minutes à feu vif, jusqu'à évaporation de l'eau.",
            "Mélanger au sarrasin avec 20 g de beurre, 1 g de sel et 1 g de poivre.",
            "Parsemer de 15 g de persil et servir.",
        ]),
    recipe(
        rid="brkf_syrniki_7c48b9", fr="Syrniki, galettes de fromage blanc",
        en="Syrniki, Farmer's Cheese Pancakes",
        cuisine="ukrainian", country="ukraine", region="kyiv", city="",
        dish="breakfast", prep=15, cook=15,
        desc="Petites galettes moelleuses de fromage blanc égoutté et de semoule, dorées à la poêle et "
             "servies avec de la crème aigre et de la confiture.",
        texture=("moelleux",), taste=("fromage", "sucre"),
        compo=[
            ("cottage_cheese_4pct_cow", 500, "g", "protein"),
            ("egg_raw", 110, "g", "binder"),
            ("wheat_semolina_raw", 60, "g", "carbohydrate"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 40, "g", "carbohydrate"),
            ("white_sugar", 40, "g", "sweetener"),
            ("vanilla_extract", 5, "ml", "aromatic"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("sour_cream_fermented_18pct", 120, "g", "sauce"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Écraser 500 g de fromage blanc bien égoutté avec 2 œufs (110 g), 40 g de sucre, 5 ml de vanille et 2 g de sel.",
            "Ajouter 60 g de semoule fine et laisser reposer 10 minutes, le temps qu'elle gonfle.",
            "Former 12 galettes de 2 cm d'épaisseur et les fariner légèrement (40 g de farine).",
            "Les dorer dans 30 g de beurre, 3 minutes de chaque côté à feu moyen.",
            "Servir chaud avec 120 g de crème aigre.",
        ]),
    recipe(
        rid="entry_badrijani_nigvzit_9b62d1", fr="Badrijani nigvzit, aubergines géorgiennes aux noix",
        en="Badrijani Nigvzit, Georgian Eggplant Walnut Rolls",
        cuisine="georgian", country="georgia", region="tbilissi", city="tbilissi",
        dish="starter", prep=20, cook=15,
        desc="Tranches d'aubergine frites roulées sur une pâte de noix pilées à l'ail, au vinaigre et aux "
             "épices géorgiennes, parsemées de grains de grenade.",
        texture=("fondant",), taste=("noisette", "ail"),
        compo=[
            ("eggplant_raw", 700, "g", "vegetable"),
            ("walnut_shelled_dried", 150, "g", "plant_protein"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("coriander_spice_seed", 3, "g", "spice"),
            ("fenugreek_spice_seed", 2, "g", "spice"),
            ("white_vinegar_liquid_distilled", 25, "ml", "condiment"),
            ("pomegranate_raw", 80, "g", "garnish"),
            ("coriander_raw_fresh_herb", 20, "g", "herb"),
            ("sunflower_oil_plant", 35, "ml", "fat"),
            ("water", 80, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Couper 700 g d'aubergines en tranches de 8 mm dans la longueur, les saler légèrement et les laisser 10 minutes, puis les éponger.",
            "Les dorer dans 35 ml d'huile, 3 minutes par face, et les égoutter sur du papier absorbant.",
            "Mixer 150 g de cerneaux de noix avec 15 g d'ail, 3 g de coriandre moulue, 2 g de fenugrec, 25 ml de vinaigre, 80 ml d'eau et 2 g de sel, jusqu'à obtenir une pâte tartinable.",
            "Étaler la pâte sur chaque tranche et la rouler.",
            "Parsemer de 80 g de grains de grenade et de 20 g de coriandre, et servir à température ambiante.",
        ]),
    recipe(
        rid="side_ghomi_fromage_4e29a8", fr="Ghomi au fromage, polenta géorgienne",
        en="Ghomi with Cheese, Georgian Cornmeal Porridge",
        cuisine="georgian", country="georgia", region="samegrelo", city="",
        dish="side", prep=5, cook=30,
        desc="Bouillie de maïs géorgienne, sans sel ni beurre, dans laquelle on enfouit des morceaux de "
             "fromage frais qui filent à la chaleur.",
        texture=("ferme", "filant"), taste=("fromage", "cereale"),
        compo=[
            ("cornmeal_whole_dried", 250, "g", "carbohydrate"),
            ("cows_milk_mozzarella_cow", 250, "g", "protein"),
            ("water", 1000, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Porter 1 L d'eau à ébullition avec 2 g de sel.",
            "Verser 250 g de semoule de maïs en pluie en fouettant.",
            "Cuire 25 minutes à feu doux en remuant souvent, jusqu'à obtenir une bouillie très épaisse.",
            "Répartir dans les assiettes et enfouir 250 g de fromage en morceaux au centre, pour qu'il fonde.",
            "Servir aussitôt, avec un plat en sauce.",
        ]),
]
