"""Lot 7 de nouvelles recettes : desserts, snacks, boissons, recettes crues et sans gluten.

Au recomptage du 2026-09-22 : 43 desserts, 24 snacks, 8 boissons et 4 recettes crues seulement.
"""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="dessert_basbousa_5c19f7", fr="Basbousa, gâteau de semoule au sirop",
        en="Basbousa, Semolina Cake in Syrup",
        cuisine="egyptian", country="egypt", region="le_caire", city="",
        dish="dessert", servings=8, prep=15, rest=20, cook=35,
        desc="Gâteau égyptien de semoule et de noix de coco, cuit en plaque puis imbibé brûlant d'un sirop "
             "au citron et à la fleur d'oranger, décoré d'amandes.",
        texture=("moelleux", "granuleux"), taste=("sucre", "coco"),
        compo=[
            ("wheat_semolina_raw", 300, "g", "carbohydrate"),
            ("coconut_flesh_dried", 80, "g", "ingredient"),
            ("yogurt_plain_3pct", 200, "g", "liquid"),
            ("butter_sup80pct", 100, "g", "fat"),
            ("white_sugar", 220, "g", "sweetener"),
            ("baking_powder", 8, "g", "leavening"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("orange_blossom_water", 10, "g", "aromatic"),
            ("almond_raw_with_skin_unsalted", 50, "g", "garnish"),
            ("water", 200, "ml", "liquid"),
        ],
        steps=[
            "Préchauffer le four à 180°C. Mélanger 300 g de semoule, 80 g de noix de coco râpée, 80 g de sucre et 8 g de poudre à lever.",
            "Ajouter 200 g de yaourt et 80 g de beurre fondu, puis laisser reposer 20 minutes.",
            "Étaler dans un plat beurré, marquer les parts au couteau et poser une amande sur chacune (50 g).",
            "Cuire 35 minutes, jusqu'à ce que le dessus soit bien doré.",
            "Sirop : porter 140 g de sucre et 200 ml d'eau à ébullition 5 minutes, puis ajouter 20 ml de jus de citron et 10 g d'eau de fleur d'oranger.",
            "Verser le sirop chaud sur le gâteau chaud et laisser absorber avant de servir.",
        ]),
    recipe(
        rid="dessert_daifuku_haricots_rouges_8a37c2", fr="Daifuku à la pâte de haricots rouges",
        en="Daifuku with Red Bean Paste",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="dessert", servings=8, prep=25, cook=10,
        desc="Petits mochi japonais : pâte de riz gluant cuite à la vapeur, souple et élastique, roulée "
             "autour d'une boule de pâte de haricots rouges sucrée.",
        texture=("elastique", "moelleux"), taste=("sucre",),
        compo=[
            ("white_glutinous_rice_flour", 200, "g", "carbohydrate"),
            ("red_bean_paste", 250, "g", "ingredient"),
            ("white_sugar", 50, "g", "sweetener"),
            ("cornstarch_flour", 40, "g", "ingredient"),
            ("water", 260, "ml", "liquid"),
        ],
        steps=[
            "Mélanger 200 g de farine de riz gluant, 50 g de sucre et 260 ml d'eau en une pâte lisse.",
            "Couvrir et cuire 8 minutes à la vapeur, en remuant à mi-cuisson : la pâte devient translucide et très collante.",
            "Former 8 boules de 30 g avec 250 g de pâte de haricots rouges.",
            "Étaler la pâte de riz sur un plan généreusement saupoudré de 40 g de fécule, puis découper 8 disques.",
            "Envelopper chaque boule de haricots dans un disque, souder par-dessous et rouler légèrement dans la fécule.",
        ]),
    recipe(
        rid="dessert_churros_chocolat_3f82b6", fr="Churros et chocolat chaud épais",
        en="Churros with Thick Hot Chocolate",
        cuisine="spanish", country="spain", region="madrid", city="madrid",
        dish="dessert", servings=6, prep=20, cook=20,
        desc="Pâte à choux sans œufs poussée à la douille cannelée et frite, roulée dans le sucre et la "
             "cannelle, servie avec un chocolat chaud épais à tremper.",
        texture=("croustillant",), taste=("sucre", "chocolat"),
        compo=[
            ("wheat_all_purpose_flour_unenriched_unbleached", 250, "g", "carbohydrate"),
            ("water", 500, "ml", "liquid"),
            ("sunflower_oil_plant", 70, "ml", "fat"),
            ("white_sugar", 60, "g", "sweetener"),
            ("cinnamon", 3, "g", "spice"),
            ("dark_chocolate_40_cocoa_baking_tablet", 150, "g", "ingredient"),
            ("milk_liquid_uht_3_5pct", 400, "ml", "liquid"),
            ("cornstarch_flour", 10, "g", "thickener"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Porter 400 ml d'eau à ébullition avec 3 g de sel, puis verser 250 g de farine d'un coup et remuer vivement jusqu'à ce que la pâte se détache.",
            "Laisser tiédir 10 minutes, puis mettre la pâte en poche à douille cannelée.",
            "Chauffer l'huile à 180°C et y pousser des bandes de pâte de 12 cm, coupées aux ciseaux, 3 minutes par face (environ 70 ml d'huile absorbée).",
            "Égoutter et rouler dans 40 g de sucre mélangé à 3 g de cannelle.",
            "Chocolat : faire fondre 150 g de chocolat dans 400 ml de lait chaud avec 20 g de sucre et 10 g de fécule délayée dans 100 ml d'eau, puis cuire 3 minutes jusqu'à épaississement.",
            "Servir les churros brûlants avec le chocolat.",
        ]),
    recipe(
        rid="dessert_alfajores_dulce_de_leche_7b41e9", fr="Alfajores au dulce de leche",
        en="Alfajores with Dulce de Leche",
        cuisine="argentinian", country="argentina", region="buenos_aires", city="",
        dish="dessert", servings=10, prep=30, rest=60, cook=90,
        desc="Biscuits argentins très friables à la fécule de maïs, collés deux par deux avec du dulce de "
             "leche obtenu en cuisant du lait concentré, puis roulés dans la noix de coco.",
        texture=("friable",), taste=("sucre", "caramel"),
        compo=[
            ("cornstarch_flour", 250, "g", "carbohydrate"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 150, "g", "carbohydrate"),
            ("butter_sup80pct", 150, "g", "fat"),
            ("egg_raw", 110, "g", "binder"),
            ("white_sugar", 80, "g", "sweetener"),
            ("condensed_milk_concentrated_sweetened_canned_whole", 400, "g", "ingredient"),
            ("coconut_flesh_dried", 60, "g", "garnish"),
            ("baking_powder", 8, "g", "leavening"),
            ("lemon_peel_raw", 5, "g", "aromatic"),
        ],
        steps=[
            "Dulce de leche : cuire la boîte de lait concentré sucré (400 g) immergée dans l'eau bouillante 1 heure 15, puis la laisser refroidir complètement avant d'ouvrir.",
            "Travailler 150 g de beurre avec 80 g de sucre, puis ajouter 2 jaunes d'œufs (110 g au total) et 5 g de zeste de citron.",
            "Incorporer 250 g de fécule, 150 g de farine et 8 g de poudre à lever, puis réfrigérer la pâte 1 heure.",
            "Préchauffer le four à 170°C. Étaler la pâte sur 8 mm, découper 20 disques de 5 cm et cuire 12 minutes : ils doivent rester pâles.",
            "Coller les biscuits deux par deux avec le dulce de leche et rouler les bords dans 60 g de noix de coco râpée.",
        ]),
    recipe(
        rid="dessert_brigadeiros_9d63a4", fr="Brigadeiros au chocolat",
        en="Brazilian Chocolate Brigadeiros",
        cuisine="brazilian", country="brazil", region="rio_de_janeiro", city="",
        dish="dessert", servings=10, prep=15, rest=60, cook=15,
        desc="Les truffes brésiliennes des anniversaires : lait concentré sucré et cacao cuits jusqu'à se "
             "détacher de la casserole, roulés en boules dans les vermicelles de chocolat.",
        texture=("fondant",), taste=("chocolat", "sucre"),
        compo=[
            ("condensed_milk_concentrated_sweetened_canned_whole", 400, "g", "ingredient"),
            ("cocoa_powder_unsweetened", 40, "g", "ingredient"),
            ("butter_sup80pct", 30, "g", "fat"),
            ("dark_chocolate_40_cocoa_baking_tablet", 60, "g", "garnish"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Mélanger 400 g de lait concentré sucré, 40 g de cacao tamisé, 20 g de beurre et 1 g de sel dans une casserole à fond épais.",
            "Cuire 12 minutes à feu moyen en remuant sans arrêt, jusqu'à ce que la masse se détache du fond en un seul bloc.",
            "Verser sur une assiette beurrée (10 g de beurre) et laisser refroidir 1 heure.",
            "Hacher 60 g de chocolat en petits éclats.",
            "Former 20 boules avec les mains beurrées et les rouler dans les éclats de chocolat.",
        ]),
    recipe(
        rid="snack_sigara_boregi_2e57d8", fr="Sigara böreği au fromage et à la menthe",
        en="Sigara Böreği, Cheese and Mint Filo Cigars",
        cuisine="turkish", country="turkey", region="istanbul", city="",
        dish="snack", servings=6, prep=20, cook=15,
        desc="Cigares de pâte filo farcis de fromage de brebis, persil et menthe, roulés serré puis frits "
             "jusqu'à être dorés et craquants.",
        texture=("croustillant",), taste=("fromage", "menthe"),
        compo=[
            ("phyllo_filo_pastry_raw_paste", 300, "g", "carbohydrate"),
            ("feta", 250, "g", "protein"),
            ("parsley_fresh_herb", 20, "g", "herb"),
            ("mint_fresh_herb", 10, "g", "herb"),
            ("egg_raw", 55, "g", "binder"),
            ("sunflower_oil_plant", 60, "ml", "fat"),
            ("black_pepper_spice", 1, "g", "spice"),
        ],
        steps=[
            "Écraser 250 g de fromage de brebis à la fourchette avec 20 g de persil, 10 g de menthe ciselée et 1 g de poivre.",
            "Couper 300 g de pâte filo en triangles.",
            "Déposer une cuillerée de farce sur la base, replier les côtés et rouler serré en cigare, en soudant le bord avec de l'œuf battu (55 g).",
            "Frire dans l'huile à 180°C, 2 minutes par face, jusqu'à ce qu'ils soient dorés (environ 60 ml d'huile absorbée).",
            "Égoutter sur du papier absorbant et servir chaud.",
        ]),
    recipe(
        rid="beverage_lassi_mangue_6c28f1", fr="Lassi à la mangue et à la cardamome",
        en="Mango Cardamom Lassi",
        cuisine="indian", country="india", region="punjab", city="",
        dish="beverage", prep=10, cook=0,
        desc="Boisson indienne fraîche : yaourt battu avec de la purée de mangue, un peu de sucre et de "
             "cardamome, servie très froide.",
        texture=("liquide",), taste=("sucre", "acidule"),
        compo=[
            ("yogurt_plain_3pct", 500, "g", "protein"),
            ("mango_raw", 400, "g", "fruit"),
            ("white_sugar", 30, "g", "sweetener"),
            ("cardamom", 1, "g", "spice"),
            ("water", 200, "ml", "liquid"),
        ],
        steps=[
            "Éplucher 400 g de mangue bien mûre et la mixer en purée lisse.",
            "Ajouter 500 g de yaourt, 30 g de sucre, 1 g de cardamome moulue et 200 ml d'eau glacée.",
            "Mixer 30 secondes, jusqu'à ce que le lassi soit mousseux.",
            "Servir aussitôt, très froid.",
        ]),
    recipe(
        rid="beverage_horchata_riz_4a91d3", fr="Horchata de riz à la cannelle",
        en="Rice Horchata with Cinnamon",
        cuisine="mexican", country="mexico", region="ciudad_de_mexico", city="",
        dish="beverage", prep=10, rest=480, cook=0,
        desc="Boisson mexicaine sans produit laitier : riz cru et cannelle trempés une nuit, mixés puis "
             "filtrés, sucrés et servis sur glace.",
        texture=("liquide",), taste=("cannelle", "sucre"),
        compo=[
            ("white_rice_raw_seed_unenriched", 200, "g", "carbohydrate"),
            ("cinnamon", 5, "g", "spice"),
            ("white_sugar", 80, "g", "sweetener"),
            ("almond_raw_skinless_unsalted", 60, "g", "ingredient"),
            ("vanilla_extract", 5, "ml", "aromatic"),
            ("water", 1400, "ml", "liquid"),
        ],
        steps=[
            "Faire tremper 200 g de riz, 60 g d'amandes et 5 g de cannelle dans 700 ml d'eau, une nuit au frais.",
            "Mixer longuement le tout avec son eau de trempage, jusqu'à ce que le riz soit finement broyé.",
            "Filtrer à travers un linge fin en pressant bien.",
            "Ajouter 700 ml d'eau, 80 g de sucre et 5 ml de vanille, puis mélanger.",
            "Servir très froid, sur des glaçons.",
        ]),
    recipe(
        rid="beverage_the_menthe_marocain_8f34b7", fr="Thé à la menthe marocain",
        en="Moroccan Mint Tea",
        cuisine="moroccan", country="morocco", region="marrakech", city="",
        dish="beverage", prep=5, cook=10,
        desc="Thé vert gunpowder rincé puis infusé avec une grosse poignée de menthe fraîche et du sucre, "
             "versé de haut pour le faire mousser.",
        texture=("liquide",), taste=("menthe", "sucre"),
        compo=[
            ("tea_leaf", 10, "g", "ingredient"),
            ("mint_fresh_herb", 40, "g", "herb"),
            ("white_sugar", 60, "g", "sweetener"),
            ("water", 1000, "ml", "liquid"),
        ],
        steps=[
            "Mettre 10 g de thé vert dans la théière, verser un verre d'eau bouillante, remuer et jeter cette première eau pour retirer l'amertume.",
            "Ajouter 40 g de menthe fraîche et 60 g de sucre.",
            "Verser 1 L d'eau bouillante et laisser infuser 4 minutes.",
            "Remplir un verre puis le reverser dans la théière, deux fois, pour mélanger.",
            "Servir en versant de haut, pour faire mousser le thé.",
        ]),
    recipe(
        rid="beverage_agua_fresca_pasteque_5b72c9", fr="Agua fresca de pastèque et citron vert",
        en="Watermelon Lime Agua Fresca",
        cuisine="mexican", country="mexico", region="ciudad_de_mexico", city="",
        dish="beverage", prep=10, cook=0, raw=True,
        desc="Boisson mexicaine d'été : chair de pastèque mixée et filtrée, relevée de citron vert et à "
             "peine sucrée, servie sur glace avec de la menthe.",
        texture=("liquide",), taste=("frais", "acidule"),
        compo=[
            ("watermelon_raw", 1200, "g", "fruit"),
            ("lime_juice_fresh", 50, "ml", "condiment"),
            ("white_sugar", 30, "g", "sweetener"),
            ("mint_fresh_herb", 15, "g", "herb"),
            ("water", 400, "ml", "liquid"),
        ],
        steps=[
            "Couper 1,2 kg de pastèque, retirer les pépins et mixer la chair.",
            "Filtrer à travers une passoire fine.",
            "Ajouter 400 ml d'eau froide, 50 ml de jus de citron vert et 30 g de sucre, puis mélanger.",
            "Servir sur glace avec 15 g de menthe fraîche.",
        ]),
    recipe(
        rid="side_kale_massee_avocat_3d18e7", fr="Salade de kale massée à l'avocat",
        en="Massaged Kale and Avocado Salad",
        cuisine="american", country="united_states", region="californie", city="",
        dish="side", prep=15, rest=10, cook=0, raw=True,
        desc="Salade crue : feuilles de kale massées à la main avec de l'avocat, du citron et du sel jusqu'à "
             "s'attendrir, avec graines de tournesol et tomates cerises.",
        texture=("tendre", "croquant"), taste=("citron", "vegetal"),
        compo=[
            ("kale_raw", 400, "g", "vegetable"),
            ("avocado_raw", 200, "g", "fruit"),
            ("lemon_juice", 40, "ml", "condiment"),
            ("olive_oil_extra_virgin_plant", 30, "ml", "fat"),
            ("sunflower_seed_dried", 40, "g", "garnish"),
            ("cherry_tomato_raw", 200, "g", "vegetable"),
            ("red_onion_raw", 60, "g", "aromatic"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Retirer les côtes de 400 g de kale et déchirer les feuilles en petits morceaux.",
            "Ajouter 200 g d'avocat, 40 ml de jus de citron, 20 ml d'huile d'olive et 3 g de sel, puis masser 3 minutes à la main : les feuilles foncent et s'assouplissent.",
            "Laisser reposer 10 minutes.",
            "Ajouter 200 g de tomates cerises coupées en deux, 60 g d'oignon rouge émincé, 40 g de graines de tournesol, 10 ml d'huile et 1 g de poivre.",
        ]),
    recipe(
        rid="snack_energy_balls_dattes_7e51a2", fr="Boules d'énergie dattes, noix et cacao",
        en="Date, Walnut and Cocoa Energy Balls",
        cuisine="international", country="international", region="world", city="",
        dish="snack", servings=8, prep=15, rest=30, cook=0, raw=True,
        desc="Bouchées crues sans cuisson : dattes mixées avec noix, flocons d'avoine et cacao, roulées en "
             "billes et raffermies au frais.",
        texture=("fondant",), taste=("sucre", "cacao"),
        compo=[
            ("date_with_skin_dried", 300, "g", "ingredient"),
            ("walnut_shelled_dried", 120, "g", "plant_protein"),
            ("oat_flakes_whole_seed", 80, "g", "carbohydrate"),
            ("cocoa_powder_unsweetened", 25, "g", "ingredient"),
            ("coconut_flesh_dried", 30, "g", "garnish"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Dénoyauter 300 g de dattes et les mixer avec 120 g de cerneaux de noix, jusqu'à obtenir une pâte collante.",
            "Ajouter 80 g de flocons d'avoine, 25 g de cacao et 1 g de sel, puis mixer par impulsions.",
            "Former 24 billes de 20 g.",
            "Les rouler dans 30 g de noix de coco râpée et les raffermir 30 minutes au frais.",
        ]),
    recipe(
        rid="entry_carpaccio_courgettes_citron_9a26d4", fr="Carpaccio de courgettes au citron et parmesan",
        en="Zucchini Carpaccio with Lemon and Parmesan",
        cuisine="italian", country="italy", region="lazio", city="", allow_similar=("carpaccio",),
        dish="starter", prep=15, rest=10, cook=0, raw=True,
        desc="Entrée crue : courgettes tranchées à la mandoline, marinées au citron et à l'huile d'olive, "
             "avec copeaux de parmesan, pignons et menthe.",
        texture=("croquant",), taste=("citron", "fromage"),
        compo=[
            ("green_zucchini_squash_raw", 600, "g", "vegetable"),
            ("lemon_juice", 40, "ml", "condiment"),
            ("lemon_peel_raw", 4, "g", "aromatic"),
            ("olive_oil_extra_virgin_plant", 40, "ml", "fat"),
            ("parmesan_grated_dried_cow", 60, "g", "protein"),
            ("pine_nuts_raw", 30, "g", "garnish"),
            ("mint_fresh_herb", 10, "g", "herb"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Tailler 600 g de courgettes en rubans très fins à la mandoline.",
            "Les mélanger avec 40 ml de jus de citron, 4 g de zeste, 30 ml d'huile d'olive, 2 g de sel et 1 g de poivre, puis laisser mariner 10 minutes.",
            "Torréfier 30 g de pignons à sec, 2 minutes.",
            "Dresser les rubans en rosace, parsemer de 60 g de parmesan en copeaux, des pignons et de 10 g de menthe.",
            "Arroser des 10 ml d'huile restants et servir aussitôt.",
        ]),
    recipe(
        rid="snack_edamame_sel_sesame_4c83b5", fr="Edamame au sel de sésame",
        en="Edamame with Sesame Salt",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="snack", prep=5, cook=8,
        desc="Gousses de soja vert cuites à l'eau salée, égouttées puis roulées dans un sel de sésame grillé : "
             "on presse la gousse pour manger les graines.",
        texture=("tendre",), taste=("umami", "sesame"),
        compo=[
            ("edamame_raw", 600, "g", "plant_protein"),
            ("sesame_seed_hulled_dried", 20, "g", "garnish"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
            ("water", 1500, "ml", "liquid"),
        ],
        steps=[
            "Porter 1,5 L d'eau à ébullition avec 3 g de sel.",
            "Y cuire 600 g de gousses d'edamame 6 minutes, jusqu'à ce qu'elles soient tendres.",
            "Les égoutter sans les rincer.",
            "Griller 20 g de graines de sésame à sec, les piler grossièrement avec 2 g de sel.",
            "Rouler les gousses encore chaudes dans ce sel de sésame et servir aussitôt.",
        ]),
    recipe(
        rid="snack_socca_nicoise_6b47d9", fr="Socca niçoise à la farine de pois chiches",
        en="Socca, Niçoise Chickpea Flour Pancake",
        cuisine="french_provencal", country="france", region="provence_alpes_cote_dazur", city="nice",
        dish="snack", prep=10, rest=60, cook=12,
        desc="Galette niçoise sans gluten : pâte liquide de farine de pois chiches et d'huile d'olive, cuite "
             "très chaud jusqu'à être dorée et souple, poivrée au moment de servir.",
        texture=("moelleux", "croustillant"), taste=("legumineuse", "poivre"),
        compo=[
            ("chickpea_flour", 250, "g", "carbohydrate"),
            ("water", 600, "ml", "liquid"),
            ("olive_oil_extra_virgin_plant", 60, "ml", "fat"),
            ("black_pepper_spice", 3, "g", "spice"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Fouetter 250 g de farine de pois chiches avec 600 ml d'eau, 40 ml d'huile d'olive et 5 g de sel, sans grumeaux.",
            "Laisser reposer 1 heure, puis écumer la mousse en surface.",
            "Préchauffer le four à 250°C avec une plaque ou un plat en fonte huilé de 20 ml d'huile.",
            "Verser la pâte sur 5 mm d'épaisseur et cuire 12 minutes, jusqu'à ce que le dessus soit taché de brun.",
            "Découper en morceaux, poivrer généreusement (3 g) et manger brûlant.",
        ]),
    recipe(
        rid="brkf_chilla_pois_chiches_2f95e6", fr="Chilla, galettes de pois chiches aux légumes",
        en="Chilla, Chickpea Flour Vegetable Pancakes",
        cuisine="indian", country="india", region="rajasthan", city="",
        dish="breakfast", prep=15, cook=20, spice=1,
        desc="Petit-déjeuner indien sans gluten : pâte de farine de pois chiches aux oignons, tomates et "
             "coriandre, cuite en galettes fines à la poêle.",
        texture=("moelleux",), taste=("epice", "legumineuse"),
        compo=[
            ("chickpea_flour", 250, "g", "carbohydrate"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("tomato_raw_ripe", 150, "g", "vegetable"),
            ("coriander_raw_fresh_herb", 20, "g", "herb"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("turmeric_powder", 2, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("water", 400, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Fouetter 250 g de farine de pois chiches avec 400 ml d'eau, 2 g de curcuma, 3 g de cumin et 4 g de sel, jusqu'à obtenir une pâte fluide.",
            "Ajouter 150 g d'oignon et 150 g de tomate hachés très finement, 10 g de gingembre râpé, 6 g de piment et 20 g de coriandre.",
            "Laisser reposer 10 minutes.",
            "Chauffer une poêle avec un peu d'huile (40 ml en tout) et verser une louche de pâte, étalée en galette fine.",
            "Cuire 3 minutes de chaque côté, jusqu'à ce que la galette soit dorée. Répéter et servir chaud avec un chutney.",
        ]),
    recipe(
        rid="bread_pain_sarrasin_sans_gluten_8d52c4", fr="Pain de sarrasin sans gluten",
        en="Gluten-Free Buckwheat Bread",
        cuisine="french", country="france", region="bretagne", city="",
        dish="bread", servings=10, prep=15, rest=60, cook=50,
        desc="Pain sans gluten à la farine de sarrasin et de riz, levé à la levure et lié aux graines de "
             "lin moulues, à la mie dense et au goût de noisette.",
        texture=("dense",), taste=("noisette", "cereale"),
        compo=[
            ("buckwheat_flour", 300, "g", "carbohydrate"),
            ("rice_flour", 150, "g", "carbohydrate"),
            ("potato_starch_flour", 50, "g", "binder"),
            ("flaxseed_linseed_ground", 30, "g", "binder"),
            ("bakers_yeast_dehydrated", 8, "g", "leavening"),
            ("water", 480, "ml", "liquid"),
            ("olive_oil_plant", 30, "ml", "fat"),
            ("honey", 15, "g", "sweetener"),
            ("table_salt_unenriched", 8, "g", "seasoning"),
        ],
        steps=[
            "Mélanger 30 g de graines de lin moulues avec 90 ml d'eau et laisser gonfler 10 minutes.",
            "Délayer 8 g de levure sèche et 15 g de miel dans 390 ml d'eau tiède, puis attendre 10 minutes.",
            "Mélanger 300 g de farine de sarrasin, 150 g de farine de riz, 50 g de fécule et 8 g de sel.",
            "Ajouter les liquides, le lin et 30 ml d'huile, puis battre 3 minutes : la pâte est molle, presque coulante.",
            "Verser dans un moule à cake huilé et laisser lever 1 heure.",
            "Cuire 50 minutes à 200°C, puis démouler et laisser refroidir complètement avant de trancher.",
        ]),
    recipe(
        rid="starter_rouleaux_crus_cacahuete_5a38f1", fr="Rouleaux de riz crus aux légumes, sauce cacahuète",
        en="Fresh Rice Paper Rolls with Peanut Sauce",
        cuisine="vietnamese", country="vietnam", region="saigon", city="", allow_similar=("rouleaux",),
        dish="starter", prep=30, cook=0, raw=True,
        desc="Rouleaux frais non cuits : galettes de riz humidifiées, garnies de vermicelles, carotte, "
             "concombre, avocat et herbes, avec une sauce cacahuète au citron vert.",
        texture=("frais", "croquant"), taste=("arachide", "frais"),
        compo=[
            ("rice_paper", 120, "g", "carbohydrate"),
            ("rice_vermicelli_raw_dried", 120, "g", "carbohydrate"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("cucumber_raw_with_skin", 200, "g", "vegetable"),
            ("avocado_raw", 150, "g", "fruit"),
            ("lettuce", 100, "g", "vegetable"),
            ("mint_fresh_herb", 15, "g", "herb"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("peanut_butter_natural_plant", 80, "g", "sauce"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("lime_juice_fresh", 30, "ml", "condiment"),
            ("coconut_sugar", 10, "g", "sweetener"),
            ("garlic_raw", 6, "g", "aromatic"),
            ("water", 80, "ml", "liquid"),
        ],
        steps=[
            "Réhydrater 120 g de vermicelles de riz 4 minutes dans l'eau chaude, les rincer à l'eau froide et les égoutter.",
            "Tailler 150 g de carotte et 200 g de concombre en julienne, couper 150 g d'avocat en lamelles et émincer 100 g de laitue.",
            "Sauce : mélanger 80 g de beurre de cacahuète, 25 ml de sauce soja, 30 ml de jus de citron vert, 10 g de sucre de coco, 6 g d'ail râpé et 80 ml d'eau chaude.",
            "Humidifier une galette de riz 10 secondes, la poser à plat, garnir de laitue, vermicelles, légumes et herbes.",
            "Replier les côtés et rouler serré. Répéter pour les 12 rouleaux (120 g de galettes).",
            "Servir frais avec la sauce cacahuète.",
        ]),
    recipe(
        rid="salad_quinoa_concombre_feta_7c64b8", fr="Salade de quinoa, concombre et feta",
        en="Quinoa, Cucumber and Feta Salad",
        cuisine="mediterranean", country="international", region="world", city="",
        dish="starter", prep=15, cook=15,
        desc="Salade sans gluten et complète : quinoa refroidi, concombre, tomates cerises, feta et herbes, "
             "en vinaigrette au citron et à l'huile d'olive.",
        texture=("croquant",), taste=("citron", "fromage"),
        compo=[
            ("quinoa_raw_dried", 200, "g", "carbohydrate"),
            ("cucumber_raw_with_skin", 250, "g", "vegetable"),
            ("cherry_tomato_raw", 250, "g", "vegetable"),
            ("feta", 120, "g", "protein"),
            ("red_onion_raw", 60, "g", "aromatic"),
            ("parsley_fresh_herb", 20, "g", "herb"),
            ("mint_fresh_herb", 10, "g", "herb"),
            ("lemon_juice", 40, "ml", "condiment"),
            ("olive_oil_extra_virgin_plant", 40, "ml", "fat"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("water", 400, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Rincer 200 g de quinoa et le cuire 13 minutes dans 400 ml d'eau salée avec 1 g de sel, puis l'égrener et le laisser refroidir.",
            "Couper 250 g de concombre en dés et 250 g de tomates cerises en deux, émincer 60 g d'oignon rouge.",
            "Mélanger 40 ml de jus de citron, 40 ml d'huile d'olive, 1 g de sel et 1 g de poivre.",
            "Mélanger le quinoa, les légumes, 20 g de persil et 10 g de menthe avec la vinaigrette.",
            "Ajouter 120 g de feta émiettée au moment de servir.",
        ]),
]
