"""Lot 8 de nouvelles recettes : Asie de l'Est (Chine, Japon, Corée)."""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="noodle_dan_dan_mian_6c41f8", fr="Dan dan mian végétarien",
        en="Vegetarian Dan Dan Noodles",
        cuisine="sichuan", country="china", region="sichuan", city="chengdu",
        dish="main", prep=15, cook=15, spice=3, kid_friendly=False,
        desc="Nouilles du Sichuan : sauce au sésame, doubanjiang et poivre du Sichuan au fond du bol, "
             "champignons hachés croustillants dessus, tout se mélange à table.",
        texture=("enrobe",), taste=("epice", "sesame"),
        compo=[
            ("pasta_raw_dried", 320, "g", "carbohydrate"),
            ("button_mushroom_raw", 300, "g", "protein"),
            ("base_doubanjiang_paste_340399", 30, "g", "condiment"),
            ("sesame_tahini_raw_butter_seed_plant", 60, "g", "sauce"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("white_vinegar_liquid_distilled", 15, "ml", "condiment"),
            ("sichuan_pepper", 3, "g", "spice"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("green_onion_raw", 50, "g", "garnish"),
            ("peanut_roasted_salted_dry", 40, "g", "garnish"),
            ("peanut_oil_plant", 35, "ml", "fat"),
            ("coconut_sugar", 8, "g", "sweetener"),
            ("water", 120, "ml", "liquid"),
        ],
        steps=[
            "Hacher 300 g de champignons au couteau et les sauter dans 20 ml d'huile d'arachide à feu vif, 8 minutes, jusqu'à ce qu'ils soient bien secs et dorés. Ajouter 15 g de doubanjiang et réserver.",
            "Torréfier 3 g de poivre du Sichuan à sec, 1 minute, puis le piler.",
            "Sauce : mélanger 60 g de purée de sésame, 30 ml de sauce soja, 15 ml de vinaigre, 15 g de doubanjiang, 15 g d'ail et 10 g de gingembre râpés, 8 g de sucre, le poivre pilé, 15 ml d'huile et 120 ml d'eau chaude.",
            "Cuire 320 g de nouilles selon leur temps, puis les égoutter.",
            "Répartir la sauce au fond des bols, poser les nouilles, puis les champignons.",
            "Parsemer de 50 g d'oignons verts et de 40 g de cacahuètes concassées, et mélanger avant de manger.",
        ]),
    recipe(
        rid="side_pai_huang_gua_3d92b5", fr="Pai huang gua, concombre écrasé à l'ail",
        en="Pai Huang Gua, Smashed Cucumber Salad",
        cuisine="chinese", country="china", region="sichuan", city="",
        dish="side", prep=10, rest=15, cook=0, spice=1, raw=True,
        desc="Concombres écrasés au plat du couteau pour mieux s'imbiber, assaisonnés d'ail, de vinaigre, "
             "de sauce soja et d'huile de sésame.",
        texture=("croquant",), taste=("ail", "acidule"),
        compo=[
            ("cucumber_raw_with_skin", 700, "g", "vegetable"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("white_vinegar_liquid_distilled", 25, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("coconut_sugar", 6, "g", "sweetener"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Écraser 700 g de concombres au plat d'un grand couteau, puis les couper en tronçons irréguliers.",
            "Les saler avec 3 g de sel et laisser dégorger 15 minutes, puis jeter l'eau rendue.",
            "Mélanger 15 g d'ail pilé, 25 ml de sauce soja, 25 ml de vinaigre, 15 ml d'huile de sésame, 6 g de sucre et 2 g de piment.",
            "Verser sur les concombres, parsemer de 10 g de sésame et servir frais.",
        ]),
    recipe(
        rid="snack_cong_you_bing_8b57d1", fr="Cong you bing, galettes feuilletées aux oignons verts",
        en="Cong You Bing, Scallion Pancakes",
        cuisine="chinese", country="china", region="shanghai", city="",
        dish="snack", servings=6, prep=25, rest=45, cook=20,
        desc="Galettes chinoises feuilletées : pâte à l'eau chaude roulée avec une huile aux oignons verts, "
             "enroulée en escargot puis aplatie et poêlée jusqu'à être croustillante.",
        texture=("feuillete", "croustillant"), taste=("oignon", "cereale"),
        compo=[
            ("wheat_all_purpose_flour_unenriched_unbleached", 400, "g", "carbohydrate"),
            ("water", 250, "ml", "liquid"),
            ("green_onion_raw", 150, "g", "aromatic"),
            ("peanut_oil_plant", 70, "ml", "fat"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("table_salt_unenriched", 6, "g", "seasoning"),
        ],
        steps=[
            "Verser 250 ml d'eau bouillante sur 400 g de farine en remuant, puis pétrir 5 minutes et laisser reposer 45 minutes sous un linge.",
            "Mélanger 20 ml d'huile d'arachide, 15 ml d'huile de sésame et 3 g de sel.",
            "Diviser la pâte en 6, étaler chaque pâton finement, le badigeonner d'huile, parsemer de 150 g d'oignons verts émincés et de 3 g de sel au total.",
            "Rouler en boudin, l'enrouler en escargot, puis l'aplatir au rouleau sur 5 mm.",
            "Cuire dans 50 ml d'huile d'arachide, 3 minutes de chaque côté, jusqu'à ce que les galettes soient dorées et feuilletées.",
        ]),
    recipe(
        rid="main_tomates_oeufs_sautes_5f18c7", fr="Tomates et œufs sautés à la chinoise",
        en="Chinese Tomato and Egg Stir-Fry",
        cuisine="chinese", country="china", region="pekin", city="",
        dish="main", prep=10, cook=10,
        desc="Le plat familial chinois par excellence : œufs brouillés très moelleux mêlés à des tomates "
             "fondues au sucre et à la sauce soja, servis sur du riz.",
        texture=("moelleux",), taste=("tomate", "umami"),
        compo=[
            ("tomato_raw_ripe", 700, "g", "fruit"),
            ("egg_raw", 275, "g", "protein"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("garlic_raw", 9, "g", "aromatic"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "condiment"),
            ("coconut_sugar", 8, "g", "sweetener"),
            ("sesame_oil_plant", 10, "ml", "fat"),
            ("peanut_oil_plant", 30, "ml", "fat"),
            ("white_rice_raw_seed_unenriched", 250, "g", "carbohydrate"),
            ("water", 370, "ml", "liquid"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Cuire 250 g de riz dans 370 ml d'eau, 12 minutes à couvert, puis le laisser reposer.",
            "Battre 5 œufs (275 g) avec 1 g de sel et les brouiller 1 minute dans 20 ml d'huile d'arachide, en les gardant baveux. Réserver.",
            "Dans 10 ml d'huile, faire revenir 9 g d'ail, puis 700 g de tomates en quartiers, 8 g de sucre et 2 g de sel, 5 minutes à feu vif, jusqu'à ce qu'elles rendent leur jus.",
            "Ajouter 20 ml de sauce soja, remettre les œufs et mélanger 30 secondes.",
            "Arroser de 10 ml d'huile de sésame, parsemer de 40 g d'oignons verts et servir sur le riz.",
        ]),
    recipe(
        rid="side_haricots_verts_sichuan_2a63e9", fr="Haricots verts sautés secs à la sichuanaise",
        en="Sichuan Dry-Fried Green Beans",
        cuisine="sichuan", country="china", region="sichuan", city="",
        dish="side", prep=10, cook=15, spice=2, kid_friendly=False,
        desc="Haricots verts saisis jusqu'à se rider, puis sautés avec ail, gingembre, piment séché et "
             "légumes conservés : secs, fripés et très parfumés.",
        texture=("fripe", "croquant"), taste=("epice", "umami"),
        compo=[
            ("french_bean_raw", 600, "g", "vegetable"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("ginger_raw_root_fresh", 10, "g", "aromatic"),
            ("red_hot_chili_pepper_spice_dried", 4, "g", "spice"),
            ("sichuan_pepper", 2, "g", "spice"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("coconut_sugar", 6, "g", "sweetener"),
            ("peanut_oil_plant", 35, "ml", "fat"),
            ("green_onion_raw", 30, "g", "garnish"),
        ],
        steps=[
            "Équeuter 600 g de haricots verts et les sécher soigneusement.",
            "Les saisir dans 25 ml d'huile d'arachide à feu vif, 8 minutes sans trop remuer, jusqu'à ce que la peau se ride et brunisse par endroits. Réserver.",
            "Dans 10 ml d'huile, faire grésiller 4 g de piment séché et 2 g de poivre du Sichuan, 30 secondes, puis ajouter 15 g d'ail et 10 g de gingembre hachés.",
            "Remettre les haricots, ajouter 25 ml de sauce soja et 6 g de sucre, puis sauter 2 minutes.",
            "Parsemer de 30 g d'oignons verts et servir.",
        ]),
    recipe(
        rid="noodle_nouilles_froides_sesame_7d25a4", fr="Nouilles froides à la sauce sésame",
        en="Cold Noodles in Sesame Sauce",
        cuisine="chinese", country="china", region="pekin", city="",
        dish="main", prep=15, cook=10, spice=1,
        desc="Nouilles rafraîchies à l'eau froide, nappées d'une sauce sésame-soja-vinaigre, avec concombre "
             "et carotte en julienne : un plat d'été prêt en un quart d'heure.",
        texture=("glissant", "croquant"), taste=("sesame", "acidule"),
        compo=[
            ("pasta_raw_dried", 320, "g", "carbohydrate"),
            ("sesame_tahini_raw_butter_seed_plant", 70, "g", "sauce"),
            ("soy_sauce_shoyu_reduced_sodium", 35, "ml", "condiment"),
            ("white_vinegar_liquid_distilled", 20, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("coconut_sugar", 10, "g", "sweetener"),
            ("cucumber_raw_with_skin", 250, "g", "vegetable"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
            ("water", 100, "ml", "liquid"),
        ],
        steps=[
            "Cuire 320 g de nouilles, les rincer à l'eau froide et les égoutter, puis les mélanger à 5 ml d'huile de sésame.",
            "Sauce : fouetter 70 g de purée de sésame avec 35 ml de sauce soja, 20 ml de vinaigre, 10 ml d'huile de sésame, 12 g d'ail râpé, 10 g de sucre, 2 g de piment et 100 ml d'eau froide.",
            "Tailler 250 g de concombre et 150 g de carotte en fine julienne.",
            "Répartir les nouilles, napper de sauce, ajouter les légumes et 40 g d'oignons verts, puis mélanger.",
        ]),
    recipe(
        rid="side_pommes_terre_aigre_piquantes_9e84c3", fr="Pommes de terre sautées aigres-piquantes",
        en="Hot and Sour Potato Slivers",
        cuisine="sichuan", country="china", region="sichuan", city="",
        dish="side", prep=15, cook=10, spice=2, kid_friendly=False,
        desc="Bâtonnets de pomme de terre rincés pour retirer l'amidon, sautés très vite au vinaigre, "
             "piment et poivre du Sichuan : ils restent croquants.",
        texture=("croquant",), taste=("acidule", "epice"),
        compo=[
            ("potato_raw_flesh", 700, "g", "vegetable"),
            ("green_bell_pepper_raw", 150, "g", "vegetable"),
            ("red_hot_chili_pepper_spice_dried", 3, "g", "spice"),
            ("sichuan_pepper", 2, "g", "spice"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("white_vinegar_liquid_distilled", 35, "ml", "condiment"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "condiment"),
            ("peanut_oil_plant", 30, "ml", "fat"),
            ("green_onion_raw", 30, "g", "garnish"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Tailler 700 g de pommes de terre en fins bâtonnets, les rincer à l'eau froide jusqu'à ce qu'elle soit claire, puis les égoutter et les sécher.",
            "Chauffer 30 ml d'huile et y faire grésiller 3 g de piment séché et 2 g de poivre du Sichuan, 30 secondes.",
            "Ajouter les pommes de terre et 150 g de poivron en lanières, puis sauter 6 minutes à feu vif.",
            "Ajouter 12 g d'ail, 35 ml de vinaigre, 20 ml de sauce soja et 2 g de sel, et sauter 2 minutes.",
            "Parsemer de 30 g d'oignons verts et servir aussitôt, les bâtonnets doivent rester fermes.",
        ]),
    recipe(
        rid="main_wontons_sauce_chili_4b71d6", fr="Wontons aux légumes, sauce chili au vinaigre",
        en="Vegetable Wontons in Chili Vinegar Sauce",
        cuisine="sichuan", country="china", region="sichuan", city="chengdu",
        dish="main", prep=35, cook=10, spice=2, kid_friendly=False,
        desc="Wontons farcis de chou et de champignons, pochés puis servis dans une sauce d'huile pimentée, "
             "vinaigre, ail et sauce soja, parsemés de sésame.",
        texture=("moelleux",), taste=("epice", "acidule"),
        compo=[
            ("base_wonton_wrapper_7bfeb5", 350, "g", "carbohydrate"),
            ("napa_cabbage_raw", 350, "g", "vegetable"),
            ("shiitake_mushroom_raw", 200, "g", "protein"),
            ("tofu_plain_pre_packaged", 150, "g", "protein"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("green_onion_raw", 50, "g", "aromatic"),
            ("soy_sauce_shoyu_reduced_sodium", 35, "ml", "condiment"),
            ("white_vinegar_liquid_distilled", 30, "ml", "condiment"),
            ("red_hot_chili_pepper_spice_dried", 4, "g", "spice"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("sesame_oil_plant", 20, "ml", "fat"),
            ("peanut_oil_plant", 30, "ml", "fat"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("coconut_sugar", 8, "g", "sweetener"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Hacher 350 g de chou chinois, le saler avec 3 g de sel, laisser dégorger 10 minutes puis presser.",
            "Hacher 200 g de shiitakés et 150 g de tofu, les mélanger au chou avec 12 g de gingembre, 30 g d'oignons verts, 15 ml de sauce soja, 10 ml d'huile de sésame et 1 g de sel.",
            "Garnir chaque feuille de wonton d'une cuillerée de farce, humidifier les bords et replier en triangle puis en aumônière (350 g de feuilles).",
            "Huile pimentée : chauffer 30 ml d'huile d'arachide et la verser sur 4 g de piment séché écrasé.",
            "Sauce : mélanger cette huile avec 20 ml de sauce soja, 30 ml de vinaigre, 12 g d'ail râpé, 8 g de sucre et 10 ml d'huile de sésame.",
            "Pocher les wontons 4 minutes dans l'eau bouillante, les égoutter, les napper de sauce et parsemer de sésame et d'oignons verts.",
        ]),
    recipe(
        rid="entry_chawanmushi_6d39f2", fr="Chawanmushi, flan salé au dashi",
        en="Chawanmushi, Savoury Dashi Custard",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="starter", prep=15, cook=20,
        desc="Flan japonais très soyeux : œufs battus avec du dashi et de la sauce soja, cuits à la vapeur "
             "douce en tasses avec shiitakés et oignons verts.",
        texture=("soyeux",), taste=("umami", "doux"),
        compo=[
            ("egg_raw", 220, "g", "protein"),
            ("base_dashi_broth_a3a517", 600, "ml", "liquid"),
            ("shiitake_mushroom_raw", 120, "g", "vegetable"),
            ("green_onion_raw", 30, "g", "garnish"),
            ("soy_sauce_shoyu_reduced_sodium", 20, "ml", "condiment"),
            ("mirin", 15, "ml", "condiment"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Battre 4 œufs (220 g) sans les faire mousser, puis ajouter 600 ml de dashi tiède, 20 ml de sauce soja, 15 ml de mirin et 1 g de sel.",
            "Passer l'appareil au chinois pour obtenir une texture parfaitement lisse.",
            "Répartir 120 g de shiitakés émincés dans quatre tasses, puis verser l'appareil.",
            "Couvrir chaque tasse de film ou d'aluminium et cuire 18 minutes à la vapeur douce : le flan doit trembler sans bouillonner.",
            "Parsemer de 30 g d'oignons verts et servir chaud, à la cuillère.",
        ]),
    recipe(
        rid="side_kinpira_carottes_3c58b7", fr="Kinpira de carottes et de lotus",
        en="Kinpira of Carrot and Lotus Root",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="side", prep=15, cook=15,
        desc="Racines taillées en fins bâtonnets sautées puis glacées à la sauce soja, au mirin et au sucre, "
             "finies au sésame et au piment.",
        texture=("croquant",), taste=("umami", "sucre"),
        compo=[
            ("carrot_raw", 350, "g", "vegetable"),
            ("lotus_raw_root", 250, "g", "vegetable"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("mirin", 25, "ml", "condiment"),
            ("coconut_sugar", 10, "g", "sweetener"),
            ("sesame_oil_plant", 20, "ml", "fat"),
            ("sesame_seed_hulled_dried", 15, "g", "garnish"),
            ("red_hot_chili_pepper_spice_dried", 2, "g", "spice"),
        ],
        steps=[
            "Tailler 350 g de carotte et 250 g de racine de lotus en bâtonnets de 5 cm.",
            "Les sauter dans 20 ml d'huile de sésame à feu vif, 6 minutes, jusqu'à ce qu'ils commencent à dorer.",
            "Ajouter 30 ml de sauce soja, 25 ml de mirin, 10 g de sucre et 2 g de piment.",
            "Cuire 6 minutes à feu moyen, jusqu'à ce que le liquide ait presque disparu et glace les légumes.",
            "Parsemer de 15 g de sésame grillé et servir tiède ou froid.",
        ]),
    recipe(
        rid="noodle_hiyashi_chuka_8f42c1", fr="Hiyashi chuka, nouilles froides japonaises",
        en="Hiyashi Chuka, Japanese Cold Ramen",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="main", prep=20, cook=12,
        desc="Nouilles ramen refroidies, rangées en bandes de garnitures colorées — omelette, concombre, "
             "tomate, pousses de soja — arrosées d'une sauce soja-vinaigre-sésame.",
        texture=("glissant", "croquant"), taste=("acidule", "umami"),
        compo=[
            ("pasta_raw_dried", 320, "g", "carbohydrate"),
            ("egg_raw", 165, "g", "protein"),
            ("cucumber_raw_with_skin", 200, "g", "vegetable"),
            ("tomato_raw_ripe", 250, "g", "vegetable"),
            ("mung_bean_sprouts_raw_seed_sprouted", 120, "g", "vegetable"),
            ("soy_sauce_shoyu_reduced_sodium", 45, "ml", "condiment"),
            ("white_vinegar_liquid_distilled", 35, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("coconut_sugar", 15, "g", "sweetener"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("peanut_oil_plant", 10, "ml", "fat"),
            ("water", 60, "ml", "liquid"),
        ],
        steps=[
            "Battre 3 œufs (165 g) et les cuire en omelette fine dans 10 ml d'huile, puis les rouler et les couper en lanières.",
            "Cuire 320 g de nouilles, les rincer longuement à l'eau froide et les égoutter.",
            "Sauce : mélanger 45 ml de sauce soja, 35 ml de vinaigre, 15 g de sucre, 15 ml d'huile de sésame et 60 ml d'eau froide.",
            "Blanchir 120 g de pousses de soja 30 secondes et les rafraîchir. Tailler 200 g de concombre en julienne et 250 g de tomates en quartiers.",
            "Dresser les nouilles dans des assiettes creuses et ranger les garnitures en bandes par-dessus.",
            "Verser la sauce et parsemer de 10 g de sésame juste avant de servir.",
        ]),
    recipe(
        rid="side_nasu_dengaku_5a17e4", fr="Nasu dengaku, aubergines glacées au miso",
        en="Nasu Dengaku, Miso-Glazed Eggplant",
        cuisine="japanese", country="japan", region="kansai", city="",
        dish="side", prep=10, cook=25,
        desc="Demi-aubergines quadrillées, rôties jusqu'à être fondantes, nappées d'un miso sucré au mirin "
             "puis passées sous le gril jusqu'à caraméliser.",
        texture=("fondant",), taste=("miso", "sucre"),
        compo=[
            ("eggplant_raw", 800, "g", "vegetable"),
            ("base_miso_paste_1faeef", 80, "g", "condiment"),
            ("mirin", 30, "ml", "condiment"),
            ("coconut_sugar", 20, "g", "sweetener"),
            ("sesame_oil_plant", 20, "ml", "fat"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("green_onion_raw", 30, "g", "garnish"),
        ],
        steps=[
            "Préchauffer le four à 210°C. Couper 800 g d'aubergines en deux et quadriller la chair au couteau.",
            "Les badigeonner de 20 ml d'huile de sésame et les rôtir 20 minutes, chair vers le haut.",
            "Mélanger 80 g de miso, 30 ml de mirin et 20 g de sucre.",
            "Étaler ce glaçage sur les aubergines et passer 4 minutes sous le gril, jusqu'à ce qu'il boursoufle.",
            "Parsemer de 10 g de sésame et de 30 g d'oignons verts.",
        ]),
    recipe(
        rid="snack_korokke_pomme_de_terre_2e95d8", fr="Korokke, croquettes japonaises de pomme de terre",
        en="Korokke, Japanese Potato Croquettes",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="snack", servings=6, prep=30, rest=30, cook=25,
        desc="Croquettes de purée de pomme de terre aux oignons et au maïs, panées au panko et frites : "
             "croûte très croustillante, cœur moelleux.",
        texture=("croustillant", "fondant"), taste=("doux", "umami"),
        compo=[
            ("potato_raw_flesh", 800, "g", "carbohydrate"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("sweet_corn_canned", 150, "g", "vegetable"),
            ("breadcrumbs_dried", 150, "g", "ingredient"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 80, "g", "ingredient"),
            ("egg_raw", 110, "g", "binder"),
            ("butter_sup80pct", 20, "g", "fat"),
            ("sunflower_oil_plant", 70, "ml", "fat"),
            ("soy_sauce_shoyu_reduced_sodium", 15, "ml", "condiment"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Cuire 800 g de pommes de terre à l'eau salée 25 minutes, les éplucher et les écraser grossièrement.",
            "Faire fondre 200 g d'oignon haché dans 20 g de beurre, 8 minutes, puis les mélanger à la purée avec 150 g de maïs, 15 ml de sauce soja, 3 g de sel et 1 g de poivre.",
            "Former 12 palets et les réfrigérer 30 minutes.",
            "Les passer dans 80 g de farine, puis dans 2 œufs battus (110 g), puis dans 150 g de panko.",
            "Frire dans l'huile à 180°C, 3 minutes par face, jusqu'à ce qu'ils soient bien dorés (environ 70 ml d'huile absorbée).",
            "Égoutter sur une grille et servir chaud.",
        ]),
    recipe(
        rid="noodle_zaru_soba_7b83a5", fr="Zaru soba, soba froides et sauce tsuyu",
        en="Zaru Soba with Dipping Sauce",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="main", prep=10, cook=12,
        desc="Nouilles de sarrasin rincées à l'eau glacée, servies sur une natte avec une sauce tsuyu au "
             "dashi, soja et mirin, wasabi et oignons verts à côté.",
        texture=("ferme",), taste=("sarrasin", "umami"),
        compo=[
            ("buckwheat_flour", 300, "g", "carbohydrate"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 100, "g", "carbohydrate"),
            ("base_dashi_broth_a3a517", 400, "ml", "liquid"),
            ("soy_sauce_shoyu_reduced_sodium", 80, "ml", "condiment"),
            ("mirin", 50, "ml", "condiment"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("wasabi_japanese_horseradish_raw_root", 15, "g", "condiment"),
            ("nori_dried", 5, "g", "garnish"),
            ("water", 200, "ml", "liquid"),
        ],
        steps=[
            "Pétrir 300 g de farine de sarrasin et 100 g de farine de blé avec 200 ml d'eau, 10 minutes, puis étaler très finement et découper des nouilles de 2 mm.",
            "Tsuyu : chauffer 400 ml de dashi avec 80 ml de sauce soja et 50 ml de mirin, 3 minutes, puis laisser refroidir.",
            "Cuire les nouilles 3 minutes à grande eau, en remuant.",
            "Les rincer sous l'eau froide jusqu'à ce qu'elles soient parfaitement froides, puis les égoutter.",
            "Servir les soba avec la sauce en coupelles, 40 g d'oignons verts, 15 g de wasabi et 5 g de nori en lanières.",
        ]),
    recipe(
        rid="brkf_tamagoyaki_4d61c9", fr="Tamagoyaki, omelette roulée japonaise",
        en="Tamagoyaki, Rolled Japanese Omelette",
        cuisine="japanese", country="japan", region="kanto", city="",
        dish="breakfast", prep=10, cook=12,
        desc="Omelette cuite en fines couches successives et roulée sur elle-même, légèrement sucrée au mirin "
             "et au dashi, tranchée en bouchées.",
        texture=("moelleux",), taste=("doux", "umami"),
        compo=[
            ("egg_raw", 330, "g", "protein"),
            ("base_dashi_broth_a3a517", 80, "ml", "liquid"),
            ("mirin", 20, "ml", "condiment"),
            ("soy_sauce_shoyu_reduced_sodium", 15, "ml", "condiment"),
            ("coconut_sugar", 12, "g", "sweetener"),
            ("peanut_oil_plant", 20, "ml", "fat"),
            ("table_salt_unenriched", 1, "g", "seasoning"),
        ],
        steps=[
            "Battre 6 œufs (330 g) avec 80 ml de dashi, 20 ml de mirin, 15 ml de sauce soja, 12 g de sucre et 1 g de sel, puis filtrer.",
            "Huiler une poêle rectangulaire au pinceau (20 ml d'huile en tout) et la chauffer à feu moyen.",
            "Verser une fine couche d'appareil, la laisser juste prendre, puis la rouler vers soi.",
            "Repousser le rouleau au fond, huiler, verser une nouvelle couche en soulevant le rouleau pour qu'elle s'y colle, et rouler à nouveau.",
            "Répéter jusqu'à épuisement, puis serrer le rouleau dans une natte ou un linge et laisser tiédir avant de trancher.",
        ]),
    recipe(
        rid="noodle_japchae_6e27b4", fr="Japchae, nouilles de patate douce sautées",
        en="Japchae, Korean Glass Noodle Stir-Fry",
        cuisine="korean", country="south_korea", region="seoul", city="seoul",
        dish="main", prep=20, cook=15,
        desc="Nouilles de patate douce translucides sautées avec épinards, carotte, champignons et oignon, "
             "assaisonnées à la sauce soja et à l'huile de sésame, servies tièdes.",
        texture=("glissant", "croquant"), taste=("sesame", "umami"),
        compo=[
            ("base_nouilles_de_patate_douce_fdeb79", 300, "g", "carbohydrate"),
            ("spinach_raw_mature", 250, "g", "vegetable"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("shiitake_mushroom_raw", 150, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("egg_raw", 110, "g", "protein"),
            ("soy_sauce_shoyu_reduced_sodium", 50, "ml", "condiment"),
            ("sesame_oil_plant", 30, "ml", "fat"),
            ("coconut_sugar", 20, "g", "sweetener"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("sesame_seed_hulled_dried", 15, "g", "garnish"),
            ("peanut_oil_plant", 20, "ml", "fat"),
        ],
        steps=[
            "Cuire 300 g de nouilles de patate douce 6 minutes, les rincer et les couper grossièrement aux ciseaux.",
            "Blanchir 250 g d'épinards 30 secondes, les presser et les assaisonner de 10 ml d'huile de sésame.",
            "Battre 2 œufs (110 g), les cuire en omelette fine dans 10 ml d'huile et les couper en lanières.",
            "Sauter séparément 150 g de carotte en julienne, 150 g de shiitakés et 150 g d'oignon émincés dans 10 ml d'huile, 3 minutes chacun.",
            "Mélanger le tout avec 50 ml de sauce soja, 20 ml d'huile de sésame, 20 g de sucre et 12 g d'ail râpé.",
            "Parsemer de 15 g de sésame et de 40 g d'oignons verts, et servir tiède.",
        ]),
    recipe(
        rid="stew_doenjang_jjigae_9c54a7", fr="Doenjang jjigae, ragoût coréen de soja fermenté",
        en="Doenjang Jjigae, Korean Soybean Paste Stew",
        cuisine="korean", country="south_korea", region="seoul", city="", allow_similar=("doenjang", "jjigae"),
        dish="main", prep=15, cook=25, spice=1,
        desc="Ragoût coréen de tous les jours : bouillon relevé de pâte de soja fermentée, courgette, pomme "
             "de terre, tofu et champignons, servi bouillonnant avec du riz.",
        texture=("nappant",), taste=("umami", "fermente"),
        compo=[
            ("base_fermented_bean_paste_817412", 70, "g", "condiment"),
            ("tofu_plain_pre_packaged", 300, "g", "protein"),
            ("green_zucchini_squash_raw", 250, "g", "vegetable"),
            ("potato_raw_flesh", 250, "g", "vegetable"),
            ("button_mushroom_raw", 150, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("gochugaru", 5, "g", "spice"),
            ("green_onion_raw", 40, "g", "garnish"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("water", 900, "ml", "liquid"),
            ("white_rice_raw_seed_unenriched", None, "1 portion", "serving_suggestion"),
        ],
        steps=[
            "Porter 900 ml d'eau à frémissement et y délayer 70 g de pâte de soja fermentée.",
            "Ajouter 250 g de pommes de terre en cubes et 150 g d'oignon émincé, puis cuire 12 minutes.",
            "Ajouter 250 g de courgette en demi-rondelles, 150 g de champignons et 12 g d'ail haché, puis cuire 6 minutes.",
            "Ajouter 300 g de tofu en cubes et 5 g de gochugaru, puis mijoter 5 minutes sans remuer.",
            "Arroser de 15 ml d'huile de sésame, parsemer de 40 g d'oignons verts et servir bouillonnant avec du riz.",
        ]),
    recipe(
        rid="soup_kongnamul_guk_3f76e2", fr="Kongnamul guk, soupe coréenne aux pousses de soja",
        en="Kongnamul Guk, Korean Soybean Sprout Soup",
        cuisine="korean", country="south_korea", region="seoul", city="",
        dish="soup", prep=10, cook=20,
        desc="Soupe claire et légère : pousses de soja cuites dans un bouillon à l'ail et à l'algue, relevée "
             "d'un peu de gochugaru et d'huile de sésame.",
        texture=("liquide", "croquant"), taste=("doux", "umami"),
        compo=[
            ("mung_bean_sprouts_raw_seed_sprouted", 400, "g", "vegetable"),
            ("nori_dried", 5, "g", "ingredient"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("green_onion_raw", 50, "g", "garnish"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("gochugaru", 3, "g", "spice"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("water", 1200, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Porter 1,2 L d'eau à ébullition avec 5 g d'algue nori et 12 g d'ail écrasé, puis laisser infuser 10 minutes.",
            "Ajouter 400 g de pousses de soja et cuire 8 minutes à couvert, sans soulever le couvercle pour éviter l'amertume.",
            "Assaisonner de 25 ml de sauce soja, 2 g de sel et 3 g de gochugaru.",
            "Arroser de 15 ml d'huile de sésame, ajouter 50 g d'oignons verts et 10 g de sésame, puis servir chaud.",
        ]),
    recipe(
        rid="snack_hobak_jeon_8d19c5", fr="Hobak jeon, galettes de courgette coréennes",
        en="Hobak Jeon, Korean Zucchini Pancakes",
        cuisine="korean", country="south_korea", region="seoul", city="",
        dish="snack", prep=15, cook=15,
        desc="Rondelles de courgette farinées et passées à l'œuf, dorées à la poêle, servies avec une sauce "
             "soja au vinaigre et au piment.",
        texture=("moelleux",), taste=("doux", "umami"),
        compo=[
            ("green_zucchini_squash_raw", 700, "g", "vegetable"),
            ("egg_raw", 165, "g", "binder"),
            ("wheat_all_purpose_flour_unenriched_unbleached", 80, "g", "carbohydrate"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("white_vinegar_liquid_distilled", 15, "ml", "condiment"),
            ("gochugaru", 2, "g", "spice"),
            ("green_onion_raw", 30, "g", "garnish"),
            ("peanut_oil_plant", 40, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Couper 700 g de courgettes en rondelles de 8 mm, les saler avec 3 g de sel et laisser 10 minutes, puis les éponger.",
            "Les fariner légèrement (80 g de farine), puis les passer dans 3 œufs battus (165 g) avec 1 g de sel.",
            "Les dorer dans 40 ml d'huile, 3 minutes de chaque côté à feu moyen.",
            "Sauce : mélanger 25 ml de sauce soja, 15 ml de vinaigre, 2 g de gochugaru et 30 g d'oignons verts émincés.",
            "Servir les galettes chaudes avec la sauce.",
        ]),
    recipe(
        rid="soup_tteok_mandu_guk_5b28d3", fr="Tteok guk, soupe de gâteaux de riz",
        en="Tteok Guk, Korean Rice Cake Soup",
        cuisine="korean", country="south_korea", region="seoul", city="",
        dish="soup", prep=15, cook=25,
        desc="La soupe du Nouvel An coréen : bouillon d'algue et de champignons dans lequel cuisent des "
             "tranches de tteok, avec œuf en filet et lanières de nori.",
        texture=("moelleux",), taste=("umami", "doux"),
        compo=[
            ("tteok", 500, "g", "carbohydrate"),
            ("egg_raw", 110, "g", "protein"),
            ("shiitake_mushroom_raw", 150, "g", "vegetable"),
            ("nori_dried", 5, "g", "garnish"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("green_onion_raw", 50, "g", "garnish"),
            ("soy_sauce_shoyu_reduced_sodium", 30, "ml", "condiment"),
            ("sesame_oil_plant", 15, "ml", "fat"),
            ("water", 1300, "ml", "liquid"),
            ("table_salt_unenriched", 2, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 500 g de tteok 15 minutes dans l'eau froide s'ils sont durs, puis les égoutter.",
            "Porter 1,3 L d'eau à ébullition avec 5 g de nori, 150 g de shiitakés émincés et 12 g d'ail, puis laisser frémir 10 minutes.",
            "Ajouter les tteok et cuire 6 minutes, jusqu'à ce qu'ils remontent et soient moelleux.",
            "Assaisonner de 30 ml de sauce soja et 2 g de sel, puis verser 2 œufs battus (110 g) en filet en remuant doucement.",
            "Arroser de 15 ml d'huile de sésame, parsemer de 50 g d'oignons verts et de nori, et servir.",
        ]),
]
