"""Lot 9 de nouvelles recettes : Asie du Sud (Inde du Sud et de l'Ouest, Sri Lanka, Népal, Pakistan)."""
from ._schema import recipe

RECIPES = [
    recipe(
        rid="brkf_idli_vapeur_5d72c8", fr="Idli, galettes de riz vapeur fermentées",
        en="Idli, Steamed Fermented Rice Cakes",
        cuisine="indian", country="india", region="tamil_nadu", city="",
        dish="breakfast", prep=20, rest=720, cook=15,
        desc="Petits pains vapeur du sud de l'Inde : pâte de riz et de lentilles urad trempées, broyées puis "
             "fermentées une nuit, cuits à la vapeur jusqu'à être aériens.",
        texture=("moelleux", "aere"), taste=("acidule", "doux"),
        compo=[
            ("white_rice_raw_seed_unenriched", 300, "g", "carbohydrate"),
            ("urad_lentil", 100, "g", "plant_protein"),
            ("wheat_semolina_raw", 50, "g", "carbohydrate"),
            ("water", 700, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 300 g de riz et 100 g de lentilles urad séparément, 6 heures dans l'eau froide.",
            "Les égoutter et les broyer séparément avec un peu d'eau (350 ml en tout) : le riz en pâte granuleuse, les lentilles en crème mousseuse.",
            "Mélanger les deux pâtes avec 50 g de semoule fine et 5 g de sel, puis laisser fermenter 12 heures à température ambiante : la pâte double et sent l'acidité.",
            "Verser dans des moules à idli huilés, sans les remplir complètement.",
            "Cuire 12 minutes à la vapeur, jusqu'à ce qu'une lame ressorte propre.",
            "Démouler tiède et servir avec un chutney et un sambar.",
        ]),
    recipe(
        rid="brkf_uttapam_oignon_3a86d1", fr="Uttapam aux oignons et à la tomate",
        en="Uttapam with Onion and Tomato",
        cuisine="indian", country="india", region="tamil_nadu", city="",
        dish="breakfast", prep=20, rest=720, cook=20, spice=1,
        desc="Crêpe épaisse du sud de l'Inde, cuite d'un seul côté sur une pâte fermentée, garnie d'oignon, "
             "de tomate, de piment et de coriandre pressés dans la pâte.",
        texture=("moelleux",), taste=("acidule", "epice"),
        compo=[
            ("white_rice_raw_seed_unenriched", 300, "g", "carbohydrate"),
            ("urad_lentil", 100, "g", "plant_protein"),
            ("onion_raw", 200, "g", "vegetable"),
            ("tomato_raw_ripe", 200, "g", "vegetable"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("coriander_raw_fresh_herb", 20, "g", "herb"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("water", 650, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 300 g de riz et 100 g de lentilles urad 6 heures, les broyer séparément avec 350 ml d'eau, mélanger avec 5 g de sel et laisser fermenter 12 heures.",
            "Hacher finement 200 g d'oignon, 200 g de tomate, 8 g de piment et 20 g de coriandre.",
            "Chauffer une poêle huilée (40 ml en tout) et verser une louche de pâte en disque épais de 1 cm.",
            "Parsemer aussitôt de garniture et appuyer légèrement avec le dos de la louche.",
            "Cuire 4 minutes à couvert, jusqu'à ce que le dessus soit pris et le dessous doré, puis servir sans retourner.",
        ]),
    recipe(
        rid="snack_medu_vada_7b41e5", fr="Medu vada, beignets de lentilles urad",
        en="Medu Vada, Urad Dal Fritters",
        cuisine="indian", country="india", region="karnataka", city="",
        dish="snack", servings=6, prep=20, rest=240, cook=20, spice=1,
        desc="Beignets en couronne du petit-déjeuner indien : pâte de lentilles urad battue en mousse, "
             "parfumée au poivre, au gingembre et aux feuilles de curry, frite jusqu'à être croustillante.",
        texture=("croustillant", "moelleux"), taste=("legumineuse", "poivre"),
        compo=[
            ("urad_lentil", 350, "g", "plant_protein"),
            ("ginger_raw_root_fresh", 15, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("black_pepper_spice", 4, "g", "spice"),
            ("onion_raw", 100, "g", "aromatic"),
            ("sunflower_oil_plant", 70, "ml", "fat"),
            ("water", 150, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Faire tremper 350 g de lentilles urad 4 heures, puis les égoutter.",
            "Les broyer avec 150 ml d'eau seulement, jusqu'à obtenir une pâte épaisse, puis la battre 3 minutes pour l'aérer : une noisette de pâte doit flotter dans l'eau.",
            "Ajouter 15 g de gingembre, 8 g de piment, 5 g de feuilles de curry et 100 g d'oignon hachés, 4 g de poivre concassé et 5 g de sel.",
            "Former des boules, percer un trou au centre avec le doigt mouillé.",
            "Frire à 175°C, 4 minutes en les retournant, jusqu'à ce qu'elles soient dorées (environ 70 ml d'huile absorbée).",
            "Égoutter et servir chaud avec un chutney à la noix de coco.",
        ]),
    recipe(
        rid="sauce_chutney_coco_menthe_9e35b7", fr="Chutney de noix de coco à la menthe",
        en="Coconut Mint Chutney",
        cuisine="indian", country="india", region="kerala", city="",
        dish="sauce", servings=8, prep=10, cook=5, spice=1,
        desc="Chutney frais du sud de l'Inde : noix de coco râpée mixée avec menthe, coriandre, gingembre et "
             "citron, relevée d'un tempérage de moutarde et de feuilles de curry.",
        texture=("cremeux",), taste=("coco", "frais"),
        compo=[
            ("coconut_flesh_dried", 120, "g", "ingredient"),
            ("mint_fresh_herb", 20, "g", "herb"),
            ("coriander_raw_fresh_herb", 25, "g", "herb"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("lemon_juice", 25, "ml", "condiment"),
            ("yellow_mustard_spice_seed", 3, "g", "spice"),
            ("curry_leaf", 4, "g", "herb"),
            ("coconut_oil_plant", 20, "ml", "fat"),
            ("water", 150, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Mixer 120 g de noix de coco râpée avec 20 g de menthe, 25 g de coriandre, 12 g de gingembre, 8 g de piment, 25 ml de jus de citron, 4 g de sel et 150 ml d'eau.",
            "Tempérage : chauffer 20 ml d'huile de coco, y faire éclater 3 g de graines de moutarde avec 4 g de feuilles de curry.",
            "Verser le tempérage sur le chutney et mélanger.",
            "Servir frais avec des idli, dosa ou vada.",
        ]),
    recipe(
        rid="main_avial_kerala_8d51a3", fr="Avial, légumes du Kerala au yaourt et à la coco",
        en="Avial, Kerala Vegetables in Coconut and Yogurt",
        cuisine="indian", country="india", region="kerala", city="",
        dish="main", prep=20, cook=25, spice=1,
        desc="Mélange de légumes taillés en bâtonnets, cuits juste tendres puis liés d'une pâte de noix de "
             "coco, cumin et piment vert, détendue au yaourt et parfumée à l'huile de coco crue.",
        texture=("fondant",), taste=("coco", "acidule"),
        compo=[
            ("carrot_raw", 250, "g", "vegetable"),
            ("french_bean_raw", 200, "g", "vegetable"),
            ("plantain_banana_raw", 250, "g", "vegetable"),
            ("eggplant_raw", 200, "g", "vegetable"),
            ("drumstick_horseradish_tree_raw_pod", 150, "g", "vegetable"),
            ("coconut_flesh_dried", 120, "g", "ingredient"),
            ("yogurt_plain_3pct", 250, "g", "sauce"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("turmeric_powder", 3, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("coconut_oil_plant", 30, "ml", "fat"),
            ("water", 400, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Tailler 250 g de carotte, 200 g de haricots verts, 250 g de plantain, 200 g d'aubergine et 150 g de pilons de moringa en bâtonnets de 5 cm.",
            "Les cuire dans 400 ml d'eau avec 3 g de curcuma et 4 g de sel, 12 minutes : ils doivent rester entiers.",
            "Mixer 120 g de noix de coco râpée avec 8 g de piment vert et 4 g de cumin, sans trop d'eau.",
            "Ajouter cette pâte aux légumes et cuire 5 minutes en remuant délicatement.",
            "Hors du feu, incorporer 250 g de yaourt battu, 30 ml d'huile de coco crue et 5 g de feuilles de curry.",
            "Servir tiède avec du riz.",
        ]),
    recipe(
        rid="rice_bisi_bele_bath_4f28d9", fr="Bisi bele bath, riz et lentilles épicés du Karnataka",
        en="Bisi Bele Bath, Spiced Rice and Lentils",
        cuisine="indian", country="india", region="karnataka", city="bangalore",
        dish="main", prep=20, cook=45, spice=2, kid_friendly=False,
        desc="Plat unique de Bangalore : riz et lentilles toor cuits ensemble avec légumes, tamarin et un "
             "masala grillé à la noix de coco, monté au ghee.",
        texture=("fondant", "nappant"), taste=("epice", "acidule"),
        compo=[
            ("white_rice_raw_seed_unenriched", 250, "g", "carbohydrate"),
            ("pigeon_peas_red_gram_raw", 150, "g", "plant_protein", "dried"),
            ("carrot_raw", 150, "g", "vegetable"),
            ("french_bean_raw", 150, "g", "vegetable"),
            ("green_peas_raw", 100, "g", "vegetable"),
            ("onion_raw", 150, "g", "aromatic_base"),
            ("tamarind", 30, "ml", "condiment"),
            ("coconut_flesh_dried", 60, "g", "ingredient"),
            ("coriander_spice_seed", 6, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 4, "g", "spice"),
            ("cinnamon", 2, "g", "spice"),
            ("cloves", 1, "g", "spice"),
            ("base_ghee_ec9064", 40, "ml", "fat"),
            ("curry_leaf", 5, "g", "herb"),
            ("water", 1600, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Cuire 150 g de lentilles toor dans 700 ml d'eau, 30 minutes, jusqu'à ce qu'elles se défassent.",
            "Masala : griller à sec 6 g de coriandre, 4 g de piment séché, 2 g de cannelle, 1 g de girofle et 60 g de noix de coco, 3 minutes, puis mixer en poudre.",
            "Cuire 250 g de riz dans 600 ml d'eau, 12 minutes.",
            "Cuire 150 g de carotte, 150 g de haricots verts et 100 g de petits pois dans 300 ml d'eau, 8 minutes, avec 150 g d'oignon.",
            "Mélanger riz, lentilles, légumes, 30 ml de tamarin, le masala et 5 g de sel, puis mijoter 8 minutes en remuant.",
            "Terminer avec 40 ml de ghee chaud et 5 g de feuilles de curry.",
        ]),
    recipe(
        rid="side_kootu_courge_lentilles_6b93c4", fr="Kootu de courge et lentilles à la coco",
        en="Squash and Lentil Kootu",
        cuisine="indian", country="india", region="tamil_nadu", city="",
        dish="side", prep=15, cook=30, spice=1,
        desc="Plat doux du Tamil Nadu : courge cuite avec des lentilles corail, liée d'une pâte de coco au "
             "cumin, sans acidité, pour accompagner un riz et un rasam.",
        texture=("fondant",), taste=("doux", "coco"),
        compo=[
            ("butternut_squash_raw_skinless", 600, "g", "vegetable"),
            ("red_lentil_dried", 150, "g", "plant_protein", "dried"),
            ("coconut_flesh_dried", 80, "g", "ingredient"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("yellow_mustard_spice_seed", 3, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("coconut_oil_plant", 25, "ml", "fat"),
            ("water", 800, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Cuire 150 g de lentilles corail avec 2 g de curcuma dans 500 ml d'eau, 15 minutes.",
            "Ajouter 600 g de courge en cubes et 300 ml d'eau, puis cuire 12 minutes.",
            "Mixer 80 g de noix de coco avec 4 g de cumin et 6 g de piment vert, puis l'ajouter avec 4 g de sel et cuire 5 minutes.",
            "Tempérage : chauffer 25 ml d'huile de coco, y faire éclater 3 g de moutarde avec 5 g de feuilles de curry.",
            "Verser sur le kootu et servir avec du riz.",
        ]),
    recipe(
        rid="curry_kadai_paneer_7c51b8", fr="Kadai paneer aux poivrons",
        en="Kadai Paneer with Peppers",
        cuisine="indian", country="india", region="punjab", city="",
        dish="main", prep=15, cook=25, spice=2, kid_friendly=False,
        desc="Paneer et poivrons sautés au wok indien avec un masala de coriandre et de piment fraîchement "
             "pilé, sauce tomate courte et beaucoup de gingembre.",
        texture=("ferme",), taste=("epice", "tomate"),
        compo=[
            ("base_paneer_04e1db", 350, "g", "protein"),
            ("red_bell_pepper_raw", 200, "g", "vegetable"),
            ("green_bell_pepper_raw", 200, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("tomato_raw_ripe", 350, "g", "fruit"),
            ("ginger_raw_root_fresh", 15, "g", "aromatic"),
            ("garlic_raw", 12, "g", "aromatic"),
            ("coriander_spice_seed", 8, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 4, "g", "spice"),
            ("garam_masala", 3, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("sunflower_oil_plant", 35, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Piler 8 g de graines de coriandre et 4 g de piment séché en poudre grossière.",
            "Saisir 200 g de poivron rouge et 200 g de poivron vert en lanières dans 15 ml d'huile à feu vif, 3 minutes, puis réserver.",
            "Faire revenir 200 g d'oignon dans 20 ml d'huile, 6 minutes, puis ajouter 12 g d'ail, 15 g de gingembre et le masala pilé.",
            "Ajouter 350 g de tomates concassées, 2 g de curcuma et 4 g de sel, puis cuire 8 minutes jusqu'à ce que la sauce épaississe.",
            "Ajouter 350 g de paneer en cubes et les poivrons, puis cuire 4 minutes.",
            "Ajouter 3 g de garam masala et 15 g de coriandre, et servir avec des rotis.",
        ]),
    recipe(
        rid="side_bharwa_bhindi_3e74a9", fr="Bharwa bhindi, gombos farcis aux épices",
        en="Bharwa Bhindi, Spice-Stuffed Okra",
        cuisine="indian", country="india", region="rajasthan", city="", allow_similar=("bhindi",),
        dish="side", prep=20, cook=20, spice=1,
        desc="Gombos fendus et farcis d'un mélange sec de farine de pois chiches, coriandre, cumin et amchur, "
             "puis poêlés doucement jusqu'à être tendres.",
        texture=("tendre",), taste=("epice", "acidule"),
        compo=[
            ("okra_raw", 600, "g", "vegetable"),
            ("chickpea_flour", 60, "g", "carbohydrate"),
            ("coriander_spice_seed", 6, "g", "spice"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("red_hot_chili_pepper_spice_dried", 3, "g", "spice"),
            ("lemon_juice", 20, "ml", "condiment"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Laver et sécher 600 g de gombos, couper les extrémités et les fendre sur la longueur sans les séparer.",
            "Griller 60 g de farine de pois chiches à sec, 3 minutes, puis la mélanger à 6 g de coriandre, 4 g de cumin, 2 g de curcuma, 3 g de piment, 4 g de sel et 20 ml de jus de citron.",
            "Farcir chaque gombo de ce mélange.",
            "Les ranger en une seule couche dans une poêle avec 40 ml d'huile et cuire 15 minutes à feu doux, en les retournant délicatement.",
            "Servir chaud avec des rotis.",
        ]),
    recipe(
        rid="bread_thepla_epinards_9a28c5", fr="Thepla aux épinards et au fenugrec",
        en="Spinach Thepla Flatbread",
        cuisine="indian", country="india", region="gujarat", city="",
        dish="bread", servings=6, prep=20, rest=20, cook=20, spice=1,
        desc="Galettes gujaraties souples à la farine complète, aux épinards hachés, yaourt et épices, "
             "cuites à la plaque avec un peu d'huile : elles se gardent en voyage.",
        texture=("souple",), taste=("epice", "vegetal"),
        compo=[
            ("whole_wheat_flour_seed", 350, "g", "carbohydrate"),
            ("spinach_raw_mature", 250, "g", "vegetable"),
            ("yogurt_plain_3pct", 100, "g", "liquid"),
            ("fenugreek_spice_seed", 3, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("chilli_pepper_raw", 6, "g", "spice"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("sunflower_oil_plant", 50, "ml", "fat"),
            ("water", 80, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Hacher finement 250 g d'épinards.",
            "Pétrir 350 g de farine complète avec les épinards, 100 g de yaourt, 20 ml d'huile, 3 g de fenugrec moulu, 2 g de curcuma, 6 g de piment, 3 g de cumin, 5 g de sel et 80 ml d'eau.",
            "Laisser reposer 20 minutes sous un linge.",
            "Diviser en 12 boules et étaler chacune en galette fine de 18 cm.",
            "Cuire sur une plaque chaude 1 minute par face, puis badigeonner d'huile (30 ml en tout) et cuire encore 1 minute par face.",
        ]),
    recipe(
        rid="bread_aloo_paratha_5c83f2", fr="Aloo paratha, galette farcie aux pommes de terre",
        en="Aloo Paratha, Potato-Stuffed Flatbread",
        cuisine="indian", country="india", region="punjab", city="",
        dish="bread", servings=6, prep=30, rest=30, cook=25, spice=1,
        desc="Galette du Pendjab farcie de purée de pommes de terre épicée au gingembre, piment et coriandre, "
             "étalée avec soin et cuite au ghee jusqu'à être dorée.",
        texture=("moelleux", "croustillant"), taste=("epice", "beurre"),
        compo=[
            ("whole_wheat_flour_seed", 400, "g", "carbohydrate"),
            ("potato_raw_flesh", 600, "g", "vegetable"),
            ("onion_raw", 100, "g", "aromatic"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("coriander_raw_fresh_herb", 20, "g", "herb"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("garam_masala", 3, "g", "spice"),
            ("base_ghee_ec9064", 50, "ml", "fat"),
            ("water", 250, "ml", "liquid"),
            ("table_salt_unenriched", 6, "g", "seasoning"),
        ],
        steps=[
            "Pétrir 400 g de farine complète avec 250 ml d'eau et 3 g de sel, 8 minutes, puis laisser reposer 30 minutes.",
            "Cuire 600 g de pommes de terre 25 minutes, les écraser avec 100 g d'oignon, 12 g de gingembre, 8 g de piment et 20 g de coriandre hachés, 4 g de cumin, 3 g de garam masala et 3 g de sel.",
            "Diviser pâte et farce en 6, aplatir un disque de pâte, poser une boule de farce et refermer en bourse.",
            "Étaler délicatement en galette de 18 cm, sans faire sortir la farce.",
            "Cuire 2 minutes par face sur une plaque chaude, en badigeonnant de ghee (50 ml en tout), jusqu'à ce que des taches dorées apparaissent.",
        ]),
    recipe(
        rid="side_raita_concombre_2d47b6", fr="Raita de concombre à la menthe",
        en="Cucumber Mint Raita",
        cuisine="indian", country="india", region="punjab", city="",
        dish="side", prep=10, rest=20, cook=2,
        desc="Yaourt battu au concombre râpé, cumin grillé, menthe et coriandre : le contrepoint frais des "
             "currys épicés.",
        texture=("cremeux",), taste=("frais", "cumin"),
        compo=[
            ("yogurt_plain_3pct", 500, "g", "protein"),
            ("cucumber_raw_with_skin", 300, "g", "vegetable"),
            ("mint_fresh_herb", 15, "g", "herb"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Griller 4 g de graines de cumin à sec, 2 minutes, puis les piler.",
            "Râper 300 g de concombre et le presser pour retirer l'eau.",
            "Battre 500 g de yaourt avec 3 g de sel, 1 g de poivre et le cumin grillé.",
            "Ajouter le concombre, 15 g de menthe et 15 g de coriandre ciselées.",
            "Réfrigérer 20 minutes avant de servir.",
        ]),
    recipe(
        rid="snack_dhokla_8e52c7", fr="Dhokla, gâteau vapeur de pois chiches",
        en="Dhokla, Steamed Chickpea Flour Cake",
        cuisine="indian", country="india", region="gujarat", city="ahmedabad",
        dish="snack", servings=6, prep=15, rest=20, cook=25, spice=1,
        desc="Spécialité gujaratie : pâte de farine de pois chiches acidulée au yaourt, levée au bicarbonate "
             "puis cuite à la vapeur, arrosée d'un tempérage sucré-salé au sésame.",
        texture=("aere", "moelleux"), taste=("acidule", "doux"),
        compo=[
            ("chickpea_flour", 300, "g", "plant_protein"),
            ("yogurt_plain_3pct", 200, "g", "liquid"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("baking_soda_powder", 4, "g", "leavening"),
            ("lemon_juice", 25, "ml", "condiment"),
            ("white_sugar", 25, "g", "sweetener"),
            ("yellow_mustard_spice_seed", 4, "g", "spice"),
            ("sesame_seed_hulled_dried", 10, "g", "garnish"),
            ("curry_leaf", 5, "g", "herb"),
            ("coriander_raw_fresh_herb", 15, "g", "herb"),
            ("sunflower_oil_plant", 30, "ml", "fat"),
            ("water", 300, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Fouetter 300 g de farine de pois chiches avec 200 g de yaourt, 300 ml d'eau, 12 g de gingembre et 8 g de piment mixés, 2 g de curcuma et 5 g de sel, puis laisser reposer 20 minutes.",
            "Ajouter 4 g de bicarbonate et 15 ml de jus de citron, mélanger 10 secondes : la pâte mousse.",
            "Verser aussitôt dans un plat huilé et cuire 20 minutes à la vapeur, jusqu'à ce qu'une lame ressorte propre.",
            "Tempérage : chauffer 30 ml d'huile, y faire éclater 4 g de moutarde avec 10 g de sésame et 5 g de feuilles de curry, puis ajouter 25 g de sucre, 10 ml de jus de citron et 100 ml d'eau, et porter à ébullition.",
            "Découper le dhokla en carrés, l'arroser du tempérage et parsemer de 15 g de coriandre.",
        ]),
    recipe(
        rid="brkf_pongal_4a91d8", fr="Ven pongal, riz et lentilles au poivre",
        en="Ven Pongal, Rice and Lentil Porridge",
        cuisine="indian", country="india", region="tamil_nadu", city="",
        dish="breakfast", prep=10, cook=30, spice=1,
        desc="Bouillie salée du petit-déjeuner tamoul : riz et lentilles moong cuits très mous, parfumés au "
             "poivre, au cumin, au gingembre et aux noix de cajou frites au ghee.",
        texture=("cremeux",), taste=("poivre", "beurre"),
        compo=[
            ("white_rice_raw_seed_unenriched", 250, "g", "carbohydrate"),
            ("mung_bean_dried", 100, "g", "plant_protein", "dried"),
            ("black_pepper_spice", 5, "g", "spice"),
            ("cumin_spice_seed", 5, "g", "spice"),
            ("ginger_raw_root_fresh", 15, "g", "aromatic"),
            ("cashew_nuts_raw", 40, "g", "garnish"),
            ("curry_leaf", 5, "g", "herb"),
            ("base_ghee_ec9064", 50, "ml", "fat"),
            ("water", 1200, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Griller 100 g de lentilles moong à sec, 3 minutes, jusqu'à ce qu'elles sentent la noisette.",
            "Rincer avec 250 g de riz, puis cuire le tout dans 1,2 L d'eau avec 5 g de sel, 25 minutes, jusqu'à obtenir une bouillie très molle.",
            "Faire frire 40 g de noix de cajou dans 50 ml de ghee, puis ajouter 5 g de poivre concassé, 5 g de cumin, 15 g de gingembre et 5 g de feuilles de curry.",
            "Verser ce tempérage dans le pongal et mélanger.",
            "Servir brûlant, avec un chutney à la noix de coco.",
        ]),
    recipe(
        rid="snack_gobi_manchurian_9c72e5", fr="Gobi manchurian, chou-fleur croustillant sauce soja",
        en="Gobi Manchurian, Indo-Chinese Crispy Cauliflower",
        cuisine="indian", country="india", region="karnataka", city="",
        dish="snack", prep=20, cook=25, spice=2, kid_friendly=False,
        desc="Plat indo-chinois : bouquets de chou-fleur panés à la farine de pois chiches et frits, enrobés "
             "d'une sauce soja-ketchup à l'ail, au gingembre et au piment.",
        texture=("croustillant",), taste=("epice", "umami"),
        compo=[
            ("cauliflower_raw_flower", 700, "g", "vegetable"),
            ("chickpea_flour", 100, "g", "carbohydrate"),
            ("cornstarch_flour", 60, "g", "carbohydrate"),
            ("garlic_raw", 20, "g", "aromatic"),
            ("ginger_raw_root_fresh", 15, "g", "aromatic"),
            ("green_onion_raw", 50, "g", "garnish"),
            ("soy_sauce_shoyu_reduced_sodium", 35, "ml", "condiment"),
            ("tomato_ketchup_catsup_pre_packaged_normal", 60, "g", "condiment"),
            ("chilli_pepper_raw", 10, "g", "spice"),
            ("sunflower_oil_plant", 70, "ml", "fat"),
            ("water", 180, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Blanchir 700 g de bouquets de chou-fleur 3 minutes, puis les égoutter et les sécher.",
            "Fouetter 100 g de farine de pois chiches, 60 g de fécule, 4 g de sel et 180 ml d'eau en pâte épaisse, puis y enrober le chou-fleur.",
            "Frire à 180°C, 4 minutes, jusqu'à ce que les bouquets soient dorés et croustillants (environ 60 ml d'huile absorbée).",
            "Dans 10 ml d'huile, sauter 20 g d'ail, 15 g de gingembre et 10 g de piment hachés, 1 minute.",
            "Ajouter 35 ml de sauce soja et 60 g de ketchup, puis cuire 2 minutes.",
            "Enrober le chou-fleur de sauce hors du feu, parsemer de 50 g d'oignons verts et servir aussitôt.",
        ]),
    recipe(
        rid="side_pol_sambol_3b84d7", fr="Pol sambol, coco râpée pimentée sri lankaise",
        en="Pol Sambol, Sri Lankan Coconut Relish",
        cuisine="sri_lankan", country="sri_lanka", region="province_occidentale", city="",
        dish="side", prep=10, cook=0, spice=2, kid_friendly=False, raw=True,
        desc="Condiment cru du Sri Lanka : noix de coco râpée travaillée à la main avec piment, oignon rouge, "
             "citron vert et sel, à manger avec le riz ou les hoppers.",
        texture=("granuleux",), taste=("epice", "coco"),
        compo=[
            ("coconut_flesh_dried", 150, "g", "ingredient"),
            ("red_onion_raw", 100, "g", "aromatic"),
            ("red_hot_chili_pepper_spice_dried", 6, "g", "spice"),
            ("lime_juice_fresh", 35, "ml", "condiment"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("water", 60, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Humidifier 150 g de noix de coco râpée avec 60 ml d'eau.",
            "Ajouter 6 g de piment en poudre, 100 g d'oignon rouge très finement haché, 4 g de sel et 1 g de poivre.",
            "Travailler le mélange à la main 3 minutes, pour que la coco prenne la couleur du piment.",
            "Ajouter 35 ml de jus de citron vert et servir aussitôt.",
        ]),
    recipe(
        rid="main_kottu_roti_legumes_7e19c6", fr="Kottu roti aux légumes",
        en="Vegetable Kottu Roti",
        cuisine="sri_lankan", country="sri_lanka", region="colombo", city="colombo",
        dish="main", prep=20, cook=20, spice=2, kid_friendly=False,
        desc="Plat de rue de Colombo : pain roti haché à la spatule sur la plaque avec légumes, œufs et curry "
             "en poudre, dans un grand bruit de lames.",
        texture=("moelleux",), taste=("epice", "umami"),
        compo=[
            ("white_bread_unsalted", 400, "g", "carbohydrate"),
            ("egg_raw", 220, "g", "protein"),
            ("green_cabbage_raw", 300, "g", "vegetable"),
            ("carrot_raw", 200, "g", "vegetable"),
            ("onion_raw", 200, "g", "aromatic_base"),
            ("leeks_raw", 150, "g", "vegetable"),
            ("garlic_raw", 15, "g", "aromatic"),
            ("ginger_raw_root_fresh", 12, "g", "aromatic"),
            ("curry_powder", 10, "g", "spice"),
            ("chilli_pepper_raw", 10, "g", "spice"),
            ("curry_leaf", 5, "g", "herb"),
            ("soy_sauce_shoyu_reduced_sodium", 25, "ml", "condiment"),
            ("coconut_oil_plant", 40, "ml", "fat"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Couper 400 g de pain plat en lanières.",
            "Faire revenir 200 g d'oignon, 150 g de poireau, 15 g d'ail, 12 g de gingembre et 10 g de piment dans 40 ml d'huile de coco, 6 minutes.",
            "Ajouter 300 g de chou et 200 g de carotte émincés, 10 g de curry et 5 g de feuilles de curry, puis sauter 5 minutes.",
            "Casser 4 œufs (220 g) dans la poêle et les brouiller rapidement.",
            "Ajouter le pain, 25 ml de sauce soja et 3 g de sel, puis hacher et mélanger énergiquement à la spatule 4 minutes.",
            "Servir aussitôt, très chaud.",
        ]),
    recipe(
        rid="entry_chana_chaat_5f27b3", fr="Chana chaat, salade de pois chiches épicée",
        en="Chana Chaat, Spiced Chickpea Salad",
        cuisine="indian", country="pakistan", region="punjab", city="lahore",
        dish="starter", prep=15, cook=0, spice=1,
        desc="Salade de rue du Pendjab : pois chiches, oignon, tomate et pomme de terre, réveillés au chaat "
             "masala, au citron et à la coriandre, avec un peu de yaourt.",
        texture=("croquant",), taste=("acidule", "epice"),
        compo=[
            ("chickpea_boiled", 450, "g", "plant_protein", "cooked"),
            ("potato_raw_flesh", 250, "g", "vegetable"),
            ("onion_raw", 120, "g", "aromatic"),
            ("tomato_raw_ripe", 200, "g", "vegetable"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("cumin_spice_seed", 4, "g", "spice"),
            ("lemon_juice", 40, "ml", "condiment"),
            ("yogurt_plain_3pct", 150, "g", "sauce"),
            ("coriander_raw_fresh_herb", 20, "g", "herb"),
            ("mint_fresh_herb", 10, "g", "herb"),
            ("black_pepper_spice", 2, "g", "spice"),
            ("table_salt_unenriched", 3, "g", "seasoning"),
        ],
        steps=[
            "Cuire 250 g de pommes de terre 20 minutes, les refroidir et les couper en dés.",
            "Griller 4 g de cumin à sec et le piler.",
            "Mélanger 450 g de pois chiches, les pommes de terre, 120 g d'oignon, 200 g de tomate et 8 g de piment hachés.",
            "Assaisonner de 40 ml de jus de citron, du cumin grillé, 3 g de sel et 2 g de poivre.",
            "Ajouter 20 g de coriandre et 10 g de menthe, puis servir avec 150 g de yaourt battu.",
        ]),
    recipe(
        rid="dessert_gajar_halwa_8a63d4", fr="Gajar ka halwa, carottes confites au lait",
        en="Gajar ka Halwa, Carrot Milk Pudding",
        cuisine="indian", country="india", region="punjab", city="",
        dish="dessert", servings=8, prep=15, cook=55,
        desc="Dessert d'hiver indien : carottes râpées cuites longuement dans le lait jusqu'à absorption, "
             "sucrées, parfumées à la cardamome et parsemées d'amandes au ghee.",
        texture=("fondant",), taste=("sucre", "cardamome"),
        compo=[
            ("carrot_raw", 1000, "g", "fruit"),
            ("milk_liquid_uht_3_5pct", 700, "ml", "liquid"),
            ("white_sugar", 140, "g", "sweetener"),
            ("base_ghee_ec9064", 40, "ml", "fat"),
            ("cardamom", 2, "g", "spice"),
            ("almond_raw_with_skin_unsalted", 50, "g", "garnish"),
            ("grape_dried", 40, "g", "garnish"),
        ],
        steps=[
            "Râper 1 kg de carottes.",
            "Les cuire dans 700 ml de lait, 35 minutes à feu moyen en remuant souvent, jusqu'à ce que le lait soit presque entièrement absorbé.",
            "Ajouter 140 g de sucre et cuire encore 10 minutes, jusqu'à ce que le mélange épaississe.",
            "Faire revenir 50 g d'amandes et 40 g de raisins secs dans 40 ml de ghee, puis les ajouter avec 2 g de cardamome.",
            "Cuire 5 minutes en remuant et servir tiède.",
        ]),
    recipe(
        rid="snack_chatamari_nepalaise_2b95f7", fr="Chatamari, crêpe de riz népalaise",
        en="Chatamari, Nepali Rice Crêpe",
        cuisine="nepali", country="nepal", region="bagmati", city="katmandou",
        dish="snack", prep=15, rest=30, cook=20, spice=1,
        desc="La « pizza » népalaise des Newars : crêpe fine de farine de riz cuite d'un côté, garnie d'œuf, "
             "d'oignon, de tomate et de coriandre.",
        texture=("moelleux",), taste=("epice", "doux"),
        compo=[
            ("rice_flour", 300, "g", "carbohydrate"),
            ("egg_raw", 220, "g", "protein"),
            ("onion_raw", 150, "g", "vegetable"),
            ("tomato_raw_ripe", 200, "g", "vegetable"),
            ("chilli_pepper_raw", 8, "g", "spice"),
            ("coriander_raw_fresh_herb", 20, "g", "herb"),
            ("cumin_spice_seed", 3, "g", "spice"),
            ("turmeric_powder", 2, "g", "spice"),
            ("sunflower_oil_plant", 40, "ml", "fat"),
            ("water", 600, "ml", "liquid"),
            ("table_salt_unenriched", 4, "g", "seasoning"),
        ],
        steps=[
            "Fouetter 300 g de farine de riz avec 600 ml d'eau, 2 g de curcuma, 3 g de cumin et 4 g de sel, puis laisser reposer 30 minutes.",
            "Hacher 150 g d'oignon, 200 g de tomate, 8 g de piment et 20 g de coriandre.",
            "Chauffer une poêle huilée (40 ml en tout) et verser une louche de pâte en disque de 20 cm.",
            "Casser un œuf dessus (220 g pour quatre crêpes), l'étaler, puis parsemer de garniture.",
            "Couvrir et cuire 5 minutes, sans retourner, jusqu'à ce que l'œuf soit pris.",
        ]),
    recipe(
        rid="beverage_masala_chai_6f52a8", fr="Masala chai aux épices",
        en="Spiced Masala Chai",
        cuisine="indian", country="india", region="uttar_pradesh", city="",
        dish="beverage", prep=5, cook=15,
        desc="Thé noir bouilli avec du lait, du gingembre frais et des épices pilées — cardamome, cannelle, "
             "girofle, poivre — puis sucré et filtré.",
        texture=("liquide",), taste=("epice", "sucre"),
        compo=[
            ("tea_leaf", 12, "g", "ingredient"),
            ("milk_liquid_uht_3_5pct", 500, "ml", "liquid"),
            ("ginger_raw_root_fresh", 20, "g", "aromatic"),
            ("cardamom", 3, "g", "spice"),
            ("cinnamon", 2, "g", "spice"),
            ("cloves", 1, "g", "spice"),
            ("black_pepper_spice", 1, "g", "spice"),
            ("white_sugar", 40, "g", "sweetener"),
            ("water", 500, "ml", "liquid"),
        ],
        steps=[
            "Piler 3 g de cardamome, 2 g de cannelle, 1 g de girofle et 1 g de poivre.",
            "Porter 500 ml d'eau à ébullition avec les épices et 20 g de gingembre râpé, puis laisser bouillir 5 minutes.",
            "Ajouter 12 g de thé noir et laisser infuser 2 minutes.",
            "Ajouter 500 ml de lait et 40 g de sucre, puis porter à frémissement en remuant, 4 minutes.",
            "Filtrer et servir brûlant.",
        ]),
    recipe(
        rid="bread_puri_frite_9b37c5", fr="Puri, petits pains frits gonflés",
        en="Puri, Puffed Fried Bread",
        cuisine="indian", country="india", region="uttar_pradesh", city="",
        dish="bread", servings=6, prep=20, rest=20, cook=20,
        desc="Petits disques de pâte complète frits très chaud : ils gonflent en quelques secondes en boule "
             "creuse, à manger avec un curry ou un halwa.",
        texture=("gonfle", "croustillant"), taste=("cereale",),
        compo=[
            ("whole_wheat_flour_seed", 400, "g", "carbohydrate"),
            ("wheat_semolina_raw", 50, "g", "carbohydrate"),
            ("sunflower_oil_plant", 80, "ml", "fat"),
            ("water", 230, "ml", "liquid"),
            ("table_salt_unenriched", 5, "g", "seasoning"),
        ],
        steps=[
            "Pétrir 400 g de farine complète, 50 g de semoule fine, 5 g de sel, 15 ml d'huile et 230 ml d'eau en une pâte ferme, 8 minutes.",
            "Laisser reposer 20 minutes sous un linge.",
            "Diviser en 18 boules et étaler chacune en disque de 10 cm, sans fariner (huiler légèrement le plan).",
            "Chauffer l'huile à 190°C et y plonger un disque : l'appuyer doucement avec l'écumoire pour qu'il gonfle.",
            "Le retourner après 20 secondes et le sortir dès qu'il est doré (environ 65 ml d'huile absorbée).",
            "Égoutter sur du papier absorbant et servir aussitôt.",
        ]),
]
